### ISSUE TITLE
Logro: Hermandad en el Trono de los cuatros vientos.

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#10]
Nombre de personaje principal: Skala
Usuario de discord: JorDaNN#5575
Descripción del error: Nos disponíamos a sacar este logro ya mencionado. Sin embargo al matar al jefe Al'Akir en modo normal, no contó para el logro de hermandad. recalcar que estábamos en grupo de hermandad. Es más salió el logro para la hermandad pero ''Heroico: Hermandad con Al'kir''. Tampoco pudimos lotear ya que nos separo del medio, hacia los extremos de la plataforma
Integrantes del grupo de hermandad:
-Skala, Logan, Zenkishi, Anfetamina(desconectado), Rhamnus, Alfonsmd, Alarcon, Vicio, Bounce, Dolthepro.

![WoWScrnShot_112319_193000](https://user-images.githubusercontent.com/58092128/69487586-9fc31900-0e2a-11ea-8967-fa5e5951a35d.jpg)

![WoWScrnShot_112319_193122](https://user-images.githubusercontent.com/58092128/69487656-d188af80-0e2b-11ea-9892-0ec57f928b61.jpg)
![WoWScrnShot_112319_195313](https://user-images.githubusercontent.com/58092128/69487675-0268e480-0e2c-11ea-9b39-02246ca45be1.jpg)

**Comment by Skala101** [comment]
Logro: https://es.wowhead.com/achievement=4987/hermandad-en-el-trono-de-los-cuatro-vientos
![WoWScrnShot_112319_193212](https://user-images.githubusercontent.com/58092128/69487709-7a370f00-0e2c-11ea-962e-1c3b40a98a58.jpg)

**Comment by DennisCalderon** [comment]
Actualmente en pruebas.

**Comment by DennisCalderon** [comment]
reparado y aplicado al server.
