### ISSUE TITLE
Bonus de Tier +4 Pala tanque no funciona

### ISSUE THREAD

**Issue by jmora142** [athenaswow/BugTracker-Athenas-WoW#100]
# #@Kam

Buenas,

Como indica el titulo, el bonus +4 del set de paladín de Dragon Soul no funciona, el bonus da al PJ -60segundos de cooldown para el hechizo Guardián Divino.

El paladín tanque, tiene un talento que se llama "Escudo del templario"  y este le ayuda ya a reducir su CD de Guardián Divino en 3 minutos, ( Sin el talento serian 5 minutos como lo es en la rama de Sagrado) añadiendo el set +4 del paladín tanque de Dragon Soul que dice lo siguiente:
Conjunto+4: Reduce 60 segundos el tiempo de reutilizacion de Guardián Divino y aumenta 70 metros el radio de efecto.

El bonus +2 si funciona correctamente.

Adjunto una imagen donde se muestra la evidencia de lo dicho anteriormente.

![image](https://user-images.githubusercontent.com/59556502/71806207-d85f3080-302d-11ea-989a-d3e0c7d1c82e.png)

Cabe mencionar que se envió un ticket con el tema y lo atendio el GM "Aquiles" el día 3 de Enero del presente año, indicando  que también podría tratarse de un error de mi PJ como tal, ya que se hizo pruebas quitando el set, volviéndolo a colocar, desconectándose, reiniciando talentos y mas, sin hacerlo funcionar correctamente.

Agradezco la ayuda con el problema.

Saludos,

**Comment by Alfonsmd** [comment]
Kam, es el hechio "guardian divino". Tu estas hablando de "guardián de los antiguos reyes". El tier funciona bien.

**Comment by jmora142** [comment]
Uff, es cierto! jaja creo que me gano el sueño, curioso por que tampoco me corrijo el GM jaja, bueno, gracias, fallonazo.
