### ISSUE TITLE
Error con los portales 

### ISSUE THREAD

**Issue by kennyr1120** [athenaswow/BugTracker-Athenas-WoW#101]
Nombre: Carla
Discord: mink1rk#7987
Los portales que se utilizan para ir a mazmorras, terrallende, portal de magos, no funcionan, esto solo pasa con este pj.
Desde hace varios dias no puedo utilizar ningun portal y me quedo encerrado en la torre de magos sin poder pasar, espero puedan solucionarlo.

**Comment by AresGM** [comment]
Hola,

Lamentamos las molestias causadas debido al fallo que está presentando, para la solución del mismo se necesita el personaje en línea, he contactado con usted vía mensaje privado de Discord para concordar horarios y proceder con la solución.

Maestro de Juego Ares.
AthenasWoW GameMaster Team.

**Comment by yuremuch** [comment]
Hola,
Me pasa el mismo problema con mi pj su nick es: Koara 
Discord: Edwin#7846
