### ISSUE TITLE
Cadena de misiones para sacar el Protodraco Verde 

### ISSUE THREAD

**Issue by Mechho** [athenaswow/BugTracker-Athenas-WoW#102]
PERSONAJE PRINCIPAL: Mechho
DISCORD: Mechho #5107

_________________________________________________________________________________________________________

ASI DEBERIA FUNCIONAR LA MISIÓN O LA CADENA DE MISIONES: 

https://www.youtube.com/watch?v=U-uWJSfsDHg

_________________________________________________________________________________________________________

Existe una cadena de misiones en Cuenca de Sholazar la cual al final nos permite comprar un huevo de donde puede salir el Protodraco verde.
Al momento de recibir la tercera misión de esta cadena, otorgada por "Goregek el Cazador de Gorilas" el cual es invocado de "Grilletes de Goregek", nos dice que no cumplinos los requisitos para esta misión... la misión es "Atormentar a los badanudillos".
Originalmente esta misión (( https://es.wowhead.com/quest=12530/atormentar-a-los-badanudillos#comments))  solo pide un requisito y es ser de nivel minimo 66  ( mi pj es 85 ) ya que hace parte de la cadena de misiones que es para subir reputación en la facción "Tribu Corazon frenetico".

**Comment by athenaswow** [comment]
OK se le a quitado el requisito para las razas se implementara el otro martes.
