### ISSUE TITLE
Bug en cadena de misiones -mision final (Adiós, pezqueñín)

### ISSUE THREAD

**Issue by esscanor999000** [athenaswow/BugTracker-Athenas-WoW#103]
https://es.wowhead.com/quest=14392/adi%C3%B3s-pezque%C3%B1%C3%ADn   Mision bug.
El npc que tiene que dar la antepenultima mision no la da es un dragon llamado azufregos.
https://www.youtube.com/watch?v=8bKYyDiI8TI
El npc no esta para entregar la mision final de la cadena,
https://www.youtube.com/watch?v=D4zPhjZcGWI
![Screenshot_2](https://user-images.githubusercontent.com/59712954/72114819-c7a30900-3312-11ea-9981-5588fb8ed43a.png)
Item de recompensa.

![WoWScrnShot_010920_191552](https://user-images.githubusercontent.com/59712954/72115343-b3600b80-3314-11ea-9ef8-e1c96dfeb7c9.jpg)

lugar donde el npc tendria que estar.

**Comment by athenaswow** [comment]
A ver si entiendo... te dan la misión pero no la puedes entregar?

**Comment by athenaswow** [comment]
No hay suficiente información del problema.
