### ISSUE TITLE
Bug en talento del sacerdote. 

### ISSUE THREAD

**Issue by ViktorKr0m** [athenaswow/BugTracker-Athenas-WoW#105]
Hola soy ViktorKrum, sacer no-muerto!
Viktor Kun#5048 en discord.
He leído ya en varios foros de diferentes servers que el talento Fe distorcionada - El cual transforma 1=1 la estadistica de espiritu por indice de golpe - no funciona como debería; en otros servidores comentaron que lo que se subía era la estadistica base del indice, pero tampoco funciona, ya que la transformacion de espiritu por ind. de golpe no sucede. Este talento es vital para Pve pero no sirve. 
Me he dado cuenta que esto es asi ya que al reforjar a espiritu, el indice no sube, ni al encantar, ni al engermar, pero cuando engemo, encanto o reforjo esos mismos items con indice de golpe, es la unica forma de hacer que la estadistica mejore, es decir, los tier del sacer que dan espiritu estan como una estadistica muerta, y no da es el ind. de golpe, una de las estadisticas principales para hacer dps sostenido.
Por ejemplo: Este es el talento - Del cual no hay registro en wowhead ya que fue eliminado hace mucho tiempo- 
![1](https://user-images.githubusercontent.com/59740192/72169258-c28a9c00-339c-11ea-8f9c-27c68e13563f.png)
Y esta es mi estadistica de golpe, con el talento activo. 
![2](https://user-images.githubusercontent.com/59740192/72169283-cf0ef480-339c-11ea-9a96-905c66b3b503.png)
Ahora, despues de olvidar talentos, y no ponerlo y relogear.
![3](https://user-images.githubusercontent.com/59740192/72169335-e8b03c00-339c-11ea-8901-afafdf2ecf73.png)
Absolutamente ningun cambio en la estadistica, ni usandolo, ni dejandolo de usar. 
![4](https://user-images.githubusercontent.com/59740192/72169357-f82f8500-339c-11ea-8132-85938288e3b3.png)

**Comment by Alfonsmd** [comment]
si te fijas claramente el talento especifica, "indice de golpe con HECHIZOS". Funciona perfectamente.

**Comment by tequilas-elite** [comment]
si estas viendo el indice de golpe cuerpo a cuerpo o a distancia(hunters) obvio no se vera afectado pero verifica donde dice hechizos xD

**Comment by ViktorKr0m** [comment]
Sí el error era mio, que pena! Gracias!
