### ISSUE TITLE
Mision: "Distráelos" (Ciudadela Crepuscular - Tierras altas Crepusculares) 

### ISSUE THREAD

**Issue by dunnabugtracker** [athenaswow/BugTracker-Athenas-WoW#107]
Reporte por: **Dunna**
Alter: **Marabela**

¿Como debería de funcionar?
Simplemente el Maestro Mathias shaw (Alianza), o Garona semiorco (Horda) te envia a matar a la dama Alys Finnson, al maestro Klem y a Mia la Rosa. Luego regresas a entregar la quest.
**Link/WowHead:** https://es.wowhead.com/quest=27688/distr%C3%A1elos
**Link/Youtube:** https://www.youtube.com/watch?v=NNYsMBhPznw
(Minuto 1:35 dama Alys Finnson)

¿Cual es el problema?
La dama Alys Finnson no aparece como puedes observar en la siguiente:
https://subefotos.com/ver/?eb99979affde1caef2296062a9bed342o.jpg

Intente esperar la y darle un tiempo creyendo que alguien mas pudo matarla mucho antes que yo; aun asi nunca aparecio como puedes apreciar el tiempo transcurrido:
https://subefotos.com/ver/?388264720f1538910bdd14b186574e9eo.jpg

Gracias!

**Comment by athenaswow** [comment]
corregido.
