### ISSUE TITLE
Misión bug (Las celadoras de las sombras)

### ISSUE THREAD

**Issue by waltrax** [athenaswow/BugTracker-Athenas-WoW#108]
Nombre pj principal: Fantasma
Usuario de discord: Waltrax#4718
Link misión Wowhead: https://es.wowhead.com/quest=29214/las-celadoras-de-las-sombras

Al tener las 150 marcas del árbol del mundo nos deberíamos poder dirigir hacia la Capitana Saynna Corretormenta para completar esta misión, pero cuando voy hacia donde dice el mapa ésta no se encuentra.

https://ibb.co/4f1nQbw

Y si voy un poco más atrás la encuentro, pero no me permite entregar la misión para completarla.

https://ibb.co/SsYjnbd

Quedo atento, muchas gracias.

**Comment by athenaswow** [comment]
Todos los reportes de hyjal serán  cerrados ya que estoy trabajando en ese lugar desde cero logrando un mejor resultado en las cadenas de misiones, el parche se aplicara a mas tardar el 15 de abril del 2020.
