### ISSUE TITLE
Misión bug (Druidas de la Garfa)

### ISSUE THREAD

**Issue by waltrax** [athenaswow/BugTracker-Athenas-WoW#109]
Nombre pj principal: Fantasma
Usuario de discord: Waltrax#4718
Link misión Wowhead: https://es.wowhead.com/quest=29181/druidas-de-la-garfa

Al tener las 150 marcas del árbol del mundo nos deberíamos poder dirigir hacia el Señor del Cielo Omnuron para completar esta misión, pero cuando voy hacia donde dice el mapa se encuentran dos de estos (uno en el primer piso de la estructura y otro en el tercero) y con ninguno puedo entregar la misión.

Señor del Cielo Omnuron del primer piso:

https://ibb.co/sjH1rwq

Señor del Cielo Omnuron del tercer piso:

https://ibb.co/TTG6mgf

Quedo atento, muchas gracias.

**Comment by athenaswow** [comment]
Todos los reportes de hyjal serán  cerrados ya que estoy trabajando en ese lugar desde cero logrando un mejor resultado en las cadenas de misiones, el parche se aplicara a mas tardar el 15 de abril del 2020.
