### ISSUE TITLE
Misión: Conciencia medioambiental bug

### ISSUE THREAD

**Issue by Lamela-La-Buscadora** [athenaswow/BugTracker-Athenas-WoW#11]
Lamela
Lamela#3066
Usa la bomba de extracción de aceite en los cadáveres de tortugas de agua dulce Malezamarina, rémoras Registraintestinos y tiburones martillo Escamaespina en Malezamarina para obtener 4 unidades de aceite de tortuga de agua dulce, 4 de aceite de rémora y 4 de aceite de tiburón martillo.
https://www.youtube.com/watch?v=U9KDh2kHkCM

El error está podemos recoger aceites únicamente de las rémoras mientras que el de los tiburones y las tortugas no.
https://www.youtube.com/watch?v=FXAqoTaTwKk&feature=youtu.be

**Comment by athenaswow** [comment]
corregido.
