### ISSUE TITLE
Misión bug (La bendición de la naturaleza)

### ISSUE THREAD

**Issue by waltrax** [athenaswow/BugTracker-Athenas-WoW#110]
Nombre pj principal: Fantasma
Usuario de discord: Waltrax#4718
Link misión Wowhead: https://es.wowhead.com/quest=29162/la-bendici%C3%B3n-de-la-naturaleza
Link misión Youtube: https://youtu.be/5Ax9gPwzhs0

Esta misión en un inicio servía en el servidor, pero hace más o menos uno o dos meses empezó a fallar ya que para invocar a Piroaraña (o a Millagazor, que hace parte de otra misión) se necesita un portal que antes había, pero ahora no. Por lo cual no he podido volver a hacer esta misión (y la de Millagazor) desde entonces.

Foto del lugar donde estaba y se supone que debería estar el portal:

https://ibb.co/Sm0n6y5

La misión "Esos osos de ahí arriba (https://es.wowhead.com/quest=29161/esos-osos-de-ah%C3%AD-arriba)" que va antes de esta misión está completamente bien.

Quedo atento, muchas gracias.

**Comment by athenaswow** [comment]
Corregido.
