### ISSUE TITLE
Me quede con un buff que no me deja mover

### ISSUE THREAD

**Issue by erasglo** [athenaswow/BugTracker-Athenas-WoW#111]
El nombre de mi pj es Guayacojorge Coji la mision que envia a los globins de kezan a islas perdidas despues apareci con el buff al filo de la muerte que no se me quita ya hasta desbloquie por la pagina de athenas el personaje y nada.

**Comment by AresGM** [comment]
Hola,

Lamentamos las molestias causadas debido al fallo que está presentando, para la solución del mismo se necesita el personaje en línea, he contactado con usted dentro del juego para proceder con la solución.

Maestro de Juego Ares.
AthenasWoW GameMaster Team.
https://athenaswow-project.com/
