### ISSUE TITLE
NPC matogarra no aparece

### ISSUE THREAD

**Issue by kaymbel** [athenaswow/BugTracker-Athenas-WoW#113]
pj principal: Bankotzu
Discord: kaymbel#9968
https://es.wowhead.com/npc=52669/matogarra
El npc llamado matogarra no aparece y por eso estoy teniendo problemas para continuar con la cadena de misiones  de Guardianes de Hyjal invasion de las tierras de fuego 
https://es.wowhead.com/quest=29389/guardianes-de-hyjal-invasi%C3%B3n-de-las-tierras-de-fuego
ya había visto un post con este problema antes y esta cerrado porque el problema ya estaba arreglado pero al parecer algo paso y el npc volvio a desaparecer https://github.com/athenaswow/BugTracker-Athenas-WoW/issues/54
![WoWScrnShot_011120_143803](https://user-images.githubusercontent.com/59715235/72209804-947e8800-3480-11ea-8ff3-5dc960a9f807.jpg)

**Comment by athenaswow** [comment]
Ya reportado.
