### ISSUE TITLE
PNJ <Hiena rabiosa> (Uldum)

### ISSUE THREAD

**Issue by dunnabugtracker** [athenaswow/BugTracker-Athenas-WoW#114]
**Reporte generado por: Dunna**
Alter: **Marabela**

**Problema que se esta generando:** El auto-ataque del PNJ <**Hiena rabiosa**> esta realizando entre 12.000 y 15.000 de daño por segundo. (Ubicación: 66.0, 53.0 - Uldum)
Demostración: 

**(Imagen 1)**
https://subefotos.com/ver/?47732d1f2b52d9698b79d7cd93eb98cdo.jpg#codigos
**(Imagen 2)**
https://subefotos.com/ver/?3580c1b79f6a9cfff07b4f2888b4ced9o.jpg#codigos

**¿Como debería de funcionar?**
Realmente desconozco el daño en concreto que esta debería de realizar. Aun así el daño de este PNJ es exagerado.

**Información mas detallada del PNJ:** 
https://es.wowhead.com/npc=51671/hiena-rabiosa#drops

Gracias!

**Comment by athenaswow** [comment]
corregido.
