### ISSUE TITLE
MISION BUG (A la cicatriz)

### ISSUE THREAD

**Issue by martnez55** [athenaswow/BugTracker-Athenas-WoW#117]
PJ principal: Crainers
Usuario de discord : ⇤★ヅ | Nando |ヅ★⇥#9366
Descripción del problema: La misión A la cicatriz https://es.wowhead.com/quest=27927/a-la-cicatriz no aparece para aceptarla o cogerla ya q esta permite seguir con una cadena de misiones q al final da como recompensa tres items el cual en mi caso yo deseo https://es.wowhead.com/item=63192/reductor-de-borlallave 
IMAGENES : 
https://ibb.co/y68b9Wn
https://ibb.co/rcHT5pv

**Comment by pangolp** [comment]
Buenas tardes. Gracias por el reporte. ¿Cual es el problema de la misión? ¿Usted realiza la cadena, pero al llegar al npc que debería de darla, este no le asigna la misión?

**Comment by pangolp** [comment]
Listo. Se le asignó la misión al npc, cuando se aplique el fix usted podrá tomar la misión, pero debe tener como condición para poder hacerlo, la misión https://www.wowhead.com/quest=27794/return-to-blam entregada para poder pedirla. Gracias por el reporte, después me avisa cualquier cosa cuando se aplique el arreglo, si puedo pedir ficha misión.
