### ISSUE TITLE
Bug: Salida de Grim Batol (Mazmorra)

### ISSUE THREAD

**Issue by dunnabugtracker** [athenaswow/BugTracker-Athenas-WoW#119]
Reporte por: **Dunna**
Alter: **Marabela**

**¿Como debería de funcionar?**
Al momento de usar la entrada de Grim Batol para salir deberia enviarte a las afueras de las Tierras altas Crepusculares.

**¿Cual es el problema?**
El portal de teletransporte de la mazmorra no funciona correctamente, al momento de intentar usarlo y salir de la mazmorra el cliente realiza la pantalla de carga dos veces y te regresa al interior de la mazmorra; mas no te da salida al exterior como deberia de ser.

(En esta imagen me dirigia a la salida, y el cliente realiza la pantalla de carga dos veces).
**Prueba (Imagen) 1:** https://subefotos.com/ver/?e70b5adbb0f1bcc2261409b749d2d52eo.jpg

(En esta imagen acto siguiente te regresa al interior de la mazmorra; mas no te da salida al exterior).
**Prueba (Imagen) 2:** https://subefotos.com/ver/?2bc26adaf233fe517a68d1eb4ec03dc2o.jpg

**NOTA: Inexplicablemente el problema surgio en el momento que mi grupo y yo tuvimos que deshacer el grupo por un inconveniente interno o "Bug" con un dragón crepuscular que nos dejo en un especie de mundo crepuscular y no lograbamos salir de el.**

Gracias!

**Comment by pangolp** [comment]
Acabo de probar ingresando a la mazmorra por la puerta y la misma no me genero ningún tipo de problema. Cualquier cosa doy por cerrado el tema, pero si sigue fallando nos avisan.

![WoWScrnShot_020420_231939](https://user-images.githubusercontent.com/2810187/73805245-e2975a80-47a4-11ea-8988-057ac7e17375.jpg)

![WoWScrnShot_020420_231948](https://user-images.githubusercontent.com/2810187/73805250-e62ae180-47a4-11ea-94ab-cfedd3915414.jpg)
