### ISSUE TITLE
Desaparición de item

### ISSUE THREAD

**Issue by renzoypilco** [athenaswow/BugTracker-Athenas-WoW#120]
1. Dhoraemon
2. rellenitho#1162
3. https://es.wowhead.com/item=25978/ca%C3%B1a-de-pescar-de-grafito-de-seth 
(Caña de pescar de grafito de Seth)
4. Buenas tardes, vengo a reclamar mi ítem que se borro de mi bolsa, después de haber terminado la mision "Mejor pescando" y reclamar la CAÑA DE PESCAR me voto el juego, cuando entre la caña ya no se encontraba en mi bolsa ni la misión solo tenia los requisitos para completar la misión, Me gustaría que arreglen eso, Gracias.
![WoWScrnShot_011420_170917](https://user-images.githubusercontent.com/59895609/72387293-2bea1200-36f1-11ea-9201-ee1acf62361d.jpg)

**Comment by athenaswow** [comment]
Por favor ponte en contacto con un Game Master por medio de ticket ya que sucedió en el momento de un rollback.
