### ISSUE TITLE
Problemas con el draco ala abysal

### ISSUE THREAD

**Issue by AdamJesusSE** [athenaswow/BugTracker-Athenas-WoW#126]
Tensha, AdamSE#2100

Estaba intentando conseguir el draco abysal (https://es.wowhead.com/item=32858/riendas-del-draco-ala-abisal-azur) y me encontré con algunos errores, primero que Neltharaku (https://es.wowhead.com/npc=21657/neltharaku) se cae de su vuelo de vez en cuando lo que imposibilita hablar con el. Lo que hice fue alejarme y esperar a que se desbugueara para continuar las misiones. Ya terminé el hilo de misiones y a pesar de que ya soy exaltado no me transforma en orco al acercarme a la isla lo que no me permite continuar. Gracias por la ayuda...

![1](https://user-images.githubusercontent.com/60044177/72668857-b16f0a00-39f0-11ea-9af4-48b83d3b40b9.jpg)
![2](https://user-images.githubusercontent.com/60044177/72668859-b2a03700-39f0-11ea-9002-8231c34dcfde.jpg)

**Comment by athenaswow** [comment]
Necesitas https://es.wowhead.com/spell=34091/artesano-jinete para que te convierta en orco de otra manera no podrás seguir
