### ISSUE TITLE
bug en misión del monte hyjal 

### ISSUE THREAD

**Issue by darkhalow** [athenaswow/BugTracker-Athenas-WoW#127]
el bug es en la misión llamada instigar a los elementos en la cual hay que coger unas bayas que se encuentran en la zona y darle una baya a unos dragones los dragones nos deben revelar a unos enemigos que debemos de matar pero al darle la baya a los dragones no sucede nada.
hace unas semanas hice esta misma misión con otro pj y funcionaba a la perfección

**Comment by athenaswow** [comment]
Esta funcionando correctamente.
![image](https://user-images.githubusercontent.com/50283962/72688608-f4a3a880-3ad6-11ea-888d-695ebc847fc2.png)
