### ISSUE TITLE
Misión: "Se aproxima un frente frío" (Corona de hielo)

### ISSUE THREAD

**Issue by dunnabugtracker** [athenaswow/BugTracker-Athenas-WoW#128]
Reporte realizado por: **Marabela**
Alter: **Dunna**

**- ¿Que problema se esta generando?**
El NPC **"Maestro de asedio Fezzik"** no te da la opción de entregarle la misión.
Imagen relacionada con el problema: https://subefotos.com/ver/?84950195f4dbb4fbf12c32787bbe995eo.jpg#codigos

**-¿Como debería de funcionar?**
Es simple, solo entregar la misión al NPC **"Maestro de asedio Fezzik"**.
Para mas información de esta misión comparto los siguientes links:
https://es.wowhead.com/quest=13070/se-aproxima-un-frente-fr%C3%ADo
https://www.youtube.com/watch?v=v3nbS6wjGiI

Gracias!

**Comment by athenaswow** [comment]
En revisión.

**Comment by athenaswow** [comment]
Corregido.
