### ISSUE TITLE
Misión bug Montañas Crestagrana (Jorgensen)

### ISSUE THREAD

**Issue by Srchocorramo** [athenaswow/BugTracker-Athenas-WoW#129]
Lunaza
Lunaza-Splinh#8325

Presento el reporte de esta misión ya que el Npc no esta. Así es como debería ser https://www.youtube.com/watch?v=GAD4Kj7AIcM y así es como esta 
![image](https://user-images.githubusercontent.com/60051124/72672736-d84b3180-3a2c-11ea-9326-099fdf761ded.png) 

Link de misión Wowhead: https://es.wowhead.com/quest=26560/jorgensen

**Comment by athenaswow** [comment]
En revision

**Comment by athenaswow** [comment]
Corregida la misión reportada y la siguiente llamada https://es.wowhead.com/quest=26561/krakauer
