### ISSUE TITLE
Misión: ¿No era obvio? (Azshara)

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#13]
Nombre de personaje principal: Skala
Usuario de discord: JorDaNN#5575
Descripción del error: Como se ve en la foto, el npc tiene la misión y aparece como diaria, sin embargo no te deja tomarla. Esta misión es necesaria para la cadena de misiones de este lugar.
Wowhead: https://es.wowhead.com/npc=36372/joanna
Como debería funcionar: https://www.youtube.com/watch?v=pfKHc4PpYnI 
Fotos del servidor athenas: 
![WoWScrnShot_112419_082714](https://user-images.githubusercontent.com/58092128/69495420-e0f01300-0e94-11ea-8af7-a6cbc397aaff.jpg) 
![WoWScrnShot_112419_083211](https://user-images.githubusercontent.com/58092128/69495557-4264b180-0e96-11ea-8ac7-be2877db7c9e.jpg)

**Comment by athenaswow** [comment]
corregido.
