### ISSUE TITLE
Cambio de facción

### ISSUE THREAD

**Issue by Abderrash** [athenaswow/BugTracker-Athenas-WoW#130]
El día 18/01/2020 se ha realizado una donación de 120c para el cambio de facción de la horda a la alianza (personaje Mediinela). Realicé la donación pensando en dejarla ahí hasta el momento que la fuese a utilizar "siendo más directo al finalizar la temporada Rank2 2c2.) De momento estoy deseando que apliquen para cuando quiera hacer el cambio de facción.

gracias

**Comment by Abderrash** [comment]
@athenaswow que respuesta me darán???? me gustaría saber que tengo que hacer

**Comment by pangolp** [comment]
Hola @Abderrash buen día. Estas en el lugar equivocado para hacer tu reclamo. Este es el bugtracker, es el lugar donde estamos a la espera de fallos para reparar. Todo lo relacionado a donaciones, tengo entendido que los atiende Vantepaz de forma personal en su discord. Al menos así me avisaron ayer. Por eso te cerraron el issue. Porque no seria el lugar para realizar dicho reclamo.
