### ISSUE TITLE
Misión bug (Desactivando la aguja)

### ISSUE THREAD

**Issue by Arthamix** [athenaswow/BugTracker-Athenas-WoW#131]
Usuario: Arthamix
Nombre de PJ principal: Arthamix
Discord: Arthamix#6111

Como debería funcionar:
En el orbe de translado debería suceder algo similar a lo que se muestra en el siguiente vídeo: https://www.youtube.com/watch?v=pGeDJSXGJuc
Para ser más exactos, en el minuto 0:36.

Como se presenta en el servidor:
En el servidor se presenta el error de que el orbe de translado no se activa, por lo cual no se puede completar la misión. A continuación, se adjunta una imagen mostrando el bug debido a que no se puede hacer uso del orbe.
![image](https://user-images.githubusercontent.com/60125348/72776729-2d2fa900-3be1-11ea-8e2a-31e1a5fa2397.png)

**Comment by athenaswow** [comment]
Corregido.
