### ISSUE TITLE
Receta: Gafas de nieve Mecanizadas

### ISSUE THREAD

**Issue by HermesGM** [athenaswow/BugTracker-Athenas-WoW#132]
La receta de gafas de nieve mecanizada no es enseñada por ninguno de los instructores, tanto de la horda como de la alianza, que dice en wow head, a pesar de tener la profesión en 525

id de la receta en wowhead: https://es.wowhead.com/item=44742/gafas-de-nieve-mecanizadas#taught-by-npc

**Comment by athenaswow** [comment]
Corregido a hora podrás aprenderlas en los Npc ID 28697 26991 26955 25277 26907 33586 11017 5518
