### ISSUE TITLE
Misión: Forjando una alianza (Las cumbres tormentosas)

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#133]
Nombre de personaje principal: Skala
Usuario de discord: JorDaNN#5575
Descripción del error: No se sí solo sea a mí pero el NPC Thorim que da esta misión, no me la da. Cabe decir que ya hice absolutamente todas las misiones para desbloquear esta misma. Uso wowhead y addon loremaster. Le pedí la misión a un gm, sin embargo aún así no se me ha activado la cadena de misiones ya que a los npcs donde tengo que llegar no hacen absolutamente nada.

wowhead: http://www.wowhead.com/quest=12924
Fotos athenaswow donde los npcs no tienen ninguna misión para mí como en el video
![WoWScrnShot_012120_153854](https://user-images.githubusercontent.com/58092128/72841902-56921880-3c65-11ea-9418-5d929ee2d409.jpg)
![WoWScrnShot_012120_153718](https://user-images.githubusercontent.com/58092128/72841921-5f82ea00-3c65-11ea-84af-dae451e32425.jpg)

Como debería funcionar: https://www.youtube.com/watch?v=IvyQ9iQmhn4

**Comment by pangolp** [comment]
Es que muchos scripts, se ejecutan cuando la misión te la entrega el mismo npc. Si te la asignan, como no es el npc el que inicia la misión, entonces no arranca. Si vamos al caso, no deberían de darte misiones. Habría que investigar un poco mas a fondo el problema. Debe haber un tema con la reputación o con alguna misión. Pero para eso, habría que inspeccionarte para determinar cual es la quest que te esta faltando (si es que es un problema de misión)

**Comment by Skala101** [comment]
Como digo antes he hecho todas las misiones antes de esta, no pido las misiones por pedir, solo quería comprobar esto. La pedí más que nada por que, mucho antes cuando comenzó el server y sus varias caídas las misiones se rompían y no se podía continuar. Uso addons y wowhead para las misiones y completar el loremaster puede ser que se me haya pasado algo. Pero ya lo he comprobado más de 3-4 veces. Entonces al no tener ninguna solución pedí la misión. Sin embargo, si alguien ha podido tomar la misión de manera normal solo sería un problema de mi personaje.

**Comment by pangolp** [comment]
Nose si alguien la pudo o no tomar, yo me incorpore hace unos días al área de desarrollo e estoy intentando dar una mano con los reportes que se van generando. No te lo tomes personal, porque en realidad es un comentario general que estoy haciendo. Muchos scripts se inician, cuando es el mismo npc el que te entrega la quest. Lo de entregar misiones, entiendo que haya sido algo temporal para poder salir del apuro, pero lo ideal seria que se reporten y que se arreglen. Algunas pueden llevar mas tiempo que otras, porque dependerá de la complejidad del tema.

En este caso en particular, aun no apareció nadie, veremos que pasa si aparece alguien mas confirmando el tema del error. Si encontras mas errores, te pido que los reportes porque es la única manera que tenemos de enterarlos y repararlos.

**Comment by Skala101** [comment]
Entiendo lo que dices, quiero que el servidor progrese en ese sentido ya que hay muy pocos errores y bugs de misiones. Y todo lo que este en mi mano será reportado
