### ISSUE TITLE
bug de la pet del cazador

### ISSUE THREAD

**Issue by riquip** [athenaswow/BugTracker-Athenas-WoW#134]
muy buenas tarde me dirijo a ustedes xq presento un problema com mi cazador ya que al domesticar una pet.. al desconectarme o al entrar a una bg se me borra sola y me toca nuevamente domesticarla y com el pasar el rato se me vuelve a borrar la pet  no se si pasara com otros cazadores pero en mi caso si...lo q quiero dar a enteder esq domestico las mascota y com el pasar del tienpo mas tardar un dia se me borran las pet osea q me toca domesticar 5 veces la misma pet para cuando se me borren me queda la otra..

**Comment by riquip** [comment]
mi personaje se llama Rokereslayer cazador humano alianza

**Comment by lumgilru** [comment]
Lo que sucede es que a las 5.40 del servidor me encontraba en una Bg Garganta grito de guerra con mi Cazador bestias Barbatosrex (orco), en dicha bg saque a una de mis bestias espíritu ( un tigre espectral que se consigue en rasganorte), sin embargo, la pet no salio, por lo tanto invoque a otra. Cuando salí de la Bg intente sacar de nuevo a la bestia espíritu pero esta no salia por lo que reloguee. Para mi sorpresa cuando me conecte de nuevo la pet ya no estaba con las otras y desapareció por completo. Esta pet es difícil de conseguir por lo que quiero que me la devuelvan. me pueden ayudar con esto ? 
Gracias por la atencion

**Comment by athenaswow** [comment]
Elaborar un nuevo reporte si el problema continua.
