### ISSUE TITLE
reporte de objeto desaparecido

### ISSUE THREAD

**Issue by Joosto01** [athenaswow/BugTracker-Athenas-WoW#135]
pj principal: Joost
usuario de discord: jesudas#0942

buenos días, por medio de la presente me permito hacer el reclamo de un objeto de arqueología.

mi pj es un horda llamado Joost, el día de ayer me dedique a far-mear objetos para la profesión de arqueología, haciéndolo encontré uno importante el cual es el Cetro de Azj'Aqir (https://es.wowhead.com/item=64883/cetro-de-azjaqir) un objeto bastante raro el cual es una montura, lo aprendí y alrededor de una hora retomé el far-meo, se cayo el servidor, me conecte y sin percatarme del objeto continué con mi far-meo, alrededor de una media hora después me dispuse a usar la montura, para mi sorpresa dicha montura había desaparecido tanto del libro de hechizos como de mis mochilas, la única prueba con la que dispongo, es que la profesión tiene una sección en donde puedes ver todos lo objetos que has conseguido con la misma, y gracias al addon carbonite, también dice la fecha, hora y cantidad de veces que has hecho el objeto en cuestión, espero puedan ayudarme, gracias. 

pruebas: como se puede ver, si hice dicho cetro.
![WoWScrnShot_012220_104256](https://user-images.githubusercontent.com/60186171/72909310-cf947d00-3d04-11ea-814d-4a295e71dd82.jpg)

pero no lo tengo:
![WoWScrnShot_012220_104306](https://user-images.githubusercontent.com/60186171/72909398-f357c300-3d04-11ea-8689-dc2b9987030e.jpg)

![WoWScrnShot_012220_104310](https://user-images.githubusercontent.com/60186171/72909412-f8b50d80-3d04-11ea-8dc9-7547c22f37fa.jpg)
 
si existe alguna duda sobre este caso, estoy dispuesto a dedicarle el tiempo necesario para resolverlo. GRACIAS.

**Comment by athenaswow** [comment]
Este no es el medio correcto para darle una solución a su problema, mas sin embargo ya se le informo a un Game Marter para que te den una pronta solución.
