### ISSUE TITLE
bug dragones: Incitar los elementos Athenas wow

### ISSUE THREAD

**Issue by neslepacks** [athenaswow/BugTracker-Athenas-WoW#136]
Al tomar las moras que se tienen que dar a los dragones el dragon da un dialogo y sale un moob a matar: incitador crepuscular, pero al darles la mora no sale el incitador, y es muy raro q un dragon de el dialogo...

Solo se arregla cuando el servidor se cae porque los moobs se reinician y permiten entrar en dialogo, pero despues de muchos usos del moob se buguea.

Mision: https://es.wowhead.com/quest=25370/instigar-a-los-elementos
Video YouTube: https://www.youtube.com/watch?v=ngKggLcjvtk&t=5s

Gracias.

**Comment by athenaswow** [comment]
Corregido y probado se aplicara en unos días.
