### ISSUE TITLE
Falta Npc Para Completar,  [Guardianes de Hyjal: ¡Invasión de las Tierras de Fuego!]

### ISSUE THREAD

**Issue by newmiguel** [athenaswow/BugTracker-Athenas-WoW#137]
Pj principal: Newzor
Discord: taka (Miguel)#7843
Link de la mision:
https://es.wowhead.com/quest=29389/guardianes-de-hyjal-invasi%C3%B3n-de-las-tierras-de-fuego

Descripción del problema:

Bueno, La cosa es que no aparece el Npc Matogarra id 52669. No se encuentra en el santuario de malorne para poder continuar con la cadena de mision para abrir el portal a frente de magma.

Link de como debería funcionar la misión:

https://www.youtube.com/watch?v=HlTZzzFfiso&feature=emb_logo

Link Del Npc Faltante

https://es.wowhead.com/npc=52669/matogarra

Pruebas del mal funcionamiento.

Recogida de mision.
https://ibb.co/bHwY6Pg

En el Santuario
https://ibb.co/4Wbv2xD
https://ibb.co/jHBYP1v
https://ibb.co/k1S5sqf

**Comment by athenaswow** [comment]
Ya fue reportado.
