### ISSUE TITLE
Bug en el drop (Trepamusgo anciano)

### ISSUE THREAD

**Issue by Arthamix** [athenaswow/BugTracker-Athenas-WoW#138]
Usuario: Arthamix
Nombre de PJ principal: Arthamix
Discord: Arthamix#6111

Como debería funcionar:
Los drops de estas alimañas debería ser según los porcentajes que se presentan a continuación.
![image](https://user-images.githubusercontent.com/60125348/73006108-12735500-3dd8-11ea-9b97-f7366b03a4d2.png)

Como se presenta en el servidor:
No tienen drop alguno sin importar cuantos de estos bichos se maten.
![image](https://user-images.githubusercontent.com/60125348/73006314-6e3dde00-3dd8-11ea-95aa-386c7ad8ec8c.png)

**Comment by athenaswow** [comment]
Corregido.
