### ISSUE TITLE
se me crashea el juego cuado reporto jugador por spam

### ISSUE THREAD

**Issue by KINTO95Z** [athenaswow/BugTracker-Athenas-WoW#139]
pj principal: smorgeetyxc
usuario de discord: no lo uso
Descripcion del problema: se me crashea el juego cuando reporto a un jugador por spam
cuado le doy informar de jugador por-spam... ay se me crashea el juego lo probe como 5 o 7 veses..no se si me pasa ami. o a otros jugadores.solo eso...

**Comment by athenaswow** [comment]
Te agradecería si pudieras dar las suficientes pruebas para poder ayudarte :) https://github.com/athenaswow/BugTracker-Athenas-WoW/blob/master/README.md
