### ISSUE TITLE
Bug en la cadena de las Legendarias del Picaro

### ISSUE THREAD

**Issue by Wolfurion** [athenaswow/BugTracker-Athenas-WoW#14]
Complete la misión de infiltrarse en Ravenholdt y ahora no me da la misión "Nuestro Hombre en Guilneas" Antes me aparecía el icono de la misión sobre Wrathion pero no me la daba, así que no puedo seguir, ya hable con un gm y lastimosamente aunque les muestre el bug por el Discord hay que llorar por acá para que me ayuden. Mi personaje es Sinner.
Gracias por la rápida atención. 
![WoWScrnShot_112419_134801](https://user-images.githubusercontent.com/58147842/69500007-75726980-0ec5-11ea-86fa-248135ebda3a.jpg)

**Comment by athenaswow** [comment]
Necesito mas información sobre este reporte, donde empieza la cadena de misiones y donde termina.
