### ISSUE TITLE
Problemas con misiones en Nagrand

### ISSUE THREAD

**Issue by ivar-dahl** [athenaswow/BugTracker-Athenas-WoW#140]
Nombre del personaje: Pest
Usuario de Discord: Ivar Dahl#4972
Link misión N°1: https://es.wowhead.com/quest=9933/mensaje-para-telaar
Link misión N°2: https://es.wowhead.com/quest=10011/campamento-forja-aniquilado

Descripción del problema: Hola, bueno, básicamente estas misiones pertenecen cada una a una mini cadena de misiones, el problema es que al avanzar en la respectiva cadena de cada una, al llegar al punto en el cual debería recibir estas misiones, los npcs no me dan ninguna misión, probé con reloguear y borrar caché pero el problema persiste. A continuación adjunto capturas de pantalla de los PNJ que dan las respectivas misiones en las cuales se ve que no se puede tomar ninguna misión;

Misión N°1: https://imgur.com/2M45Xxb

Misión N°2: https://imgur.com/BX6KVy8

**Comment by athenaswow** [comment]
Debes abrir un nuevo reporte y especificar en donde y cuando se rompe la cadena de misiones, muchas gracias.
