### ISSUE TITLE
Jefe: Dominamentes Ghur'sha (Trono de las Mareas) Calabozo Normal.

### ISSUE THREAD

**Issue by dunnabugtracker** [athenaswow/BugTracker-Athenas-WoW#141]
Reporte por: **Dunna**
Alter: **Marabela**

**Dominamentes Ghur'sha** 
https://es.wowhead.com/npc=40788/dominamentes-ghursha

**¿Que fallo se presenta?**
Este jefe después de usar "Esclavizar" (https://es.wowhead.com/spell=76207/esclavizar) termina quedándose atascado bajo el suelo y nunca vuelve a salir hasta que haya Wipe. 

**Prueba del fallo**
https://subefotos.com/ver/?5c3930f424ddba9b37eb13da6d331da0o.jpg#codigos

**¿Como debería funcionar?**
El jefe sube encima de la cabeza del jugador para controlarlo, después de que acabe la habilidad "Esclavizar" en el jugador este jefe vuelve a bajar de el y empieza a dar auto ataques.

Mecanicas del jefe:
https://www.youtube.com/watch?v=52uBe67xDRc

**Muchas gracias!**

**Comment by dunnabugtracker** [comment]
Ayer realice dos veces esta mazmorra y este jefe me ha trabajado bien, podría decir que ya se encuentra solucionado.
Muchas gracias al staff de athenas! :)

**Comment by pangolp** [comment]
¿Ya se encuentra solucionado entonces el problema? @dunnabugtracker
