### ISSUE TITLE
Error de entrada portal Maraudon (Mazmorra)

### ISSUE THREAD

**Issue by Srchocorramo** [athenaswow/BugTracker-Athenas-WoW#142]
Hago este post para dar a conocer un error o bug del portal para entrar a la mazmorra Maraudon, me guíe por otro vídeo y en el mostraba que tocaba pasar por el portal para poder entrar y en el caso de Athenas-Wow no funciona. 
Dejo unas imágenes como muestra: https://imgur.com/AelkEi7   https://imgur.com/YkGt87V
en las imágenes trato de dar click sobre el portal y no pasa nada.

Dejo este vídeo como muestra de como debería funcionar: https://www.youtube.com/watch?v=XPV5EFszSOM

Nota: Mi personaje no esta bug ya que puedo usar todos los portales, es el portal que presenta inconvenientes.

**Comment by pangolp** [comment]
Listo, ya tengo un arreglo para este problema, aunque va a requerir de un tiempo para que se aplique. Por el momento, debemos esperar a que el servidor vuelva y luego aplicaremos el cambio correspondiente. Lo unico, **que a diferencia del vídeo, el portal es clickeable**. Otra cosa que desconozco, es si el portal puede ser accedido por todos o si requiere de alguna misión previa.

![WoWScrnShot_020420_192219](https://user-images.githubusercontent.com/2810187/73792755-b5868000-4783-11ea-9fa4-c2f216238257.jpg)

**Comment by pangolp** [comment]
La próxima vez que caiga el servidor, debería de estar solucionado el problema del portal. Una vez que confirmemos eso, daremos por cerrado el tema. Gracias por el reporte.
