### ISSUE TITLE
NPC Ancestro Ohanzee no existente (festival lunar)

### ISSUE THREAD

**Issue by megalocuts** [athenaswow/BugTracker-Athenas-WoW#143]
He estado completando logros por el evento del festival lunar y en eso, me percaté de que este NPC no está en ninguna parte de la mazmorra Gundrak (NM y HC). Me perjudica porque quiero completar los logros y obtener el título Ancestro.

NPC link: https://es.wowhead.com/npc=30537/ancestro-ohanzee#starts
Necesario para el logro https://es.wowhead.com/achievement=910/ancestros-de-las-mazmorras

Imágenes de donde debería estar: https://imgur.com/a/RulTsM7

In-game nick: Freazy
Discord: zkiller#2610

**Comment by ViktorKr0m** [comment]
Sí es el unico NPC faltante, unico que falta para completar logro.

**Comment by athenaswow** [comment]
corregido.
