### ISSUE TITLE
Talento Cólera totémica y totem's de fuego (no cerrar sin antes haber visto evidencias)

### ISSUE THREAD

**Issue by Enfermera** [athenaswow/BugTracker-Athenas-WoW#145]
Hola en la rama elemental del Shaman hay un talento llamado Cólera Totémica https://es.wowhead.com/spell=57658/t%C3%B3tem-de-c%C3%B3lera ,
del cual beneficia con los tótem's de fuego del chaman , ya sea tótem lengua de fuego, abrasador, magma o del elemental de fuego, del cual funciona en todos excepto con Tótem lengua de fuego https://es.wowhead.com/spell=79431/t%C3%B3tem-lengua-de-fuego del cual se desaparece el buff del beneficio de Cólera Totémica reemplazando por el de tótem lengua de fuego en el que se tendrían que quedar los 2 bufos ya que es un talento adicional del que debe dar el tótem. También si estamos en grupo junto con otro chaman si yo siendo chaman elemental uso cualquier tótem de fuego que no sea el de lengua de fuego estaría beneficiado de cólera totémica pero si el otro chaman usa su tótem lengua de fuego automáticamente se desaparece cólera totémica y no debería de funcionar de esa manera... Y no solo es eso en ocasiones si se usa cualquier tótem de fuego pueda que ni salga el beneficio de cólera totémica , ni siquiera lengua de fuego aparece, igual adjunto fotos como evidencia. En la imagen N° 1 se puede evidenciar de que se ha lanzado el tótem lengua del fuego pero no se beneficia del buffo que da el tótem, en la imagen N°2 se ve que si se beneficia del tótem lengua de fuego pero no del buff que da el talento cólera totémica, a diferencia de los demás tótem's de fuego como en las imágenes N° 3, 4 y 5.....
espero pronta respuesta XD, **Mi pj se llama Exenfermera en la horda mi Discord es Ex...#4877**

![1](https://user-images.githubusercontent.com/6820799/73125037-aabd3580-3fa2-11ea-9b73-f7fbe9281900.png)
![2](https://user-images.githubusercontent.com/6820799/73125038-aabd3580-3fa2-11ea-9e68-601ef00e92cc.png)
![3](https://user-images.githubusercontent.com/6820799/73125039-aabd3580-3fa2-11ea-8044-2ed82f3c4349.png)
![4](https://user-images.githubusercontent.com/6820799/73125040-ab55cc00-3fa2-11ea-8390-19121af4a75e.png)
![5](https://user-images.githubusercontent.com/6820799/73125041-ab55cc00-3fa2-11ea-8ce0-7e3e9d5b3c6a.png)

**Comment by athenaswow** [comment]
Ya lo reportaste anteriormente. https://github.com/athenaswow/BugTracker-Athenas-WoW/issues/144
