### ISSUE TITLE
Alquimia: Maestro de transmutacion no sirve

### ISSUE THREAD

**Issue by JOGUER5** [athenaswow/BugTracker-Athenas-WoW#146]
Joguer

Buenas tardes, dentro la profesion de alquimia se subespecializa en diferentes maestros entre ellos esta el de maestro de transmutacion, que genera que al transmutar nos suelte mas materiales de lo normal, dependiendo lo que se transmute, no sucede tal cosa en vez de eso produce "elemento volatil aleatorio" es un item que no sirve para nada.
https://es.wowhead.com/spell=28672/maestro-de-transmutaci%C3%B3n
https://es.wowhead.com/spell=78866/convertir-elementos-vivos#comments

**Comment by Enfermera** [comment]
Si estás transmutando la vida volatil en cualquier elemento aleatorio siempre te va a dar eso junto al nuevo volátil, y sobre el maestro muy bien dice "a veces" eso significa que casi nunca te va a dar más de lo normal XD

**Comment by JOGUER5** [comment]
Bueno, suena triste, pero gracias por responder, a sí corrijan la ubicación
del primer boss de la mazmorra pozo de la eternidad anda mal ubicado
