### ISSUE TITLE
Bug en logro de Festival Lunar de Mazmorras. 

### ISSUE THREAD

**Issue by ezequielhladis2019** [athenaswow/BugTracker-Athenas-WoW#148]
Pj Principal : Quelral 
Id De discord: EžEqUiEł#3985

Descripción del problema: Hola!. Paso a explicar lo que paso, pues estaba haciendo y terminando el logro del Festival Lunar " Ancestros de las mazmorras " ( https://es.wowhead.com/achievement=910/ancestros-de-las-mazmorras ) ya me estaba faltando el ultimo, cual termino siendo " Ancestro Ohanzee en Gundrak " Este npc no esta en la mazmorra, ya que no aparece en ningún lado de la misma, pues hice lo que pude pasando a normal a héroico, o esperando que se reinicie el server y nada, es como si no existiera el mismo, en varios videos se muesta parado al lado del segundo Boss, y este no esta. 

Adjunto pruebas del momento donde estuve en la mazmorra, se ve que no lo tengo completo ni menos se ve que este el icono del ancestro en cuestión que me da una misión para completar. 
https://imgur.com/a/9gwHJTr

https://es.wowhead.com/quest=13065/ohanzee-el-ancestro

**Comment by Darksask** [comment]
Pj principal : Darksask
Id De Discord: sergio sanchez (Darksask)#5394

exactamente me pasa lo mismo no esta el ancestro ohanzee en Gundrak,tengo otro ancestro al que no puedo llegar al acercarme desaparece  dejo el link de video.

https://www.youtube.com/watch?v=uCD6SioV1to

https://es.wowhead.com/npc=30359/ancestro-fargal

**Comment by athenaswow** [comment]
Corregido.
