### ISSUE TITLE
Hechizo: Escudo de Mana. 

### ISSUE THREAD

**Issue by dunnabugtracker** [athenaswow/BugTracker-Athenas-WoW#149]
Reporte por: **Dunna**
Alter: **Marabela**

Escudo de Mana.
https://es.wowhead.com/spell=38151/escudo-de-man%C3%A1

**¿Que fallo se presenta?**
El escudo de mana esta absorbiendo una cantidad de daño muy minima (4k de daño a nivel 85). Recibe tres golpes de un mob y termina agotándose inmediatamente. En Bg ahora mismo es completamente inservible para mi.

**Prueba del fallo**
https://subefotos.com/ver/?3a9aabd27d75218df405310ec13f6958o.jpg#codigos

**¿Como debería funcionar?**
Imaginamos que debería al menos resistir unos ataques básicos en bg... pero no esta así.
Se que no deberia ser como la barrera de hielo... pero es algo absurdo el poco daño que resiste.

**Muchas gracias!**

**Comment by pangolp** [comment]
Buenas tardes, gracias por el reporte. La verdad es que necesitamos mas información para saber si realmente debería de ocurrir de la manera que usted lo menciona. Deberíamos de ver que ocurre con el resto de los personajes. Estamos tratando de recolectar información, pero vamos a depender de encontrarla realmente y del debate que pueda presentarse sobre el tema. Si conoce otros magos, dígale que comenten acá sus experiencias y vemos que podemos llegar a deducir.

**Comment by dunnabugtracker** [comment]
A continuación comparto información del Hechizo **<Escudo de mana>** (Mago) vinculado de la pagina de Youtube. 
Video: https://www.youtube.com/watch?v=FXivT8vUc_w **(Tiempo: 0:35)**
Imagen: https://subefotos.com/ver/?d2f1666bacb8373a3c1e8a3060421416o.png#codigos
Lo cual, prueba que el post que realice el pasado sábado 25 de enero del 2020 sobre este hechizo no presenta ningún fallo al cual deba atenderse. El hechizo <Escudo de mana> esta trabajando bien, Amortiguando entre 5000 (Amortiguacion base al nivel 80) y 9000 de daño tanto físico como mágico. 
Nota: La amortiguacion de este hechizo varia del nivel de objeto adquirido en el personaje.

Me disculpo con el staf. Debí indagar mas sobre este hechizo antes de realizar este post.
De antemano agradezco su atención al post.

**Comment by pangolp** [comment]
No te preocupes, mejor que funcione. Saludos.
