### ISSUE TITLE
Misión: Entre implacables llamas

### ISSUE THREAD

**Issue by Lamela-La-Buscadora** [athenaswow/BugTracker-Athenas-WoW#15]
Lamela
Lamela#3066
Habla con Aggra en Crestaserena, Infralar, para viajar a las Tierras de Fuego.
https://www.youtube.com/watch?v=uejdy4m_u70

Al hablar con Aggra en Infralar nos teletransporta corectamente a las Tierras de Fuego. El error está en que Aggra en Las Tierras de Fuego no es interactiva...
https://www.youtube.com/watch?v=ar1VJv8hNHQ&feature=youtu.be

**Comment by athenaswow** [comment]
corregido
