### ISSUE TITLE
 Festival lunar! no hay ancestros imposible completar evento

### ISSUE THREAD

**Issue by Darksask** [athenaswow/BugTracker-Athenas-WoW#150]
Pj principal : Darksask
Id De Discord: sergio sanchez (Darksask)#5394

1 no se encuentra el ancestro ohanzee en Gundrak, cumbres tormentosas
prueba: https://ibb.co/2NkNFRn
https://es.wowhead.com/npc=30537/ancestro-ohanzee

2 imposible llegar al ancestro fargal en fuerte escarcha,cumbres tormentosas
Descripción del problema : al acercarme desaparece dejo el link de video.

https://www.youtube.com/watch?v=uCD6SioV1to

https://es.wowhead.com/npc=30359/ancestro-fargal

sin estos 2 ancentros no puedo completar el evento.

Gracias.

**Comment by athenaswow** [comment]
Ya reportado..
