### ISSUE TITLE
Bug en misión "Atormentar a los badanudillos" 

### ISSUE THREAD

**Issue by maferozu** [athenaswow/BugTracker-Athenas-WoW#151]
Nombre del personaje: Mafcaza
Link de misión: https://es.wowhead.com/quest=12530/atormentar-a-los-badanudillos
ítem de misión: https://es.wowhead.com/item=38619/grilletes-de-goregek

Descripción del problema: Hola, bueno, en la Colina de corazón frenetico (Cuenca de Sholazar) deberían darme la misión Atormentar a los badanudillos, pero, ni el NPC Goregek (https://es.wowhead.com/npc=28214/goregek-el-cazador-de-gorilas), ni el mismo NPC invocado por (https://es.wowhead.com/item=38619/grilletes-de-goregek) me dan la misión y sin está no puedo seguir la cadena de misiones para las reputaciones "Los Oraculos" y "Tribu Corazón Frenético". A continuación adjunto capturas de pantalla de los NPC que dan la respectiva misión;

 NPC : https://imgur.com/tidRYVQ
NPC invocado: https://imgur.com/HMViF5s

**Comment by athenaswow** [comment]
Te estas saltando alguna misión.
![image](https://user-images.githubusercontent.com/50283962/73219318-d7e82000-4129-11ea-8cab-4efe0433bdae.png)
