### ISSUE TITLE
Ancestro ohanzee - bug en Gundrak

### ISSUE THREAD

**Issue by lfuquene** [athenaswow/BugTracker-Athenas-WoW#152]
Nombre PJ Principal: **Maiorh**
Usuario de discord: **Maiorh#6188**

Buen día, se que este problema ya ha sido reportado varias veces pero he encontrado algunos fallos al tratar de entregar la misión: https://es.wowhead.com/quest=13065/ohanzee-el-ancestro dentro de la mazmorra de **Gundrak**:

1. Al estar paseando por la mazmorra en dificultad **Normal** pude notar que el NPC **"Ancestro ohanzee"** si se encuentra dentro de esta pero en una ubicación incorrecta. Esto se puede evidenciar en la siguiente imagen: https://imgur.com/a/gKowJQd donde en el minimapa sale el NPC el cual se encuentra por los lados del **Santuario de Eck**: https://es.wowhead.com/npc=29932/eck-el-feroz

Pense que al matar a **"Moorabi"**: https://es.wowhead.com/npc=29305/moorabi esta puerta se abriría pero supongo que esto solamente ocurre cuando es Gundrak heroica, tal como se evidencia en esta imagen https://imgur.com/a/s0ZeK69

2. Pense que el NPC **"Ancestro ohanzee"** seguiría en ese mismo lugar si se cambiaba la dificultad a Heroica pero el NPC desaparece, tal como se evidencia en esta imagen: https://imgur.com/a/oBmnpFg

3. Al tratar de encontrar al NPC en la ubicación correcta (la cual es detrás del boss **"Coloso drakkari"**) https://es.wowhead.com/npc=29307/coloso-drakkari este no esta.

Imagen de **Gundrak** en dificultad **Normal**: https://imgur.com/a/6gvamMy
Imagen de **Gundrak** en dificultad **Heroica**: https://imgur.com/a/5pqXpqL

4. Este es el método correcto o evidencia donde el NPC se debería encontrar: https://www.youtube.com/watch?v=s_-zNdg5Ysk (Minuto 02:03 / 02:37)

Agradecería una respuesta, ya que es para completar los logros de https://es.wowhead.com/achievement=910/ancestros-de-las-mazmorras

**Comment by athenaswow** [comment]
En revisión.

**Comment by jeiduart** [comment]
en revisión cuando se acabe el evento? solo es mover un npc.

**Comment by pangolp** [comment]
@jeiduart no es tan simplemente como mover un npc como vos decís, esa es la "solución fácil" pero haciendo eso, se han llenado de porquerías las bases de datos y después los escucho quejarse cuando el servidor se cae. No es moverlo simplemente, las cosas hay que hacerlas bien. De hecho, ya esta el tema solucionado, simplemente me falta agregarlo en el juego de manera oficial.

![WoWScrnShot_013020_163602](https://user-images.githubusercontent.com/2810187/73483695-a1efa980-437e-11ea-94d8-25ca8a339785.jpg)

Sean un poco mas pacientes, nada de lo que hacemos lo hacemos apropósito, todo tiene un porque. Pero si la hacemos de la manera "fácil" tarde o temprano se ven las consecuencias de no hacerlo como corresponde.

**Comment by pangolp** [comment]
Listo, el npc ya fue insertado, pero no voy a tirar el servidor por 1 solo npc faltante, así que cuando el mismo caiga de manera involuntaria, el npc debería de aparecer en la mazmorra. Cuando eso ocurra, avísenme y damos por cerrado el tema. Gracias @lfuquene por el reporte.

**Comment by lfuquene** [comment]
Buenas noches @pangolp, el npc se encuentra funcionando. Gracias por la gestión

![WoWScrnShot_013020_195353](https://user-images.githubusercontent.com/47583598/73503616-c6f21580-439a-11ea-8c8b-0c1ce925a1c5.jpg)

![WoWScrnShot_013020_195401](https://user-images.githubusercontent.com/47583598/73503654-df623000-439a-11ea-9ffa-462e9ecbd3f5.jpg)

**Comment by pangolp** [comment]
Gracias a vos por confirmar. Doy por cerrado el tema.
