### ISSUE TITLE
Bug en el botín de los jefes de estancia.

### ISSUE THREAD

**Issue by jeiduart** [athenaswow/BugTracker-Athenas-WoW#153]
Nombre de PJ: Tainys
Usuario DC: Tairys#8409

Me he encontrado con un problema en el botín de jefes de estancia y ya me a pasado varias veces, pasa muy a menudo en las estancias de burning crusade.

El problema es que muchas veces los jefes no dan objetos azules el cual es su botín, hay veces que dan puramente objetos verdes, deberían dejar 1 objeto azul y el jefe final 2, si se esta haciendo en Heroica.

Nota: la gema no cuenta como objeto en Heroica, eso lo deberían dar la mayoría de jefes cuando haces la estancia en Heroica ademas de su objeto azul o de mayor rareza.

Acá dejo imaginen de los 2 primeros jefes y hay se puede ver lo que me dieron en Heroico https://es.wowhead.com/the-black-morass 

https://es.wowhead.com/npc=17879/cronolord-deja
![lootbug](https://user-images.githubusercontent.com/60366740/73216405-504fe080-412c-11ea-9f25-345e7eacb3d8.png)

https://es.wowhead.com/npc=17880/temporus
![lootbug2](https://user-images.githubusercontent.com/60366740/73216685-d0764600-412c-11ea-9b71-2f8bf122c40c.png)

**Comment by athenaswow** [comment]
Corregido.
