### ISSUE TITLE
Tengo un BUG con algunas misiones 

### ISSUE THREAD

**Issue by maferozu** [athenaswow/BugTracker-Athenas-WoW#154]
Nombre del personaje: Mafcaza

Descripción del problema: Hola, tengo un inconveniente con algunas misiones qué he seleccionado, éstas al ser agarradas desaparecen, osea, qué no aparecen en el registro de misión, ni en el mapa y tampoco me lo da el NPC (de nuevo) y no puedo completarla de ningún modo, no puedo entregarla ya que aparece como si no la hubiera tomado, necesito una solución pronta, ya que esto afecta en mi experiencia de juego al igual en mi LVL, tampoco puedo hacer misiones para subir reputación, anterior mente hice un reporte pensando qué el error era de la misión Atormentar a los badanudillos (https://github.com/athenaswow/BugTracker-Athenas-WoW/issues/151) pero la solucion era qué me volé una misión, pero pueden comprobar que no lo hice, en cuenca de Sholazar no me dan ninguna misión más (lo volé todo buscando misiones y vi guías) entonces con esas y una en Monte Hyjal me ha pasado eso 3 veces.

Prueba 1: https://imgur.com/dgrzMg1 (tomé la misión del tablero) 
Prueba 2: https://imgur.com/BDheXbn (se la entregué a Naraat y tomé la otra misión, la que me debería llevar a Infalar)
Prueba 3: https://imgur.com/vDkINix (no tengo la misión en el historial, tampoco la completé) 
Prueba 4: https://imgur.com/kkKlPM0 (como pueden ver tampoco me aparecen misiones para tomar/entregar en Infalar)
Prueba 5: https://github.com/athenaswow/BugTracker-Athenas-WoW/issues/151 (mi reporte anterior con lo sucedido en Cuenca de Sholazar)
Prueba 6: https://imgur.com/Oz9nO3f (creo que fue con este NPC lo qué pasó en Monte Hyjal)

NOTA: cabe recalar que no pasa con todas las misiones, solo con algunas y es muy aleatorio.

**Comment by Seigan94** [comment]
También me acaba de pasar, sin embargo, no anote el nombre de la misión, era una de una cadena en la isla Draenei, en donde me pedía coger barco a Auberdine y presentarme, la misión desapareció del NPC, pero oh sorpresa me lleve cuando al llegar a Auberdine la misión no la tenia en el registro.

**Comment by athenaswow** [comment]
El Npc ya esta en su lugar para que puedas seguir, si se te presenta de nuevo el problema porfavor elabora un mejor reporte con mas pruebas como lo dice en los requisitos Gracias :).
