### ISSUE TITLE
bug en la profesión desuello  

### ISSUE THREAD

**Issue by darkhalow** [athenaswow/BugTracker-Athenas-WoW#155]
mi pj principal es wolff
en la profesión de desuello al matar a los npc y despojarlos no deja sacarles el cuero ya que aparece que primero hay que despojar a la criatura pero al darle despojar no tiene nada.
esto no pasa siempre creo que solo pasa cuando matas al npc y rápidamente lo despojas pero cuando mato al npc y espero unos segundos y lo despojo no pasa
prueba 1: https://ibb.co/0FtZQRw  al matar al npc y despojarlo no deja sacarle el cuero y aparece la opción de despojarlo pero no tiene nada 
prueba 2: https://ibb.co/fkYjn86 al darle directamente con la habilidad de desuello dice que primero hay que despojar a la criatura

**Comment by athenaswow** [comment]
Corregido.. https://es.wowhead.com/item=33567/trocitos-de-cuero-boreal 80.53%
https://es.wowhead.com/item=33568/cuero-boreal  40.44%
https://es.wowhead.com/item=44128/pelaje-%C3%A1rtico 2.03%
