### ISSUE TITLE
bug despojar poseidus

### ISSUE THREAD

**Issue by neslepacks** [athenaswow/BugTracker-Athenas-WoW#156]
Hola, estaba farmenado y me encontre a poseidus y no lo pude despojar, aqui adjunto pruebas 
https://www.youtube.com/watch?v=rwU2UwTLliw&t=2s
https://imgur.com/gallery/KOmHqMn
gracias

**Comment by athenaswow** [comment]
Ya fue corregido se implementara en unos días.
