### ISSUE TITLE
No hay "Engarce de joyero"

### ISSUE THREAD

**Issue by jackdown1010** [athenaswow/BugTracker-Athenas-WoW#157]
PJ: Celestiana
Usser Discord: jackdown1010#0731
item: https://es.wowhead.com/item=52188/engarce-de-joyero
En los <suministros de joyeria> se supone que venden este ítem pero ninguno los vende y es algo primordial para la profesión en si.
![WoWScrnShot_012820_221501](https://user-images.githubusercontent.com/60414221/73323034-78b70800-421c-11ea-8851-a69ae9676c05.jpg)
![WoWScrnShot_012820_222103](https://user-images.githubusercontent.com/60414221/73323035-78b70800-421c-11ea-8371-17643c453b26.jpg)

**Comment by pangolp** [comment]
Hola, ¿que paso que cerraste el tema?

**Comment by pangolp** [comment]
Falta agregarle el engarce al vendedor de Dalaran.

**Comment by athenaswow** [comment]
Corregido.
