### ISSUE TITLE
No hay maestro de hipogrifos en El Exodar

### ISSUE THREAD

**Issue by Seigan94** [athenaswow/BugTracker-Athenas-WoW#158]
PJ Principal: Pethor
Link WoWHead: https://es.wowhead.com/npc=17555/stephanos#screenshots
El NPC no aparece en donde marca el minimapa, y se comprueba la ubicación con la misión https://es.wowhead.com/quest=9606/regresa-junto-a-la-cuidadora-chellan
Link adicional: https://cata-twinhead.twinstar.cz/?npc=17555#.
Adjuntos: 
![WoWScrnShot_012920_125042](https://user-images.githubusercontent.com/60443191/73384821-084ecc00-429a-11ea-83ea-fa8b5ef4ff86.jpg)

**Comment by athenaswow** [comment]
Corregido.
