### ISSUE TITLE
NPCs flotando en el puerto que lleva de Auberdine a Ventormenta

### ISSUE THREAD

**Issue by Seigan94** [athenaswow/BugTracker-Athenas-WoW#159]
PJ Principal: Pethor
Hay NPCs que permanecen flotando en la bahía del puerto que conduce de Auberdine a Ventormenta
Adjuntos: 
![WoWScrnShot_012920_131631](https://user-images.githubusercontent.com/60443191/73384853-18ff4200-429a-11ea-82b8-280441b164b5.jpg)

**Comment by athenaswow** [comment]
En revisión.

**Comment by athenaswow** [comment]
Corregido.
