### ISSUE TITLE
Logro: Heroico: Hermandad en Las Cámaras de Reflexión

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#16]
Nombre de personaje principal: Skala
Usuario de discord: JorDaNN # 5575
Descripción del error: Al terminar la mazmorra o sea justo ahí donde se ve la primera foto que sylvanas bloquea la entrada con piedras, ahí mismo termina la mazmorra y es donde tendría que salir el logro. El logro sale para cada personaje más no para la hermandad, aún así teniendo el grupo de hermandad activo.
![WoWScrnShot_112419_145332](https://user-images.githubusercontent.com/58092128/69500973-3dbbef80-0ece-11ea-8246-6de182e667e9.jpg)
Logro para jugadores: https://es.wowhead.com/achievement=4521/heroico-las-c%C3%A1maras-de-reflexi%C3%B3n#english-comments 
![WoWScrnShot_112519_082830](https://user-images.githubusercontent.com/58092128/69544388-9e463d80-0f5d-11ea-9121-4c3b4c98eda8.jpg)
Logro para la hermandad:  https://es.wowhead.com/achievement=5114/heroico-hermandad-en-las-c%C3%A1maras-de-reflexi%C3%B3n
![WoWScrnShot_112519_080356](https://user-images.githubusercontent.com/58092128/69544687-3e03cb80-0f5e-11ea-9179-bb40516bc6b7.jpg)

**Comment by DennisCalderon** [comment]
actualmente bajo revisión

**Comment by DennisCalderon** [comment]
Reparado, el próximo martes se aplicará el parche al servidor
