### ISSUE TITLE
Mision bugg [La purificación de Quel'Delar]

### ISSUE THREAD

**Issue by Abhyl** [athenaswow/BugTracker-Athenas-WoW#160]
Main: Abhyl
Alter de la mision: Waspain
DC: Abhyl#3010
enlaces de como se hace la mision
https://www.wowhead.com/quest=24564/the-purification-of-queldelar
https://youtu.be/i0KB-rAJER0?t=10

Evidencia del bugg:
https://youtu.be/5YuGnt_ZTUc

Hola estoy haciendo la cadena de misiones de la empuñadura titanica voy en [La purificación de Quel'Delar] y hago todo como deberia pero cuando acaba la animacion de los npc y voy a recoger el item de la mision "Quel'Delar restaurada" no sale el engrane de interaccion solo necesito ese item para completarla. gracias :3

**Comment by pangolp** [comment]
Perfecto, gracias por el reporte, estamos en revisión del problema.

**Comment by athenaswow** [comment]
Corregido.

**Comment by Abhyl** [comment]
Gracias!

**Comment by millonario30** [comment]
Pj: Fhenrir
Discord: Fhenrir #9869
Tuve exactamente el mismo problema, vengo desarrollando la cadena de misiones de la empuñadura maltrecha y cuando llegue a la misión ''La purificación de Quel'delar'' fui a la meseta de la fuente del sol. Los npc empezaron a hablar y me pedía que arroje la espada a la fuente del sol para purificarla y luego no paso mas nada, no puedo agarrar la espada (no sale el engranaje de interacción) y por lo tanto no puedo entregar la misión en la corona de hielo y tampoco tengo mas el item y no quiero abandonar la misión por que perderé la empuñadura que era el objeto con el que comenzaba la cadena.
Añado el link donde muestra la misma cadena de misiones de la empuñadura: https://www.youtube.com/watch?v=-x-mI5tDXIE
Por favor, ayuda y muchas gracias

**Comment by jeiduart** [comment]
¿la misión la repararon?
