### ISSUE TITLE
(Quest) Un esfuerzo asombroso ID: 26557

### ISSUE THREAD

**Issue by colomboalexx** [athenaswow/BugTracker-Athenas-WoW#161]
Pj principal: Vlaxar
Usuario de discord: Vlaxar#4402
Descripcion: la mision consiste en matar un venado en azshara y aplicar a la caña el ojo de venado. al intentar pescar carpa arenosa que se encuentra en el valle de la sabiduria en orgrimmar, deberia dar este objeto https://es.wowhead.com/item=58946/carpa-arenosa
Prueba del loot: https://imgur.com/XhaH9c6
Como deberia funcionar la mision: https://www.youtube.com/watch?v=is4VhvQMih8

**Comment by pangolp** [comment]
Bien, en otras palabras, ¿el problema es que no aparece el item para lootear? Porque según el vídeo, no sale fácilmente, se ve que tiene una probabilidad media baja de aparecer. Funcionaria todo menos el loot, ¿eso es lo que usted quiere decir?

**Comment by pangolp** [comment]
Supongo que en este lugar, debería de aparecer la carpa.

![WoWScrnShot_013020_172857](https://user-images.githubusercontent.com/2810187/73487650-27c32300-4386-11ea-90f4-395f586f9fe9.jpg)

![WoWScrnShot_013020_172722](https://user-images.githubusercontent.com/2810187/73487659-2b56aa00-4386-11ea-8d18-92ea798caf5f.jpg)

**Comment by pangolp** [comment]
Ya se aplico un fix, ahora vemos que pasa cuando el servidor reinicia.

![WoWScrnShot_013020_214435](https://user-images.githubusercontent.com/2810187/73504407-1130c200-43ae-11ea-9bd3-f421712b614f.jpg)

![WoWScrnShot_013020_214438](https://user-images.githubusercontent.com/2810187/73504408-142bb280-43ae-11ea-843b-bb9d650aa8a8.jpg)

Entre las correcciones:
- Se elimino el ojo si no estas en la quest, para que no lo tire mas.
- No te da mas de un ojo.
- Creo que logramos reparar la quest.

Habra que probar luego del reinicio a ver como funciona.

**Comment by colomboalexx** [comment]
intente pescar en el lugar que me recomendaste, 20 minutos pescando y nada; intente de todo y aqui tengo las pruebas
https://imgur.com/aiDqjVs
https://imgur.com/nQ9GQ6z
intenten arreglarlo por favor, ya voy perdiendo sin exagerar 20 misiones de pesca y de cocina por estos bugs
Personaje principal: Vlaxar
Discord: Vlaxar#4402

**Comment by pangolp** [comment]
Si, ya detectamos cual es el problema, pero para solucionarlo necesitamos tirar el servidor un par de minutos y hacer unos cambios, por lo que pronto tendrán novedades al respecto. Pasa que tampoco se puede tirar en todo momento. Hay que buscar el momento en el que menos jugadores online haya o avisar con tiempo para evitar problemas.

**Comment by colomboalexx** [comment]
espero la respuesta para cuando lo arreglen

**Comment by pangolp** [comment]
No deberíamos de tarda demasiado en aplicar el cambio, pero como hay que tirar el servidor y veníamos de un mantenimiento de 8 horas, no quisimos dejarlos mucho tiempo sin jugar, próximamente, tendrán novedades al respecto.
