### ISSUE TITLE
mision de pesca: prohibido lanzar residuos BUG

### ISSUE THREAD

**Issue by colomboalexx** [athenaswow/BugTracker-Athenas-WoW#162]
Pj principal: Vlaxar
Usuario de discord: Vlaxar#4402
Descripcion: en la mision hay que ir a pescar a los suburbios goblin en orgrimmar. al pescar deberia dar este objeto https://es.wowhead.com/item=58945/pez-esp%C3%A1tula-t%C3%B3xico
Prueba del loot: https://imgur.com/rXmrqTU
Como deberia funcionar la mision: https://www.youtube.com/watch?v=6OZBsBtYGHQ

**Comment by athenaswow** [comment]
Corregido.
