### ISSUE TITLE
mision de cocina: hasta los ladrones tienen hambre BUG

### ISSUE THREAD

**Issue by colomboalexx** [athenaswow/BugTracker-Athenas-WoW#163]
Pj principal: Vlaxar
Usuario de discord: Vetoxx#4402
Descripcion: al aceptar la mision hay que ir a matar ladrones de orgrimmar (https://es.wowhead.com/npc=42594/ladr%C3%B3n-de-orgrimmar) que deberian dropear este objeto https://es.wowhead.com/item=57879/raciones-de-infanter%C3%ADa-de-la-horda
Prueba de la ausencia del NPC: https://imgur.com/oy9QnpO
Como deberia funcionar la mision: https://www.youtube.com/watch?v=AZXF-ncKk94

**Comment by athenaswow** [comment]
Corregido.
