### ISSUE TITLE
Imposible hablar con el Ancestro Fargal en fuerte escarcha!

### ISSUE THREAD

**Issue by Darksask** [athenaswow/BugTracker-Athenas-WoW#164]
Pj principal : Darksask
Id De Discord: sergio sanchez (Darksask)#5394

Hola buenas noches tengo un problema con el ancestro fargal de fuerte escarcha en cumbres tormentosas pues al acercarme desaparece impidiendo terminar con el festival lunar siendo el ultimo ancestro para obtener el logro Honrar a los ancestros personales,espero puedan ayudarme a finalizar el evento.
Gracias
 wowhead:https: //es.wowhead.com/npc=30359/ancestro-fargal
prueba en video: https://www.youtube.com/watch?v=ZlTpkpNckHo

**Comment by pangolp** [comment]
Bien, eso es sencillo de explicar. En esa zona, en **cumbres tormentosa** en general, tenes varios cambios de fase, el tema es que ese ancestro, tendria que ser inmune a esos cambios. **Que los otros npc aparezcan y desaparezcan es normal**, porque depende de las misiones **completadas**, pero en particular los npc de evento no debería de ser afectados. Déjame corroborar el error, porque hasta ahora nadie mas había reparado ese problema.

**Comment by pangolp** [comment]
Ya debería de estar funcionando el npc, si podes probarlo y avísame.

![WoWScrnShot_013020_234334](https://user-images.githubusercontent.com/2810187/73508346-61ae1c80-43ba-11ea-9d24-d7fff8ca40a6.jpg)

**Comment by Darksask** [comment]
hola estoy mirando y a un sigo sin poder verlo T_T  y de echo estoy tratando de hacer todas las misiones para ver si alguna me manda alli pero ya no me dan mas ya e recorrido todo cumbres y nada solo misiones diarias 

imagen: https://ibb.co/Vvyszc2

**Comment by pangolp** [comment]
> hola estoy mirando y a un sigo sin poder verlo T_T y de echo estoy tratando de hacer todas las misiones para ver si alguna me manda alli pero ya no me dan mas ya e recorrido todo cumbres y nada solo misiones diarias
> 
> imagen: https://ibb.co/Vvyszc2

Que extraño, bueno tratare de seguir investigando pero el problema es ese, justo el npc se encuentra en una zona que te afecta a vos como jugador, por las misiones que tenes realizadas, dada que las misiones de cumbres tormentosas, afectan el mapa en la medida que vas desarrollando la historia. No es el mismo mapa cuando arrancas que cuando terminas la cadena y descubrís a muradin.

**Comment by Darksask** [comment]
ok vale y gracias ojala se puede terminar de alguna manera.

**Comment by pangolp** [comment]
Efectivamente el tema es un problema de fases, porque vos estabas en la fase 4 y el npc en la fase 1. Te deben faltar misiones por completar en el área, aunque lo extraño es que el evento no debería de afectar en eso. Termina si podes de hacer todas las quest de la zona hasta conseguir ver a muradin. Si lo terminas antes del evento mejor, así me saco la duda. Gracias.
