### ISSUE TITLE
Una distracción que desarma, no está la misión

### ISSUE THREAD

**Issue by yongkuon** [athenaswow/BugTracker-Athenas-WoW#165]
La misión "Una distracción que desarma" no está disponible.
En Uldum, al ir donde se encuentra Terminal A.I.D.A. ( https://es.wowhead.com/object=206293/terminal-a-i-d-a ), la misma no da la misión: https://es.wowhead.com/quest=27761/una-distracci%C3%B3n-que-desarma
en el nivel 83 como debería.
Muestro un screen de lo que me dice en Athenaswow al seleccionar A.I.D.A:
https://i.imgur.com/a5mhxzG.jpg
Muestro como debería ser la quest:
https://cata-twinhead.twinstar.cz/?quest=27761

El nombre de mi personaje principal es: Lujin, maga alianza
mi usuario de discord es: Bongssao#9399

**Comment by athenaswow** [comment]
En revisión.

**Comment by athenaswow** [comment]
Corregido junto con la mision https://www.wowhead.com/quest=28501/the-defense-of-nahom, la mision entregada por el item https://www.wowhead.com/item=62483/a-i-d-a-communicator.
