### ISSUE TITLE
Bug Festival Lunar, ancestros de las mazmorras

### ISSUE THREAD

**Issue by Elmaxwell12** [athenaswow/BugTracker-Athenas-WoW#166]
El ancestro Ohanzee de la mazmorra Gundrak [https://es.wowhead.com/npc=30537/ancestro-ohanzee](url) se encuentra en una zona inaccesible en modo normal y en modo en heroico el npc desaparece de la zona en la que se debería encontrar. 

Me gustaría que lo re ubicaran ya que actualmente en el servidor oficial el npc se encuentra es detrás del Jefe Coloso Drakarri https://es.wowhead.com/npc=29307/coloso-drakkari o si no se puede que al menos el npc no desaparezca al momento de entrar a la mazmorra en modo normal, ya que el npc hace parte del logro https://es.wowhead.com/achievement=910/ancestros-de-las-mazmorras y sin el, dicho logro no se puede completar.

Nombre del Jugador: Maxjadden
Nombre en Discord: ElMaxwell12#2308

Gracias...

**Comment by pangolp** [comment]
Buenas tardes, hasta el momento no se había reportado errores de este tipo. Si estaba faltando el npc y lo reubicamos detrás de lo que seria el segundo jefe, de hecho, muchos pudieron acceder al logro que mencionas. El hecho de que este en una zona inaccesible, me llama mucho la atención. Lo que estoy tratando de averiguar, es si el npc debería de estar tanto en la modalidad heroica, como en la modalidad normal. Hasta ahora, lo que logre encontrar no revela el hecho de que exista de forma simultanea en ambas instancias. Por lo que si llegas a encontrar información al respecto y me la podes compartir excelente, mientras tanto, reviso eso de la zona inaccesible y la desaparición del npc.

**Comment by pangolp** [comment]
En dificultad normal, sin matar al primer jefe, me fui por el camino de la derecha (cuando miras al boss), y matando al segundo boss, llegue hasta el ancestro sin problemas.

![WoWScrnShot_013120_172623](https://user-images.githubusercontent.com/2810187/73572386-6b359400-444f-11ea-8fed-115da44a3bc4.jpg)

Luego, también mate al primer jefe, me sumergí en el agua y puede llegar el. (siempre en normal). Ahora probare el modo heroico.

![WoWScrnShot_013120_172832](https://user-images.githubusercontent.com/2810187/73572433-8accbc80-444f-11ea-8e6d-4d3d2e1b1140.jpg)

**Comment by pangolp** [comment]
En modo heroico, hice el mismo procedimiento, sin matar al primer jefe, fui hasta donde debería de estar el npc y lo encontré, pude interactuar con el sin problemas.

![WoWScrnShot_013120_173433](https://user-images.githubusercontent.com/2810187/73572732-4b52a000-4450-11ea-9154-ea61bbe44c15.jpg)

Elimine al jefe y en ningún momento me dio ningún mensaje de zona inaccesible, ni nada.

![WoWScrnShot_013120_173503](https://user-images.githubusercontent.com/2810187/73572762-5e657000-4450-11ea-830b-9d5660db87b6.jpg)

Por ultimo, mate al primer jefe y también puede llegar a el sin problemas.

![WoWScrnShot_013120_173606](https://user-images.githubusercontent.com/2810187/73572787-6f15e600-4450-11ea-93dd-f31ad6b581c3.jpg)

Nose que otra prueba realizar.
