### ISSUE TITLE
BUG EN SISTEMA PVE

### ISSUE THREAD

**Issue by HANORAK** [athenaswow/BugTracker-Athenas-WoW#168]
Soy jugador PVE y recien empece a jugar en el server, me arme con la armadura de justicia que es 378 de item level y de pronto me enteré de que no se hacen tierras de fuego para equiparse ya que con ese item level tan bajo se puede hacer Alma de dragón, esto afecta la experiencia PVE y limita a disfrutar de bandas que son esenciales tanto para la expansión como para armarse, como lo es tierras de fuego.
Me gustaria que arreglaran el sistema ya que es necesario pasar por tierras de fuego para poder hacer Alma de dragón, ya que tierras de fuego HC otorgan items 391, lo cual es el necesario para hacer alma de dragón y así lograr una trayectoria fluida respecto a la subida de item level, y no simplemente hacer un salto grandísimo entre el 378 y 397 de item level.
Nombre del Jugador: Hanorak
Nombre en Discord: HANORAK64#1310

**Comment by Alfonsmd** [comment]
Si se esta en el ultimo parche de cataclismo, es normal que ni dios haga tf y no sea necesario pasar directamente por ahí para hacer ds.

**Comment by athenaswow** [comment]
No lo tomes a mal te agradezco por el reporte pero en verdad no veo ningún fallo que arreglar, Si la gente no quiere armar Tierras de fuego no se les puede obligar.
