### ISSUE TITLE
BUG BG, CUMBRES GEMELAS

### ISSUE THREAD

**Issue by zolr4k** [athenaswow/BugTracker-Athenas-WoW#169]
**Mi PJ Principal**: Xghul
**Discord:** .-Carlz #0699

En el mapa de (BG) Cumbres Gemelas, el jugador que tomó la bandera se cayó al vació pero al parecer no murió, haciendo así que la partida quedara bug.

**Pruebas:**

https://www.youtube.com/watch?v=XZ2K4RAkFSs

**Comment by athenaswow** [comment]
Hola zolr4k mira este problema viene directamente desde el oficial, estas cosas aun siguen pasado aya emm quizá mas adelante de nos ocurra algo para darle una solución Gracias.
