### ISSUE TITLE
Misión: A puerta cerrada (Desolace)

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#17]
Nombre de personaje principal: Skala
Usuario de discord: JorDaNN#5575
Descripción del error: El npc que completa la misión aparece hostil. Cabe decir que antes de obtener la misión el npc no aparecía de esta forma. Creí que se podría tratar por las 2 facciones que se encuentra aquí Centauros del clan gelkis y centauros del clan Magram, pero corrobore subiendo una de ellas a amistoso y la otra odiada, y viceversa ya que no se pueden tener ambas en positivo. También lo corrobore con un GM por si pedía más reputación pero a él también le aparecía en hostil.
![WoWScrnShot_112519_104828](https://user-images.githubusercontent.com/58092128/69555629-782a9880-0f71-11ea-8770-6260eff942b4.jpg)
![WoWScrnShot_112519_104813](https://user-images.githubusercontent.com/58092128/69556502-d1df9280-0f72-11ea-828a-648de1936d90.jpg)

![WoWScrnShot_112519_110339](https://user-images.githubusercontent.com/58092128/69557942-6814b800-0f75-11ea-8b85-b89cf8f4b4c5.jpg)

Misión wowhead: https://es.wowhead.com/quest=14330/a-puerta-cerrada
Como debería funcionar: https://www.youtube.com/watch?v=XjDDvIRNblg

**Comment by athenaswow** [comment]
corregido.
