### ISSUE TITLE
Npc de area 52 no vende armadura de cazador

### ISSUE THREAD

**Issue by tr00lx** [athenaswow/BugTracker-Athenas-WoW#170]
Personaje: Bozhidar
usuario de discord: Медведь#6748

El npc Kezzik el Asediador no aparece en el area 52, tormenta abisal, es el que vende la armadura que se muestra en la captura,  (Fogato Ardemagma los vende igual, pero este es de legion, y ya es otra cosa).
Las capturas
https://ibb.co/9bhNKgV

El NPC que los vende
https://es.wowhead.com/npc=54650/kezzik-el-asediador

Se puede ver que no los vende en Wowhead, pero en realidad en esta expansion de cata si lo hace.

**Comment by athenaswow** [comment]
Quizá revisaste en el lugar incorrecto.
![image](https://user-images.githubusercontent.com/50283962/73698773-0d53b700-46b0-11ea-9f91-fcec26c2e941.png)
