### ISSUE TITLE
mision de pesca: prohibido lanzar residuos BUG

### ISSUE THREAD

**Issue by colomboalexx** [athenaswow/BugTracker-Athenas-WoW#171]
PJ principal: Vlaxar
Discord: Vlaxar#4402
hice este mismo ticket hace un par de dias y lo cerraron por alguna razon que desconozco
Objetivo de la mision: pescar 6 https://es.wowhead.com/item=58945/pez-esp%C3%A1tula-t%C3%B3xico en los suburbios goblin ubicado en orgrimmar; pero al momento de pescar no salen peces como loot; aqui la prueba
https://imgur.com/noIh3vK
espero lo arreglen por favor

**Comment by athenaswow** [comment]
Ya fue reportado y corregido, el cambio se implementara en unos días.
