### ISSUE TITLE
Error del juego que provoca que se cierre el cliente

### ISSUE THREAD

**Issue by Lluvatar** [athenaswow/BugTracker-Athenas-WoW#172]
Desde hoy comence a experimentar un error que cierra el juego cuando visite infralar tuve que usar la herramienta de desatascar el personaje por que no podía entrar con el a esa zona, luego me sucedió en ventormenta con otro de mis personajes.

PJ Main: Yerim

Discord: RACEC#8161

Este es el código del error: #134 0x85100086
![Captura de pantalla (6)](https://user-images.githubusercontent.com/60628679/73698783-50f1f500-469f-11ea-88b6-e92119891628.png)

**Comment by pangolp** [comment]
¿Tenes descargado el cliente completo o aun se esta descargando? Porque ha estado ocurriendo errores con la versión minimal. Seria conveniente intentar descargar de una vez el cliente completo. Pero si el cliente esta completo, entonces el problema puede estar en otro lado.

**Comment by pangolp** [comment]
Al parecer, el problema es que todos los clientes minimal, **dejaron de funcionar**, por lo que no hay mas remedio que volver a descargar el cliente de manera completa esta vez, para no depender de esos servidores que dejaron de funcionar, **pero esto es independiente de athenas, es a nivel general.**

[Descarga por Google Drive](https://mega.nz/#!pMZ1kCaD!mYcRARcyEjpeYdBPAp2ZQZANdizmQbM2CkQVBvm7Vlc) o [ Descarga por Mediafire](http://www.mediafire.com/file/6bewlj91i111lju/World_of_Warcraft_4.3.4.15595_esES.rar/file)

Aunque el de Mediafire, no estoy 100%, el de google drive seria el oficial.
Pero no queda otra que probar, lamentablemente nos afecto a todos.
Saludos.
