### ISSUE TITLE
Mision Cuenca de Sholazar (Npc no otorga la mision)

### ISSUE THREAD

**Issue by mctac** [athenaswow/BugTracker-Athenas-WoW#174]
**Nombre del Pjta:** Gathubela
**Nombre de User Discord:** Dragonethh#9304
**Link de la Mision Problema:** https://es.wowhead.com/quest=12530/atormentar-a-los-badanudillos
Descripcion: La mision **[quest=12530]** "Atormentar a los badanudillos" que deberia ser otorgada por el [**npc=28214]** "Goregek el Cazador de gorilas" no esta activa, ya que al invocarlo con el **item [item=38619]** "Grilletes de Goregek" solamente aparece y no te proporciona dicha misión, mas al contrario te salta otra misión que es próxima y por supuesto al aceptarla te aparece "No cumples los Requisitos para Esta Misión", les pido por favor corrijan este error ya que es necesaria para subir la reputación de "Tribu Corazón Frenético".
Nota: Esta misión es otorgada después de completar la misión **[quest=12529]** "El esclavo del cazador de monos" única cadena de misiones para subir la reputación.
Dejo las imágenes a continuación. Y gracias por su tiempo, buenas tardes.
1.- https://imgur.com/gGStzBk (entrega de la mision anterior)
2.- https://imgur.com/We7FN8d (mision futura que te salta)
3.- https://imgur.com/QVpziKT (No cumples lo requisitos para esa mision futura obviamente)
4.- https://imgur.com/Kns7GPA (El Npc no te otorga la cadena de misiones)

**Comment by athenaswow** [comment]
Ya fue corregido te pido que esperes mientras se implementa la corrección.
