### ISSUE TITLE
No viaja a Rasganorte

### ISSUE THREAD

**Issue by eselandrey** [athenaswow/BugTracker-Athenas-WoW#175]
pj principal: Sombramoon

https://www.youtube.com/watch?v=FWcYMhWuKHI&feature=youtu.be

**Comment by eselandrey** [comment]
Se reinició, se eliminó  y se reinstaló full (videojuego completo) luego se descargó el cliente y se instaló y no se puede viajar a rasganorte. Ni de ogrimar, ni de claros de Cristal. Gracias.

**Comment by pangolp** [comment]
Al desconectarte, **¿donde aparece tu personaje?** Trataré de hacer la prueba. Por lo que veo es el que está frente a **Entrañas.** ¿El de durotar tiene el mismo problema?

**Comment by pangolp** [comment]
Lo acabo de probar y al menos el de durotar funciona bien.

![WoWScrnShot_020620_085624](https://user-images.githubusercontent.com/2810187/73935262-e61f0480-48be-11ea-8eb6-34ee60fe9303.jpg)

![WoWScrnShot_020620_085634](https://user-images.githubusercontent.com/2810187/73935267-ea4b2200-48be-11ea-906d-766e43550262.jpg)

![WoWScrnShot_020620_085745](https://user-images.githubusercontent.com/2810187/73935285-efa86c80-48be-11ea-99c7-6005d0d59057.jpg)
