### ISSUE TITLE
Error pequeño, pero sigue siendo un error

### ISSUE THREAD

**Issue by Srunholy** [athenaswow/BugTracker-Athenas-WoW#176]
PJ: Irinne - Maga
Discord: SrUnholy#7035
Descripcion: En Orgrimmar (al lado del banco de valle de la fuerza)  se encuentra este "Yunque del herrero" en este lugar y no debería estar ahí, es un error pequeño pero bueno, son detalles visuales que no son molestos pero que de una u otra forma son un error.
Prueba: https://imgur.com/gallery/Gj5K6Yk

**Comment by athenaswow** [comment]
Corregido.
