### ISSUE TITLE
Bug en misiones Planes diabolicos! 

### ISSUE THREAD

**Issue by ViktorKr0m** [athenaswow/BugTracker-Athenas-WoW#178]
Hola jugadores y creadores, soy ViktorKrum Shadow priest Horda; les quería compartir un bug que he encontrado en una mision que se recoje por loot, llamada Planes diabolicos: https://es.wowhead.com/item=23780/planes-diab%C3%B3licos 
La cual permite acceder a esta misión: 
https://es.wowhead.com/quest=26443/planes-diab%C3%B3licos

el bug es el objeto ya que al seleccionarlo y darle click sucede esto: 
![WoWScrnShot_020720_011303](https://user-images.githubusercontent.com/59740192/74042470-99f2c380-4995-11ea-9e45-d6acca8d45b0.jpg)

considero que debe ser arreglada esta quest ya que es el único logro que no se puede conseguir hasta el momento en las misiones en Kalimdor. 
![WoWScrnShot_020720_011330](https://user-images.githubusercontent.com/59740192/74042537-bc84dc80-4995-11ea-8c83-49ada2f56710.jpg)
Saludos!

**Comment by athenaswow** [comment]
Corregido.
-- la mision https://es.wowhead.com/quest=26447/planes-diab%C3%B3licos requiere de aver completado la mision  26448 horda

-- la mision https://www.wowhead.com/quest=26443/diabolical-plans requiere de aver completado las misiones id  26444 y 26446 alianza
