### ISSUE TITLE
mision crece tan deprisa

### ISSUE THREAD

**Issue by terrocaos** [athenaswow/BugTracker-Athenas-WoW#179]
despues de completar las diarias conseguir los materiales y despues de conseguir el oro la mision sale para entregar pero no deja entregarsela al npc de crater`un goro

**Comment by athenaswow** [comment]
Hola, trata de facilitarnos mas pruebas para poder ayudarte.
![image](https://user-images.githubusercontent.com/50283962/74079494-4d939c00-4a06-11ea-8f8b-36e1b7e6b792.png)
