### ISSUE TITLE
Misión: La bruja anciana (Las Mil Agujas)

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#18]
Nombre de personaje principal: Skala
Usuario de discord: JorDaNN#5575
Descripción del error: La misión debería completarse al terminar de hablar con el npc liberado e igualmente debería dar la misión siguiente pero no se puede completar. Fui al npc que me dio la misión y a la posición siguiente para continuar con esta cadena de misiones pensando que podría completarlas ahí pero de ninguna de las formas lo pude conseguir. 

![WoWScrnShot_112519_103526](https://user-images.githubusercontent.com/58092128/69559002-2d138400-0f77-11ea-951b-73809d62e284.jpg)

![WoWScrnShot_112519_103714](https://user-images.githubusercontent.com/58092128/69559232-8b406700-0f77-11ea-9cdf-49f6c37761d7.jpg)

Misión wowhead: https://es.wowhead.com/quest=28140/la-bruja-anciana#english-comments
Como debería funcionar: https://www.youtube.com/watch?v=OL3ZfsaPxYs

**Comment by athenaswow** [comment]
corregido.
