### ISSUE TITLE
Misión desaparecida por caída y perdida total de reputación

### ISSUE THREAD

**Issue by MateoMS** [athenaswow/BugTracker-Athenas-WoW#182]
Nombre de personaje: Nurer
ID Usuario de Discord: Nurer#7365

Resulta que el 7 de febrero a las 8:00 pm (mas o menos) tras una caída perdí la reputación obtenida con el Vuelo abisal (supongo que por los rates de reputación) quedo en exaltado tras completar la misión de https://www.wowhead.com/quest=10870/ally-of-the-netherwing

El problema es que cuando el server se callo tras de haber obtenido el logro de "Sobre alas abisales" y al entrar de nuevo no solo no hay misiones para tomar de ninguno de los npc de las misiones anteriores, sino que tampoco tengo la reputación, ni el logro.
Por desgracia no sabría que fotos tomar de evidencia, puesto que no tome pantallazo antes de la caída con dicho logro.

Agradezco la atención por adelantado y cualquier inconveniente quedo atento.

Muchas gracias y feliz noche

**Comment by athenaswow** [comment]
Ya le informe a un Game Master para que atienda su caso Gracias por el reporte.
