### ISSUE TITLE
Bug en monte hyjal 

### ISSUE THREAD

**Issue by renzoypilco** [athenaswow/BugTracker-Athenas-WoW#183]
Rellenitho
Rellenitho#1162
https://es.wowhead.com/quest=29387/guardianes-de-hyjal-invasi%C3%B3n-de-las-tierras-de-fuego
https://es.wowhead.com/quest=25510/tortolla-habla
Descripcion: 
No aparece el npc que tengo que entregar
![WoWScrnShot_020920_101415](https://user-images.githubusercontent.com/59895609/74104994-f259ca80-4b27-11ea-8ae7-e6339e72c3e1.jpg)
![WoWScrnShot_020920_101143](https://user-images.githubusercontent.com/59895609/74104995-f4238e00-4b27-11ea-819e-0876a84d7c4b.jpg)

**Comment by renzoypilco** [comment]
Ya lo arreglaron?

**Comment by athenaswow** [comment]
Todos los reportes de hyjal serán  cerrados ya que estoy trabajando en ese lugar desde cero logrando un mejor resultado en las cadenas de misiones, el parche se aplicara a mas tardar el 15 de abril del 2020.
