### ISSUE TITLE
Quest id 26235 (diaria de cocina) Orgrimmar bug

### ISSUE THREAD

**Issue by urudark** [athenaswow/BugTracker-Athenas-WoW#184]
En dicha quest se debe matar los npc que dropean el item al aceptarla...pero los Npc no aparecen...una sugerencia seria colocar contenedores con los items...sin esta quest no se podra sacar logro de cocina en Orgrimmar...gracias...https://es.wowhead.com/quest=26235/hasta-los-ladrones-tienen-hambre

**Comment by athenaswow** [comment]
Gracias por tu reporte, ya fue corregido se implementara en unos dias ya que fueron eliminados por ciertos errores que estaban dando.
