### ISSUE TITLE
Quest id 10526 de Montañas Filospada bug

### ISSUE THREAD

**Issue by urudark** [athenaswow/BugTracker-Athenas-WoW#185]
En esta quest se debe tomar un contenedor que invoca al Npc que dropea el item de la misma...pero al usar el contenedor dicho npc=21319/Gor Tripuriosa no aparece y se bugea el combate...gracias...https://es.wowhead.com/item=30435/la-punta-de-trueno...sin ella no se puede seguir y tampoco sacar logro.

**Comment by athenaswow** [comment]
Corregido.

**Comment by urudark** [comment]
> Corregido

lamento informarles que la quest aun sigue bug...tal vez sea mejor colocar el Npc que dropea el item para que les sea mas facil...gracias
