### ISSUE TITLE
spam moobs en uldum

### ISSUE THREAD

**Issue by natsumi3000** [athenaswow/BugTracker-Athenas-WoW#186]
natsumi, kagura, zaronrose
shadowlands#6275

me encontraba normalmente farmeando unas menas de elementium en uldum cuando de repente vi que salio un dragón atravesando las texturas de las montañas seguí normal con el farmeo pero al pasar por segunda ves por el mismo punto me encontré con muchos de esos dragones tal y como muestro en las imágenes entonces decidí seguirlos hasta el punto que salían de uldum y llegaban a tanaris, probé atacando a uno de ellos y oh sorpresa me doy cuenta que el npc tiene un nombre incorrecto y adicional este tampoco ataca tal como muestro en el vídeo.
en cuestión sabiendo lo que causan los npc cuando son invocados ya sea por un ite, spameo muy rápidos o una misión masivamente causa la caída del servidor decido subir el reporte para que lo comprueben ya que puede ser una de las causas de la inestabilidad de athenas en este momento quedo atento a cualquier inquietud.
pruebas: https://imgur.com/a/lkV53YW
vídeo: https://youtu.be/OIZOYPr7Zko
ORIGEN: https://imgur.com/a/wTd8IJv

**Comment by athenaswow** [comment]
Gracias por tu reporte, ya fue corregido.
