### ISSUE TITLE
bug caminando en monte hyjal

### ISSUE THREAD

**Issue by hanxiangjiangyao** [athenaswow/BugTracker-Athenas-WoW#187]
Me caí solo caminando en las coordenadas 35, 58. Posteriormente, no puedo revivir al no llegar a mi cuerpo. 
![WoWScrnShot_021020_230209](https://user-images.githubusercontent.com/60909934/74210369-79f32680-4c59-11ea-9cc3-051e153aa0ec.jpg)

**Comment by athenaswow** [comment]
Hola.. necesito mas información de momento puedes revivir con el ángel.

**Comment by athenaswow** [comment]
Falta de pruebas.
