### ISSUE TITLE
Quest (La Punta de Trueno id 10526) en Montañas Filospada sigue bug.

### ISSUE THREAD

**Issue by urudark** [athenaswow/BugTracker-Athenas-WoW#188]
Lamento informales que dicha quest sigue bug...https://es.wowhead.com/quest=10526/la-punta-de-trueno...con los mismos problemas anteriores...sugiero colocar el Npcc...https://es.wowhead.com/npc=21319/gor-tripuriosa...quien dropea el item... https://es.wowhead.com/item=30435/la-punta-de-trueno... para asi ahorrarles contratiempos...desde ya muchas gracias...dicha quest sucede en la Mina Draenista...Montañas Filospada

**Comment by athenaswow** [comment]
Gracias..
Ya fue reportado y corregido.

**Comment by urudark** [comment]
> Gracias ..
> Ya fue reportado y corregido

**Comment by urudark** [comment]
La verdad que sigo sin poder completar esta quest...el Npc no esta y sigue bugeando el combate...
