### ISSUE TITLE
bug con maestro de glifo o de personaje 

### ISSUE THREAD

**Issue by Tadoki** [athenaswow/BugTracker-Athenas-WoW#189]
No puedo conocer nuevos puntos de vuelo y tampoco me muestra el mapa de viaje
![2020 02 14-20 23](https://user-images.githubusercontent.com/61069168/74576247-ca73c800-4f68-11ea-902f-37b5d13d417e.png)

**Comment by athenaswow** [comment]
Hola buen día respondiendo a tu reporte.. es por que aun no conoces otros puntos de vuelo y por esa razón no te salen los lugares.
Pruebas
![image](https://user-images.githubusercontent.com/50283962/74589222-5c172000-4fd1-11ea-9ddc-1f654965e7d8.png)
 y 
![image](https://user-images.githubusercontent.com/50283962/74589232-79e48500-4fd1-11ea-8c34-f9c4ef1362f3.png)
