### ISSUE TITLE
Corona de hielo (Npc´s y objetos) desaparecen al acercarse.

### ISSUE THREAD

**Issue by Lamela-La-Buscadora** [athenaswow/BugTracker-Athenas-WoW#19]
Comienzo con la misión https://es.wowhead.com/quest=13261/volatilidad en donde el ingeniero jefe Garrabronce quiere que utilicemos el aceite volátil de Garrabronce en El Frente Roto para atraer a 3 garfacielo Razaescarcha.
Para utilizar el aceite, hay que agrupar una pila de huesos, un casco abandonado y una armadura abandonada del campo de batalla allí como se demuestra en https://www.youtube.com/watch?v=LzGNwewjRj0 

En athenas Wow funciona de la siguiente manera.. https://youtu.be/2eH8rf5v6dU
en esa zona todas las entidades y objetos desaparecen, no hay nada que recoger, nada que atacar, nada que seleccionar...

Anexo de 3 misiones más, ya completadas, que presentan el mismo bug al intentar entregarlas:
-https://es.wowhead.com/quest=13211/purgar-con-fuego
-https://es.wowhead.com/quest=13106/la-guardia-negra
-https://es.wowhead.com/quest=13134/vierte-su-sangre

Prueba: https://youtu.be/2r7qvluscMA

**Comment by athenaswow** [comment]
Ya fue reportado.

**Comment by eltrankiilo12** [comment]
https://es.wowhead.com/quest=13152/una-visita-al-doctor          en el mismo lugar
