### ISSUE TITLE
npc Doba no vende las recetas para subir cocina

### ISSUE THREAD

**Issue by Warkiria** [athenaswow/BugTracker-Athenas-WoW#190]
Warkiria#6526
Hola,
Hola, hice una guía de pesca y el npc en la alianza que debe vender unas recetas no está vendiendo nada.
https://www.youtube.com/watch?v=_76scF3IYhU&t=566s
minuto 9:26

NPC: Doba
ID: 20028
LUGAR: Marisma de Zangar
LINK WOWHEAD: https://es.wowhead.com/npc=20028/doba

RECETA: trucha ennegrecida
ID RECETA: 27694
PRECIO: 2 oros

RECETA: delicias de colavil
ID RECETA: 27695
PRECIO: 2 oros

OBJETO: Especias suaves x5
ID OBJETO: 2678
PRECIO: 10 cobres

OBJETO: Harina simple x5
ID OBJETO: 30817
PRECIO: 25 cobres

OBJETO: Agua de manantial refrescante x5
ID OBJETO: 159
PRECIO: 25 cobres

**Comment by athenaswow** [comment]
Hola.. respecto a su problema es por que no eres neutral con la facción a la que pertenece el Npc y por esa razón no te permite interactuar con el.
Pruebas 
![image](https://user-images.githubusercontent.com/50283962/74589146-b2379380-4fd0-11ea-8bb2-2a74c3a5f91d.png)
