### ISSUE TITLE
You can't take 'em alone quest gilneas

### ISSUE THREAD

**Issue by hasblike** [athenaswow/BugTracker-Athenas-WoW#192]
buenas tardes
https://www.wowhead.com/quest=14348/you-cant-take-em-alone
esa misión se encuentra autocompletable  la misión consiste en  arrojar  barriles a  4 abominaciones en las cuales cuando se les aplica el barril  ellos deben explotar. aquí les dejo un vídeo de como debe funcionar la misión de manera correcta
https://www.youtube.com/watch?v=K3xNB8NuGcg

**Comment by athenaswow** [comment]
Corregido.
