### ISSUE TITLE
boss sylvanas de fin de los dias bug

### ISSUE THREAD

**Issue by darkhalow** [athenaswow/BugTracker-Athenas-WoW#193]
pj principal : wolff
discord: beltran#6255

estábamos haciendo fin de los días en el boss de sylvanas y en el momento en la que sylvanas baja despues de decir la muerte los rodea la mascota del caza coge el agroo y hace que sylvanas se caiga del mapa   https://ibb.co/rfTTkhv  este fue el momento en que sylvanas desapareció y su vida esta a 0
despues de esperar un rato se escucho a sylvanas diciendo la muerte los rodea y esto paso
https://ibb.co/xjg4f5q  despues esto  https://ibb.co/4MdnxPv  en  este momento los no-muertos en vez de caminar al centro se metieron dentro de la montaña  https://ibb.co/0nLkLSw despues reiniciamos y ya estaba bien volvimos a intentar matarla y en el momento en el que dice la muerte los rodea el dk la logro atraer y sylvanas quedo con medio cuerpo fuera del mapa  https://ibb.co/7ggNPDC   y despues de esto sylvanas callo del mapa y volvió a pasar lo mismo

**Comment by athenaswow** [comment]
Ya fue reportado.
