### ISSUE TITLE
spaw y daño de npc 

### ISSUE THREAD

**Issue by hasblike** [athenaswow/BugTracker-Athenas-WoW#194]
buenas noches  en la zona del gilneas este npc tiene exceso de daño 
https://es.wowhead.com/npc=36690/velador-de-refugio-del-ocaso
mata a este npc muy rápidamente y no deja hacer la siguiente misión:
https://es.wowhead.com/npc=34511/invasor-renegado (npc necesario de la mision)
https://es.wowhead.com/quest=14347/mantener-el-frente (quest)

**Comment by athenaswow** [comment]
Corregido.
