### ISSUE TITLE
Misión Bug (Reliquias Perdidas)

### ISSUE THREAD

**Issue by Maxxyty** [athenaswow/BugTracker-Athenas-WoW#195]
Nombre de PJ principal: Palabugs
Usuario de Discord: Maxxyty#6512
Link misión Wowhead: https://es.wowhead.com/quest=29415/reliquias-perdidas

![WoWScrnShot_021620_002657](https://user-images.githubusercontent.com/61103537/74599746-13a14600-5055-11ea-87ab-911ef73b8184.jpg)
![image](https://user-images.githubusercontent.com/61103537/74599751-20259e80-5055-11ea-9101-45549637260b.png)

Debería aparecer el NPC muerto con sangre en el piso en el camarote para poder así finalizar la misión y entregarla con ese NPC que hace falta.

Link misión Youtube: https://www.youtube.com/watch?v=WliV868Uai0

**Comment by athenaswow** [comment]
Ya fue reportado.
