### ISSUE TITLE
Misión Bug (Pisándole los talones)

### ISSUE THREAD

**Issue by Maxxyty** [athenaswow/BugTracker-Athenas-WoW#196]
Nombre del PJ principal: Palabugs
Usuario de discord: Maxxyty#6512
Link misión Wowhead: https://es.wowhead.com/quest=24851/pis%C3%A1ndole-los-talones

![WoWScrnShot_021620_004505](https://user-images.githubusercontent.com/61103537/74599790-dbe6ce00-5055-11ea-8aba-953a597b4947.jpg)
![image](https://user-images.githubusercontent.com/61103537/74599794-e86b2680-5055-11ea-8692-51098872c393.png)
![image](https://user-images.githubusercontent.com/61103537/74599797-f9b43300-5055-11ea-8e36-bf854f9b1e3b.png)

Al entrar a cada una de las casas o instancias, se debería completar la investigación, sin embargo esto no sucede.

Quedo atento. Muchas gracias

**Comment by athenaswow** [comment]
Elaborar un nuevo reporte donde se especifique un poco mas el reporte.
