### ISSUE TITLE
Reinicio de cadena de misiones  Dragonira, el Reposo de Tarecgosa

### ISSUE THREAD

**Issue by Moonserrath** [athenaswow/BugTracker-Athenas-WoW#197]
Buenas tardes, la cadena de misiones para sacar el bastón "Dragonira, el Reposo de Tarecgosa" se reinició de repente, el Lunes en la noche entré a tf para seguir recogiendo las cenizas de la misión (El tiempo se acaba) y al matar un add salió la misión inicial de la cadena como si la hubiese completado. Al ver mi lista de misiones, me habían devuelto a la primer misión. Adjunto link de imagen donde se observa que iba en la misión de las cenizas que habia nombrado.

![Mision Tarecgosa](https://user-images.githubusercontent.com/61120763/74610304-15542380-50c0-11ea-8b81-b5f5d148fe7f.jpg)

Nombre del pj : Drie
Discord: Irithel # 6306

**Comment by athenaswow** [comment]
Falta de pruebas.
