### ISSUE TITLE
Reporte de bug sobre la cadena de misiones para ir a pandaria

### ISSUE THREAD

**Issue by SmikelGr** [athenaswow/BugTracker-Athenas-WoW#198]
Pj: Smikel
Dc: SmikelGr#6248
![WoWScrnShot_021620_160741](https://user-images.githubusercontent.com/61124397/74612707-e779d980-50d5-11ea-9d9e-76f8bf276304.jpg)
Al momento de subir a 85 se entrega una mision para comenzar la cadena de misiones que lleva a pandaria, pero en vez de dar la de la alianza da la mision de la horda, comprobe esto con el GM Hefesto, también en la horda si entrega la mision correspondiente, pero al momento de completarla esta bug y la mision que envia a al buque de guerra para ir a pandaria esta bug, mil disculpas por la explicación, espero que lo entiendan

**Comment by AresGM** [comment]
Hola,
Por favor utilizar el siguiente enlace para reportar fallos de la expansión de Pandaria: `github.com/athenaswow/BugTracker-Athenas-WoW-Pandaria`
