### ISSUE TITLE
(Quest Diaria de Pesca en Ventormenta) El Desafío del Leucoma

### ISSUE THREAD

**Issue by SKLucifer** [athenaswow/BugTracker-Athenas-WoW#199]
Nombre del Personaje Principal: **SKLucifer**
ID Discord: **Aun sin cuenta en la misma**

La Quest diaria de Pesca (**El desafío del Leucoma**) que te da **Catherine Leland** ( la que vende lo suministros de pesca que esta al lado del instructor de pesca de Ventormenta) esta bugueada, y esto se debe a que trato de pescar el **Leucoma Endurecido** en la zona que corresponde según la misión (les dejo link abajo de **wowhead** donde se ubica el **ítem de misión** y el video de **Youtube** de como debería funcionar), y llevo casi 2 hora tratando de pescarlo y nada que sale ( y mas bien me salen otros ítems de quest que no es de ella). Sin mas que comentar y reportar, y agradeciendo la atención, me despido. 

Estaré al pendiente por acá en cuanto a la respuesta que le den al asunto publicado.

Aquí les dejo el **link** de la misión de la pagina **wowhead**:

https://es.wowhead.com/quest=26414/el-desaf%C3%ADo-del-leucoma

y en donde se ubica el **ítem** para pescar:

https://es.wowhead.com/item=58503/leucoma-endurecido#objective-of

Video de **Youtube** de como debería funcionar:

https://www.youtube.com/watch?v=sx98DJIayGw

**Comment by athenaswow** [comment]
Corregido.

**Comment by SKLucifer** [comment]
Soy **SKLucifer**, el que posteo el bug

Acabo de retomar la misión en vista que mi solicitud fue resuelta, y aun no pesco el ítem **Leucoma Endurecido** (me puse a probar y dure 20 minutos) que me pide la misión. A menos que la corrección se realice en el trascurso del día!!

Pido disculpa al Staff si sueno algo insistente!! pero soy de la clase de jugador que disfruta hacer las misiones y el Pve.

Cordialmente me despido y agradeciendo la atención prestada.

**Comment by SKLucifer** [comment]
> 
> 
> Corregido.

Nombre del Personaje Principal: **SKLucifer**
ID Discord: **Aun sin cuenta en la misma**

Aun persiste el error en la misión diaria de pesca **El desafío del Leucoma** (https://es.wowhead.com/quest=26414/el-desaf%C3%ADo-del-leucoma). el item **Leucoma Endurecido** (https://es.wowhead.com/item=58503/leucoma-endurecido#objective-of) no aparece cuando lo trato de pescar en la zona que corresponde pescarlo en la misión y llevo bastante rato tratando de pescarlo.

Sin mas que decir, me despido
