### ISSUE TITLE
Misión: "A Vil gustar fuego" Corona de Hielo

### ISSUE THREAD

**Issue by Lamela-La-Buscadora** [athenaswow/BugTracker-Athenas-WoW#20]
Lamela
Lamela#3066
 https://es.wowhead.com/quest=13071/a-vil-gustar-fuego Vil en La Cámara de las Sombras quiere que robes un protodraco Njorndar y lo uses para incendiar 8 edificios vrykuls en la región de Jotunheim.
https://www.youtube.com/watch?v=MlubyWXcW7U

En Athenas no es posible montarse en los https://es.wowhead.com/npc=30272/protodraco-njorndar para comenzar con la misión... https://www.youtube.com/watch?v=CkRjcSqwUX8&feature=youtu.be

**Comment by athenaswow** [comment]
corregida.
