### ISSUE TITLE
Fallo en "Rey de la montaña" (npc no existe para seguir la cadena")

### ISSUE THREAD

**Issue by Daniel-mecato** [athenaswow/BugTracker-Athenas-WoW#201]
Buenas noches, la presentes para informar que "**Rey de la montaña"** logro, está bug y se para en el npc de (es decir, _no sale el npc para seguir con la cadena_, solo está ahí parado)  https://www.wowhead.com/quest=28712/enter-the-dragon-queen

**Comment by athenaswow** [comment]
Corregido el cambio se agregara en unos días.
