### ISSUE TITLE
La Punta de Trueno (quest nº 10526 continua bug)

### ISSUE THREAD

**Issue by urudark** [athenaswow/BugTracker-Athenas-WoW#203]
Por favor señores de mantenimiento esta es la tercera vez que reporto dicha quest bug...las dos anteriores supuestamente estaban solucionadas y lista para ser completada...pero la verdad no solucionaron nada...el unico cambio que hubo fue que ya no te dejaba en combate pero el Npc Gor Tripuriosa (Nº 21319) sigue sin estar al usar el contenedor que lo invoca...para poder obtener La Punta de Trueno (Item Nº 30435) y asi completar la quest...Dicha quest se completa en la Mina Draenetista al final de la misma...en las Montañas Filospada...por favor solucionen este bug ya que no se podra completar el logro Maestro Cultural de Terrallende...
Eh hablado con algunos GM pero estos son muy incompetentes y no se molestan en hablar con los jugadores...

**Comment by athenaswow** [comment]
Hola buenas tardes muchas gracias por su reporte pero el bug ya fue solucionado y se implementara en unos días ya que las correcciones no se suben de un día para otro.
