### ISSUE TITLE
Aún no sirven las misiones y los npc ´´corregidos´´ en Vallefresno.

### ISSUE THREAD

**Issue by ViktorKr0m** [athenaswow/BugTracker-Athenas-WoW#204]
Hace unos días abrí un hilo sobre como no se deja aceptar una mision de objeto:
https://github.com/athenaswow/BugTracker-Athenas-WoW/issues/178
He sido curioso de por qué no sirve; termine todas las misiones de Maestro cultural de Kalimdor, pero vallefresno aún no he podido ya que la cadena que se agarra desde Azshara esta bug. 
El hilo de las misiones del npc Valusha, que fue la misión que se linkeo en el pasado hilo del bugtracker como necesario para empezar: https://es.wowhead.com/quest=26447/planes-diab%C3%B3licos no se puede agarrar ya que este npc: https://es.wowhead.com/npc=34195/kulg-salpicasangre#ends no deja empezar esta cadena.
Deja terminar esta: https://es.wowhead.com/quest=24463/investigaciones-en-vallefresno
Pero no inicia esta: https://es.wowhead.com/quest=13866/a-la-empalizada
Estoy a dos misiones de completar el logro, pero no encuentro forma de acceder a ellas.
Estoy haciendo las misiones con el addon Quest hubber, quien me dice que solo esa cadena me falta en Vallefresno: 
![tracke](https://user-images.githubusercontent.com/59740192/74698469-e4611500-51cb-11ea-8fed-dba746de174b.jpg)
 y de hecho ya termine la cadena del tablero de Ogrimmar y todas las misiones de Azshara que inician la cadena en vallefresno:
![ashara](https://user-images.githubusercontent.com/59740192/74698483-f5118b00-51cb-11ea-9b42-b69fa7d7bb6e.jpg)

Porfavor; arreglen esto ya que no se puede sacar este logro sin esta cadena:
![WoWScrnShot_020720_011330](https://user-images.githubusercontent.com/59740192/74698443-c8f60a00-51cb-11ea-94f5-cc73b15b1d25.jpg)

**Comment by athenaswow** [comment]
Hola buenas noches Las misiones del reporte anterior fueron corregidas pero el cambio aun no se a aplicado.. si ya fue cerrado su tema por favor.. no lo abra nuevamente, si decae reportar algo mas por favor que sea en otro reporte

**Comment by athenaswow** [comment]
Corregido.
-- la mision https://es.wowhead.com/quest=26447/planes-diab%C3%B3licos requiere de aver completado la mision 26448 horda

-- la mision https://www.wowhead.com/quest=26443/diabolical-plans requiere de aver completado las misiones id 26444 y 26446 alianza
