### ISSUE TITLE
Misión Bug (Misión Improbable)

### ISSUE THREAD

**Issue by Maxxyty** [athenaswow/BugTracker-Athenas-WoW#205]
Nombre del PJ principal: Palabugs
Usuario de discord: Maxxyty#6512
Link misión Wowhead: https://www.wowhead.com/quest=13808/mission-improbable
Link misión Youtube: https://www.youtube.com/watch?v=Kug7s305As0
![WoWScrnShot_021720_222442](https://user-images.githubusercontent.com/61103537/74701406-a0264280-51d4-11ea-9126-f0486db43e3b.jpg)

Una vez dado click derecho o activado el item "Polvo de santo y señas", el NPC "Krokk" debería aparecer para poder entregar la misión, sin embargo no permite usar el item y el NPC no está ahí desde un principio, por lo que es imposible entregar la misión.

Muchas gracias, quedo atento.

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
