### ISSUE TITLE
Quest ¡El monstruo del foso! (id 29361) de pesca en Entrañas bug

### ISSUE THREAD

**Issue by urudark** [athenaswow/BugTracker-Athenas-WoW#206]
Al principio parecía funcionar todo bien pero al convocar en dicho Npc para asi alimentarlo con el  item 69995 rana hinchada...no se puede por que al intentarlo, una advertencia dice que no tienes objetivo y pobre de muchas formas y no hubo caso, no se puede...el Npc es invocado pero no se le puede alimentar...y no completas dicha quest.

**Comment by athenaswow** [comment]
Ya fue reportado.

**Comment by urudark** [comment]
no entiendo la etiqueta de invalido...que significa eso? Significa que fue mal reportado o que?
Porque la quest no se puede llevar a cabo ya que no se puede alimentar al objetivo...necesito una respuesta mas contundente...gracias...
