### ISSUE TITLE
Perdida de reliquias de leveo

### ISSUE THREAD

**Issue by Dalaran03** [athenaswow/BugTracker-Athenas-WoW#208]
Personaje principal: Vaskr
Nombre en Discord: Miike#0345
Buenas noches. Hace aproximadamente 3 días tomé la decisión de crearme un huargen druida, su nombre fue "Skyburn" así que decidí comprarle las reliquias tales como: El yelmo, los hombros, la capa y el arma para facilitar el tema de leveo. Por problemas que tuve con el personaje (No obtuve la racial de cambio de forma) decidí eliminar el personaje, pero anteriormente envié por correo las reliquias + 40 de oro para no poderlas obviamente. Cuando recibí el correo con mi personaje principal me percaté de que solo había llegado el oro pero no las reliquias, finalmente decidí borrar el personaje y me cree otro Huargen druida con el mismo nombre (Skyburn) El tema es que perdí las reliquias al enviar el correo. Es un bug bastante extraño, porque anteriormente me cree como 2 o 3 personajes druidas para testar a ver que tal me iba y nunca se perdieron las reliquias. Puede que este tipo de bugs sucedan en 1 caso de 100, me gustaría saber como podría recuperar las reliquias, ya que sinceramente me costó mucho conseguirlas, agregando que no son para nada económicas. Por desgracia no tengo fotos de cuando envié y recibí los correos, pero pueden revisar los logs con mi personaje principal (Vaskr). De no ser posible recuperar las reliquias, aunque sea me gustaría recibir el honor y el oro que gaste, ya que como mencione anteriormente, no son para nada económicas. Adjunto las imágenes de las reliquias exactas que compré.
*Yelmo comprado con el vendedor de objetos de la hermandad: https://es.wowhead.com/item=61937/almete-arte-sombr%C3%ADo-manchado
*Hombros comprado con puntos de justicia: https://es.wowhead.com/item=44103/sobrehombros-de-embozo-de-tormenta-excepcionales
*Capa comprada con el vendedor de objetos de la hermandad: https://es.wowhead.com/item=62039/manteo-heredado-del-bar%C3%B3n-negro
*Arma comprada con puntos de justicia: https://es.wowhead.com/item=48718/draga-de-lava-de-nueva-funcionalidad
Agrego finalmente los precios de cada objeto.
*Yelmo: 1350 monedas de oro
*Hombros: 2175 puntos de honor
*Capa: 1080 monedas de oro
*Arma: 3500 puntos de justicia que son equivalentes a 5250 puntos de honor
Agradezco su colaboración y comprensión respecto al tema, quedo atento a una respuesta, gracias.

**Comment by athenaswow** [comment]
No debería estar reportado aquí ya que fue a causa del rolback, Ponte en contacto con un Game master.
