### ISSUE TITLE
Tierras altas Crepusculares, imposibilidad de continuar con las misiones.

### ISSUE THREAD

**Issue by Lamela-La-Buscadora** [athenaswow/BugTracker-Athenas-WoW#21]
Lamela
Lamela#3066
Con la ayuda de Grail y Wholly add-ons es posible determinar qué misiones faltan en alguna zona y si necesitan requisitos o no... https://youtu.be/Ne86BDD88PU se observa que el NPC https://es.wowhead.com/npc=47902/lirastrasza no da la misión https://es.wowhead.com/quest=28249/machacolpe que abre una nueva cadena.

**Comment by athenaswow** [comment]
![image](https://user-images.githubusercontent.com/50283962/69622819-b4143b00-100f-11ea-95c0-a734f90c1dc4.png)

**Comment by athenaswow** [comment]
Para poder seguir con esa cadena deber de hacer esta misión que es la que te lleva a ese jugar.
![image](https://user-images.githubusercontent.com/50283962/69623122-4583ad00-1010-11ea-9b03-75184b9104fe.png)

![image](https://user-images.githubusercontent.com/50283962/69623169-5c2a0400-1010-11ea-94f2-b62bc48a885a.png)
