### ISSUE TITLE
Misión Bug (¡Ardeanaar!)

### ISSUE THREAD

**Issue by Maxxyty** [athenaswow/BugTracker-Athenas-WoW#216]
Nombre del PJ principal: Palabugs
Usuario de discord: Maxxyty#6512
Link misión Wowhead: https://es.wowhead.com/quest=13947/ardeanaar
Link misión Youtube: https://www.youtube.com/watch?v=r_lNMGARmns

![image](https://user-images.githubusercontent.com/61103537/74893805-37b59d80-535b-11ea-9e7e-86e27c503064.png)

De acuerdo con la misión, uno debe montarse en un murciélago que se toma donde el NPC Jinete de Vuelo para poder bombardear Ardeanaar, sin embargo el Jinete no ofrece esta opción y no se pueden matar los mobs normalmente sin el bombardeo porque son de nivel muy alto para lo requerido en la misión (+40), así que es mejor que la misión funcione como debería

Muchas gracias, quedo atento.

**Comment by athenaswow** [comment]
Corregido, el cambio se agregara en unos días.
