### ISSUE TITLE
Misiones Bug de Pesca Diaria en Ventormenta

### ISSUE THREAD

**Issue by SKLucifer** [athenaswow/BugTracker-Athenas-WoW#218]
Nombre del Personaje Principal: **SKLucifer**
ID Discord: Aun sin cuenta en la misma

**Misiones Bugs**
**El Desafío del Leucoma** y **Excavando en busca de lombrices**

En la misión diaria de pesca **El desafío del Leucoma** (https://es.wowhead.com/quest=26414/el-desaf%C3%ADo-del-leucoma). el ítem **Leucoma Endurecido** (https://es.wowhead.com/item=58503/leucoma-endurecido#objective-of) no aparece cuando lo trato de pescar en la zona que corresponde pescarlo en la misión y llevo bastante rato tratando de pescarlo.

Al igual que la anterior, la misión de pesca diaria **Excavando en busca de lombrices** (https://es.wowhead.com/quest=26420/excavando-en-busca-de-lombrices), se necesita para pescarlo el ítem **Lombriz desmesurada** (https://es.wowhead.com/item=58788/lombriz-desmesurada) que no aparece en el lugar de misión que junto con la habilidad de pesca, se necesita para pescar el ítem **Lubina de cristal** (https://es.wowhead.com/item=58787/lubina-de-cristal), la cual impide terminar la misión.

Sin mas que comentar y reportar, y agradeciendo la atención, me despido.

Estaré al pendiente por acá en cuanto a la respuesta que le den al asunto publicado.

**Comment by athenaswow** [comment]
Ya fue corregido, Se agregara la correcciones en unos días.
