### ISSUE TITLE
Misión Bug (Carnicería de Llagapata)

### ISSUE THREAD

**Issue by Maxxyty** [athenaswow/BugTracker-Athenas-WoW#219]
Nombre del PJ principal: Palabugs
Usuario de discord: Maxxyty#6512
Link misión Wowhead: https://es.wowhead.com/quest=25115/carnicer%C3%ADa-de-llagapata
Link misión youtube: https://www.youtube.com/watch?v=KfrdY_N2iDQ
![image](https://user-images.githubusercontent.com/61103537/75085516-2fdf3000-54f8-11ea-8a29-adc925225118.png)
De acuerdo con la misión, una vez matado el monstruo se activa el item y te cuenta el cadáver, sin embargo esto no sucede cuando se activa el item, la animación de agacharse a recogerlo se hace pero no cuenta la acción, y es muy extraño porque las dos misiones anteriores a esta tratan de lo mismo pero con otros monstruos y no hay ningún problema con esas

Muchas gracias, quedo atento.

**Comment by athenaswow** [comment]
Hola buenos días... disculpa pero no puedo ayudarte necesito mas información  e probado 5 veces la misión y esta perfectamente.
pruebas
![image](https://user-images.githubusercontent.com/50283962/75105778-d5240200-55e5-11ea-9f77-3103edca69ae.png)

**Comment by athenaswow** [comment]
estas usando el npc que no es :)
![image](https://user-images.githubusercontent.com/50283962/75105809-2633f600-55e6-11ea-8756-362f74d5430f.png)
 el npc que debes matar y al que le debes usar el item es https://es.classic.wowhead.com/npc=5426/hiena-llagapata
