### ISSUE TITLE
Uldum no nos da la bienvenida, primeras misiones bug.

### ISSUE THREAD

**Issue by Lamela-La-Buscadora** [athenaswow/BugTracker-Athenas-WoW#22]
Lamela
Lamela#3066
En Uldum los NPC´s que comiezan con el desarrollo de todas las misiones de este lugar: https://es.wowhead.com/npc=45799/pr%C3%ADncipe-nadun y https://es.wowhead.com/npc=47684/rey-phaoris solo son seleccionables, mas no asignan ni reciben ningún tipo de misión.
https://youtu.be/qKg4uf0DX2Q

**Comment by athenaswow** [comment]
corregido
