### ISSUE TITLE
QUEST Monte Hyjal El regreso del barón Geddon Bug

### ISSUE THREAD

**Issue by fedemaster36** [athenaswow/BugTracker-Athenas-WoW#223]
Buenas Soy Curamdero. 
Durante el leveleo en monte hyjal me encontré con una quest llamada "  El regreso del barón Geddon" la cual nos la brinda Malfurion Temprestira. (https://es.wowhead.com/quest=25464/el-regreso-del-bar%C3%B3n-geddon)
Dicha quest no pide ir al encuentro del Barón Geddon quien es un "elemental de juego Elite" y tenes que usar un ítem que nos da Malfurion en el. el item se llama "Bastón de vidente de llamas", al usar nuestro personaje entra en una fase chaleling el cual a medida que pasa este se nos va a completando la quest. Adjunto un link de un video de youtube. (https://www.youtube.com/watch?v=yhxgik4hvIs ).
![WoWScrnShot_022220_161130](https://user-images.githubusercontent.com/61362139/75098795-54d7af80-5599-11ea-8cb0-9a7aec04166a.jpg)

![WoWScrnShot_022220_161116](https://user-images.githubusercontent.com/61362139/75098802-61f49e80-5599-11ea-8161-2b6f1a24a2fd.jpg)
El asunto es que al terminal 1 o 2 veces el casteo del ítem no se completa la quest.! 
ante cualquier cosa mi Discord es federico#6821

**Comment by athenaswow** [comment]
Reporte invalido.
![image](https://user-images.githubusercontent.com/50283962/75105656-0f8c9f80-55e4-11ea-9fe8-d2743b90aa01.png)

**Comment by fedemaster36** [comment]
estamos hablando del servidor de pandaria verdad?
