### ISSUE TITLE
Misión Armas de disfunción masiva BUG

### ISSUE THREAD

**Issue by fedemaster36** [athenaswow/BugTracker-Athenas-WoW#224]
Buenas Soy Curamdero.
Hola nuevamente. mientras hacia la cadena de quest para poder ir a Tierras altas crepusculares me encontré con la misiones "Armas de disfunción masiva". en dicha quest debería hablar con los ingenieros goblin que están en Orgrimar y comprobar si las maquinas de salto fabricados por estos son de excelente calidad. Pero en lugar de poder interactuar con los Ingenieros tuve que matarlos a ellos y a las catapultas de asedio para poder completar la quest.  Acá dejo el link de la quest ( https://es.wowhead.com/quest=26294/armas-de-disfunci%C3%B3n-masiva)
![WoWScrnShot_022220_174133](https://user-images.githubusercontent.com/61362139/75099010-818cc680-559b-11ea-9b91-234da3cc82b1.jpg)

![WoWScrnShot_022220_174726](https://user-images.githubusercon
![WoWScrnShot_022220_174245](https://user-images.githubusercontent.com/61362139/75099009-7f2a6c80-559b-11ea-9d67-b8e5467d6cd9.jpg)
tent.com/61362139/75099006-7afe4f00-559b-11ea-9f12-3489a889180d.jpg)

![WoWScrnShot_022220_174731](https://user-images.githubusercontent.com/61362139/75099003-76d23180-559b-11ea-9de9-38e32132f18a.jpg)
![WoWScrnShot_022220_174630](https://user-images.githubusercontent.com/61362139/75099007-7cc81280-559b-11ea-8366-990af1b81d0b.jpg).
ante cualquier cosa me pueden contactar en el discord : federico#6821

**Comment by athenaswow** [comment]
![image](https://user-images.githubusercontent.com/50283962/75105582-339bb100-55e3-11ea-8f31-67578ca0ee41.png)

Algo estas haciendo mal.
