### ISSUE TITLE
Portales Faltantes Uldum

### ISSUE THREAD

**Issue by GM-Hercules** [athenaswow/BugTracker-Athenas-WoW#23]
Los portales que dirigen a las capitales en Uldum no se encuentran en el lugar indicado.
Pruebas: https://cdn.discordapp.com/attachments/631555195737735229/648693151632064531/unknown.png

Donde deberian estar: https://media.discordapp.net/attachments/631555195737735229/648681874461425684/unknown.png?width=1168&height=657

**Comment by athenaswow** [comment]
corregido.
