### ISSUE TITLE
No funciona Skill "Distraer"

### ISSUE THREAD

**Issue by precipicio** [athenaswow/BugTracker-Athenas-WoW#230]
el reporte es simple, el Spell "Distraer" de los picaros, No funciona en BG cuando se trata de evitar que tomen una bandera o capturen una base.
https://classic.wowhead.com/spell=1725/distract
KrioLina#7748
Ferrnanda

**Comment by athenaswow** [comment]
Hola buenas noches, Te agradecería si pudieras subir un vídeo explicando lo que sucede ya que sus pruebas son insuficientes.

**Comment by athenaswow** [comment]
Falta de pruebas.
