### ISSUE TITLE
Se olvidaron mi llave instanteno lvl 85 

### ISSUE THREAD

**Issue by renzoypilco** [athenaswow/BugTracker-Athenas-WoW#231]
Sonrisas
Esponjosho#2602
Buenas días, tengo un problema sobre la migración que se olvidaron de enviar mi llave para ser insta lvl 85 a mi personaje Sonrisas, solo me dieron la llave de profesión 525 y los 5000 de oro pero no apareció la llave para pueda ser insta lvl 85, a mis otros 2 personajes le dieron los 2 llaves(profesión y insta lvl 85), pensé que llegaría al trascurrir el tiempo pero ya paso 1 semana y todavía no aparece. 
Mis pjtas que fueron migrados fueron lvl 85 y con profesiones full, me gustaría que me ayuden a arreglar este problema que tengo, gracias.
![WoWScrnShot_022920_112030](https://user-images.githubusercontent.com/59895609/75612888-ca8dcf00-5af5-11ea-85a9-d61c08c6aff3.jpg)
![WoWScrnShot_022920_094958](https://user-images.githubusercontent.com/59895609/75612890-ce215600-5af5-11ea-8e60-a51e5b67ed6c.jpg)

**Comment by AresGM** [comment]
Hola, informo que éste canal únicamente es para el reporte de fallos de la expansión Cataclismo. si tuvo inconvenientes o tiene dudas acerca de su migración por favor ponerse en contacto vía mensaje privado de Discord a: AndrésRamírez#4717 ó Badingm#3364.
