### ISSUE TITLE
Misión Bug (¡Infernales por los aires!)

### ISSUE THREAD

**Issue by Maxxyty** [athenaswow/BugTracker-Athenas-WoW#232]
Nombre del PJ principal: Palabugs
Usuario de discord: Maxxyty#6512
Link misión Wowhead: https://es.wowhead.com/quest=10598/infernales-por-los-aires
Link misión youtube: https://www.youtube.com/watch?v=llCvmfRtatE
![WoWScrnShot_022920_210740](https://user-images.githubusercontent.com/61103537/75618189-b4edc900-5b38-11ea-812e-2204f586a053.jpg)
![WoWScrnShot_022920_210745](https://user-images.githubusercontent.com/61103537/75618190-b6b78c80-5b38-11ea-8637-d5a57b9cb4b8.jpg)

La misión funciona en cierta parte, el objeto bien (no hay ubicación de donde hay que utilizarlo pero pues se puede buscar en wowhead), sin embargo el problema está al momento de entregarla, como se aprecia en las dos imágenes adjuntas ya tengo la misión completada, pero no me deja entregarla, no me permite darle en el botón de "Continuar" para reclamar mis recompensas, espero que eso no me esté sucediendo solo a mi :)

Muchas gracias, quedo atento

**Comment by athenaswow** [comment]
Ya fue corregido, falta aplicar el cambio.
