### ISSUE TITLE
Todas la habilidades que intento aprender desaparecen

### ISSUE THREAD

**Issue by fridositaju21** [athenaswow/BugTracker-Athenas-WoW#233]
Nombre del PJ principal: Arioki
Usuario de discordia: Claudio Claudiano#8132
![image](https://user-images.githubusercontent.com/61641558/75618856-39951300-5b4a-11ea-84c2-4363ba327556.png)
este es un pequeño ejemplo de que siendo nivel 69 no puedo ni aprender a volar ni aprender a volar en clima frio, tampoco puedo aprender habilidades, titulo de herbosteria y objetos de inscripcion; todos esos desaparecen cuando llego a los requisitos.
Gracias por el apoyo.

**Comment by AresGM** [comment]
Hola, lamentamos las molestias causadas debido al fallo que está presentando. Informo que éste no es el canal indicado para reportar inconvenientes que únicamente suceden con su personaje, teniendo en cuenta esto, por favor realizar ticket dentro del juego y le será atendido lo más pronto posible, recuerde que el ticket debe contener la mayor cantidad de información posible y detallada.
Agradecemos su comprensión.
