### ISSUE TITLE
Ya no deja atacar en las arenas!.

### ISSUE THREAD

**Issue by T0biTron** [athenaswow/BugTracker-Athenas-WoW#234]
Mi pj principal es :Angell
Discord: Daniel ^^#4027
En las Arenas ahora no se puede atacar y los enemigos aparecen aliados.
Adjunto Fotos: https://imgur.com/gallery/ITetBu4

**Comment by AresGM** [comment]
Hola, lamentamos las molestias causadas debido al fallo que está presentando, dado que el enlace de la o las capturas de pantalla está caído y el reporte carece de poca información no podemos brindar una solución óptima.
Recuerde que en nuestro README se encuentran las reglas de reporte las cuales son:

Reglas para subir reportes:
- Colocar en el reporte el nombre de su PJ principal.
- Colocar en el reporte su usuario de discord (ej.: jugador#0123).
- Agregar link de wowhead de el hechizo, item, logro para ser mas exactos.
- Agregar una descripción del error comprensible para cualquier persona.
- Agregar fotos y/o vídeos. (imgur.com www.youtube.com imgbb.com)
- Agregar enlaces que validen el error (wowhead o https://cata-twinhead.twinstar.cz/)
Nota: https://cata-twinhead.twinstar.cz/ es una web que maneja las bases de datos de: Vanilla, TBC, Wotlk y Cataclysm.
