### ISSUE TITLE
Mision del Torneo Argenta no funciona

### ISSUE THREAD

**Issue by juanchoDev** [athenaswow/BugTracker-Athenas-WoW#237]
Desde hace varios días estoy haciendo las misiones del Torneo Argenta y hay una en particular que no deja hacerla (al hacer los objetivos de la misión no los cuenta). Es la mision donde te montas en la montura de tu faccion con una lanza y debes golpear los blancos como te lo indican. https://es.wowhead.com/quest=13625/aprende-a-llevar-las-riendas

![image](https://user-images.githubusercontent.com/61710900/75794350-0c618400-5d47-11ea-96db-b5249b05e4cb.png)

![WoWScrnShot_030320_120615](https://user-images.githubusercontent.com/61710900/75794837-bc36f180-5d47-11ea-9507-16b6d94369ea.jpg)

Además creo que la velocidad de la montura esta bugueada también porque va bastante lento (aunque no estoy seguro si esto oficialmente es asi)

Muchas gracias de antemano, espero por su arreglo...

**Comment by athenaswow** [comment]
Hola buenos días, ya fue reportado.
https://github.com/athenaswow/BugTracker-Athenas-WoW/issues/227
