### ISSUE TITLE
[Disparo firme mejorado] talento no funciona 

### ISSUE THREAD

**Issue by MoteroHunterSkilled** [athenaswow/BugTracker-Athenas-WoW#238]
Talento [Disparo firme mejorado] de la rama puntería de los cazadores, no funciona correctamente, ya que no da el buff de 15% de celeridad (3/3), al utilizar dos o más  veces el disparo firme.

![image](https://user-images.githubusercontent.com/61750643/75797889-8d734800-5d54-11ea-887e-e3e3a72b3426.png)

Pj principal: Motero
Usuario Discord: @SkilledPlayer#1768

**Comment by aragoon796** [comment]
si funciona solo que hay que estar quieto.

**Comment by aragoon796** [comment]
![image](https://user-images.githubusercontent.com/61800970/75912201-7006b280-5e16-11ea-9f33-5f9c4c90acdf.png)

**Comment by MoteroHunterSkilled** [comment]
> si funciona solo que hay que estar quieto

Debería funcionar en movimiento.

**Comment by athenaswow** [comment]
Como las pruebas NO son suficientes para ayudar y dar a entender cual es su problema me veo obligado a cerrar su reporte ya que es Invalido.
Pruebas: https://www.youtube.com/watch?v=itaiHWbExLc&feature=youtu.be

**Comment by IkariuzH** [comment]
si se puede disparar, tienes que buscar bien el macro 
#showtooltip Disparo firme
/castsequence reset=1 Aspecto del zorro, null
/cast disparo firme
