### ISSUE TITLE
Misión bug diaria de pesca en Ventormenta: [Excavando en busca de lombrices] ó [Diggn' For Worms]

### ISSUE THREAD

**Issue by aragoon796** [athenaswow/BugTracker-Athenas-WoW#239]
Pj principal Aragoon
Usuario de Discord Aragoon#5565

Descripción del problema: Se necesita unas lombrices que salen en la zona indicada y al llegar allí no hay ninguna lombriz para coger y poder pescar para  hacer la mision.

Link de la mision en Wowhead: https://www.wowhead.com/quest=26420/diggin-for-worms#screenshots 
Link de lo que toca pescar luego de usar la lombriz: https://www.wowhead.com/item=58787/crystal-bass
Imagen del item que hay que coger para poder hacerla: 
![625621-diggin-for-worms](https://user-images.githubusercontent.com/61800970/75910810-24eba000-5e14-11ea-9c48-f28b9ad2ba02.jpg)
Vídeo de como se hace la misión: https://www.youtube.com/watch?v=F59y2c8QhL8``
Espero y lo solucionen. 
#Misión bug diaria de pesca en Ventormenta: [Excavando en busca de lombrices] ó [Diggn' For Worms]

**Comment by aragoon796** [comment]
No le pude poner categoría pero es MISIONES.

**Comment by athenaswow** [comment]
Corregido, el cambio se implementara en unos días.

**Comment by aragoon796** [comment]
corregido? hace 23 dias y aun sigue bug jajajaj q risa esta gente a lo bien
