### ISSUE TITLE
Misión Diaria: ¡El monstruo del foso! (Entrañas)

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#24]
Nombre de personaje principal: Skala
Usuario de discord: JorDaNN # 5575
Descripción del error: Sale el monstruo para darle las ranas hinchadas, sin embargo, no deja darle de comer. Aparece como si no hubiera objetivo.
Misión wowhead: https://es.wowhead.com/quest=29361/el-monstruo-del-foso
Athenas wow: https://www.youtube.com/watch?v=yGBGTtNfWgU
Como debería funcionar: https://www.youtube.com/watch?v=_IgLBcw83ms min 2:00

**Comment by pangolp** [comment]
Problema solucionado. Aunque le **falta el efecto del lanzamiento de la rana**, pero al usar el item, ahora cuenta hasta llegar a 10 y lo da como completada a la quest. Nose cuanto demoraran en aplicar el cambio.

![WoWScrnShot_011920_034056](https://user-images.githubusercontent.com/2810187/72676260-ef5e4380-3a6d-11ea-8bea-7588103baf8d.jpg)

**Gracias por el reporte.**
