### ISSUE TITLE
No aparecen los add en la mision:Caparazón del demonio(Monte Hyjal.)

### ISSUE THREAD

**Issue by h15chile** [athenaswow/BugTracker-Athenas-WoW#240]
Creatore
Mauricio(Creatore)#1258
como debería funcionar: //www.wowhead.com/quest=25492/firebreak
se supone que al matar a 10 lava Surgers me sueltan un ítem pero a mi no me aparecen los Add por ende no me deja hacer la misión.
Como esta funcionando: En las fotos adjuntadas a este reporte se vee claramente que en ningún lado donde marca que deberian aparecer los Add para la misión no están, necesito completar esa misión para sacar la montura hipogrifo en llamas, otra cosa que es complementaria; tampoco me deja entregar la misión: https://www.wowhead.com/quest=29387/guardians-of-hyjal-firelands-invasion
![WoWScrnShot_030420_170332](https://user-images.githubusercontent.com/61804579/75924487-cd662800-5e45-11ea-8c68-916edc2110e8.jpg)
![WoWScrnShot_030420_170259](https://user-images.githubusercontent.com/61804579/75924494-d1924580-5e45-11ea-981a-b6bf0bafb0bb.jpg)
![WoWScrnShot_030420_170418](https://user-images.githubusercontent.com/61804579/75924500-d48d3600-5e45-11ea-8836-a5850127825c.jpg)

por su atención muchas gracias.

**Comment by RafgonWoW** [comment]
Los mobs están en la parte más cercana al lago, si mal no recuerdo.

**Comment by h15chile** [comment]
no están los mobs
mire le adjunto una foto alado del lago.
![WoWScrnShot_030520_222921](https://user-images.githubusercontent.com/61804579/76041514-10e99080-5f31-11ea-8da1-2ee6c06dca68.jpg)

**Comment by athenaswow** [comment]
Todos los reportes de hyjal serán  cerrados ya que estoy trabajando en ese lugar desde cero logrando un mejor resultado en las cadenas de misiones, el parche se aplicara a mas tardar el 15 de abril del 2020.
