### ISSUE TITLE
Mazmorra: Laberinto de la sombras | Jefe Bug: Maestro Mayor Vorpil

### ISSUE THREAD

**Issue by Osvaldomtzg** [athenaswow/BugTracker-Athenas-WoW#241]
Osvaldo
Mart_Z#6190
Como debería funcionar: https://www.youtube.com/watch?v=KPpxVYGKJMs
NPC: https://es.wowhead.com/npc=18732/gran-maestro-vorpil

El NPC se bugea al matarlo, este vuelve a revivir y no se le puede volver a matar porque aparece "Tu objetivo esta muerto" y eso no permite el despojar, en el vídeo de prueba tengo lag pero eso no es motivo del bug ya que ya he realizado la mazmorra anteriormente e igual se bugea.

Asi funciona en el servidor: https://youtu.be/PlxDPNXTrck

**Comment by athenaswow** [comment]
Corregido La corrección se aplicara en unos días.
