### ISSUE TITLE
Bug de Puntos de Valor

### ISSUE THREAD

**Issue by miguel4345080** [athenaswow/BugTracker-Athenas-WoW#243]
[](https://youtu.be/nWc6cIT6Gpw) normalmente procedo a cambiar mis puntos de valor por puntos de conquista, la vez pasada hice lo mismo y me ocurrió lo del video. Espero que estos puntos me sean devueltos

**Comment by athenaswow** [comment]
Hola buenos días,  Aquí un vídeo de como elaborar el reporte https://www.youtube.com/watch?v=Nbjwet8wh7M ya que no entiendo de que hablas :)
