### ISSUE TITLE
Misión Bug; **Muestra de Control**

### ISSUE THREAD

**Issue by SKLucifer** [athenaswow/BugTracker-Athenas-WoW#244]
Nombre del Personaje Principal: **SKLucifer**
Nombre de mi Personaje Secundario: **Reivin**
ID Discord: **Aun sin cuenta en la misma**

Misión Bug; **Muestra de Control**

En la misión del Norte de la Vega de Tuercespina: **Muestra de Control** (https://es.wowhead.com/quest=26733/muestra-de-control). el **DROP** que suelta el Basilisco: "**Sangre de basilisco Espina de Cristal**" (https://es.wowhead.com/item=60213/sangre-de-basilisco-espina-de-cristal) no aparece porque el Basilisco desaparece al instante que se le elimina impidiendo saquear el drop del mismo, la cual impide terminar la misión.

Dejo muestra de Ejemplo en video de la falla con mi personaje secundario en acción: https://youtu.be/Y03P6tIzfQM

Sin mas que comentar y reportar, y agradeciendo la atención, me despido.

**Comment by athenaswow** [comment]
No puedo ver el vídeo pero revisare a ver cual es tu problema.

**Comment by athenaswow** [comment]
Corregido, la corrección se subirá en unos días.
