### ISSUE TITLE
Perdida y error al equipar reliquias de leveo

### ISSUE THREAD

**Issue by Fydeo** [athenaswow/BugTracker-Athenas-WoW#245]
El dia de ayer me encontraba leviando en monte hyjal. De pronto un ali me mato unpar de veces y despues al revivir, me di cuenta que tres de mis reliquias de leveo se me habian desequipado en mi dk.
Dichas reliquias son:
* Segadora de arcanita ensangrentada (Hacha de dos manos)
* Bufas pulidas de valor (hombro)
* Coraza pulida de valor (Pecho)

Depues de un rato me llegaron al correo del pj con remitente Blizzard, y al retirarlas del correo y tratar de equiparlas de nuevo me arrojo un mensaje: "Este objeto no se puede equipar" (para cada una de las tres reliquias me mostro esto). 
Compre otras reliquias con mi pj 85 y se las reenvie a mi Dk (llamado "Irie") pero me sigue arrojando el mensaje "Este objeto no se puede equipar"

![WoWScrnShot_030620_112915](https://user-images.githubusercontent.com/61884147/76110186-0d471f80-5fac-11ea-9315-8a2c30155dcc.jpg)
![WoWScrnShot_030620_112917](https://user-images.githubusercontent.com/61884147/76110189-0ddfb600-5fac-11ea-8deb-a150c5a45149.jpg)
![WoWScrnShot_030620_112918](https://user-images.githubusercontent.com/61884147/76110190-0e784c80-5fac-11ea-95fb-29daad0e2325.jpg)

**Comment by athenaswow** [comment]
Hola buenos días, La razón por la cual no puedes equipar la reliquias es por ya eres nivel 82 y la segunda razón por la que se desaparecieron sus reliquias es por que subiste a nivel 81 una ves subes a 81 automáticamente sus reliquias se des equipan y te las envían por correo.

**Comment by Fydeo** [comment]
no me queda mas que agradecer por la aclaracion. =) Feliz dia
