### ISSUE TITLE
Bug dagas legendarias...

### ISSUE THREAD

**Issue by neslepacks** [athenaswow/BugTracker-Athenas-WoW#246]
fui a completar la mision de las dagas... y no me dejaba aqui esta el video... y lo intente varias veces en la tarde y ahora en la noche y nada... me ayudan porfavor. hay dejo video de lo q pasa

https://www.youtube.com/watch?v=6KRWnKA-G2Y

**Comment by AresGM** [comment]
Hola, agradecemos su reporte, sin embargo necesitamos más información para la solución del fallo.
Puede basarse en nuestra guía de uso de GitHub la cual requiere de lo siguiente: 

- Agregar link de wowhead de el hechizo, item, logro o misión para ser mas exactos.
- Agregar una descripción del error comprensible para cualquier persona.
- Agregar enlaces que validen el error (wowhead o https://cata-twinhead.twinstar.cz/)
