### ISSUE TITLE
Bug de cambio de puntos de valor por puntos de conquista

### ISSUE THREAD

**Issue by miguel4345080** [athenaswow/BugTracker-Athenas-WoW#248]
Mis puntos de conquista no fueron dados a causa de un bug descontandome también los puntos de valor, exijo que me sean devueltos ya que no tiene ningún sentido que los farmee y me los quite. https://youtu.be/nWc6cIT6Gpw

**Comment by athenaswow** [comment]
Hola buenos días, El problema que estas teniendo es por que ya alcanzaste el limite semanal de puntos de conquista.

Pruebas. 
![image](https://user-images.githubusercontent.com/50283962/76325617-86e55300-62b5-11ea-81c1-ab50546d5406.png)
