### ISSUE TITLE
La hija superviviente

### ISSUE THREAD

**Issue by Armagedones** [athenaswow/BugTracker-Athenas-WoW#249]
Es una mision que mas o menos nos cuenta la historia de Morgan Ladimor.
Despues de una cadena de misiones en el Bosque del ocaso (Faccion alianza) llegamos con la npc llamada comandante althea cerranegro ella nos pide que hablemos con la Hija de morgan que se llama Sara Ladimor que ahora es una guardia, siempre ah estado atormentada por las circunstancias que rodearon la muerte de su padre. Pero el personaje llamada Sara Ladimor no se encuentra por ningun lado, busque y busque a mas nodar y no eh logrado encontrarla en todo caso dejo un video: https://www.youtube.com/watch?v=Qh6obm3i990

**Comment by athenaswow** [comment]
Corregido, El cambio ya fue aplicado.
