### ISSUE TITLE
Bug al entregar misión + error en objeto de misión (fiordo Aquilonal)

### ISSUE THREAD

**Issue by Lamela-La-Buscadora** [athenaswow/BugTracker-Athenas-WoW#25]
Lamela
Lamela#3066
El Npc https://es.wowhead.com/npc=24032/celea-crines-de-hielo no recibe la misión luego de completarla... https://imgur.com/GYPEckz 

*Nota: Revisar el objeto de misión https://es.wowhead.com/item=33347/planes-de-ataque-de-gjalerbron#starts presenta problemas para obtener https://es.wowhead.com/quest=11266/los-planes-de-ataque-de-gjalerbron. Dice que la misión ya se está llevando a cabo cuando no es así.

**Comment by athenaswow** [comment]
para poder aceptar la mision del item  https://es.wowhead.com/item=33347/planes-de-ataque-de-gjalerbron#starts  debes de aver entregado https://es.wowhead.com/quest=11261/el-conquistador-de-skorn
![image](https://user-images.githubusercontent.com/50283962/69771228-06fa0980-115a-11ea-90b7-fc19114ae81b.png)

**Comment by Lamela-La-Buscadora** [comment]
Para asegurar el error en la primera parte del post decidí abandonar la misión https://es.wowhead.com/quest=11267/la-vermis-de-escarcha-y-su-maestro y hacerla nuevamente, para mi sorpresa el Npc https://es.wowhead.com/npc=24032/celea-crines-de-hielo no me asignó la misión. En el vídeo se comprueba que sí la tenía y que además ya estaba completada... 
https://youtu.be/3IEWPnUx8rk

**Comment by athenaswow** [comment]
![image](https://user-images.githubusercontent.com/50283962/69890664-f0bc8c80-12c4-11ea-9456-0a1e8162686c.png)

![image](https://user-images.githubusercontent.com/50283962/69890672-f914c780-12c4-11ea-93b3-e31296cbc24e.png)

![image](https://user-images.githubusercontent.com/50283962/69890690-10ec4b80-12c5-11ea-81f6-4797f11e7715.png)

![image](https://user-images.githubusercontent.com/50283962/69890701-28c3cf80-12c5-11ea-9706-96b1bf120854.png)

![image](https://user-images.githubusercontent.com/50283962/69890709-35482800-12c5-11ea-8752-7b78fb3e09a3.png)

![image](https://user-images.githubusercontent.com/50283962/69890723-4abd5200-12c5-11ea-9ed7-5f2070c000ac.png)

corregido.

**Comment by Lamela-La-Buscadora** [comment]
> ![image](https://user-images.githubusercontent.com/50283962/69890664-f0bc8c80-12c4-11ea-9456-0a1e8162686c.png)
> 
> ![image](https://user-images.githubusercontent.com/50283962/69890672-f914c780-12c4-11ea-93b3-e31296cbc24e.png)
> 
> ![image](https://user-images.githubusercontent.com/50283962/69890690-10ec4b80-12c5-11ea-81f6-4797f11e7715.png)
> 
> ![image](https://user-images.githubusercontent.com/50283962/69890701-28c3cf80-12c5-11ea-9706-96b1bf120854.png)
> 
> ![image](https://user-images.githubusercontent.com/50283962/69890709-35482800-12c5-11ea-8752-7b78fb3e09a3.png)
> 
> ![image](https://user-images.githubusercontent.com/50283962/69890723-4abd5200-12c5-11ea-9ed7-5f2070c000ac.png)
> 
> corregido.

Ahora no me da la misión https://es.wowhead.com/quest=11267/la-vermis-de-escarcha-y-su-maestro el Npc https://es.wowhead.com/npc=24032/celea-crines-de-hielo
