### ISSUE TITLE
Misión Bug (Crecen tan deprisa)

### ISSUE THREAD

**Issue by Maxxyty** [athenaswow/BugTracker-Athenas-WoW#251]
Nombre del PJ principal: Palabugs
Usuario de discord: Maxxyty#6512
Link misión Wowhead: https://es.wowhead.com/quest=13906/crecen-tan-deprisa
![WoWScrnShot_031220_192544](https://user-images.githubusercontent.com/61103537/76579425-2d8a4900-649a-11ea-875b-6c8f8e0cb3b3.jpg)

Muchachos de Athenas WoW, por favor pido urgentemente arreglar esto, no sé si es sólo a mi pero como pueden ver en mi inventario tengo todo lo requerido para completar la misión, y de verdad deseo mucho esa montura, sin embargo no me permite completar la misión, el continuar aparece bloqueado y pues me esforcé mucho buscando los materiales y duré 10 días haciendo las diarias para conseguirlo y ahora que ya terminé no puedo obtener mi montura.

Muchas gracias, quedo atento a mi correo informenme lo antes posible por favor, esa montura la quiero :v

**Comment by athenaswow** [comment]
Hola buenas noches, El bug ya fue reportado y esta bajo revisión https://github.com/athenaswow/BugTracker-Athenas-WoW/issues/211
