### ISSUE TITLE
Elimina al Desterrado

### ISSUE THREAD

**Issue by Armagedones** [athenaswow/BugTracker-Athenas-WoW#252]
Vi que ya lo habían corregido pero veo que sigue estando bug o no se si solo funciona del lado Horda por que fui con mi alianza a realizar misiones de El cabo de Tuercespina pero al llegar y tratar de eliminar a Zanzil no se Auto-completo la misión y me quede atascado ademas que intente tomar el portal que estaba ahi y se supone que te deja en otro lugar mas apartado pero tampoco funcionaba actualmente tengo la misión completa pero no puedo entregarla.

**Comment by athenaswow** [comment]
Hola buenas noches, Necesito mas pruebas para poder ayudarte y solucionar el problema.

**Comment by Armagedones** [comment]
https://www.youtube.com/watch?v=Nz1Xx9DQ3W4 A eso me referia cuando la mision se Auto-completa, y cuando yo me acerco para acabar la mision me aparece que la mision se completa tipico anuncio de color amarillo pero no me aparece la opcion de que la pueda acabar. Espero esto sea suficiente.

**Comment by athenaswow** [comment]
Corregido, su función sera igual a la de la horda se entregara en el mismo npc que se acepto la corrección se aplicara en unos días.
