### ISSUE TITLE
Misión Bug; **Deliciosos estridadores**

### ISSUE THREAD

**Issue by SKLucifer** [athenaswow/BugTracker-Athenas-WoW#253]
Nombre del Personaje Principal: **SKLucifer**
Nombre de mi Personaje Secundario: **Reivin**
ID Discord: **Aun sin cuenta en la misma**

Misión Bug: **Deliciosos estridadores**

En la misión de **Cuna del Invierno**: **Deliciosos estridadores** (https://es.wowhead.com/quest=28745/deliciosos-estridadores). el **NPC** que da la misión: "**Jeb Guthrie**" (https://es.wowhead.com/npc=49537/jeb-guthrie) no da la opción para terminar a pesar de haber hecho la petición de su misión, y así dar su recompensa para pasar a la siguiente misión del mismo **NPC**.

Dejo muestra de Ejemplo la captura de pantalla de la falla con mi personaje secundario en acción: https://ibb.co/L9kv1Vf

Sin mas que comentar y reportar, y agradeciendo la atención, me despido.

**Comment by athenaswow** [comment]
Corregida, a hora deberá ser entregada en el NPc https://es.wowhead.com/npc=49537/jeb-guthrie 
la corrección se aplicara en unos días.
