### ISSUE TITLE
Mazmorra (Horno de Sangre) bug

### ISSUE THREAD

**Issue by miguelangel789123** [athenaswow/BugTracker-Athenas-WoW#254]
Nombre personaje principal: Immanuelkant
Usuario de Discord: Landa#6508
Link de la mazmorra en wowhead: https://www.wowhead.com/the-blood-furnace

En un cuarto anterior a un boss, existe un evento: Accionar una palanca para liberar orcos encerrados. Al ser liberados, los orcos atacan a los jugadores. Esto se hace por tandas. En el momento de accionar la palanca, solamente se libera la primera tanda, después, no ocurre nada y el boss es inaccesible y no se puede seguir haciendo la mazmorra.

Lugar en cuestión:
https://cdn.discordapp.com/attachments/438154568522661892/689697789562847271/unknown.png

El boss en cuestión:
https://cdn.discordapp.com/attachments/438154568522661892/689697820303032320/unknown.png

https://cata-twinhead.twinstar.cz/?zone=3713
https://cata-twinhead.twinstar.cz/?npc=17380

**Comment by athenaswow** [comment]
Ya fue revisado y no se encontró el fallo.
