### ISSUE TITLE
Misión de pesca bug

### ISSUE THREAD

**Issue by miguelangel789123** [athenaswow/BugTracker-Athenas-WoW#255]
Nombre de personaje: Immanuelkant
Usuario de Discord: Landa#6508
Misión: https://es.wowhead.com/quest=26420/excavando-en-busca-de-lombrices

El objeto de la misión no está donde corresponde. Las lombrices no se encuentran en ninguna parte, o no por lo menos donde deberían.

Lugar en cuestión (He revisado muy bien la zona):
https://cdn.discordapp.com/attachments/438154568522661892/689710368268091497/unknown.png

https://cata-twinhead.twinstar.cz/?quest=26420

**Comment by athenaswow** [comment]
Hola buenas noches, El bug ya fue reportado y corregido y esta pendiente aplicar la corrección :)
