### ISSUE TITLE
Misión Bug; **Naturaleza y Nutrición**

### ISSUE THREAD

**Issue by SKLucifer** [athenaswow/BugTracker-Athenas-WoW#256]
Nombre del Personaje Principal: **SKLucifer**
Nombre de mi Personaje Secundario: **Reivin**
ID Discord: **Aun sin cuenta en la misma**

Misión Bug: **Naturaleza y Nutrición**

En la misión de **Frondavil**: **Naturaleza y Nutrición** (https://es.wowhead.com/quest=28229/naturaleza-y-nutrici%C3%B3n).  la misión no da la opción para terminar a pesar de haber hecho la petición de la misión, y de esta forma aparezca el otro **NPC** (https://es.wowhead.com/npc=48032/protector-de-esqueje) que da la siguiente misión.

Dejo muestra de Ejemplo la captura de pantalla de la falla con mi personaje secundario en acción: https://ibb.co/9h0Vz12

Dejo de Ejemplo como debería funcionar la misión: https://youtu.be/SHd70aMi9Yo?t=169

Sin mas que comentar y reportar, y agradeciendo la atención, me despido.

**Comment by athenaswow** [comment]
Corregido, la misión deberá ser entregada al Npc https://es.wowhead.com/npc=48126/isural-jurabosques 
La corrección se agregara en unos días.
