### ISSUE TITLE
[QUEST] Hasta los ladrones tienen hambre

### ISSUE THREAD

**Issue by MijaelElohim** [athenaswow/BugTracker-Athenas-WoW#258]
**PJ PRIN:** Lohem
**DISCORD:** Lohem #4611
**LINK:** https://es.wowhead.com/quest=26235
El problema con esta misión diaria de Cocina es que te manda a matar Ladrones de Orgrimmar (https://www.wowhead.com/npc=42594) pero estos ladrones no están por ninguna parte y por eso no se puede lootear las Raciones de infantería de la Horda (https://es.wowhead.com/item=57879), con las que se completa la quest

**VIDEO:**  
Así deberia poder hacerse...
https://www.youtube.com/watch?v=qKApePuxGxc

**Comment by athenaswow** [comment]
Hola buenas noches, el bug ya fue reportado y corregido esta pendiente aplicar el cambio.
