### ISSUE TITLE
[QUEST] Una presa furiosa

### ISSUE THREAD

**Issue by MijaelElohim** [athenaswow/BugTracker-Athenas-WoW#259]
**PJ PRIN:** Lohem
**DISCORD:** Lohem #4611
**LINK:** https://es.wowhead.com/quest=26588
Para completar esta misión diaria de Pesca debe pescarse el Lucio Furioso Gigante (https://es.wowhead.com/item=58951) en cualquier parte del Rio Furia del Sur al sur de Orgrimmar. Pero el pez no cae, ni siquiera pescando en el lugar donde la quest indica.

**VIDEO:**
Así debería de funcionar:
https://www.youtube.com/watch?v=SvNJhIyOJdo

**Comment by athenaswow** [comment]
Hola buenas noches, El bug ya fue corregido esta pendiente aplicar la corrección.
