### ISSUE TITLE
Rollback y Errores de Hc

### ISSUE THREAD

**Issue by mamamelo** [athenaswow/BugTracker-Athenas-WoW#26]
Personaje Principal Mamamelo, Hunter Huargen
![WoWScrnShot_112619_172712](https://user-images.githubusercontent.com/58236429/69744388-12bfde80-110e-11ea-9902-176da31518be.jpg)
![WoWScrnShot_112719_103924](https://user-images.githubusercontent.com/58236429/69744389-12bfde80-110e-11ea-8ea6-5c531f98b3cb.jpg)
![Uploading WoWScrnShot_112719_104135.jpg…]()
![Uploading WoWScrnShot_112719_113116.jpg…]()

Buenos días, como el titulo lo dice, tengo un rollback de una estancia, Fin De Los Días, este es el item https://es.wowhead.com/item=72897/flecha-de-tiempo&bonus=4144 , como tal no pude tomar foto porque al matar a Murozond, se termino la estancia,regreso a dalaran y hay se callo el servidor, esto pasa el 27 de noviembre a las 11.30, al momento de corroborar que no puedo volver al ultimo boss, coloco un tiqueck, el pj principal se llama Mamamelo, agradezco la colaboracion, 

Otra situación del mismo día fue que nunca apareció el cuerpo de Asira 2 boss de la Hora Del Crepúsculo, no se pudo lotear 

Y lo ultimo el día 26 de noviembre en el pozo de la eternidad entre a y la estancia estaba sola, no habían moobs 
agradezco su atención y por favor **quiero mi abalorio!!**

**Comment by Persefone4102** [comment]
Hola, buen día, esto fue un problema ingame que presentó su pj, para respuesta, debe realizar ticket igame, cierro tema al no tratarse de un reporte valido
