### ISSUE TITLE
[QUEST] El desafío del leucoma

### ISSUE THREAD

**Issue by MijaelElohim** [athenaswow/BugTracker-Athenas-WoW#260]
**PJ PRIN:** Lohem
**DISCORD:** Lohem #4611
**LINK:** https://es.wowhead.com/quest=26414
El problema con esta misión diaria de Pesca es que el Leucoma Endurecido (https://es.wowhead.com/item=58503) que deberíamos pescar en el Lago de Ventormenta no cae.

**VIDEO:**
Así es como debería de funcionar
https://www.youtube.com/watch?v=sx98DJIayGw

**Comment by athenaswow** [comment]
Ya fue corregido, esta pendiente aplicar la corrección.
