### ISSUE TITLE
Misión bug "Mejor pescando"

### ISSUE THREAD

**Issue by Lalalondo** [athenaswow/BugTracker-Athenas-WoW#262]
Nombre pj:Zeldissama
Discord:LaPatataFeliz#6792
Link:https://es.wowhead.com/quest=10037/mejor-pescando

La misión mostro un error después que la entregara se cayó el server, al relogear no aparecía el Npc de la Misión, ni el registro de la misión, una vez vuelto a iniciar la quest con la ayuda de un Admin se presentó el problema de que no dejaba entregarla, en las Screenshots están las pruebas de lo ocurrido, primero la foto del Npc faltante, y la segunda con el fallo de no dejarla entregar.
![WoWScrnShot_032020_153147](https://user-images.githubusercontent.com/62448745/77208312-8d4fa800-6ac9-11ea-93a8-612c4525da76.jpg)
![WoWScrnShot_032020_155812](https://user-images.githubusercontent.com/62448745/77208321-8e80d500-6ac9-11ea-921f-a85dec08dd63.jpg)

**Comment by athenaswow** [comment]
Corregido, el problema no es de la misión pero si encontré un detalle en la Anguila Brilloescama su modelo estaba mal emm tu problema fue que al completar la misión unos segundos después se cayo el servidor y no guardo esos segundo de progreso de su misión mas sin embargo en nuestra base de datos si se quedo registrada lo que hice fue borrar ese registro de tu misión, una ves relogees podrás tomar la misión y llevarla a cavo.
