### ISSUE TITLE
Misión que no se puede entregar(bug): invasión de las tierras de fuego!

### ISSUE THREAD

**Issue by stein1474** [athenaswow/BugTracker-Athenas-WoW#265]
Nombre de mi pj: elliot

Discord: Dìego#2579

La misión de nombre Invasión de las tierras de fuego! tiene el error de no poder entregarse, dicha misión que tengo completada y solo necesito entregar no se puede. La misión me pide ir a un punto marcado por la misión y encontrar a la npc Matogarra (la npc no se encuentra en el lugar que marca la mision), luego de buscar en internet, encontré el lugar donde esta y no permite completar la misión.
adjunte un archivo con capturas de pantalla del juego mostrando que la npc Matogarra no esta donde marca entregar la misión, otras capturas donde encuentro a la npc Matogarra pero no se puede entregar la misión completada.
esta misión es importante para poder continuar con una cadena de misiones para hacer las diarias que te dejan sacar el hipogrifo en llamas y sin esta no se puede seguir con la cadena.

[Doc1 wow athenas.docx](https://github.com/athenaswow/BugTracker-Athenas-WoW/files/4372373/Doc1.wow.athenas.docx)

**Comment by athenaswow** [comment]
Todos los reportes de hyjal serán cerrados ya que estoy trabajando en ese lugar desde cero logrando un mejor resultado en las cadenas de misiones, el parche se aplicara a mas tardar el 15 de abril del 2020.
