### ISSUE TITLE
mision  Perturbar sus refuezos

### ISSUE THREAD

**Issue by Dermin33** [athenaswow/BugTracker-Athenas-WoW#268]
Nombre del Personaje :Elmeroj
mision  Bug :Perturbar sus refuezos

los 2 poltale no se detrulle 
para destruil los 2 poltale necesita 8 piedra
4 por cada poltale pero cuando buscamo las piedra no
se puede destruise da este mesaje de error es 
( no tienes ojertivo)

**Comment by athenaswow** [comment]
Ya fue corregido. el cambio se vera cuando se reinicie el servidor.
