### ISSUE TITLE
Misión: Elimina al desterrado (Cabo de tuercespina)

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#27]
Nombre de personaje principal: Skala
Usuario de discord: JorDaNN#5575
Descripción del error: Había tomado esta misión, mate a ''Zanzil el desterrado'' pero no había npc para completarla ni se auto-completo. La deje para grabar pero ya no me dejo tomarla, curiosamente aparece como misión diaria. Un error aparte es que el item que te da la misión no funciona ''Fetiche de Chabal'' sirve para transportarte a la posición de Chabal una vez muera Zanzil para seguir con la cadena de misiones.
Misión wowhead: https://es.wowhead.com/quest=26551/elimina-al-desterrado
![WoWScrnShot_112719_142621](https://user-images.githubusercontent.com/58092128/69756232-fdf04480-1127-11ea-91c8-74263c87c1db.jpg)
![WoWScrnShot_112719_142730](https://user-images.githubusercontent.com/58092128/69756253-05afe900-1128-11ea-9e93-1229ee5b38e8.jpg)
Como debería funcionar: https://www.youtube.com/watch?v=70S_s7dnGik&feature=youtu.be

**Comment by athenaswow** [comment]
corregido.
