### ISSUE TITLE
Misión falla/" [Armonización con el Núcleo]

### ISSUE THREAD

**Issue by Daniel-mecato** [athenaswow/BugTracker-Athenas-WoW#270]
La presente es para presentar el siguiente error:
 [Armonización con el Núcleo] para completar la quest ya Guía de la quest **https://noticiasgamer.com/blizzard/world-of-warcraft-classic/guias-wow-classic/raid-classic/guia-armonizacion-con-el-nucleo-molten-core/**

eS IMPOSIBLE interactuar con dicho item https://es.classic.wowhead.com/item=18412/trozo-del-n%C3%BAcleo#objective-of
Dando así la imposibilidad de completarla.
links:
https://imgur.com/a/eK4CZjA
https://ptr.wowhead.com/quest=7487/attunement-to-the-core

Dice que no está la quest en el juego, pero el server la presenta.

**Comment by athenaswow** [comment]
Necesitamos un mejor reporte.
