### ISSUE TITLE
Diabolical Plans no funciona MISIÓN

### ISSUE THREAD

**Issue by Nkopala** [athenaswow/BugTracker-Athenas-WoW#271]
Diabolical Plans es una misión de nivel 19 la cual con un personaje de cualquier nivel superior al 19 no se puede iniciar aquí esta el ID del objeto: 23797
Links utiles:
https://cata-twinhead.twinstar.cz/?item=23797
https://es.wowhead.com/item=23798/planes-diabólicos

imagen relacionada con el nombre de mi personaje main Yishmael: https://imgur.com/a/R3aGO4Z
Discord: Yishmael#9884

**Comment by athenaswow** [comment]
La misión ya fue corregida, para poder aceptar la misión requiere de a ver completado la misión https://www.youtube.com/watch?v=ouHBxol8Ufo y https://www.youtube.com/watch?v=SR6JV8vVXVY
de otra manera no podrás aceptar la misión.

**Comment by Nkopala** [comment]
Esa manera no es blizzlike, pero bueno

**Comment by Nkopala** [comment]
Por que esa manera es la manera alianza :)
