### ISSUE TITLE
Arenas BUGEADAS

### ISSUE THREAD

**Issue by ghost** [athenaswow/BugTracker-Athenas-WoW#273]
Ayer por primera vez en este servidor hice arenas con mi compañero (yo soy chaman y mi compañero mago).
Nos salio arena de lordaeron contra otro chaman y un paladin, resulta que cada vez que yo o el chaman enemigo tiramos los totems estos se caen debajo de la tierra sin tener efecto alguno. Por ejemplo use el Earthbind Totem para rootear a mi enemigo pero las raices no salieron, ya que el totem se fue directo al vacio.
Cada vez que mi compañero (mago) utilizaba el "Blink" se iba directo al vacio, junto con mis totems, pudiendo hasta nadar en el lago de lava de esta arena, hasta podia castear habilidades debajo de la tierra. Tambien cada vez que transformaba en oveja a los enemigos (con polymorph) los enemigos tambien se iban debajo de la tierra.
Hasta cuando el chaman enemigo creaba a sus lobos (ya que era de talentos mejora) sus lobos se iban debajo de la tierra tambien.
Basicamente es imposible jugar arena y disfrutarla porque es bastante frustrante caerse cada 20 segundos debajo de la tierra.
Porfavor entiendo que estan solucionando muchos problemas como el de las caidas y que estan contratando nuevos programadores, solo quiero que esten al tanto de este problema y que lo tengan en cuenta porque lo unico que me divierte es hacer arenas.

PD: No filme la evidencia pero si es MUY necesario hacerlo, avisenme y me buscare otro compañero para anotar arenas y filmarlo, ya que mi compañero frustrado con este BUG abandono el wow. Muchas gracias

**Comment by athenaswow** [comment]
Esto debió corregirse con el parche agregado en días pasados, Por favor confirma si es así o sigues teniendo el problema.
