### ISSUE TITLE
Misión: Adiós, pequeñín.

### ISSUE THREAD

**Issue by Cjsh1179** [athenaswow/BugTracker-Athenas-WoW#275]
Nombre pj: Deogall.
Discord: JC_1179#4460
Link item: https://es.wowhead.com/item=53057/sombrero-de-zahor%C3%AD-descolorido

Descripción: 

Buenas noches, 

Resulta que esta semana he estado haciendo toda la cadena de misiones de Azshara para lograr conseguir como recompensa de la quest "Adiós, pequeñín" el ítem mencionado anteriormente. Sin embargo, al momento de tomar esta misión para ir a entregarla, se autocompleta, desaparece del inventario de misiones y cuando voy al NPC que entrega este ítem, no puedo interactuar con él. 

Agradezco mucho la atención y la ayuda si es posible, me sería de agrado saber que no perdí ese tiempo.

Gracias.

Video relacionado con la quest: https://www.youtube.com/watch?v=oe5A2fMZtgU

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días https://www.youtube.com/watch?v=ZDSZTFSNBM4&feature=youtu.be
