### ISSUE TITLE
[QUEST] El fin de la Sangre Maldita

### ISSUE THREAD

**Issue by MijaelElohim** [athenaswow/BugTracker-Athenas-WoW#276]
**PJ PRIN:** Lohem
**DISCORD:** Lohem #4611
**LINK:** https://es.wowhead.com/quest=9683
La idea es llegar a la isla Sangre Maldita y abrirse camino hasta el altar de Azshara en 86,54. Se golpea la estatua y aparece Atoph el Sangre Maldita (https://es.wowhead.com/npc=17715). El problema es que, aunque se le mate y aparezca en pantalla que se le mató, la misión no se completa.
![WoWScrnShot_032620_213447](https://user-images.githubusercontent.com/62361240/77716685-be8a1580-6fac-11ea-92b7-13653da666b2.jpg)

**VIDEO:**
La misión debería ser así
https://youtu.be/Aib0RoHEEow

**Comment by athenaswow** [comment]
Corregido, el cambio se agregara en unos días.
