### ISSUE TITLE
Error/quest/ NO SE PUEDE completar

### ISSUE THREAD

**Issue by Daniel-mecato** [athenaswow/BugTracker-Athenas-WoW#279]
Quest: https://es.wowhead.com/quest=11636/viaje-en-alfombra-m%C3%A1gica
tutorialDE COMO Sse hace : https://www.youtube.com/watch?v=qi5rc6GW5wc

![WoWScrnShot_032720_131918](https://user-images.githubusercontent.com/61131807/77787639-da81cb80-702d-11ea-9bf8-2612fb958813.jpg)

foto donde no deja https://imgur.com/a/iouu9bz
*Dejé la quest más 2 veces/relogueo y nada.

**Comment by athenaswow** [comment]
Corregido.. a hora la alfombra te llevara y podrás entregar la misión, la corrección se aplicara en unos días.
