### ISSUE TITLE
Misión: El corazón de Mokk (Cabo de tuercespina)

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#28]
Nombre de personaje principal: Skala 
Usuario de discord: JorDaNN#5575 
Descripción del error: La situación es que los gorilas de esta zona tendrían que dar ''Colmillo de gorila'' sin embargo, estuve un buen tiempo matando estos mobs y no hablo de 2-10min. Tiene un 44%de drop en wowhead no se cual sea su porcentaje en cataclismo. Me gustaría que puedan corroborar que su drop en athenas sea el correcto                                                                             
Misión wowhead: https://es.wowhead.com/quest=26598/el-coraz%C3%B3n-de-mokk
Colmillo de gorila: https://es.wowhead.com/item=2799/colmillo-de-gorila
Vídeo de la misión y la fácil caída del colmillo de gorila:  https://www.youtube.com/watch?v=1ynPlqsjlLo

**Comment by athenaswow** [comment]
corregido.
