### ISSUE TITLE
error/quest/ [El emisario]

### ISSUE THREAD

**Issue by Daniel-mecato** [athenaswow/BugTracker-Athenas-WoW#280]
como se hace: https://www.youtube.com/watch?v=6__yZ5VmQGQ
wow head  : https://es.wowhead.com/quest=11626/el-emisario 

Al tirar la "lanza" que dan para matar el npc, hace daño correctamente, pero el npc se cura y se hace imposible completarla

https://imgur.com/a/IxcLZMl

**Comment by athenaswow** [comment]
Corregido y aplicado en el servidor.
