### ISSUE TITLE
mision salvemos a los  esporotes

### ISSUE THREAD

**Issue by Dermin33** [athenaswow/BugTracker-Athenas-WoW#285]
el la caverna funggor entro 
tengo que mata 10 dragores de marisma y
10 Rondador de marisma
pero uno de Rondador de marisma no me ataca

**Comment by athenaswow** [comment]
Necesito que sea mas especifico por favor, NO entiendo nada trata de tomar capturas del problema :)

**Comment by Dermin33** [comment]
nota no se escribir bien hola creía que nadie me asía caso aquí 
es cuando entro el la mina uno de los enemigo no me ataca ni yo puedo atacarlos si lo arreglaste pues bien porque no me deja entra en juego para ver tu mejora si me ayuda a comunicarme por emeil  para borrar este mensaje me gusta usa git y github descubrí esto de git y github por tu juego control de versiones

**Comment by athenaswow** [comment]
Corregido, el cambio se agregara en unos días.

**Comment by Dermin33** [comment]
tengo un error para entra en juegos pongo mi nombre y mi contrasella  cojo mi avata cuando esta descargado se queda maun libre puedo movelos en la pantalla y la ralla de descarga se que parada
