### ISSUE TITLE
[QUEST] Un viejo favorito

### ISSUE THREAD

**Issue by MijaelElohim** [athenaswow/BugTracker-Athenas-WoW#286]
**PJ PRIN:** Lohem
**DISCORD:** Lohem #4611
**LINK:** https://es.wowhead.com/quest=29359
La misión te pide pescar alrededor de RuthTheran 8 Arenques Kaldorei (https://es.wowhead.com/item=69987), no nodo sino en mar abierto:
![mapita](https://user-images.githubusercontent.com/62361240/78041728-b5939e00-7336-11ea-9ccb-5f5306d9aa51.JPG)
El problema es que por mucho que lo intentes, nunca cae.
Probado con 6PJs de más de 200 en Pesca.

**VIDEO:**
https://www.youtube.com/watch?v=okNYFnliru8

**Comment by athenaswow** [comment]
Corregido, la corrección se aplicara en unos días.
