### ISSUE TITLE
Bug en mision de infralar que conlleva a la cadena de therazane

### ISSUE THREAD

**Issue by slaughterize** [athenaswow/BugTracker-Athenas-WoW#287]
Pj principal: Jess
Pj Afectado: Xains
Usuario de discord: ⭐Jess⭐#6970

Descripcion del tema: El dia de hoy 31/03/2020 he estado leveando mi paladin en las horas de la tarde en infralar, hice las primeras misiones bien, pero la momento de llegar a la mision de ( https://es.wowhead.com/quest=26771/probando-la-trampa#comments ) y tratar de realizarla, simplemente no se activaba la mision al usar el objeto entregado por el npc 

Imagen de prueba: 
https://imgur.com/a/nAke54s

**Comment by slaughterize** [comment]
No se si sea mucho pedir, pero dado que es una mision importante ( Tanto para la reputacion de Tharazane como para la El anillo de la tierra, Me preguntaba si es posible que me la autocompletaran y asi poder avanzar a la siguiente, cabe mencioanar que dicha mision ya la habia hecho con mi pj principal y saque la reputacion de therazane sin problemas

**Comment by slaughterize** [comment]
Otra cosa, primera vez que uso esta plataforma, asi que no sabia como colocar las etiquetas o tags, Espero que eso no sea impedimento para que me puedan solucionar el problema :)

**Comment by slaughterize** [comment]
Algun gm reponderia mi post y mi problema en esa mision, porfavor  @Persefone4102

**Comment by athenaswow** [comment]
Corrección aplicada el cambio es temporal mientras se corrige correctamente.

**Comment by Skulldafn** [comment]
Debo abrir este tema nuevamente? tengo el mismo problema, las misiones de anillo de la tierra en infralar se quedaron a medias despues del baro
