### ISSUE TITLE
ERROR/MAZ// [Cámaras de Relámpagos]

### ISSUE THREAD

**Issue by Daniel-mecato** [athenaswow/BugTracker-Athenas-WoW#289]
al pagarle a los npc de dicha mazmorra ( [Cámaras de Relámpagos] (está ubicado las cumbres tormentosas)se bajan de las texturas de la misma, haciendo imposible hacerla completa.

https://imgur.com/a/ZCAzVQL pruebas de lo dicho

**Comment by athenaswow** [comment]
Esto se debió corregir con el parche agregado en días pasado, Puedes confirmarlo por favor?

**Comment by Daniel-mecato** [comment]
ok
