### ISSUE TITLE
Misión: Nuestro enemigos mortales (Cabo de tuercespina)

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#29]
Nombre de personaje principal: Skala 
Usuario de discord: JorDaNN#5575 
Descripción del error: Según la misión al ir a la ''Isla Jaguero'' usando el ítem que nos dan ''Pistola de bengalas de Certero'' saldrá un npc que nos ayudará a detectar a los ''Ninjas'' que hay que matar. Sin embargo, a la hora de activarlo también provoca a todo a su alrededor en un área bastante amplia. Pareciera que no hubieran estos ''Ninjas'' para matar o no los activa el item.
Misión wowhead: https://es.wowhead.com/quest=26648/nuestros-enemigos-mortales
Vídeo Athenas: https://www.youtube.com/watch?v=p02XMN_A430&feature=youtu.be
Como debería funcionar: https://www.youtube.com/watch?v=xgsmgJVDuyU

**Comment by athenaswow** [comment]
corregido.
