### ISSUE TITLE
Cepelin Ogrimmar

### ISSUE THREAD

**Issue by Aratsu181** [athenaswow/BugTracker-Athenas-WoW#290]
Nick PJ WOW: Aratsu
Nick Discord: Aratsu#9917

El cepelin que te lleva a tundra Boreal esta bug, para ir de ogrimmar a trundra va bien, pero a la hora de cogerlo para volver de vuelta nunca llega a salir de Rasganorte y se da automaticamente la vuelta y vuelve a Tundra sin nunca volver a ogrimmar, lo que hace que si no tienes la piedra de hogar en otra parte no podras vovler de Rasganorte.

Dejo adjuntado los links con imagenes:
https://ibb.co/XVFJdM8
https://ibb.co/wKBX1CX
https://ibb.co/8PXr7hh
https://ibb.co/7VnbKKk
https://ibb.co/BVCrhZd

Si puedo ayudar en algo, estoy todos los dias por discord.

Un saludo

**Comment by athenaswow** [comment]
Hola buenas noches, Esto debió corregirse con el parche aplicado y fue confirmado por otro jugador y por mi mismo mas sin embargo prueba tu también y me comenta si sigues teniendo ese problema.
