### ISSUE TITLE
Misión: Hasta los ladrones tienen hambre.

### ISSUE THREAD

**Issue by Cefigueredo** [athenaswow/BugTracker-Athenas-WoW#292]
PJ Principal: Kaxuke
Usuario discord: cefigueredo

Descripción del problema: -------------------------------

A la hora de hacer la misión "Hasta los ladrones tienen hambre", mato a los ladrones, pero sólo el primero me suelta las raciones de la horda. Después de matar a incontables ladrones, no me volvió a salir ninguna ración. Según WowHead, el lootrate de eso es de 99%. Adjunto imágenes y lootrate de la ración:
https://ibb.co/CtP65DQ
https://ibb.co/7pTMpJP
https://es.wowhead.com/npc=42594/ladr%C3%B3n-de-orgrimmar

**Comment by Inmershus** [comment]
Confirmo que el bug está, es más, en la entrada de Orgrimmar si matas a los 3 ladrones que hay, los 3 te darán objeto, pero sólo podrás coger uno de ellos.

**Comment by athenaswow** [comment]
Okey parece que el problema esta en la cantidad de items que se pueden drapear al tener la misión, el cambio se agregara en unos días.
