### ISSUE TITLE
Marca de set bugeada por caidas

### ISSUE THREAD

**Issue by xangeil** [athenaswow/BugTracker-Athenas-WoW#295]
Pj principal: Eomerr
usuario de discord : Cretina#0673

descripcion del problema: Estabamos en la banda alma de dragon pero apartir del Jefe Hagara la Vinculatormentas empezo a caerse mas seguido el server esto produjo que una marca que me tocaba a mi guerrero Eomerr no pudiera comerciarse ya que por las caidas hacia que el item no pudiera comerciarse y que cada vez que lo intentaramos se cancelaba el comercio.
Agrego imagenes del item en el momento del comercio y del jefe de banda pidiendome que envie un ticket para que puedan solucionarlo 

https://ibb.co/x3svYb8    -   https://ibb.co/2y9sZb9    -  https://ibb.co/BGqW7js   -  https://ibb.co/Y7FgQkH

**Comment by athenaswow** [comment]
Hola buenos días, Este es un reporte invalido y no debería ser reportado aquí ya que proviene simple y llanamente de las caídas, un Game master podrá ayudarte con ese problema.
