### ISSUE TITLE
Estoy hasta la chingada de este boss de pozo.

### ISSUE THREAD

**Issue by Felixeltoro** [athenaswow/BugTracker-Athenas-WoW#296]
Pj principal: Felixeltoro
usuario de discord : FelixTheBull#6656

Descripción del problema: Estoy cansado de ir tanque en pozo y que el mismo boss tire a la basura esos 15 minutos o más de limpieza porque se bugea y nadie tiene como llamarlo o lo llaman mal y se muere la pet o lo llaman aún peor y se mueren los jugadores fuera del anillo y illidan le comienza a pegar, lleva más de 3 meses asi y se que ya pusieron el problema en la mesa pero sigue sin una solución y es muy estresante.
Necesitamos una solución aunque sea momentánea.

![WoWScrnShot_040620_000258](https://user-images.githubusercontent.com/63224422/78530803-f0b82600-77a9-11ea-8fab-6e98d7cb652f.jpg)

**Comment by athenaswow** [comment]
Este error ya debería estar corregido, Si sigue teniendo el ese problema hágalo saber en otro reporte.
