### ISSUE TITLE
Misión: Conversando con las profundidades

### ISSUE THREAD

**Issue by Cefigueredo** [athenaswow/BugTracker-Athenas-WoW#297]
PJ principal: Kaxuke
Discord: Kaxuke#3575
Descripción: -------------------------------------
La misión consiste en saltar después de usar la perla y de recibir un buff que da el monstruo, al realizar el salto no pasa nada y queda como misión fallida.
https://ibb.co/gDg9f4F

**Comment by athenaswow** [comment]
Necesito mas pruebas
Reglas para subir reportes:
Colocar en el reporte el nombre de su PJ principal.
Colocar en el reporte su usuario de discord (ej.: jugador#0123).
Agregar link de wowhead de el hechizo, item, logro para ser mas exactos.
Agregar una descripción del error comprensible para cualquier persona.
Agregar fotos y/o vídeos.
Agregar enlaces que validen el error (wowhead o https://cata-twinhead.twinstar.cz/)
Nota: https://cata-twinhead.twinstar.cz/ es una web que maneja las bases de datos de: Vanilla, TBC, Wotlk y Cataclysm.
