### ISSUE TITLE
Misión: Maliciosamente delicioso

### ISSUE THREAD

**Issue by miguelangel789123** [athenaswow/BugTracker-Athenas-WoW#299]
Nombre de pj principal: Immanuelkant
Nombre usuario Discord: Landa#6508
Link Wowhead: https://es.wowhead.com/quest=27587/maliciosamente-delicioso
La misión proporciona un objeto, el cual debiera dar respiración bajo el agua, sin embargo, aún teniendo el buff del objeto, la barra de respiración aparece y por ende, no se puede respirar bajo el agua.
Link imágen:
https://cdn.discordapp.com/attachments/438154568522661892/696523205644386414/unknown.png

https://cata-twinhead.twinstar.cz/?item=62795

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
