### ISSUE TITLE
Cuerno Negro sale 2 veces

### ISSUE THREAD

**Issue by GM-Hercules** [athenaswow/BugTracker-Athenas-WoW#3]
Hercules
Hércules#9092
En la banda "Alma de Dragon" en el Jefe "Cuerno Negro" salen 2 NPC para iniciar la batalla, si se llama  al mismo tiempo a cada NPC salen 2 Jefes de Banda.

Prueba Servidor: https://youtu.be/CUwchjkPxgw

**Comment by DennisCalderon** [comment]
actualmente bajo revisión

**Comment by DennisCalderon** [comment]
reparado
