### ISSUE TITLE
No se puede pescar en ogrimar. 

### ISSUE THREAD

**Issue by OnosferatuO** [athenaswow/BugTracker-Athenas-WoW#30]
No se si exista algún fallo, pero no se puede pescar nada, por ende no se puede completar misiones diarias de pesca que se realicen ahí.

**Comment by Skala101** [comment]
Esto ya lleva tiempo, no se si habrán hecho alguna corrección pero en ventormenta tampoco se podía.

**Comment by athenaswow** [comment]
Se necesita mas información en que lugares se presenta el problema imágenes del lugar donde estas intentando pescar, misiones etc...

**Comment by athenaswow** [comment]
Este reporte no cumple con los requisitos necesarios para poder detectar e. problema.

**Comment by athenaswow** [comment]
Información insuficiente.
