### ISSUE TITLE
Bug en la misión "la purificación de Quel' Delar" de la cadena de misiones de la empuñadura maltrecha

### ISSUE THREAD

**Issue by Gominola88** [athenaswow/BugTracker-Athenas-WoW#301]
PJ GOMOZO
Discord: xerofercho #6366
La cadena misiones presenta problemas precisamente en la misión "la purificación de Quel'Delar" dónde se tiene que ir a la meseta de la fuente del sol. Se supone que después de una historieta que desarrollan los npc en ese sitio, debo escoger la espada para ir a corona de hielo  y así terminar la cadena. No obstante, en mi caso los npc hacen unos diálogos y luego se quedan ahí sin más y no puedo recoger la espada ni nada.
Aquí añado link de una guía para esta misma cadena de la empuñadura maltrecha : https://youtu.be/-x-mI5tDXIE

**Comment by Gominola88** [comment]
![Uploading 15865410184518407757889013061192.jpg…]()

**Comment by millonario30** [comment]
Pj: Fhenrir
Discord: Fhenrir #9869
Tuve exactamente el mismo problema, vengo desarrollando la cadena de misiones de la empuñadura maltrecha y cuando llegue a la misión ''La purificación de Quel'delar'' fui a la meseta de la fuente del sol. Los npc empezaron a hablar y me pedía que arroje la espada a la fuente del sol para purificarla y luego no paso mas nada, no puedo agarrar la espada y por lo tanto no puedo entregar la misión en la corona de hielo y tampoco tengo mas el item y no quiero abandonar la misión por que perderé la empuñadura que era el objeto con el que comenzaba la cadena.
Añado el link donde muestra la misma cadena de misiones de la empuñadura: https://www.youtube.com/watch?v=-x-mI5tDXIE
Por favor, ayuda y muchas gracias
