### ISSUE TITLE
TIpologia : Mision  

### ISSUE THREAD

**Issue by atlio12** [athenaswow/BugTracker-Athenas-WoW#302]
la mision nos entrega  [Lanzallamas Krom'gar] para quemar las Tiendas de Fuerte del Norte

**Comment by athenaswow** [comment]
Necesito mas información recuerda...
Reglas para subir reportes:
Colocar en el reporte el nombre de su PJ principal.
Colocar en el reporte su usuario de discord (ej.: jugador#0123).
Agregar link de wowhead de el hechizo, item, logro para ser mas exactos.
Agregar una descripción del error comprensible para cualquier persona.
Agregar fotos y/o vídeos.
Agregar enlaces que validen el error (wowhead o https://cata-twinhead.twinstar.cz/)
Nota: https://cata-twinhead.twinstar.cz/ es una web que maneja las bases de datos de: Vanilla, TBC, Wotlk y Cataclysm.
