### ISSUE TITLE
Mision que se autocompleta sola 

### ISSUE THREAD

**Issue by atlio12** [athenaswow/BugTracker-Athenas-WoW#303]
Pj principal : Atlio - Alianza 
id Discord : italo12#9069

Mision: Despejar El Paso Elevado
Zona : Los Baldíos del Sur 
Faccion :  Horda 

La mision requiere asesinar 3 npc que se encuentran por el camino que se recorre .
Se puede notar en el video 
 en wowhead : https://es.wowhead.com/quest=24504/despejar-el-paso-elevado#videos:id=71057
en youtube : https://www.youtube.com/watch?v=WcDR-R1n9e4 

El problema en la mision no es en si que no haiga npcs que asesinar o no se pueda completar mas en si de que se completa automaticamente como se mira en el video sin necesidad de matar a los npc , como se ve en el video 
https://youtu.be/AtsY1bTxLBc

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
