### ISSUE TITLE
Bug en uldum 

### ISSUE THREAD

**Issue by joma997** [athenaswow/BugTracker-Athenas-WoW#304]
No puedo ver a ningún jugador en uldum ni enemigos ni de mi facción, tampoco me deja ver npcs para seguir haciendo misiones incluso los portales a orgrimmar que están ahí puedo ver como si estuviera en otra dimensión de uldum

**Comment by athenaswow** [comment]
Necesitamos mas pruebas, no puedo hacer nada sin pruebas ya que no hay por donde empezar uldum es muy grande.

**Comment by joma997** [comment]
@athenaswow es en todo uldum, no puedo ver portales ni a las personas ni a npc’s, el sr @AresGM dice que estoy en un tipo de fase

**Comment by athenaswow** [comment]
Sube capturas de su historial de misiones/auras y bolsas puede que algo de eso te este mantenga en esa fase.. o quizá te saltaste misiones.. Por ejemplo hay una misión bug que te cambio de fase y no la hiciste eso te dejara en ella asta que no la completes.

**Comment by joma997** [comment]
El señor ares me ayudo intentando completar varias misiones y abriéndome las cadenas que no podía hacer, conseguí el logro de las 105 misiones en uldum y aun así no se me quita esa fase 
![image](https://user-images.githubusercontent.com/63477146/79469307-a020a400-7fc5-11ea-9ab3-83d13883e39b.jpg)
