### ISSUE TITLE
Misión: Truenos de acero (Bosque de Argénteos)

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#31]
Nombre de personaje principal: Skala 
Usuario de discord: JorDaNN#5575 
Descripción del error: Al aceptar la misión no sale el npc que tiene que seguirte, y cuando encuentras las cajas que hay que recoger por ende no cuentan para la misión. 
Wowhead misión: https://es.wowhead.com/quest=27069/truenos-de-acero#comments
Athenaswow: https://www.youtube.com/watch?v=iyID3xSMQCs&feature=youtu.be
Como debería funcionar: https://www.youtube.com/watch?v=6I9jpDabUkY&feature=youtu.be

**Comment by athenaswow** [comment]
corregido.
