### ISSUE TITLE
Al fuerte livingston

### ISSUE THREAD

**Issue by Armagedones** [athenaswow/BugTracker-Athenas-WoW#311]
Descripción
El primer lugar en el que buscaremos será el que tiene más probabilidades de ser atacado primero. Tú lo llamas Fuerte Livingston.

El Fuerte Livingston eh'tá rodeado de ruinas trol... es un objetivo fácil.

Tal vez encontremos al emisario allí. Eh'peremos que no sea demasiado tarde.

Pero resulta que el npc al que hay que entregarle la mision para seguir la cadena no se encuentra por ningun lado pero en todo caso hago esto para conseguir el logro de norte de tuercespina que son 50 misiones en total, el npc se llama Mariscal de Livingston aqui dejo pruebas:
https://www.youtube.com/watch?v=tjbTt3FwDEQ

**Comment by athenaswow** [comment]
Corregido, el Npc a hora se puede ver, las de mas funciones del Npc se agregara en unos días.
