### ISSUE TITLE
Bug en pozo de la eternidad

### ISSUE THREAD

**Issue by Bobispnj** [athenaswow/BugTracker-Athenas-WoW#312]
Cuando se llega al boss Mannoroth y Varo 'then los mobs llamados "Murciélago de las sombras" está bug ya que al atacarlos no les afecta el daño y para que se les pueda dañar se necesita una mascota de cazador o tótem de chamán, por lo que sin esas clases se hace imposible avanzar y terminar la mazmorra.
Esperando respuesta, un saludo.

**Comment by Felixeltoro** [comment]
También se pueden activar con los estandartes de hermandad que se compran en los heraldos y esos los pueden comprar todos los que estén en una hermandad.
No digo que no deba ser reparado, pero mientras, está esa solución.

**Comment by DennisCalderon** [comment]
Reparado!!!
Los cambios ya fueron aplicado al servidor
