### ISSUE TITLE
[BUG] [LOGRO] "Brann totalmente nuevo" ID 2154

### ISSUE THREAD

**Issue by juanma0599** [athenaswow/BugTracker-Athenas-WoW#313]
En las Cámaras de Piedra hay un logro el cual consiste en derrotar el encuentro del Tribunal de los Tiempos en las Cámaras de Piedra en dificultad heroica sin permitir que Brann Barbabronce sufra daño
Explico, los jugadores deben defender a Brann de las oleadas de enemigos que aparecen constantemente para intentar detenerlo, si los jugadores consiguen limpiar todas las oleadas sin que Brann reciba daño de los enemigos al final de encuentro debería de dar el logro https://es.wowhead.com/achievement=2154/brann-totalmente-nuevo#criteria-of
Como se puede observar en nuestro vídeo https://youtu.be/bl9f-Jr9lEI hicimos todas las oleadas y Brann en ningun momento recibe daño de los enemigos pero al final del encuentro no nos da ningun logro, hicimos el mismo proceso 3 veces pensando que lo habiamos hecho mal, pero guiandonos del video en wowhead https://youtu.be/xh9i9QhBy9M?t=217 se observa como el jugador lo hace de la misma manera pero con la diferencia de que si le dan el logro
Un detalle a destacar es que en Athenas solo salen oleadas por la izquierda cuando deberian de salir por ambos lados

**Comment by athenaswow** [comment]
Hola buenas tardes, Este bug ya fue reportado aquí https://github.com/athenaswow/BugTracker-Athenas-WoW/issues/86
