### ISSUE TITLE
Nesingwary lo sabrá

### ISSUE THREAD

**Issue by Armagedones** [athenaswow/BugTracker-Athenas-WoW#314]
Descripción
Genial, justo lo que necesitamos: los Gurubashi arrasándolo todo con serpientes para liderar el ataque. Bueno, al menos eso lo sabemos.

Lo más seguro es que los cazadores de la Expedición de Nesingwary sepan algo de todo esto. Y si no es así, al menos saben cómo enfrentarse a estas serpientes.

Dirígete hacia allí y hazles saber lo que has visto aquí. Infórmales de que los trols están usando serpientes a modo de arma.

Llegue ah entregarle la mision al enano pero no me deja conpletarlo por que el Npc no le aparece el ? a demas las serpientes que estan al rededor no se les pueden atacar dejo el link de como debe ser:
https://www.youtube.com/watch?v=CMALXCRAIgE

**Comment by athenaswow** [comment]
Corregido, la corrección se agregara en unos días.
