### ISSUE TITLE
Misión del raptor pellejo venenoso bug 

### ISSUE THREAD

**Issue by joma997** [athenaswow/BugTracker-Athenas-WoW#315]
No puedo completar esta misión para la montura y ya tengo loa materiales.
![image](https://user-images.githubusercontent.com/63477146/79607938-bf006280-80b9-11ea-8186-256e471b2d20.jpg)

**Comment by joma997** [comment]
Ya se arreglo, toca soltar la misión y volverla a tomar

**Comment by athenaswow** [comment]
Ya fue reportado y esta en revisión, a unos les deja completar a otros no.
