### ISSUE TITLE
Bug drop pez furia sangradientes

### ISSUE THREAD

**Issue by ghost** [athenaswow/BugTracker-Athenas-WoW#318]
**PJ principal:** Chuckpalal
**Usuario de discord:** Chuckpalal#5890

Buen dia, hoy quiero reportar un bug que encontrado y dificulta el completar esta diaria de pesca.

La misión "La sangre es más espesa" (https://cata-twinhead.twinstar.cz/?quest=13833) nos pide ir a la zona tundra boreal y pescar en bancos de sangre que se crean cuando matas un animal, te queda si sangre encima y te tiras al agua, la sangre queda allí creando un banco donde llegan estos peces (Pez furia sangradientes ) de la misión como se puede ver en esta base de datos proporcionada por los desarrolladores del server para estos reportes (https://cata-twinhead.twinstar.cz/?item=45905#fished-from-object) el drop de los peces debe ser del **100%** por ser una misión.

**Descripción del problema:**

los peces tienen un drop muy muy bajo, duré 1 hora pescando para que solo me cayeran 4 peces de los 5 de la misión; después me arte y consulte el drop donde efectivamente pude ver que se encuentra bug en el server.

Prueba: https://www.youtube.com/watch?v=-ofFeFOnbjY&feature=youtu.be

Gracias por su atencion C:

**Comment by Felixeltoro** [comment]
Si quieres completarla ya solo ve al mar y pescalos, en 4 minutos o menos tienes los 5.
