### ISSUE TITLE
Y recuerden wachos, siempre lleven un chami al icc.

### ISSUE THREAD

**Issue by Felixeltoro** [athenaswow/BugTracker-Athenas-WoW#319]
Se bugueo el boss y el chamo lo salvó.
Benditos sean esos chamis que salvan la mentira.
Si el chami es dps mejor que mejor.
No lo borren.
![WoWScrnShot_041920_212634](https://user-images.githubusercontent.com/63224422/79708744-e1df7200-8285-11ea-8a11-1088b0e1b83c.jpg)
![WoWScrnShot_041920_212957](https://user-images.githubusercontent.com/63224422/79708752-e4da6280-8285-11ea-981a-39d6b78d9dc5.jpg)
![WoWScrnShot_041920_213347](https://user-images.githubusercontent.com/63224422/79708754-e6a42600-8285-11ea-8401-e4fef6df0d6e.jpg)

**Comment by Felixeltoro** [comment]
Si el chami es dps mejor que mejor

**Comment by Daniel-mecato** [comment]
Siempre pasa, ese el npc (no recuerdo su nombre) nunca da ress

**Comment by DennisCalderon** [comment]
Reparado!
Ya pueden buscar su montura
