### ISSUE TITLE
No se puede pescar en Orgrimmar - Ventormenta

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#32]
Nombre de personaje principal: Skala 
Usuario de discord: JorDaNN#5575 
Descripción del error: No se puede pescar absolutamente nada, se tira la caña y al recogerla cuando toca, no da ningún loot. Recalcar que mi pesca esta por encima del 525 que es el máximo. Vi un reporte anterior en que faltan pruebas para este reporte, sin embargo, no podemos reportar las misiones como bug por que no hay oportunidad  a probarlas. Igualmente pondré abajo algunas misiones que se llevan acabo en Orgrimmar.
Wowhead misión: https://es.wowhead.com/quest=11665/crocoliscos-en-la-ciudad#comments
Wowhead misión: https://es.wowhead.com/quest=26556/prohibido-lanzar-residuos
Wowhead misión: https://es.wowhead.com/quest=26557/un-esfuerzo-asombroso
Athenaswow: 
Orgrimmar1: https://www.youtube.com/watch?v=j7AC0R6pdAw&feature=youtu.be
Orgrimmar2: https://www.youtube.com/watch?v=ej344Rbx1bM&feature=youtu.be
Ventormenta1: https://www.youtube.com/watch?v=o-ICb-Blyic&feature=youtu.be
Ventormenta2: https://www.youtube.com/watch?v=c8Sa3Ys-02o&feature=youtu.be

**Comment by jumper-s** [comment]
Personaje: Jumpercito
Otra misión que se puede agregar a las diarias de pesca es:
https://es.wowhead.com/quest=29361/el-monstruo-del-foso
que sale error al alimentar al monstruo.
Atte. Jumper

**Comment by athenaswow** [comment]
Ya reportado.

**Comment by pangolp** [comment]
Ya lo tenemos resuelto el problema @Skala101 @jumper-s solamente no pudimos subir la solución debido a que debemos tirar el servidor por unos minutos y estamos buscando el momento adecuado para poder aplicar la corrección. Tengan un poco de paciencia, de hecho existen otros reportes como bien les menciona mi compañero.

**Comment by Skala101** [comment]
Mira las fechas antes de etiquetar por fa. Estoy al tanto del bugtracker
