### ISSUE TITLE
Mision diaria: Poder de los Magnos (los oráculos)

### ISSUE THREAD

**Issue by Felixeltoro** [athenaswow/BugTracker-Athenas-WoW#320]
Nombre pj: Felixeltoro
Usuario de discord: FelixTheBull#6656
Al estar cerca del pilar sangrevida uno podría cargar el ítem "cristal pulido durmiente" pero pues no se activa el ítem, adjunto fotos desde todos los ángulos que se me ocurrieron.
Adjunto: Encontré un lugar donde se carga, pero sigo pensando que se debería cargar en cualquier sitio cerca al cristal. (es justamente donde estoy parado).
![WoWScrnShot_041920_222954](https://user-images.githubusercontent.com/63224422/79711513-9cbf3e00-828d-11ea-83eb-a2d565879fea.jpg)
https://es.wowhead.com/quest=12762/poder-de-los-magnos
![WoWScrnShot_041920_221144](https://user-images.githubusercontent.com/63224422/79711183-c7f55d80-828c-11ea-9f6c-3787221a58a1.jpg)
![WoWScrnShot_041920_221155](https://user-images.githubusercontent.com/63224422/79711187-c9268a80-828c-11ea-8e90-c301d9f31c5c.jpg)
![WoWScrnShot_041920_221204](https://user-images.githubusercontent.com/63224422/79711188-ca57b780-828c-11ea-8fd0-1f2316e43631.jpg)
![WoWScrnShot_041920_221213](https://user-images.githubusercontent.com/63224422/79711189-caf04e00-828c-11ea-94e2-415970c2c43a.jpg)
![WoWScrnShot_041920_221221](https://user-images.githubusercontent.com/63224422/79711191-cc217b00-828c-11ea-96b6-d021eeb0d54e.jpg)
![WoWScrnShot_041920_221229](https://user-images.githubusercontent.com/63224422/79711193-cd52a800-828c-11ea-9bea-0a5dad648707.jpg)

**Comment by athenaswow** [comment]
No se encontró el problema.
