### ISSUE TITLE
TORNEO ARGENTA MISION: DROTTINN HROTHGAR

### ISSUE THREAD

**Issue by vicmatus** [athenaswow/BugTracker-Athenas-WoW#321]
personaje principal: yorha
DISCORD: manuel "YORHA"#6939

AL MOMENTO DE UTILIZAR EL ITEN QUE DA LA MISION DICE QUE NESESITAMOS ESTAR CERCA DE MONUMENTOS TUALIQ, EL EL VIDEO DEJO COMO FUNCIONA EN ATHENAS.

ASI FUNCIONA EN ATHENAS https://www.youtube.com/watch?v=T_tJXzUxqvc&feature=youtu.be
ASI DEVERIA FUNCIONAR https://www.youtube.com/watch?v=eBgzYBK-Biw
(LLEVO ESPERANDO RESPUESTA DE LA CONSULTA #263 )

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
