### ISSUE TITLE
Misión: Last Rites 

### ISSUE THREAD

**Issue by Roberth6637** [athenaswow/BugTracker-Athenas-WoW#323]
PJ Principal: Boxxyz 
Usuario de Discord: 死 ZeroTwo#0266

Descripción del problema: La misión consta de acompañar a Thassarian a ver a un infiltrado, bueno eso da igual es lore, todo esta bien, hablan, normal, pero llega el momento en el que nos tenemos que enfrentar al NPC enemigo y Thassarian se queda bug de tal forma que no hace nada, y como el NPC enemigo tiene 200K de vida, no le puedo matar, en la misión como tal Thassarian ayuda a matarlo y se da el Lore, pero se queda quieto sin target y termino muriendo, cuando vuelvo se quedan los 2 npc que aparecen junto a el de la quest, pero Thassarian desaparece, haciendo imposible matar de este.

Id de la Quest:
https://cata-twinhead.twinstar.cz/?quest=12019
Archivos Adjuntos/prueba:
https://imgur.com/a/HKHCQKz

**Comment by athenaswow** [comment]
Corregido.
