### ISSUE TITLE
Macro focus de Miedo del brujo

### ISSUE THREAD

**Issue by Sasuu7** [athenaswow/BugTracker-Athenas-WoW#324]
Kymimaro
Sasuu 🌙#6933

Como deberia Funcionar 
La Habilidad Fear o Miedo del brujo en general con esta macro de Focus (#showtooltip
/cast [@focus] Miedo) Debería funcionar normalmente como cualquier macro de focus 

Como esta Funcionando 
No se si esto solo me pasa a mi o a todos los Brujos en general pero yo al usar esta sencilla macro de Focus
#showtooltip
/cast [@focus] Miedo
Me aparece como si tuviera las lengenderia del rogue llamada Miedo/Fear y no me deja usar la macro queda bloqueada y me sale la imagen del Arma y se me hace bastante molesto esto para hacer cc 

pdta : ya he intentado usar otras macros de Focus y me sale lo mismo 

Muchas Gracias espero una pronta Respuesta o solucion 

![image](https://user-images.githubusercontent.com/55250978/80026348-9efce480-84a7-11ea-876c-4faad8b86fb9.png)

**Comment by wallefc96** [comment]
Aun a la fecha persiste dicho error.

**Comment by athenaswow** [comment]
Si el error continua por favor elabore un nuevo reporte.

**Comment by ddgcom** [comment]
El problema es que usas un macro del oficial  así debería de funcionar en un servidor privado @wallefc96 @athenaswow 

`/cast [@mouseover] Disparo silenciador`
