### ISSUE TITLE
Se desaparecio mi Sombrero elegante de Burgy Corazón Negro

### ISSUE THREAD

**Issue by renzoypilco** [athenaswow/BugTracker-Athenas-WoW#327]
- Pancitho
-esponjosho#2602
-Sombrero elegante de Burgy Corazón Negro
-Haber desapareció mi juguete Sombrero elegante de Burgy Corazón Negro despues de la caida de sever, me llego al correo  [Yelmo de placas de tinieblas de Gladiador implacable] y con un mensaje de english que no entendí, hasta en ese momento no entendi porque me enviaron el Yelmo hasta que me di cuenta después haberme re-conectado otra ves que mi  Sombrero elegante de Burgy Corazón Negro no estaba. 
Y creo que se desapareció después de la caída que ocurrio hace unas horas atrás, no pienso farmear de nuevo el sombrero ya estuve como 4hras esperando que aparezca y que de la nada se vaya asi.
Espero que pueda solucionar esto. Gracias
![WoWScrnShot_042220_204728](https://user-images.githubusercontent.com/59895609/80050197-91148700-84da-11ea-971b-9b151a57d7a5.jpg)
![WoWScrnShot_042220_201002](https://user-images.githubusercontent.com/59895609/80050201-94a80e00-84da-11ea-8a06-285a41b55b99.jpg)
- Como ven la imagen del mapa se ve que el rare ya no se encuentra porque lo mate, y la otra es la bolsa que no encuentro el juguete
- https://es.wowhead.com/item=134022/sombrero-elegante-de-burgy-coraz%C3%B3n-negro#dropped-by

**Comment by athenaswow** [comment]
Lamento decirte que este no es el lugar para hacer la reclamación de un ítem perdido luego de una caída, Debes abrir un ticket en juego o contactar con un Game máster en el grupo de discord.
Por que no es el lugar para esto ?¿   Por que es una perdida de ítem a causa de una caída que se presento en el servidor y no a causa de un bug de una misión o algo por el estilo.

**Comment by renzoypilco** [comment]
Bueno, gracias por la informacion.
