### ISSUE TITLE
La estancia de hora del crepusculo esta bugg

### ISSUE THREAD

**Issue by deznanher3** [athenaswow/BugTracker-Athenas-WoW#329]
Nombre del Personaje "Living"///-Theralion tiene ese echizo bugg>>>>spell=74807/reino-crepuscular<<<<<<<. despues que nos lleva al reino ya no podemos salir

**Comment by athenaswow** [comment]
Si no nos puedes proporcionar si quiera el 50% de lo que pedimos en las reglas, No podremos encontrar el problema.

Colocar en el reporte el nombre de su PJ principal.
Colocar en el reporte su usuario de discord (ej.: jugador#0123).
Agregar link de wowhead de el hechizo, item, logro para ser mas exactos.
Agregar una descripción del error comprensible para cualquier persona.
Agregar fotos y/o vídeos.
Agregar enlaces que validen el error (wowhead o https://cata-twinhead.twinstar.cz/)
Nota: https://cata-twinhead.twinstar.cz/ es una web que maneja las bases de datos de: Vanilla, TBC, Wotlk y Cataclysm.
