### ISSUE TITLE
Misión: ¿Quién necesita calderas? (Tierras de la peste del oeste)

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#33]
Nombre de personaje principal: Skala
Usuario de discord: JorDaNN#5575
Descripción del error: Al poner el barril en los lugares que te deja, no cuentan para la misión, recalcar que lo he usado bastantes veces alrededor de los lugares para comprobarlo bien.
Misión wowhead: https://es.wowhead.com/quest=26978/qui%C3%A9n-necesita-calderas
Athenaswow: https://www.youtube.com/watch?v=-Z97sUlUb2k&feature=youtu.be
Como debería funcionar: https://www.youtube.com/watch?v=oxIKddMAwxM

**Comment by athenaswow** [comment]
corregido.

**Comment by Skala101** [comment]
Estas correcciones cuando las vemos en el servidor?
