### ISSUE TITLE
bug de botin estancias de Burning Crusade

### ISSUE THREAD

**Issue by jeiduart** [athenaswow/BugTracker-Athenas-WoW#332]
Jugador : Tainys
Discord: Tainys#8409

Buenas abro es hilo para mostrar un bug, que ya hace tiempo ya habia reportado dicho bug, pero me lo cerraron y colocaron que ya estaba solucionado, eso fue en 27 de enero, hoy 24 de abril el bug sigue.

Los bosses de las estancias de burning tienen el botin buguiado ya que muchas veces dejan mugre o objetos verdes, cuando deberían dejar un objeto azul y en heroico el boss final 2 objetos azules.
 
Acá dejo foto de 2 bosses de la estancia La Sotienaga https://es.wowhead.com/npc=17882/la-acechadora-negra

Penultimo boss Señor del pantano Musel'ek
https://es.wowhead.com/npc=17826/se%C3%B1or-del-pantano-muselek
![boss1](https://user-images.githubusercontent.com/60366740/80240538-fc23a200-862f-11ea-8ce8-d3a03fe09c6a.png)

Ultimo boss La Acechadora, en esta oportunidad el boss me dejo puros objetos grises resalto que es el boss final de La Sotienaga y fruta hacerse toda la estancia para que te den mugre.
https://es.wowhead.com/npc=17882/la-acechadora-negra
![boss2](https://user-images.githubusercontent.com/60366740/80241297-5d984080-8631-11ea-9d5a-a8d5ce66ba0e.png)

Este bug ocurre muy frecuentemente.

**Comment by athenaswow** [comment]
Hola.. e revisado sus reportes y el único que encontré fue https://github.com/athenaswow/BugTracker-Athenas-WoW/issues/153 por lo que no creo que ayas reportado esto antes, Por lo menos en el bug tacker y en nuestro repositorio no hay información de este reporte.

**Comment by athenaswow** [comment]
No es que el loot este bug lo que pasa es que el loot tiene un porcentaje 
![image](https://user-images.githubusercontent.com/50283962/80253448-ea95c680-863e-11ea-9df1-9a456a960159.png)
![image](https://user-images.githubusercontent.com/50283962/80253460-f1bcd480-863e-11ea-8839-9a8ed30128d9.png)
![image](https://user-images.githubusercontent.com/50283962/80253523-1153fd00-863f-11ea-9d31-22461c667d56.png)
![image](https://user-images.githubusercontent.com/50283962/80253552-1dd85580-863f-11ea-8fb6-97f1ff4211bc.png)

**Comment by athenaswow** [comment]
![image](https://user-images.githubusercontent.com/50283962/80253741-6db71c80-863f-11ea-8e30-8aea672ac617.png)

**Comment by athenaswow** [comment]
![image](https://user-images.githubusercontent.com/50283962/80253810-93442600-863f-11ea-9b5f-0569fc40bdba.png)
![image](https://user-images.githubusercontent.com/50283962/80253855-b078f480-863f-11ea-8f08-392b6e49a732.png)
![image](https://user-images.githubusercontent.com/50283962/80253910-cb4b6900-863f-11ea-8316-e8790d96c3be.png)

**Comment by jeiduart** [comment]
si es por porcentaje, pero siempre debe dejar un objeto azul ya me a pasado muchas veces que da objetos grises, verdes o incluso que no den nada y si es el 153 reporte que estaba bug el botin de jefes y lo colocaron como arreglado pero aun sucede mucho y no debería, siempre deben dejar un item azul.

Y no es en solo esa estancia es en todas las de burning las de rasganorte no pasa eso
