### ISSUE TITLE
La carga de un héroe (mision)

### ISSUE THREAD

**Issue by chigii** [athenaswow/BugTracker-Athenas-WoW#333]
chigii
sebastian arenas#2763

la  quest=12581 (La carga de un héroe) 
 de la cadena de misiones del draco verde tiene un fallo

los NPC deberian estar congelados para uno escoger a quien salvar antes de matar el npc de la mision 

![WoWScrnShot_042420_192918](https://user-images.githubusercontent.com/64171166/80266717-f2676200-8662-11ea-85dd-578833f76e95.jpg)

por lo tanto cuando el objetivo "Artruis el Inhumano" npc=28659---- de la misión aparece golpea a uno de los 2 NPC y afecta el seguimiento de la mision puesto que ya no se podria salvar ese objetivo y completa la mision solo a favor de faction=1104/tribu-corazón-frenético

![WoWScrnShot_042420_182757](https://user-images.githubusercontent.com/64171166/80266849-bc76ad80-8663-11ea-98d3-813febc8bb42.jpg)

anexo link de video oficial de la mision.. a partir del minuto "1:09" 
https://www.youtube.com/watch?v=L7FKKXDZKho

Gracias

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
