### ISSUE TITLE
Problema con mis personajes para entrar en mazmorras antiguas

### ISSUE THREAD

**Issue by darko1788** [athenaswow/BugTracker-Athenas-WoW#334]
Saludos.

Resulta que con algunos de mis personajes no puedo entrar a mazmorras antiguas o bandas antiguas y bandas de cataclysm, no da ningun mensaje de id, combate, o algo por el estilo...simplemente no me deja entrar.

Me gustaria que revisaran ese caso puesto que a veces quiero ir con miembros de la guild a mazmorras y bandas y por esa situacion no puedo acceder y no se si tendre ese problema con el resto de mis personajes

Los pjs con los que tengo ese problema confirmado son
 Huntroll (Cazador lv. 85)
Moomoomilk (DK lv. 85)

Usuario discord: Mau#5051

**Comment by athenaswow** [comment]
Necesitamos mas pruebas.. Con lo dices en el reporte no tengo por donde empezar.

**Comment by athenaswow** [comment]
Reglas para subir reportes:
Colocar en el reporte el nombre de su PJ principal.
Colocar en el reporte su usuario de discord (ej.: jugador#0123).
Agregar link de wowhead de el hechizo, item, logro para ser mas exactos.
Agregar una descripción del error comprensible para cualquier persona.
Agregar fotos y/o vídeos.
Agregar enlaces que validen el error (wowhead o https://cata-twinhead.twinstar.cz/)
Nota: https://cata-twinhead.twinstar.cz/ es una web que maneja las bases de datos de: Vanilla, TBC, Wotlk y Cataclysm.
