### ISSUE TITLE
Bug ID locura

### ISSUE THREAD

**Issue by neslepacks** [athenaswow/BugTracker-Athenas-WoW#335]
Estaba haciendo DS con mi raid, y pues... hacia falta dps y heal entonces mis compas hicieron cambios... la cosa fue q un mal amigo me bugeo el lot y a los q les caia pues... se perdio... aqui tengo evidencias me ayudan porfa...

https://imgur.com/a/TzNKats 

 y pues hay termine en el fondo del abismo :c una ayuda porfa!

**Comment by athenaswow** [comment]
Ya se le informo a un Gm para que atienda su caso, Si se les bugeo el loot trata de abrir otro reporte y sube pruebas del fallo para corregirlo, la perdida de loot tienes que abrir un ticket en juego.
