### ISSUE TITLE
Personaje atascado

### ISSUE THREAD

**Issue by renzoypilco** [athenaswow/BugTracker-Athenas-WoW#338]
Buenas a todos, Tengo un problema sobre uno de mis personajes que fue CONGELADO durante el evento de AYER en Arena Gurubashi(El cabo de tuercespina) necesito alguien que me pueda ayudar en esta situacion. Gracias
Nick: Pancitho
Pruebas :
![WoWScrnShot_042720_022426](https://user-images.githubusercontent.com/59895609/80346776-e630ff80-8830-11ea-911d-08c797f73d39.jpg)

**Comment by renzoypilco** [comment]
Alguien me puede ayudar? siguo en el mismo lugar y sin poder moverme

**Comment by athenaswow** [comment]
Ya se le informo a un Gm para que remueva el aura, Recuerda que no es lugar para hacer ese tipo de reclamos siempre que tengas un problema como este abre un ticket.
