### ISSUE TITLE
BUG DE GM

### ISSUE THREAD

**Issue by renzoypilco** [athenaswow/BugTracker-Athenas-WoW#339]
Nick: Pancitho
En el evento del 26-04-2020 me dejaon bug en la arena de gurubashi
Ahora ando esperando que alguien me podria ayudar voy mas de 1hr
![WoWScrnShot_042720_105751](https://user-images.githubusercontent.com/59895609/80396719-adb61380-887a-11ea-815e-da0c2aeb6b93.jpg)

**Comment by athenaswow** [comment]
Ya se le informo a un Gm para que remueva esa aura, Recuerda que este no es el lugar para hacer ese tipo de reclamo tienes que abrir un ticket.
