### ISSUE TITLE
Misión: No les hace falta (Pantano de las penas)

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#34]
Nombre de personaje principal: Skala
Usuario de discord: JorDaNN#5575
Descripción del error: Los ''giblins'' que mato deberían dar el item ''bolsita de bonvapor'' que pide la misión, pero no lo hace o el drop es tan bajo que después de 15min matándolos no salían.
Misión wowhead: https://es.wowhead.com/quest=27599/no-les-hace-falta
Athenaswow: https://www.youtube.com/watch?v=w6XZyLQ453E&feature=youtu.be
Como debería funcionar: https://www.youtube.com/watch?v=6ojjAyp5rxI

**Comment by athenaswow** [comment]
reporte invalido, estas haciendo mal la misión.
![image](https://user-images.githubusercontent.com/50283962/69967685-f2fe3100-14e6-11ea-8735-24c726cbb3cb.png)
 
![image](https://user-images.githubusercontent.com/50283962/69967693-f98ca880-14e6-11ea-91ba-af87cd215f05.png)

**Comment by athenaswow** [comment]
Reporte invalido, estas haciendo mal la mision.
https://www.youtube.com/watch?v=6ojjAyp5rxI

![image](https://user-images.githubusercontent.com/50283962/69967879-47091580-14e7-11ea-89e6-b172d1d990ad.png)

![image](https://user-images.githubusercontent.com/50283962/69967890-4c666000-14e7-11ea-9908-d5f3b7e128a8.png)

**Comment by Skala101** [comment]
Ciertamente
