### ISSUE TITLE
Loot y logro bugg en el calabozo "cámaras de piedra".

### ISSUE THREAD

**Issue by Felixeltoro** [athenaswow/BugTracker-Athenas-WoW#340]
Nick: se ve en las fotos
discord: FelixTheBull#6656
No se puede tocar el cofre con el mouse, no se que mas poner aca.
![WoWScrnShot_042820_031340](https://user-images.githubusercontent.com/63224422/80464093-e1d31800-88fe-11ea-8e2c-a99fd2467152.jpg)
No le tocaron ni un pelo de la barba al compadre y no me dio el logro, me siento estafado.
![WoWScrnShot_042820_031426](https://user-images.githubusercontent.com/63224422/80464095-e39cdb80-88fe-11ea-8ed4-0896fd3f1ab6.jpg)
![WoWScrnShot_042820_031433](https://user-images.githubusercontent.com/63224422/80464098-e4ce0880-88fe-11ea-9e06-5fac03f522f3.jpg)
![WoWScrnShot_042820_031436](https://user-images.githubusercontent.com/63224422/80464101-e5669f00-88fe-11ea-9e5f-f929a7e9b96c.jpg)

**Comment by athenaswow** [comment]
Ya fue reportado.
