### ISSUE TITLE
Misión "Lycanthoth el Corruptor" - Monte Hyjal

### ISSUE THREAD

**Issue by PachuCeni** [athenaswow/BugTracker-Athenas-WoW#341]
Personaje: Thurundiel

Discord: PachuCeni#4237

![WoWScrnShot_042820_161019](https://user-images.githubusercontent.com/64457215/80498185-b5a1b080-896b-11ea-9ed4-98fdff619fe8.jpg)

https://www.youtube.com/watch?v=C-UdETGa6Lg

Buenas. No aparece el NPC que debería entregar la misión.
Gracias por la atención.

**Comment by athenaswow** [comment]
Se agregara la primera parte de correcciones de hyjal en algunos días y esta misión esta funcionando 90% blizzlike esta pendiente agregar dicha corrección.
