### ISSUE TITLE
Problemas con los Portales

### ISSUE THREAD

**Issue by Daysia** [athenaswow/BugTracker-Athenas-WoW#342]

**Comment by Daysia** [comment]
Nick: Daysia
Discord: Feñardo#3104 
Existe un problema desde hace aproximadamente 1 semana en el cual mi personaje no es capaz de cruzar el portal oscuro, ni los portales the fireland, ni los de las cavernas del tiempo

**Comment by athenaswow** [comment]
Duplicado https://github.com/athenaswow/BugTracker-Athenas-WoW/issues/343
