### ISSUE TITLE
Problemas con Portales

### ISSUE THREAD

**Issue by Daysia** [athenaswow/BugTracker-Athenas-WoW#343]
Nick: Daysia
Discord: Feñardo#3104
Desde hace aproximadamente una semana mi personaje era incapaz de cruzar el portal oscuro, y el fin de semana descubri que tampoco podia cruzar el portal a the fireland y ninguno de las cavernas del tiempo
![WoWScrnShot_042820_002803](https://user-images.githubusercontent.com/15348412/80571183-896d4a80-89d2-11ea-95a1-beac4ab8638e.jpg)

**Comment by athenaswow** [comment]
Ne necesito mas información ya que esto no puedo reproducir el problema, posiblemente es uno de esos bufos que tienes.

**Comment by Daysia** [comment]
sigue ocurriendo lo intente cruzar sin equipo y botando todas las misiones pero no puedo cruzar portales, tampoco puedo entrar a the fireland.
![WoWScrnShot_050120_050959](https://user-images.githubusercontent.com/15348412/80790072-40e59680-8b64-11ea-8bae-62451d82f997.jpg)

**Comment by Daysia** [comment]
Esto es detras de el portal de la matanza de stratholme
![WoWScrnShot_050120_054245](https://user-images.githubusercontent.com/15348412/80791681-c4a18200-8b68-11ea-8cf6-eaedc98593cf.jpg)

**Comment by Daysia** [comment]
Sin equipo y sin buff y aun no puedo entrar
![WoWScrnShot_050220_054424](https://user-images.githubusercontent.com/15348412/80858838-7c4e9680-8c32-11ea-91a1-2102b4af1e85.jpg)
