### ISSUE TITLE
Mision bugg: La recogida de la caravana de Mor'shan

### ISSUE THREAD

**Issue by Felixeltoro** [athenaswow/BugTracker-Athenas-WoW#345]
Nombre: felixeltoro
Discord: FelixTheBull
No puedes interactuar con el npc de la misión.
![WoWScrnShot_050120_014944](https://user-images.githubusercontent.com/63224422/80789054-7da79280-8b50-11ea-929b-4fd6eca05c19.jpg)
Si consiguen arreglar eso ultimo por favor verificar si se completa correctamente, fui a la zona donde se supone tengo que entregarla y se ve bastante... Mal.
![WoWScrnShot_050120_020705](https://user-images.githubusercontent.com/63224422/80789087-9152f900-8b50-11ea-9786-b6b38d300c4f.jpg)

**Comment by athenaswow** [comment]
Corregido, la corrección se aplicara en unos días.
