### ISSUE TITLE
Personaje no ejecuta ninguna acción, al ingresar a bg da  wow error

### ISSUE THREAD

**Issue by khraaj** [athenaswow/BugTracker-Athenas-WoW#346]
Personaje : Trinitri
Discord: khraaj#6479

El personaje no ejecuta ninguna acción entre estas poderes, montura, bg, no puedo pedir bg y cuando me deja pedir bg. sale wow error. y no puedo conectarme con el personaje al mundo

**Comment by athenaswow** [comment]
Guía de uso:
Tener una cuenta en github:
Guía para crear una cuenta https://youtu.be/Nbjwet8wh7M
Encontrar un error dentro del juego
Al momento de subir el reporte debe de cumplir las reglas, caso contrario el reporte será cerrado y desechado.
Clic en "Issues":
https://ibb.co/yp7vXjd
Clic en New Issues:
https://ibb.co/FhGmc8f
Llenar los campos solicitados y clic en submit:
https://ibb.co/cyznVjP

**Comment by athenaswow** [comment]
Reglas para subir reportes:
Colocar en el reporte el nombre de su PJ principal.
Colocar en el reporte su usuario de discord (ej.: jugador#0123).
Agregar link de wowhead de el hechizo, item, logro para ser mas exactos.
Agregar una descripción del error comprensible para cualquier persona.
Agregar fotos y/o vídeos.
Agregar enlaces que validen el error (wowhead o https://cata-twinhead.twinstar.cz/)
Nota: https://cata-twinhead.twinstar.cz/ es una web que maneja las bases de datos de: Vanilla, TBC, Wotlk y Cataclysm.
