### ISSUE TITLE
Creación de hermandad buggeada

### ISSUE THREAD

**Issue by Xyliad** [athenaswow/BugTracker-Athenas-WoW#347]
Pj principal: Xyliad
usuario de discord: Ollax#6126

Descripción del problema: el estatutos de hermandad está buggeado, cada vez que intento crear una hermandad, hablo con el npc, elijo el nombre, pago los 10 silver, recivo el item, pero en mi inventario no tiene descripción y al hacerle click derecho para pedir la firma a alguien no hace nada (lo intenté con varios amigos estando en discord, otro de ellos intentó comprar él el estatutos y tuvo el mismo problema) 

![WoWScrnShot_050120_233045](https://user-images.githubusercontent.com/64672673/80853065-25ca6380-8c04-11ea-9589-72528df8d0f8.jpg)
![WoWScrnShot_050120_233101](https://user-images.githubusercontent.com/64672673/80853070-26fb9080-8c04-11ea-9566-ce63c182f67f.jpg)
![WoWScrnShot_050120_233152](https://user-images.githubusercontent.com/64672673/80853071-27942700-8c04-11ea-830a-59f12cf02896.jpg)
![WoWScrnShot_050120_233201](https://user-images.githubusercontent.com/64672673/80853073-295dea80-8c04-11ea-8a0e-d9d665f575f0.jpg)
![WoWScrnShot_050120_233253](https://user-images.githubusercontent.com/64672673/80853074-2a8f1780-8c04-11ea-9068-7fde6ed02a97.jpg)

**Comment by athenaswow** [comment]
Elaborar un nuevo reporte si el problema persiste.
