### ISSUE TITLE
Problemas con Portales

### ISSUE THREAD

**Issue by Daysia** [athenaswow/BugTracker-Athenas-WoW#348]
Nick: Daysia
Discord: Feñardo#3104

Hace ya mas de una semana que mi personaje un hunter lvl 85 no es capaz de cruzar portales, primero crei que solo era el portal oscuro, pero tampoco soy capaz de entrar a the fireland, ni a las mazmorras de la caverna del tiempo, anteriormente pantlie en tema y me dijeron que debia ser por un buff pero estando sin buff, sin equipo y sin misiones tampoco puedo cruzar, creyendo que seria un problema producido por haber descargado el cliente minimal, descargue y reinstale el juego completo, pero no funciono, tambien le pedi a un amigo que logeara mi pj e intentara cruzar, pensando que quizas seria algo especifico de mi wow, pero este tampoco es capaz de atravesar portales con este pj. Adjunto varias fotos de diferentes dias intentando cruzar, me gustaria que me pudieran ofrecer alguna solucion o algo ya que se vuelve frustrante no poder hacer las mazmorras que en teoria deberia poder, ni poder participar en bandas.
![WoWScrnShot_042820_002803](https://user-images.githubusercontent.com/15348412/80858960-a2c10180-8c33-11ea-979a-0a5113688367.jpg)
![WoWScrnShot_050120_050959](https://user-images.githubusercontent.com/15348412/80858962-a5235b80-8c33-11ea-92f2-28a0fc18beec.jpg)
![WoWScrnShot_050220_054424](https://user-images.githubusercontent.com/15348412/80858964-a81e4c00-8c33-11ea-9b22-1107ecef9f3a.jpg)
![WoWScrnShot_050120_054245](https://user-images.githubusercontent.com/15348412/80858966-ab193c80-8c33-11ea-8fb6-132a76a88263.jpg)

**Comment by Warkiria** [comment]
Hola,
A mi me ha pasado eso, y si es un problema de un aura, lo que pasa es que es un aura invisible, es decir que tú no la puedes ver y tampoco te la puedes quitar. debes hacer un ticket y estar on con el pj que tienes el inconveniente.

**Comment by Daysia** [comment]
Hola gracias por ayudar, como se hace el ticket? para enviarlo
