### ISSUE TITLE
Monedero de Campeón

### ISSUE THREAD

**Issue by jeiduart** [athenaswow/BugTracker-Athenas-WoW#349]
Jugador : Tainys
Discord: Tainys#8409

El Monedero de Campeón https://es.wowhead.com/item=45724/monedero-de-campe%C3%B3n#comments deberia de dar siempre que lo abrimos oro y un sello de campeón, el oro lo da el sello por mas bolsas que abras no lo da.

**Comment by athenaswow** [comment]
Corregido, el cambio se implementara en unos días
Probabilidad 90%

**Comment by jeiduart** [comment]
buenas disculpen hace poco incorporaron esas monedas a las bolsas el problema es que las anda dando como objeto y no como moneda y así no sirven para nada
