### ISSUE TITLE
Misión: Cuestión de lealtad (Laderas de trabalomas)

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#35]
Nombre de personaje principal: Skala
Usuario de discord: JorDaNN#5575
Descripción del error: Después de hablar con el npc, tendría que salir Drak'tar en una cinemática y escuchar lo que dice, luego de eso se completaría pero no es así.
Misión wowhead https://es.wowhead.com/quest=28600/cuesti%C3%B3n-de-lealtad
Athenaswow: https://www.youtube.com/watch?v=M-NQjqj49Vc&feature=youtu.be
Como debería funcionar: https://www.youtube.com/watch?v=Wl8BnLXwNHI&feature=youtu.be

**Comment by pangolp** [comment]
La verdad es que hay poca información, nada mas la que se ve en el vídeo. Puede encontrar un spell, el cual sirve para summonear al captain que creo que es el que empuja la silla. Pero por el momento solo eso. 

-- Spell 34371 - [Despawn Drek'Thar, rank 1]
-- **Spell 91332 - [Summon Drek'thar/Crew, rank 1]**
-- Spell 91360 - [Summon Drek'Thar/Crew, rank 1]

![captainGalvangar](https://user-images.githubusercontent.com/2810187/72677172-5ed93080-3a78-11ea-93a3-c1df064888a5.png)

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
