### ISSUE TITLE
Bolsa de especias pequeña

### ISSUE THREAD

**Issue by jeiduart** [athenaswow/BugTracker-Athenas-WoW#350]
Jugador : Tainys
Discord: Tainys#8409

La Bolsa de especias pequeña https://db.wowlatinoamerica.com/?item=44113#contains deberia de dar https://db.wowlatinoamerica.com/?item=44113#contains pero no los da. esto hace que sea mas difícil conseguir todas las recetas y el gorro de cocina de dalaran

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.

**Comment by jeiduart** [comment]
buenas disculpen hace poco incorporaron esas monedas a las bolsas el problema es que las anda dando como objeto y no como moneda y así no sirven para nada
