### ISSUE TITLE
Error #134 (0x85100086) fatal condition!

### ISSUE THREAD

**Issue by khraaj** [athenaswow/BugTracker-Athenas-WoW#353]
Trinitri
khraaj#6479

Se me presenta el error #134 (0X85100086) fatal condition! al ingresar el mundo solo con este personaje, cuando no se genera al entrar al mundo se genera al entrar a un campo de batalla (bg).
![ERROR WOW # 134](https://user-images.githubusercontent.com/64661484/81009756-d5791e80-8e1a-11ea-976b-96aa2549ddfe.jpeg)
![image](https://user-images.githubusercontent.com/64661484/81009823-f3df1a00-8e1a-11ea-85b6-f83ebc999d93.png)

Este error solo me sucede con este personaje.
Agradezco su atención

**Comment by athenaswow** [comment]
Usa la opción de desbloquear personaje en la pagina, de esa manera solucionas el problema mas sin engarbo se necesitan mas pruebas para ver que ocasiona el error.

**Comment by DjrrSk** [comment]
No se necesitan pruebas, el error lo dice claramente, tienes el archivo World.mpq dañado
