### ISSUE TITLE
mision apagar el fuego

### ISSUE THREAD

**Issue by Dermin33** [athenaswow/BugTracker-Athenas-WoW#354]
nombre del personaje:Jeyto
mision Bug:apagar el fuego
Furibundo de lava tiene un plombema de nivel 22 pero es difirse de 
derrotalos no es benificioson tiempo y ganacia

**Comment by athenaswow** [comment]
Reglas para subir reportes:
Colocar en el reporte el nombre de su PJ principal.
Colocar en el reporte su usuario de discord (ej.: jugador#0123).
Agregar link de wowhead de el hechizo, item, logro para ser mas exactos.
Agregar una descripción del error comprensible para cualquier persona.
Agregar fotos y/o vídeos.
Agregar enlaces que validen el error (wowhead o https://cata-twinhead.twinstar.cz/)
Nota: https://cata-twinhead.twinstar.cz/ es una web que maneja las bases de datos de: Vanilla, TBC, Wotlk y Cataclysm.
