### ISSUE TITLE
Mision bug "El Milagro de Aessina"

### ISSUE THREAD

**Issue by goddyear8** [athenaswow/BugTracker-Athenas-WoW#355]
Personaje que reporta: Teds
Nombre en discord: Darkamis#6706
La mision deberia funcionar asi es simplemente entregarla aqui el ejemplo: https://www.youtube.com/watch?v=uScIX8KPaTw

Y asi es como esta 
![image](https://user-images.githubusercontent.com/64874628/81126814-17c95b00-8f02-11ea-8ee2-50d62c6eb8a9.png)

Muchas gracias

**Comment by athenaswow** [comment]
la misión se entrega en https://wow-es.gamepedia.com/Santuario_de_Malorne
