### ISSUE TITLE
Misiones de drop (Montañas filospada)

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#36]
Nombre de personaje principal: Skala
Usuario de discord: JorDaNN#5575
Descripción de la situación: Estas 2 misiones caen de los mobs, lo que pasa en este caso es que antes de sacar estos items que te dan la misión haces una misión previa que te envía a matar estos adds, durante esta corta misión los items tienen un alto porcentaje de caída. Sin embargo, si las completas los items ya no tienen tanta probabilidad de caída. Realmente no se si me estoy equivocando, pero he estado 1h farmeando el orbe ,que es lo que recomendaba los comentarios de wowhead pero nada.
Quisiera que revisarán el loot ya que en wowhead sin la misión previa el loot  de una es del 10% y la otra del 6%. Tal vez si les parece bien modificar el loot de estos items que dan misión.
 Es necesario tener estas 2 misiones para desbloquear otra cadena  para el logro de misiones de este lugar. También para poder desbloquear la cadena de misiones diarias de la reputación Ogri-la. 
Misión1 : https://www.wowhead.com/quest=10825/the-truth-unorbed
Item necesario: https://www.wowhead.com/item=31489/orb-of-the-grishna
Misión 2: https://www.wowhead.com/quest=10719/did-you-get-the-note
Item necesario: https://www.wowhead.com/item=31120/meeting-note
Si podeis verificar los comentarios de wowhead pues se quejan del poco drop de estos items al no tener la misión previa

**Comment by athenaswow** [comment]
corregido.
https://www.wowhead.com/item=31120/meeting-note  se aumento el drop a un  100% 
https://www.wowhead.com/item=31489/orb-of-the-grishna  se aumento el drop a un 15%
