### ISSUE TITLE
Bug Nivel de Pesca (no para de subir)

### ISSUE THREAD

**Issue by ghost** [athenaswow/BugTracker-Athenas-WoW#363]
**Pj principal**: Chuckpalal
**Usuario Discord:** Chuckpalal#5890

**Descripción del problema:** 
he estado haciendo las diarias de pesca de Dalaran, Shatrath y las ciudades capitales farmenando un sombrero de pesca que cae en la bolsa que tiran estas misiones, bien estas misiones son útiles cuando estas subiendo de nivel la profesión la misión te da un punto de esta habilidad; bien yo tengo la profesión full pero al entregar la misión aun seguía aumentando el nivel, hasta hoy me percate que con todas las misiones que llevo haciendo hace semanas tengo la profesión a nivel 738

**Pruebas:**
https://imgur.com/a/qHf5I8n
https://imgur.com/a/HlOhDCP

**Comment by athenaswow** [comment]
Ya reportado.
