### ISSUE TITLE
bug misiones hyjal para sacar reputacion

### ISSUE THREAD

**Issue by claupao** [athenaswow/BugTracker-Athenas-WoW#365]
estas dos misiones anda bugg y nose como lograr hacerlas pa sacar reputacion y sacar la pet exoticas anka y magria ya q ando dos semanas esperando casi todo el dia y nunca estan supongo q es porque no completo las misiones de tierras de fuego? las misiones son para seguir la cadena el señor del fuego y un ritual de llamas

**Comment by athenaswow** [comment]
Reglas para subir reportes:
Colocar en el reporte el nombre de su PJ principal.
Colocar en el reporte su usuario de discord (ej.: jugador#0123).
Agregar link de wowhead de el hechizo, item, logro para ser mas exactos.
Agregar una descripción del error comprensible para cualquier persona.
Agregar fotos y/o vídeos.
Agregar enlaces que validen el error (wowhead o https://cata-twinhead.twinstar.cz/)
Nota: https://cata-twinhead.twinstar.cz/ es una web que maneja las bases de datos de: Vanilla, TBC, Wotlk y Cataclysm.

Si no juntas parte de las pruebas no tengo por donde empezar
