### ISSUE TITLE
Misión 'Banquete o Hambruna'

### ISSUE THREAD

**Issue by Estebanbdiaz** [athenaswow/BugTracker-Athenas-WoW#37]
Pj principal Coralaine
Düs#7582

Descripción.

'Recoge 6 colas de coyote y 5 puñados de tierra fresca ---- el issue de la misión está en las tierra fresca que jamás hacen spawn y no se dejan coger, he intentado mirar en cada una de las que están en la zona de las calabazas y jamás se encuentran.

ZONA -  páramos del poniente - plantación de calabazas de cejade.

link - https://es.wowhead.com/quest=26230/banquete-o-hambruna
vídeo - https://www.youtube.com/watch?v=rHnrznJvDrw (con la misión correcta)
![WoWScrnShot_120619_011546](https://user-images.githubusercontent.com/58576052/70284936-19adb780-17c6-11ea-89d5-65aee30fa7dc.jpg)

**Comment by athenaswow** [comment]
corregido.
