### ISSUE TITLE
Receta: Gafas Trastormenta

### ISSUE THREAD

**Issue by Fernando5464** [athenaswow/BugTracker-Athenas-WoW#370]
Alleriah
Hikaru#3470

La receta Gafas Trastormenta no se puede aprender en ningún instructor que lo debería enseñar según Wow Head, según la página antes citada los requisitos para poder aprender esta receta son ser chamán o cazador en cualquiera de sus especializaciones y tener nivel de 350 en ingeniería, cosa que mi PJ Alleriah cumple.

Id de la receta en wow Head: https://es.wowhead.com/item=32476/gafas-trastormenta#taught-by-npc

Adjunto foto que tomé a uno de los instructores que lo debería enseñar, pasé por todos los que lo enseñan.

![WoWScrnShot_051520_152355](https://user-images.githubusercontent.com/16832093/82093117-206b1f80-96c0-11ea-87b2-549fbcee8516.jpg)

**Comment by athenaswow** [comment]
De momento esta disponible en estos Npcs
https://es.wowhead.com/npc=28697/timofey-oshenko
https://es.wowhead.com/npc=26991/sock-rayoluz
https://es.wowhead.com/npc=26955/jamesina-acuosa
https://es.wowhead.com/npc=25277/ingeniero-jefe-leveny
https://es.wowhead.com/npc=26907/tisha-puentelargo
https://es.wowhead.com/npc=33586/binkie-brillaengranaje
https://es.classic.wowhead.com/npc=5518/lilliam-chispeje
https://es.classic.wowhead.com/npc=11017/roxxik

**Comment by Fernando5464** [comment]
Buenas tardes señor GM, le informo que la receta aún no se puede aprender, he ido a todos los instructores de la lista que son amistosos o neutrales con la Horda, pero ninguno me enseña la receta, como lo demuestro con las siguientes imágenes:

https://imgur.com/5mrkD5X
https://imgur.com/NW0yAXD
https://imgur.com/xiEEyPS
https://imgur.com/xwVyRvU
https://imgur.com/gjqQZXf

Hace un par de días vi un chamán que si tenía ese objeto transfigurado, le pregunté y me dijo que si le dejó aprender la receta de manera normal, pero que tuvo problemas con otro de sus chamanes, a lo que voy es que parece ser que sólo deja aprender a ciertos PJs, yo como cazador entro en la clasificación de clase que puede aprender esa receta.
