### ISSUE TITLE
Bug misión "El milagro de aessina"

### ISSUE THREAD

**Issue by comandocero100** [athenaswow/BugTracker-Athenas-WoW#373]
PJ: Comandocero
Huargen
Discord: comandocero#9926
La siguiente misión de una cadena de misiones aparece bug ya que esta es tomada por Nordu https://imgur.com/O7PFWbt el cual es llevar un objeto y entregarlo al Archidruida Hamuul pero este no deja completar la misión https://imgur.com/mht8RR5

Esta es la misión:
https://cata-twinhead.twinstar.cz/?quest=25372#comments

**Comment by athenaswow** [comment]
Se debe entregar en https://es.wowhead.com/npc=39858/archidruida-hamuul-t%C3%B3tem-de-runa

![image](https://user-images.githubusercontent.com/50283962/82353776-7cd28580-99c5-11ea-94d3-ed9f4bc4d15b.png)
