### ISSUE TITLE
Error reputación con Ala Abisal.

### ISSUE THREAD

**Issue by vilgerdarson** [athenaswow/BugTracker-Athenas-WoW#377]
PERSONAJE PRINCIPAL: Vilgerdarson
DISCORD: vilgerdarson#6678
DESCRIPCIÓN DEL PROBLEMA: al completar la cadena de misiones  para iniciar a subir reputación con Ala Abisal automáticamente la reputación dicha termina exaltada lo cual hace que no tengamos que hacer misiones diarias para subir la reputación y la compra de la montura del Draco Abisal  sea inmediata.
https://es.wowhead.com/item=32858/riendas-del-draco-ala-abisal-azur#comments
Lo correcto seria completar la cadena de misiones hasta https://es.wowhead.com/quest=11013/al-servicio-de-los-illidari#comments   y en ese momento iniciar las diarias para subir reputación. 
Adjunto imagenes del momento de logro con reputación:
https://imgur.com/a/MRxBqFW

**Comment by athenaswow** [comment]
Para poder resolver el problema debes elaborar un mejor reporte del el punto en donde pierdes la cadena de misiones.
