### ISSUE TITLE
Misiones: Soltar la trampa y los esclavos del señor del fuego (chaman) 

### ISSUE THREAD

**Issue by Lamela-La-Buscadora** [athenaswow/BugTracker-Athenas-WoW#379]
1- Misión: https://es.wowhead.com/quest=11969/soltar-la-trampa
Simplemente aparece el anuncio de no tener un objetivo, no sucede nada, no se permite el uso del objeto de misión... 
> https://www.youtube.com/watch?v=zTi8G3zlGHU 
https://imgur.com/vsYP3u1
https://imgur.com/U8aWcW1

2- Misión https://es.wowhead.com/quest=28465/los-esclavos-del-se%C3%B1or-del-fuego
Bueno aquí el objeto de misión si se puede utilizar, algunas veces invoca un imp y en otras invoca alguna cosa que no se puede targetear (solo aparece el nombre de la invocación). El caso es que no libera a los elementales al usar tal objeto otorgado por la misión.
> La misión es tan sencilla que nadie ha mostrado evidencia de como debería funcionar.
https://imgur.com/TM7mOc6
https://imgur.com/BuKj4ax
https://imgur.com/2wZmfvu

**Comment by athenaswow** [comment]
Corregido  https://es.wowhead.com/quest=11969/soltar-la-trampa
