### ISSUE TITLE
Misión Diaria: Comandante de tonque (Feria de la luna negra)

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#38]
Nombre de personaje principal: Skala
Usuario de discord: JorDaNN#5575
Descripción del error: Los ''blancos'' a los que hay que darle para que cuente la diaria, están detrás del cartel y pues no deja completarla por este mismo motivo. Es bastante molesto ya que son pocos días los que se queda la feria y es por lo mismo escaso sacar las recompensas de esta. Los blancos se restablecen en una posición aleatoria después que se les pega pero al parecer todos se restablecieron en una zona imposible de golpear con el tonque.
Misión diaria: https://es.wowhead.com/quest=29434/comandante-de-tonque#english-comments
Athenaswow: https://www.youtube.com/watch?v=fnmIgFnyWbM&feature=youtu.be

**Comment by Skala101** [comment]
Esto ya se ha restablecido aunque no se si sea por magia o alguna acción vuestra :P  
![image](https://user-images.githubusercontent.com/58092128/70311738-3bb43380-17e0-11ea-9c37-ae03166837ad.png)

**Comment by athenaswow** [comment]
Falta mas pruebas para saber el momento en el que  falla.
