### ISSUE TITLE
Bug en Maestra de Hipogrifos en Feralas (Alianza)

### ISSUE THREAD

**Issue by SKLucifer** [athenaswow/BugTracker-Athenas-WoW#381]
Login de Cuenta: **SKLucifer**
Nombre de mi Personaje Alianza: **SKLucifer**
ID Discord: Aun sin cuenta en la misma

Bug en Maestra de Hipogrifos: **Seyala Mechón Nocturno**

En la región de **Feralas** (https://es.wowhead.com/feralas) de parte de **La Alianza**, la **Maestra de Hipogrifos**: **Seyala Mechón Nocturno** (https://es.wowhead.com/npc=40367/seyala-mech%C3%B3n-nocturno) no habilita la función de traslado entre puntos y me arroja el mensaje: **"No conoces ningún otro lugar de vuelo relacionado con este"**, cuando ya de por si, he descubierto casi todos los puntos de traslado con respecto al Continente de **Kalimdor**.

Dejo como prueba el video que hice con mi personaje y el bug planteado: https://youtu.be/qiev3fUk88E

Sin mas que comentar y reportar, y agradeciendo la atención, me despido.

**Comment by athenaswow** [comment]
No puedo ver el vídeo :)

**Comment by SKLucifer** [comment]
el link te lanza directamente al video posteado en youtube!!!, ademas acabo de revisar la configuracion y esta como para verlo en tu sala de cine, solo te faltan las cotufas!!! ^_^

**Comment by SKLucifer** [comment]
Ahora si esta visible!!! y disculpen las molestias causadas
