### ISSUE TITLE
Npc en zona incorrecta (Rhea)

### ISSUE THREAD

**Issue by LABLANCA** [athenaswow/BugTracker-Athenas-WoW#382]
Nombre de pj principal: lablanca
Nombre usuario Discord: JAVIER # 2355

el NPC Rhea que según wow head  deberia estar en 4 zonas solo esta en dos de las zonas marcadas, 
https://es.wowhead.com/npc=46654/rhea 
reporto esto ya que  el npc no esta donde marca el juego que se debe entregar la siguiente misión 
https://es.wowhead.com/quest=27770/levantando-el-velo , así que aunque el npc este el el juego en una locación diferente para los jugadores va a resultar confuso que el npc no este donde marca el juego que se debe entregar la misión
![Desktop Screenshot 2020 05 18 - 15 45 04 87](https://user-images.githubusercontent.com/63380249/82258117-e055a800-991e-11ea-8acc-823b3e7dd6b5.png)
![Desktop Screenshot 2020 05 18 - 15 28 34 14](https://user-images.githubusercontent.com/63380249/82258158-efd4f100-991e-11ea-9cc5-7708aecdb9a8.png)

**Comment by athenaswow** [comment]
No se encontró el problema.
