### ISSUE TITLE
Bug, misión: El Señor del Fuego

### ISSUE THREAD

**Issue by LABLANCA** [athenaswow/BugTracker-Athenas-WoW#386]
Nombre de pj principal: lablanca
Nombre usuario Discord: JAVIER # 2355
MISION: https://es.wowhead.com/quest=25551/el-se%C3%B1or-del-fuego
la mision la primera vez que se agarra funciona bien el problema viene cuando por alguna razon mueres y ni abandonando y agarrando la mision de nuevo el npc no da la opcion de activar la mecanica para invocar a ragnaros denuevo y tampoco aparece en la parte de abajo, tambien vi que es un fallo robarle el agro al npc que nos acompaña por que si robamos agro irremediablemente vamos a morir 
![Desktop Screenshot 2020 05 19 - 13 29 25 93](https://user-images.githubusercontent.com/63380249/82365237-038f5e80-99d6-11ea-9250-e9cddc39f4cd.png)
  
VIDEO DE COMO DEBERIA FUNCIONAR LA MISION 
https://www.youtube.com/watch?v=Nc_OKZr_H_8

Criterio para determinar si la mision esta bug o defectuosa y luego reportar 
1 he leido con atencion lo que dice la mision
2 compruebo las mecanicas
3 abandono y agarro denuevo la mision
4 verifico como funciona en el oficial
5 si despues de todo esto la mision no se puede completar de ninguna manera genero el reporte

**Comment by athenaswow** [comment]
Aun falta el 50% de la mecánica de la misión por eso pasan esas cosas, tratare de solucionarlo lo mas pronto posible.

**Comment by Actiontome** [comment]
Muy buenas, a fecha de hoy yo estoy teniendo también un problema con esta misión, a la mitad de la batalla contra Ragnaros, desaparece y no se puede hacer absolutamente nada más, espero que ya pronto se pueda arreglar este fallo. Agradecer de paso a los desarrolladores por el gran trabajo que están haciendo por mantener el servidor lo mejor posible.

**Comment by athenaswow** [comment]
Ya fue corregido.
