### ISSUE TITLE
Bug, misión: Los obreros Rompelanzas

### ISSUE THREAD

**Issue by LABLANCA** [athenaswow/BugTracker-Athenas-WoW#387]
Nombre de pj principal: lablanca
Nombre usuario Discord: JAVIER # 2355
Mision: https://es.wowhead.com/quest=13504/los-obreros-rompelanzas

el error de la mision consta en que la mayoria de objetivos no se dejan golpear  solo hay unos pocos a lo que se les puede golpear para que cuente la mision , aparte de con solo darles target  dejan al jugador en combate de por vida 

![Desktop Screenshot 2020 05 19 - 16 28 55 28](https://user-images.githubusercontent.com/63380249/82381203-64776080-99ef-11ea-8bea-fabef43e2f00.png)
![Desktop Screenshot 2020 05 19 - 16 28 03 50](https://user-images.githubusercontent.com/63380249/82381253-79ec8a80-99ef-11ea-9918-28c3ec400a74.png)

VIDEO DE COMO DEBERIA FUNCIONAR LA MISION
https://www.youtube.com/watch?v=sojCz6jGBRA

Criterio para determinar si la mision esta bug o defectuosa y luego reportar 
1 he leido con atencion lo que dice la mision
2 compruebo las mecanicas
3 abandono y agarro denuevo la mision
4 verifico como funciona en el oficial
5 si despues de todo esto la mision no se puede completar de ninguna manera genero el reporte

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
