### ISSUE TITLE
Misión "Los osos de ahí arriba"

### ISSUE THREAD

**Issue by ViejasLocasxd** [athenaswow/BugTracker-Athenas-WoW#389]
Anfetaminaa
J 🤙#8054
La misión data de subirnos a los árboles mediante unas escaleras, mas no se puede. Las escaleras están allí pero solo se pueden seleccionar, mas no usar. Lo otro es que hay varios osos en el suelo pero ninguno funciona, solo uno que aparece cada 3 o 4 minutos. Piden 6 y con este error o problema se hace tedioso el completar la misión. Es en Hyjal.

https://imgur.com/P0iovj4
https://imgur.com/4vRilNd
https://imgur.com/6Fb0bJv

**Comment by athenaswow** [comment]
la misión aun no funciona correctamente, necesita mas trabajo así que hay que tener paciencia.
