### ISSUE TITLE
Misión: El ultra-desconsolidador es muy útil (Tormenta abisal)

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#39]
Nombre de personaje principal: Skala
Usuario de discord: JorDaNN#5575
Descripción del error: Pues como se ve en el vídeo, no cuentan los objetos para la misión y se les puede clickear pero aún así no cuentan ni dándole directamente con el objeto que te dan.
Misión wowhead: https://es.wowhead.com/quest=10203/el-ultra-desconsolidador-es-muy-%C3%BAtil#storyline
Athenaswow: https://www.youtube.com/watch?v=BQf2jc-j01M&feature=youtu.be
Como debería funcionar: https://www.youtube.com/watch?v=u6cS3XM9yOM&feature=youtu.be

**Comment by athenaswow** [comment]
corregido.
