### ISSUE TITLE
Bug, misión: El señor de la guerra Escama Oscura

### ISSUE THREAD

**Issue by LABLANCA** [athenaswow/BugTracker-Athenas-WoW#390]
Nombre de pj principal: lablanca
Nombre usuario Discord: JAVIER # 2355
Mision: https://es.wowhead.com/quest=13899/el-se%C3%B1or-de-la-guerra-escama-oscura
el npc al que se le tiene que entregar la mision aparece muerto siempre  y aun asi ataca se supone que es obligatorio matarlo para que de un dialogo y despues entregar la mision , pero despues de matarlo simplemente desaparece y no deja entregar la mision
![Desktop Screenshot 2020 05 19 - 17 58 45 70](https://user-images.githubusercontent.com/63380249/82387010-7d860e80-99fb-11ea-8499-a547c3f87e32.png)

![Desktop Screenshot 2020 05 19 - 17 59 13 03](https://user-images.githubusercontent.com/63380249/82386881-3566ec00-99fb-11ea-8d58-ee77af4bfc1c.png)

VIDEO DE COMO DEBERIA FUNCIONAR 
https://www.youtube.com/watch?v=_oyiweq_InQ

Criterio para determinar si la mision esta bug o defectuosa y luego reportar 
1 he leido con atencion lo que dice la mision
2 compruebo las mecanicas
3 abandono y agarro denuevo la mision
4 verifico como funciona en el oficial
5 si despues de todo esto la mision no se puede completar de ninguna manera genero el reporte

**Comment by athenaswow** [comment]
Ya fue reportado.
