### ISSUE TITLE
Bug, misión:Agentes de destrucción

### ISSUE THREAD

**Issue by LABLANCA** [athenaswow/BugTracker-Athenas-WoW#392]
Nombre de pj principal: lablanca
Nombre usuario Discord: JAVIER # 2355
Mision:  https://es.wowhead.com/quest=9518/agentes-de-destrucci%C3%B3n
la mision en si tiene dos objetivos 
1 matar a 12 guardias de la horda 
2 matar a Sobrestante Gorthak 
lo que sucede es que donde debe estar Sobrestante Gorthak  aparece un guardia y no importa cuantas veces limpie no aparece,  y hay un cuerpo en el piso que no desaparece y parece ser el de Sobrestante Gorthak  lo cual indica que el mob no esta spawneando 
LAS DOS ULTIMAS CAPTURAS MUESTRAN DOS TIEMPOS DIFERENTES EN EL RELOJ PARA DEMOSTRAR QUE EL MOB NO DESAPARECE NI SPAWNEA
![Desktop Screenshot 2020 05 20 - 12 33 28 11](https://user-images.githubusercontent.com/63380249/82478853-25044f00-9a97-11ea-9c9b-0b6e7f8ccb9d.png)
![Desktop Screenshot 2020 05 20 - 12 34 41 67](https://user-images.githubusercontent.com/63380249/82478867-2766a900-9a97-11ea-9e26-96a0ccc34347.png)
![Desktop Screenshot 2020 05 20 - 12 43 02 69](https://user-images.githubusercontent.com/63380249/82479161-9d6b1000-9a97-11ea-8ccd-1623a5ee2140.png)

VIDEO DE COMO DEBERIA FUNCIONAR 
https://www.youtube.com/watch?v=H46m2C5P1D4&t=189s
Criterio para determinar si la mision esta bug o defectuosa y luego reportar 
1 he leido con atencion lo que dice la mision
2 compruebo las mecanicas
3 abandono y agarro denuevo la mision
4 verifico como funciona en el oficial
5 si despues de todo esto la mision no se puede completar de ninguna manera genero el reporte

**Comment by athenaswow** [comment]
La misión fue deshabilitada.
