### ISSUE TITLE
Bug, misión: En aprietos

### ISSUE THREAD

**Issue by LABLANCA** [athenaswow/BugTracker-Athenas-WoW#393]
Nombre de pj principal: lablanca
Nombre usuario Discord: JAVIER # 2355
Mision: https://es.wowhead.com/quest=13982/en-aprietos
el mob Kaliva  no se activa por ende no se puede completar la mision 

(ACTUALIZANCION DE LA MISION) 
el mob si esta pero un poco lejos de la ubicacion de donde debe aparecer,
así que no quita el hehco de que la mision no funciona como deberia

![Desktop Screenshot 2020 05 20 - 12 59 32 57](https://user-images.githubusercontent.com/63380249/82480852-0c496880-9a9a-11ea-83fb-89d6cee1e008.png)

VIDEO DE COMO DEBERIA FUNCIONAR 
https://www.youtube.com/watch?v=mBuuSP8GQ60
Criterio para determinar si la mision esta bug o defectuosa y luego reportar 
1 he leido con atencion lo que dice la mision
2 compruebo las mecanicas
3 abandono y agarro denuevo la mision
4 verifico como funciona en el oficial
5 si despues de todo esto la mision no se puede completar de ninguna manera genero el reporte

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
