### ISSUE TITLE
Bug, misión: El jefe Tótem Siniestro, Grundig Nube Negra

### ISSUE THREAD

**Issue by LABLANCA** [athenaswow/BugTracker-Athenas-WoW#394]
Nombre de pj principal: lablanca
Nombre usuario Discord: JAVIER # 2355
Mision: https://es.wowhead.com/quest=25846/el-jefe-t%C3%B3tem-siniestro-grundig-nube-negra
 el npc Grundig Nube Oscura al cual hay que entregar la misión anterior nombrada aparece hostil ,
busque en el foro de el oficial y al parecer algunos también tuvieron ese problema , algunos jugadores resolvieron esto dejando la mision y agarrandola denuevo, relogeando . saliendo hasta otra zona y luego regresando, pero aqui nada de eso funciona por ende no se puede entregar la mision y no se puede completar la cadena
![Desktop Screenshot 2020 05 20 - 15 57 18 54](https://user-images.githubusercontent.com/63380249/82497721-5b03fc00-9ab4-11ea-8290-4162eb0af100.png)

![Desktop Screenshot 2020 05 20 - 15 53 32 61](https://user-images.githubusercontent.com/63380249/82497767-73741680-9ab4-11ea-8966-b2a31f57d2b1.png)
![Desktop Screenshot 2020 05 20 - 15 55 52 55](https://user-images.githubusercontent.com/63380249/82497824-8a1a6d80-9ab4-11ea-805e-d05ae02e9dc7.png)

VIDEO DE COMO DEBERIA FUNCIONAR 
https://www.youtube.com/watch?v=IfQ3acih_QE
Criterio para determinar si la mision esta bug o defectuosa y luego reportar 
1 he leido con atencion lo que dice la mision
2 compruebo las mecanicas
3 abandono y agarro denuevo la mision
4 verifico como funciona en el oficial
5 si despues de todo esto la mision no se puede completar de ninguna manera genero el reporte

**Comment by athenaswow** [comment]
Corregido.
