### ISSUE TITLE
Misión "El Milagro de Aessina", anda bug

### ISSUE THREAD

**Issue by ViejasLocasxd** [athenaswow/BugTracker-Athenas-WoW#395]
Anfetaminaa
 J 🤙#8054
Hola, tengo que entregar un objeto llamado "Corazón del bosque", pero no me deja hacerlo. En la siguiente prueba "https://www.youtube.com/watch?v=uScIX8KPaTw", le permite entregar, mas a mi me sale que puedo lanzar un hechizo creo, sobre el npc que recibe el objeto. 
https://imgur.com/qEIaGjn

**Comment by athenaswow** [comment]
![image](https://user-images.githubusercontent.com/50283962/82834761-abe66c80-9e87-11ea-99ac-8b739f5568d5.png)
la entregas hay.
