### ISSUE TITLE
Misión: Flora de los ecodomos (Tormenta abisal)

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#40]
Nombre de personaje principal: Skala 
Usuario de discord: JorDaNN#5575 
Descripción del error: El ítem no lo marca como objetivo por lo que no se puede usar bien el ítem para la misión, lo cual hace que no se transformen las plantas y las que ya andan transformadas como se ve en el vídeo no cuentan para la misión.
Misión wowhead: https://es.wowhead.com/quest=10426/flora-de-los-ecodomos
Athenaswow: https://www.youtube.com/watch?v=2Rzlm9LgbMk&feature=youtu.be
Como debería funcionar: https://www.youtube.com/watch?v=uvOj0rtQbEE

**Comment by athenaswow** [comment]
corregido.
