### ISSUE TITLE
Mision Quel Delar, "La purificacion de Quel Delar"

### ISSUE THREAD

**Issue by jeiduart** [athenaswow/BugTracker-Athenas-WoW#400]
Jugador : Tainys
Discord: Tainys#8409

Buenas la misión La purificación de Quel Delar esta bug. La misión es simple debemos entrar a la banda hablando con los https://es.wowhead.com/npc=37523/celador-de-la-fuente-del-sol, luego nos dirigimos abajo y hablamos con https://es.wowhead.com/npc=38056/ayudante-de-c%C3%A1mara-galiros, al hablar con el se iniciara una conversación con los npc de la habitación, al final de la conversacion aparecera la espada como contenedor y simplemente debemos agarrarla. EL bug es que no se puede interactuar con el contenedor.https://es.wowhead.com/object=201794/queldelar

**Comment by athenaswow** [comment]
Ya fue reportado.
