### ISSUE TITLE
Frente de magma Profesion

### ISSUE THREAD

**Issue by Vacaslocas1892** [athenaswow/BugTracker-Athenas-WoW#401]
Hola, Soy 

- Vacaslocas#5190

- Pj: Vacaslocas (Druida) Profesion Peleteria 

Neceisto completar unas misiones que me llevan a frente de magma, para poder comprar unas recetas que las necesito urgentemente por favor. 

- Quede en estas 2 misiones siguientes en los links:

https://es.wowhead.com/quest=29197/desprevenidos
https://es.wowhead.com/quest=29452/ha-llegado-tu-hora#see-also

- Items necesarios por comprar son:

http://es.wowhead.com/item=70174
http://es.wowhead.com/item=70175

- NPC (Requerido para la compra):

https://es.wowhead.com/npc=53881/ayla-ventiscaumbr%C3%ADa

**Comment by athenaswow** [comment]
Se esta trabajando desde cero en la cadena de misiones que te llevan a ese lugar por lo tanto tardaremos un poco en solucionar esos errores.

**Comment by Vacaslocas1892** [comment]
podrian facilitarnos por el momento la compra de dicha receta?
Gracias
