### ISSUE TITLE
Bug, misión:Juntos de nuevo

### ISSUE THREAD

**Issue by LABLANCA** [athenaswow/BugTracker-Athenas-WoW#403]
Nombre de pj principal: lablanca
Nombre usuario Discord: JAVIER # 2355
Mision: https://es.wowhead.com/quest=27275/juntos-de-nuevo
el npc al cual se le entrega la misión no aparece como debería ni el en lugar que debiera  en npc esta unos metros mas atras para entregar la misión, pero no se puede entregar ya que la mecánica de la misión consiste en que el npc aparece por que estaba en sigilo , así que no se puede entregar y por ende no se puede continuar con la cadena de misiones de la zona 

![Desktop Screenshot 2020 05 23 - 13 34 39 72](https://user-images.githubusercontent.com/63380249/82738402-dbb53900-9cfc-11ea-8288-a8123018e35e.png)
![Desktop Screenshot 2020 05 23 - 13 34 49 24](https://user-images.githubusercontent.com/63380249/82738404-dce66600-9cfc-11ea-8600-ef2f5d4aa7d1.png)

VÍDEO DE COMO DEBERIA FUNCIONAR 
https://www.youtube.com/watch?v=nQ2A5OjSecM
Criterio para determinar si la misión esta bug o defectuosa y luego reportar 
1 he leído con atención lo que dice la misión
2 compruebo las mecánicas
3 abandono y agarro de nuevo la misión
4 verifico como funciona en el oficial
5 si después de todo esto la misión no se puede completar de ninguna manera genero el reporte

**Comment by rampague** [comment]
Corregido, El cambio se agregara en unos dias.
