### ISSUE TITLE
Bug, misión:Código del maestro de códigos

### ISSUE THREAD

**Issue by LABLANCA** [athenaswow/BugTracker-Athenas-WoW#404]
Nombre de pj principal: lablanca
Nombre usuario Discord: JAVIER # 2355
Mision: https://es.wowhead.com/item=63053/c%C3%B3digo-del-maestro-de-c%C3%B3digos
el objeto de la  mision esta pero no cuenta, no importa cuantas veces se interactue  con este 

(ACTUALIZACIÓN) 
después de interactuar con el objeto mas veces de las que se pueden contar me puse a matar  a los mobs de el area y casualmente 1 me lo boto el item 

![Desktop Screenshot 2020 05 23 - 14 03 15 01](https://user-images.githubusercontent.com/63380249/82739904-5be19b80-9d09-11ea-9d5f-ef5ec9b53f12.png)
![Desktop Screenshot 2020 05 23 - 14 03 06 80](https://user-images.githubusercontent.com/63380249/82739911-70be2f00-9d09-11ea-9fb4-be8005faf2be.png)
VÍDEO DE COMO DEBERIA FUNCIONAR 
https://www.youtube.com/watch?v=qQvyt4cTaYw
Criterio para determinar si la misión esta bug o defectuosa y luego reportar 
1 he leído con atención lo que dice la misión
2 compruebo las mecánicas
3 abandono y agarro de nuevo la misión
4 verifico como funciona en el oficial
5 si después de todo esto la misión no se puede completar de ninguna manera genero el reporte

**Comment by recuperadora** [comment]
![image](https://user-images.githubusercontent.com/35411793/95809613-d0c36b00-0cd4-11eb-88a9-764574bf4b4d.png)
![image](https://user-images.githubusercontent.com/35411793/95809631-dae56980-0cd4-11eb-863e-8798cedf5277.png)

No hay ningún problema, La razón por la cual no puedes tomar el objeto es por que estas en una banda.

**Comment by rampague** [comment]
![image](https://user-images.githubusercontent.com/35411793/95809694-09634480-0cd5-11eb-876b-3b8e840a9e9e.png)

La razón por la cual no puedes tomar el objeto es por que estas en banda.
