### ISSUE TITLE
Cadena de Misiones de Rey Mrgl-Mrgl

### ISSUE THREAD

**Issue by Felipefeik** [athenaswow/BugTracker-Athenas-WoW#405]
Al completar la cadena de misiones no entrega el objeto/disfraz que debe ser el botín final. En cambio, lo único que sucedió fue que me entregaron exp y oro.

Disfraz: https://es.wowhead.com/item=34620/traje-de-muda-del-rey-mrgl-mrgl
Misión final de la cadena: https://es.wowhead.com/quest=11566/de-rendirse-nada
NPC: https://es.wowhead.com/npc=25197/rey-mrgl-mrgl

Atte: Coronaveirus

**Comment by DavoKstro** [comment]
Un traje muy parecido a este es Traje de múrloc muchas veces se confunde ya que:

Traje de múrloc<----Se puede usar donde quieras.

Traje de muda del rey Mrgl-Mrgl<----Según se lee en el ítem dice "Solo se puede usar en Poblado Aleta Invernal y Cavernas Aleta Invernal."

**Comment by athenaswow** [comment]
Reporte invalido, la misión te entrega el traje solo mientras tienes la misión mas no te la dan por completarla.
