### ISSUE TITLE
Vuelo Druida  Kainstorm en Azeroth

### ISSUE THREAD

**Issue by kainstorm** [athenaswow/BugTracker-Athenas-WoW#406]
kainstorm

kainstorm1452

cuando me traslado a zonas como isla de quel danas o lunargenta se deshabilita la opcion de vuelo o usar monturas voladoras, solo me pasa en quel danas y en lunargenta y zonas aledañas

**Comment by athenaswow** [comment]
En esas zonas no se puede volar.
