### ISSUE TITLE
Las verdes colinas de Tuercespina - Logro -

### ISSUE THREAD

**Issue by Felipefeik** [athenaswow/BugTracker-Athenas-WoW#407]
Estuve realizando la cadena de misiones para poder conseguir el logro (https://es.wowhead.com/achievement=940/las-verdes-colinas-de-tuercespina) pero encontré una misión bug que me deja terminar de realizar con dicha cadena. 
Misión bug: https://es.wowhead.com/quest=195/persigue-al-raptor (Al matar al raptor no suma la cantidad de muertes al realizar)
Npc: https://es.classic.wowhead.com/npc=686/raptor-colazote

Atte: Coronaveirus

**Comment by athenaswow** [comment]
No se encontró ningún problema, la misión se puede realizar correctamente.
