### ISSUE TITLE
Bug en dos logros de las tierras de la peste del este

### ISSUE THREAD

**Issue by alielmgrabi** [athenaswow/BugTracker-Athenas-WoW#409]
Mi nombre de usuario: alielmagrebi
Mi nombre en discord: alielmagrebi
logros bug: https://es.wowhead.com/achievement=4892/misiones-de-las-tierras-de-la-peste-del-este
https://es.wowhead.com/achievement=5442/caravana-hacia-el-este
fotos: https://imgur.com/a/U92d2Wg
Descripciòn: he posteado estos dos bugs ya que creo que van de la mano, existe el fallo en donde no se puede coger las misiones necesarias para completar estos dos logros, esto se evidencia ya que voy a los sitios en los que segun wowhead deberia poder coger las misiones para reclutar a los miembros de la caravana, pero en ningun momento se me entragan misiones, (posdata: si cogi mision del cartel de entrañas y complete todas las misiones disponibles en tierras de la peste del este, actualmente ya no hay misiones que pueda coger) , espero su respuesta en lo mas breve posible, muchas gracias por su atención

**Comment by athenaswow** [comment]
Hola, debes elaborar un reporte mas especifico ya que no sabemos donde se rompe la cadena de misiones la cual te permite sacar los logros.
