### ISSUE TITLE
Misión: ¡Divino electrochoque! (Tormenta abisal)

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#41]
Nombre de personaje principal: Skala 
Usuario de discord: JorDaNN#5575 
Descripción del error: Usando el item que te da una ''visión de rayos'' al matar o atacar a los adds del vídeo deberían salir varios adds pequeños que son los que cuentan para la misión.
Misión wowhead: https://es.wowhead.com/quest=10411/divino-electrochoque
Athenaswow: https://www.youtube.com/watch?v=XUESEBzWqhU&feature=youtu.be
Como debería funcionar: https://www.youtube.com/watch?v=slKhmWMFyEA

**Comment by pangolp** [comment]
Hola, buen día. Gracias por el reporte. Por lo que estoy observando, no es que la misión funcione mal, sino que los criaturas, estarían mal ubicadas al parecer o al menos no coincidirían con el lugar en el que se muestra en el vídeo. Le dejo una imagen donde le muestro que he matado a alguno de ellos.

![WoWScrnShot_011920_061601](https://user-images.githubusercontent.com/2810187/72678318-72d65f80-3a83-11ea-808f-8b553142d0eb.jpg)

**Comment by pangolp** [comment]
Con mi comentario anterior, no quiero decir que la misión se encuentre en optimas condiciones, sino que en realidad se puede realizar pero que habría que averiguar si es tal cual se muestra en las imágenes del vídeo para en su defecto, ver la posibilidad de conseguir los puntos y reubicarlos en el mapa.
