### ISSUE TITLE
Bug, misión:El mal se acerca

### ISSUE THREAD

**Issue by LABLANCA** [athenaswow/BugTracker-Athenas-WoW#410]
Nombre de pj principal: lablanca
Nombre usuario Discord: JAVIER # 2355
Mision: https://es.wowhead.com/quest=10923/el-mal-se-acerca
la misión en si no funciona me piden 20 calaveras para poder interactuar con el item que da la mision pero no pasa nada y solo se desaparecen las calaveras, y el mob al que hay que invocar siempre esta pero en la parte de atrás de donde es la mision pero no se deja atacar 
![Desktop Screenshot 2020 05 26 - 19 17 50 38](https://user-images.githubusercontent.com/63380249/82963051-7fb21500-9f87-11ea-8290-e7df0750fa97.png)
![Desktop Screenshot 2020 05 26 - 19 18 30 52](https://user-images.githubusercontent.com/63380249/82963152-b2f4a400-9f87-11ea-886f-5ccbf1e75259.png)
![Desktop Screenshot 2020 05 26 - 19 19 10 33](https://user-images.githubusercontent.com/63380249/82963189-cbfd5500-9f87-11ea-8458-25910b1a4c4d.png)

![Desktop Screenshot 2020 05 26 - 19 18 03 78](https://user-images.githubusercontent.com/63380249/82963108-98bac600-9f87-11ea-87e5-18261ca7e2da.png)
VÍDEO DE COMO DEBERIA FUNCIONAR 
https://www.youtube.com/watch?v=Hks_aAdRnvw
Criterio para determinar si la misión esta bug o defectuosa y luego reportar 
1 he leído con atención lo que dice la misión
2 compruebo las mecánicas
3 abandono y agarro de nuevo la misión
4 verifico como funciona en el oficial
5 si después de todo esto la misión no se puede completar de ninguna manera genero el reporte

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
