### ISSUE TITLE
Misión diaria de pesca bug

### ISSUE THREAD

**Issue by alielmgrabi** [athenaswow/BugTracker-Athenas-WoW#414]
Mi nombre de usuario: alielmagrebi
Mi nombre en discord: alielmagrebi
mision bug: https://es.wowhead.com/quest=29361/el-monstruo-del-foso
fotos:  https://imgur.com/a/mdW8wIj
Descripción: No me deja dar de comer al monestruo del foso, ya intente de mil maneras, pero me dice "no tienes objetivo", no me pasa unicamente a mi ya que mi hermano tampoco puede completarla

**Comment by athenaswow** [comment]
Ya fue reportada.
