### ISSUE TITLE
Bug en mision de tierras inhospitas 

### ISSUE THREAD

**Issue by alielmgrabi** [athenaswow/BugTracker-Athenas-WoW#415]
Mi nombre de usuario: alielmagrebi
Mi nombre en discord: alielmagrebi
misión bug: https://es.wowhead.com/quest=27774/persuadidos-f%C3%A1cilmente#comments
fotos: https://imgur.com/a/umyE9ih
Descripción: La misión me manda a matar ogros, ya los mato muchas veces y no me cuenta ni 1 asesinato, no puedo completar la misión, con lo cual no puedo seguir con la cadena de misiones de tierras inhospitas para conseguir el logro de misiones en tierras inhospitas

**Comment by athenaswow** [comment]
La misión funciona correctamente, la razón por la que no te contaba era por que estabas en banda.

**Comment by athenaswow** [comment]
La misión funciona correctamente, la razón por la que no te contaba era por que estabas en banda.

**Comment by athenaswow** [comment]
La misión funciona correctamente, la razón por la que no te contaba era por que estabas en banda.
