### ISSUE TITLE
Mision Bug "La llave maestra"

### ISSUE THREAD

**Issue by Rassei7** [athenaswow/BugTracker-Athenas-WoW#416]
La misión de Norte de la vega de Tuercespina "La llave maestra" no se puede completar, se supone que se debe abrir "Recompensa Mosh'Ogg" al interactuar con "Hoja de sierra de Ventura y Cía" como se ve en el video https://www.youtube.com/watch?v=WRtwlNEQJvg en el min 0:48, pero no deja interactuar con "Hoja de sierra de Ventura y Cía" https://ibb.co/2c3PLzh.
"Recompensa Mosh'Ogg":https://es.wowhead.com/item=58205/recompensa-moshogg#submit-your-data

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
