### ISSUE TITLE
Misión Bug: Excavando en busca de lombrices

### ISSUE THREAD

**Issue by miguelangel789123** [athenaswow/BugTracker-Athenas-WoW#417]
Nombre del Personaje Principal: ImmanelKant
Nombre de usuario Discord: IntegralDeTheta#6508
Link de Wow head: 
https://es.wowhead.com/quest=26420/excavando-en-busca-de-lombrices#english-comments

Se supone que en <El Estanque de Olivia> uno debe pezcar teniendo el buff proporcionado por las lombrices anteriormente recogidas. Sin embargo, aún tieniendo el buff, las lubinas de cristal (Que son los objetos para completar la misión diaria de pezca) no se pezcan. Yo mismo he estado más de 45 minutos seguidos pezcando con el buff puesto y las lubinas no aparecen por ninguna parte. He recogido varios testimonios de gente que se encontraba allí mismo intentando hacer la misión y me dicen que tampoco han podido pezcar la lubina de cristal.

Link de la imágen/foto:
https://cdn.discordapp.com/attachments/438154568522661892/715656796374564965/unknown.png

Link de TwinHead:
https://cata-twinhead.twinstar.cz/?quest=26420

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos dias.
