### ISSUE TITLE
Item Drop Bug - Elemental Corrupto 

### ISSUE THREAD

**Issue by Felipefeik** [athenaswow/BugTracker-Athenas-WoW#419]
El item no es dropeado luego de matar al elemental (https://es.wowhead.com/npc=22009/elemental-corrupto#drops), pues al no ser adquirido no se podrá matar al boss (https://es.wowhead.com/npc=21212/lady-vashj)
y no se obtendrá el logro ni los items para las transfiguraciones.
Muchas Gracias.

**Comment by athenaswow** [comment]
No se encontró el problema, trata de elaborar un mejor reporte y súbelo nuevamente.
