### ISSUE TITLE
Errores sobre Poderes chaman elemental 

### ISSUE THREAD

**Issue by loscapos987** [athenaswow/BugTracker-Athenas-WoW#42]
Muy buenas noches , en el video que les mandare explico como debe funcionar y en que afecta al chaman elemental 

Link:https://www.youtube.com/watch?v=3t2mMRdvCQ4

**Comment by DennisCalderon** [comment]
reporte descartado por falta de pruebas.

**Comment by Enfermera** [comment]
Descartado por falta de pruebas y yo hace poco puse el mismo reporte y lo cerraros asi sin mas sin decir nada, apuesto de que ni lo leyeron porq puse todas las evidencias posibles
