### ISSUE TITLE
Misión Bug - "El Cristal de adivinación del Arúspice"

### ISSUE THREAD

**Issue by Felipefeik** [athenaswow/BugTracker-Athenas-WoW#420]
Al usar el orbe no se completa la misión.
 Quest: https://es.wowhead.com/quest=11490/el-cristal-de-adivinaci%C3%B3n-del-ar%C3%BAspice#comments

NPC: https://es.wowhead.com/npc=24848/kalecgos

**Comment by athenaswow** [comment]
La misión se completa después de haber terminado la cinemática.
