### ISSUE TITLE
Bug, misión: ¡Infernales por los aires!

### ISSUE THREAD

**Issue by LABLANCA** [athenaswow/BugTracker-Athenas-WoW#422]
Nombre de pj principal: lablanca
Nombre usuario Discord: JAVIER # 2355
Mision: https://es.wowhead.com/quest=10598/infernales-por-los-aires 
la mecánica de la misión funciona, se completa y todo el problema es cuando se va a entregar la misión, sale como si no tuviese el ítem que entregan  para hacerla asi que no se puede entregar
![Desktop Screenshot 2020 05 29 - 17 15 53 11](https://user-images.githubusercontent.com/63380249/83319205-e9d5ee80-a201-11ea-91bf-de75ac4729d8.png)
![Desktop Screenshot 2020 05 29 - 22 55 44 72](https://user-images.githubusercontent.com/63380249/83319214-fce8be80-a201-11ea-9beb-2a6eca984349.png)
![Desktop Screenshot 2020 05 29 - 22 56 44 58](https://user-images.githubusercontent.com/63380249/83319225-0ffb8e80-a202-11ea-987f-d2a980944ac1.png)
![Desktop Screenshot 2020 05 29 - 22 57 12 92](https://user-images.githubusercontent.com/63380249/83319230-23a6f500-a202-11ea-96fb-641081710cfd.png)

VÍDEO DE COMO DEBERIA FUNCIONAR 
https://www.youtube.com/watch?v=fl_SbjPHgDc

Criterio para determinar si la misión esta bug o defectuosa y luego reportar 
1 he leído con atención lo que dice la misión
2 compruebo las mecánicas
3 abandono y agarro de nuevo la misión
4 verifico como funciona en el oficial
5 si después de todo esto la misión no se puede completar de ninguna manera genero el reporte

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
