### ISSUE TITLE
Misión" [Cazar al ladrón]" legends picaro bug

### ISSUE THREAD

**Issue by Daniel-mecato** [athenaswow/BugTracker-Athenas-WoW#424]
https://imgur.com/a/2GgW6m4
NO completa la quest
https://www.youtube.com/watch?v=z9Yid5rMNuA minuto 14:32 se ve como se hace; como se completa.

**Comment by athenaswow** [comment]
Cerrado por falta de pruebas, se intento encontrar algún fallo pero se entrego la misión correctamente sin ningún problema.
