### ISSUE TITLE
Bug ciclón dudu

### ISSUE THREAD

**Issue by Palad0r** [athenaswow/BugTracker-Athenas-WoW#426]
En todas sus ramas, el dudu puede tirar ciclon y bueno, perfecto hasta ahí. El problema surge cuando encima de dejarte incapacitado 8segundos tú como paladín no puedes quitartelo con un inmune y encima si te tiras medallón tampoco te lo quita y encima a veces si tiras medallon se te pone en CD el medallon pero no te quita el ciclón

**Comment by athenaswow** [comment]
Colocar en el reporte el nombre de su PJ principal.
Colocar en el reporte su usuario de discord (ej.: jugador#0123).
Agregar link de wowhead de el hechizo, item, logro para ser mas exactos.
Agregar una descripción del error comprensible para cualquier persona.
Agregar fotos y/o vídeos.
Agregar enlaces que validen el error (wowhead o https://cata-twinhead.twinstar.cz/)
Nota: https://cata-twinhead.twinstar.cz/ es una web que maneja las bases de datos de: Vanilla, TBC, Wotlk y Cataclysm.
