### ISSUE TITLE
Bug en Vendedor de Suministro de Peletería en Cima del Trueno

### ISSUE THREAD

**Issue by SKAzazel** [athenaswow/BugTracker-Athenas-WoW#427]
Login de Cuenta: **SKAzazel**
Nombre de mi Personaje Alianza: **SKAzazel**
ID Discord: **Aun sin cuenta en la misma**

**Bug en Vendedor de Suministro de Peletería: Mak**

En la ciudad de **Cima del Trueno** (https://es.wowhead.com/thunder-bluff), el Vendedor de Suministro de Peletería: **Mak** (https://es.wowhead.com/npc=3008/mak) no tiene habilitado su función de Ventas de items necesarios para la subida de nivel en Peletería y actúa como un Maestro de Profesión de la misma.

Dejo como prueba el video que hice con mi personaje y el bug planteado: https://youtu.be/A8z2_7styZ4

Sin mas que comentar y reportar, y agradeciendo la atención, me despido.

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos dias.
