### ISSUE TITLE
NO TENGO LA SECUENCIA DE LA CADENA  DE CRESPUSCULAR 84

### ISSUE THREAD

**Issue by andresnovoaoficial** [athenaswow/BugTracker-Athenas-WoW#430]
no tengo la secuencia de misiones 
https://es.wowhead.com/quest=28716/se-busca-h%C3%A9roe-tierras-altas-crepusculares

**Comment by andresnovoaoficial** [comment]
mi personaje se llama drudred

**Comment by athenaswow** [comment]
Debes iniciar la cadena de misiones en el tablero, Si esto no corrige tu problema por favor elabora un mejor reporte con pruebas suficientes para poder ayudarte.


Colocar en el reporte el nombre de su PJ principal.
Colocar en el reporte su usuario de discord (ej.: jugador#0123).
Agregar link de wowhead de el hechizo, item, logro para ser mas exactos.
Agregar una descripción del error comprensible para cualquier persona.
Agregar fotos y/o vídeos.
Agregar enlaces que validen el error (wowhead o https://cata-twinhead.twinstar.cz/)
Nota: https://cata-twinhead.twinstar.cz/ es una web que maneja las bases de datos de: Vanilla, TBC, Wotlk y Cataclysm.
