### ISSUE TITLE
Misión Bug: El señor de la guerra Escama Oscura

### ISSUE THREAD

**Issue by miguelangel789123** [athenaswow/BugTracker-Athenas-WoW#431]
Nombre personaje principal: ImmanuelKant

Nombre usuario Discord: Anduin#6508

Link Wowhead:
https://es.wowhead.com/quest=13899/el-se%C3%B1or-de-la-guerra-escama-oscura

La misión tiene como objetivo matar a un monstruo y posteriormente entregar la misión con el propio cadaver del monstruo. El monstruo está, pero la misión no se puede entregar de ninguna manera. El cadaver no deja interactuar con él para entregarla.

Foto:
https://cdn.discordapp.com/attachments/469370326350954518/717202737322000414/unknown.png

Link Twinhead:
https://cata-twinhead.twinstar.cz/?quest=13899

**Comment by athenaswow** [comment]
Ya fue reportado.
