### ISSUE TITLE
Bug, misión: En esas cuevas pasa algo raro

### ISSUE THREAD

**Issue by LABLANCA** [athenaswow/BugTracker-Athenas-WoW#434]
Nombre de pj principal: lablanca
Nombre usuario Discord: JAVIER # 2355
Mision: https://es.wowhead.com/quest=11694/en-esas-cuevas-pasa-algo-raro
se usa el item tal cual corresponde pero al momento de terminar el cast dice que no tienes un objetio, 
independientemente si se se tiene o no target , en principio solo es usar el item cerca a la caldera y la mision se completaría pero no se  puede
![Desktop Screenshot 2020 06 02 - 17 18 49 50](https://user-images.githubusercontent.com/63380249/83575823-fa35e400-a4f5-11ea-9603-741efa41fc2a.png)
![Desktop Screenshot 2020 06 02 - 17 18 56 71](https://user-images.githubusercontent.com/63380249/83575869-0d48b400-a4f6-11ea-8aad-6d1c2b4edf74.png)
![Desktop Screenshot 2020 06 02 - 17 19 03 51](https://user-images.githubusercontent.com/63380249/83575905-23567480-a4f6-11ea-8ca6-23773333b0d9.png)

VÍDEO DE COMO DEBERIA FUNCIONAR 
https://www.youtube.com/watch?v=YyVe-W7BoAo
Criterio para determinar si la misión esta bug o defectuosa y luego reportar 
1 he leído con atención lo que dice la misión
2 compruebo las mecánicas
3 abandono y agarro de nuevo la misión
4 verifico como funciona en el oficial
5 si después de todo esto la misión no se puede completar de ninguna manera genero el reporte

**Comment by athenaswow** [comment]
Ya fue corregido.
