### ISSUE TITLE
Error al donar arma

### ISSUE THREAD

**Issue by Herireyes** [athenaswow/BugTracker-Athenas-WoW#438]
hola buen dia el dia de ayer 02/06/2020 realice la donacion de la espada (Espada magna rusiente de zoid) a mi personaje **Dkbeto** pero al abrir el correo con la donacion habia una gema y 10 de oro 

mi personaje principal es Huntbeto 
con el me done el arco y todo salio bien

**Comment by athenaswow** [comment]
Ponte en contacto con Vantepaz en Discord; Vantepaz#1718
