### ISSUE TITLE
Bug, misión: Reparación de trituradoras

### ISSUE THREAD

**Issue by LABLANCA** [athenaswow/BugTracker-Athenas-WoW#440]
Nombre de pj principal: lablanca
Nombre usuario Discord: JAVIER # 2355
Mision: https://es.wowhead.com/quest=12244/reparaci%C3%B3n-de-trituradoras
las trituradoras no se puede entregar  de ninguna manera 
![Desktop Screenshot 2020 06 03 - 12 12 06 47](https://user-images.githubusercontent.com/63380249/83667282-c4473d00-a593-11ea-854d-77c3cdffd3f9.png)

VÍDEO DE COMO DEBERIA FUNCIONAR 
https://www.youtube.com/watch?v=vtJJzzvvzfo
Criterio para determinar si la misión esta bug o defectuosa y luego reportar 
1 he leído con atención lo que dice la misión
2 compruebo las mecánicas
3 abandono y agarro de nuevo la misión
4 verifico como funciona en el oficial
5 si después de todo esto la misión no se puede completar de ninguna manera genero el reporte

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
