### ISSUE TITLE
Bug mision de Monte Hyjal

### ISSUE THREAD

**Issue by Millan09** [athenaswow/BugTracker-Athenas-WoW#444]
Nombre de Pj: Hundin
Discord: Hundin#6033

La Misión Milagro de Aessina se encuentra bug, al tomar la misión se completa e indica el lugar de entregar al llegar el NPC esta pero no da la opción de entrega 

https://ibb.co/k5MT1gD
https://ibb.co/rv88Kjq

**Comment by athenaswow** [comment]
![image](https://user-images.githubusercontent.com/50283962/85458698-034f2980-b567-11ea-8637-be5cc2f19687.png)
 la entregas hay
