### ISSUE TITLE
Misión bug: no aparece NPC para completar misión 

### ISSUE THREAD

**Issue by YefferMartinez-Archadixt** [athenaswow/BugTracker-Athenas-WoW#446]
Archadixt
Archadixt(Yeffer) #6423

En la zona de Garganta de Fuego, al iniciar la misión  [Operación: remover la caldera], esta se autocompleta y al ir al lugar marcado para entregarla no aparece el NPC.

Video de cómo debe ir la misión: https://www.youtube.com/watch?v=9vD0plcyS2E

No aparece el npc al final, y la misión se autocompleta sola

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.

**Comment by YefferMartinez-Archadixt** [comment]
![image](https://user-images.githubusercontent.com/59059909/86525086-ff18eb00-be47-11ea-8f70-ebc3434a804b.png)

El Npc se encuentra en otro lado que no es el marcado
