### ISSUE TITLE
Misión bug: No aparece NPC para entregar misión

### ISSUE THREAD

**Issue by YefferMartinez-Archadixt** [athenaswow/BugTracker-Athenas-WoW#449]
Archaditx
Archadixt(Yeffer)#6423

En la zona de Tierras Altas del Oeste, la misión  [Caras nuevas... y raras] que es autocompletable, al llegar al lugar de entrega no aparece el npc [Lindsay Negrosol] lo cual afecta la continuidad de la cadena.

![WoWScrnShot_061020_002505](https://user-images.githubusercontent.com/59059909/84230559-d7856b80-aab1-11ea-83b4-9dec222afb1a.jpg)

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
