### ISSUE TITLE
Bug, pasiva VENGANZA guerrero protección

### ISSUE THREAD

**Issue by LABLANCA** [athenaswow/BugTracker-Athenas-WoW#451]
Nombre de pj principal: lablanca
Nombre usuario Discord: JAVIER # 2355
lo que sucede es lo siguiente, aun que en la imagenes es mas claro y evidente no esta de mas aclarar que venganza la pasiva de todos los tankes no esta funcionando el el war tank  aunque reciva cualquier cantidad de daño el 5% de poder de ataque  que se deberia adquirir tras recibir cualquier tipo de daño y que se acumula hasta el 10%  no esta funcionando reitero en el war tank he visto que en otras clases como el dk sangre si funciona aunque no se ve el buff de esta pasiva en la barra superior de beneficios tras revisar el panel de las estadisticas si aumenta el poder de ataque, pero el el caso de el war no

![war2](https://user-images.githubusercontent.com/63380249/84283668-e0e9f480-ab00-11ea-949c-e52b6a4fc9a1.png)
![war3](https://user-images.githubusercontent.com/63380249/84283672-e3e4e500-ab00-11ea-871e-bda6f8dd45e8.png)
![war4](https://user-images.githubusercontent.com/63380249/84283674-e3e4e500-ab00-11ea-8c87-4d508ad788fc.png)

**Comment by DennisCalderon** [comment]
Reparado, pero el spell no funciona en PVP
