### ISSUE TITLE
Bug, misión: Podemos reconstruirlo

### ISSUE THREAD

**Issue by LABLANCA** [athenaswow/BugTracker-Athenas-WoW#454]
Nombre de pj principal: lablanca
Nombre usuario Discord: JAVIER # 2355
Mision: https://www.wowhead.com/quest=11483/we-can-rebuild-it
solo es obtenible el objeto que nos da el enano el el campamento (Lingotes de hierro oscuro)
los otros dos items que son de recoger de una zona especifica no estan 
![Desktop Screenshot 2020 06 11 - 15 29 53 96](https://user-images.githubusercontent.com/63380249/84436574-4caf8880-abf9-11ea-8bbf-2ff3d0ef43e2.png)
![Desktop Screenshot 2020 06 11 - 15 31 34 06](https://user-images.githubusercontent.com/63380249/84436620-62bd4900-abf9-11ea-8d90-a23df78c2b19.png)

VÍDEO DE COMO DEBERIA FUNCIONAR 
https://www.youtube.com/watch?v=FnlzyqogN9o
Criterio para determinar si la misión esta bug o defectuosa y luego reportar 
1 he leído con atención lo que dice la misión
2 compruebo las mecánicas
3 abandono y agarro de nuevo la misión
4 verifico como funciona en el oficial
5 si después de todo esto la misión no se puede completar de ninguna manera genero el reporte

**Comment by athenaswow** [comment]
Reporte invalido, el objeto no siempre va salir en esas coordenadas, hay 3 spawns y se respawnean en distintos puntos del lugar donde te marca la mision.
![image](https://user-images.githubusercontent.com/50283962/85237303-76339580-b3eb-11ea-9037-daeb6ff3e7e5.png)
