### ISSUE TITLE
Mision bug 

### ISSUE THREAD

**Issue by Alejandrotester** [athenaswow/BugTracker-Athenas-WoW#457]
nombre de pj principal: Wolff
discord: Darkhallow#6255
La misión bug es Las semillas de vordrassil
en la misión hay que meterse en un árbol y coger unas semillas, el problema es que no se pueden coger.
así es como deveria ser la misión:
https://youtu.be/JcZ7O02C9ns

**Comment by athenaswow** [comment]
No se si estas jugando en otro servidor o haces esto por fastidiar al servidor.
![image](https://user-images.githubusercontent.com/50283962/85214544-fdbcce00-b331-11ea-901c-fe119607c384.png)
