### ISSUE TITLE
mision bug 

### ISSUE THREAD

**Issue by Alejandrotester** [athenaswow/BugTracker-Athenas-WoW#458]
nombre del pj: Wolff
discord: Darkhallow#6255
la misión bug es la progenie del dios oso en esta hay que hablar con 2 osos y con esto se completaría la misión, el problema es que al hablar con los osos no completa la misión.
así deveria ser la misión:
https://youtu.be/WbOAG5UPd4M

**Comment by athenaswow** [comment]
Su reporte no es valido.
![image](https://user-images.githubusercontent.com/50283962/85214480-c4379300-b330-11ea-8263-5a34640e32c4.png)

![image](https://user-images.githubusercontent.com/50283962/85214485-db768080-b330-11ea-8fb9-525aebd3fb24.png)
