### ISSUE TITLE
mision bug 

### ISSUE THREAD

**Issue by Alejandrotester** [athenaswow/BugTracker-Athenas-WoW#459]
nombre del pj: Wolff
discord: Darkhallow # 6255
La mision se llama una posible relación en la cual hay que matar a unos npcs y estos deverian dar sangre de furbolg enloquecido pero al matarlos no dropean nada, mate a todos los que pudo y no dropearon nada. 
así deveria estar la misión: 
https://youtu.be/h8SNPSzzzHY

**Comment by athenaswow** [comment]
Su reporte no es valido.
![image](https://user-images.githubusercontent.com/50283962/85214423-b6cdd900-b32f-11ea-8511-45ae5e8cbf7a.png)

![image](https://user-images.githubusercontent.com/50283962/85214460-42e00080-b330-11ea-8d12-11a0c909b30c.png)
