### ISSUE TITLE
Cross faction en masmorras HC

### ISSUE THREAD

**Issue by cristian318** [athenaswow/BugTracker-Athenas-WoW#460]
Nombre de pj: Poker
Discord: Collyns#3043
Problema: He entrado a 2 masmorras heroicas aleatorias, una seguida de la otra y en ambos casos me emparejó con un grupo de alianzas (soy un sacerdote tauren). Obviamente se hace imposible hacer la masmorra en esas condiciones
imagen: https://ibb.co/WP23fqp

**Comment by athenaswow** [comment]
Debes elaborar un mejor reporte, las pruebas no son contundentes para poder hacer las respectivas pruebas.

Colocar en el reporte el nombre de su PJ principal.
Colocar en el reporte su usuario de discord (ej.: jugador#0123).
Agregar link de wowhead de el hechizo, item, logro para ser mas exactos.
Agregar una descripción del error comprensible para cualquier persona.
Agregar fotos y/o vídeos.
Agregar enlaces que validen el error (wowhead o https://cata-twinhead.twinstar.cz/)
Nota: https://cata-twinhead.twinstar.cz/ es una web que maneja las bases de datos de: Vanilla, TBC, Wotlk y Cataclysm.
