### ISSUE TITLE
Misión - El disfraz marino

### ISSUE THREAD

**Issue by DjrrSk** [athenaswow/BugTracker-Athenas-WoW#462]
Pj: Chiharu
Discord: #Djrr9120

El item que te da la mision para convertirse en naga no funciona y no se puede entregar mision, por consiguiente la cadena de misiones esta bloqueada.

https://es.wowhead.com/quest=14260/el-disfraz-marino

**Comment by athenaswow** [comment]
Corregida y Se ajusto la misión siguiente, El cambio se aplicara en unos días.
