### ISSUE TITLE
Items sospechosos en arenas 

### ISSUE THREAD

**Issue by Palad0r** [athenaswow/BugTracker-Athenas-WoW#465]
Básicamente éste reporte es porque no se pueden ocupar items de ningún tipo según tengo entendido en arenas y no pude grabarlo porque sólo luché 1 vez contra ellos.
Resumo, el sacer me tiró fear y el dk me hico cc chain hasta que el sacerdote disciplina se fue tras una pared cuando se estaba quedando sin mana, el tema es que de pronto empecé a ver como le subía el maná rápidamente de manera inexplicable hasta que mi colega me hizo ver que claro, como ven en los buffs, está comiendo y bastó ese descuido para ver como le subía el mana y lógicamente perdimos, pero quería tomar la captura que dejaré abajo porque todo se me hizo muy raro
Adjunto una foto como prueba https://prnt.sc/t3nzcz

**Comment by athenaswow** [comment]
Pruebas insuficientes, Lo único que veo es que salio de combate y uso una bebida para recuperar su mana.
