### ISSUE TITLE
Bug en Vehiculo Horda

### ISSUE THREAD

**Issue by SKAzazel** [athenaswow/BugTracker-Athenas-WoW#467]
Login de Cuenta: **SKAzazel**
Nombre de mi Personaje Horda: **SKAzazel**
ID Discord: **Aun sin cuenta en la misma**

**Bug con PNJ en Vehiculo Horda en Azshara**

En la Zona de **Azshara** (https://es.wowhead.com/azshara),  el uso del **Vehículo del Maestro de Vuelo** de la Horda:  **Friz Girasuelo** (https://es.wowhead.com/npc=37005/friz-girasuelo), no puede usarse a menos que seas nivel 55 o superior, debido a que el PNJ **Consorte Tronatesta** (https://es.wowhead.com/npc=6380/consorte-tronatesta), esta oculto debajo de la zona para usar el Vehiculo y ataca al jugador que se acerca a el, ademas de que es una zona para PJ de **nivel 10-20**, el PNJ es de **nivel 55**.

Dejo como prueba el video que hice con mi personaje y el bug planteado: https://youtu.be/AwFuZzENqgY

Sin mas que comentar y reportar, y agradeciendo la atención, me despido.

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
