### ISSUE TITLE
Bug en Vehiculo Transporte Horda

### ISSUE THREAD

**Issue by SKAzazel** [athenaswow/BugTracker-Athenas-WoW#472]
Login de Cuenta: **SKAzazel**
Nombre de mi Personaje Horda: **SKAzazel**
ID Discord: **Aun sin cuenta en la misma**

**Bug en Vehiculo de Transporte Horda en Vallefresno**

En la Zona de **Vallefresno** (https://es.wowhead.com/ashenvale), el Maestro de Vuelo de la Horda: **Andruk** (https://es.wowhead.com/npc=11901/andruk), no puede usarse como punto de transporte, ya que ademas de estar repetido en la misma zona el **PNJ**, ninguno de los **2** te da la opción de poder transportarte a otros puntos previamente conocidos, aunque los demás puntos de transporte si lo reconocen como punto de llegada; **el primero** si reconoce los puntos para transportarse pero no lo habilita y **el otro** dice que no reconoce otros puntos cercanos.

Dejo como prueba el video que hice con mi personaje y el bug planteado: https://youtu.be/HK01FrYj8q0

Sin mas que comentar y reportar, y agradeciendo la atención, me despido.

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
