### ISSUE TITLE
Bug Mision: Capitán Barbatroz

### ISSUE THREAD

**Issue by Cjsh1179** [athenaswow/BugTracker-Athenas-WoW#474]
Nombre PJ: Deogall.
ID Discord: JC_1179#4460
Enlace Misión: https://es.wowhead.com/quest=24950/capit%C3%A1n-barbatroz

Buen día Gm, 

Resulta que me encontraba realizando la cadena de misiones de Tanaris, todo iba bien. Sin embargo, al encontrarme con la misión: Capitán Barbatroz asignada por el NPC Megs Trituramatic (Horda) me apareció el panel como normalmente lo hacen todas las misiones con el objetivo de aceptarla, pero al darle click en aceptar, la misión desapareció de mi registro de misiones como si se hubiera autocompletado, pero este no es el caso porque nunca hubo un botón de completar misión.

Ahora no puedo interactuar con el NPC para volver a tomarla (adjunto imagen) y tampoco se me activó la cadena que continúa a la misión en cuestión.

![WoWScrnShot_062520_223802](https://user-images.githubusercontent.com/62728179/85818208-b3728d00-b735-11ea-88d8-5e45b6e734e2.jpg)

Espero se pueda hacer algo para continuar con la cadena.

Muchas gracias.

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
