### ISSUE TITLE
Una misión que sigue bugg [Caras nuevas... y raras]

### ISSUE THREAD

**Issue by Felixeltoro** [athenaswow/BugTracker-Athenas-WoW#484]
La mision que comento este usuario sigue bugg.
 https://github.com/athenaswow/BugTracker-Athenas-WoW/issues/449
![WoWScrnShot_070220_171630](https://user-images.githubusercontent.com/63224422/86413790-cb8f6280-bc87-11ea-92fa-da08958c4eed.jpg)

**Comment by rampague** [comment]
Corregido, El cambio se agregara lo mas pronto posible.
