### ISSUE TITLE
NPC Parasitus - Rare

### ISSUE THREAD

**Issue by Felipefeik** [athenaswow/BugTracker-Athenas-WoW#487]
Llevo  2 semanas esperando AFK en su zona de respawn para poder domarlo pero no hay rastro del rare, si lo han deshabilitado por favor informar.
Gracias!

NPC: https://es.wowhead.com/npc=51029/parasitus

**Comment by rampague** [comment]
El Npc fue Añadido en el parche 5.2.0.16650 por eso no te sale.
