### ISSUE TITLE
Misiones bug:  [Misiones del Norte de la Vega de Tuercespina]

### ISSUE THREAD

**Issue by YefferMartinez-Archadixt** [athenaswow/BugTracker-Athenas-WoW#488]
![image](https://user-images.githubusercontent.com/59059909/86525170-35a33580-be49-11ea-98cc-2b37b989b177.png)

En la Zona de Vega de Tuercespina, se logran hacer solo una cantidad de 45 misiones de 50 lo cual afecta la continuidad del logro, averigue y el NPC que deberia darme otra misión, no lo hace, también pasee por las zonas marcadas por el addon y en ninguna parte me dan misiones!!
![image](https://user-images.githubusercontent.com/59059909/86525185-756a1d00-be49-11ea-981f-853a5effb5bd.png)

**Comment by rampague** [comment]
Debes indicarme en que misión fue que se rompió la cadena, ósea cual fue la ultima misión que hizo en este lugar para revisar si la siguiente tiene algún requisito adicional.
