### ISSUE TITLE
Bug smoke Rogue

### ISSUE THREAD

**Issue by paulovictorc** [athenaswow/BugTracker-Athenas-WoW#491]
El tótem del chamán si todos están en el humo, debería funcionar normalmente.
https://www.youtube.com/watch?v=Q3BfoZQaNgo

**Comment by canace1234** [comment]
Se nota que no sabe jaja

https://cata-twinhead.twinstar.cz/?fixreport=show&id=10990

Smoke Bomb will disable Spirit Link Totem's health redistribution effect, and Spirit Link Totem will not target players with Smoke Bomb debuff
