### ISSUE TITLE
Bug, logro Brann totalmente nuevo

### ISSUE THREAD

**Issue by LABLANCA** [athenaswow/BugTracker-Athenas-WoW#499]
Nombre de pj principal: lablanca
Nombre usuario Discord: JAVIER # 2355
Logro: https://es.wowhead.com/achievement=2154/brann-totalmente-nuevo
El problema es que Brann despues de activar la mecánica de la computadora al terminar esta misma  Brann se acerca a la salida de la habitación y simplemente desaparece y no da  el logro, lastimosamente llevamos varias semanas intentando hacer este logro por que pensamos que habíamos hecho algo mal pero no , lo que sucede es que Brann sencillamente desaparece sin dar el logro 
![Desktop Screenshot 2020 07 07 - 17 27 06 22](https://user-images.githubusercontent.com/63380249/86854924-06760980-c07f-11ea-8fa7-5969a4a21405.png)
![Desktop Screenshot 2020 07 07 - 17 32 02 44](https://user-images.githubusercontent.com/63380249/86854929-07a73680-c07f-11ea-8cc1-7dc983a1a0de.png)
![Desktop Screenshot 2020 07 07 - 17 32 24 98](https://user-images.githubusercontent.com/63380249/86854935-08d86380-c07f-11ea-8c6e-8326644b3523.png)
![Desktop Screenshot 2020 07 07 - 17 36 13 58](https://user-images.githubusercontent.com/63380249/86854938-0a099080-c07f-11ea-83e5-d71ec120536a.png)

**Comment by athenaswow** [comment]
Ya fue reportado.
