### ISSUE TITLE
El fin de los Velasangre - Mision

### ISSUE THREAD

**Issue by DjrrSk** [athenaswow/BugTracker-Athenas-WoW#501]
Pj: Yusura
Discord: Djrr#9120

https://es.wowhead.com/quest=26703/el-fin-de-los-velasangre

Una de las recompensas no disponible, pieza indispensable para conjunto de transfiguración.
https://es.wowhead.com/item=131586/calzas-de-la-bahía-del-botín

https://imgur.com/a/TuhOXe1

**Comment by athenaswow** [comment]
https://es.wowhead.com/item=131586/calzas-de-la-bah%C3%ADa-del-bot%C3%ADn  El ítem fue añadido al parche 7.0.3.22248
