### ISSUE TITLE
bug en la montura de vuelo

### ISSUE THREAD

**Issue by Keiichi243** [athenaswow/BugTracker-Athenas-WoW#503]
Buenas noches, necesito ayuda para poder salir de la montura de vuelo al momento de que se callo el server mi personaje estaba en la montura de vuelo en direccion a sierra espolon, al momento de qiue se callo el server se quedo dando vueltas por el mundo y no me deja bajarme. Atraviesa hasta las texturas.
agradeciera mucho el apoyo, gracias 
pd intente desatarcarlo desde la pagina pero sale error del servidor numero 500
att
PJ Zarrus druida lv 36 huargen
discord Juandax #8905
![image](https://user-images.githubusercontent.com/53916255/88009762-e01d8880-cad8-11ea-8e86-fe981f64c060.png)

**Comment by athenaswow** [comment]
Cierra el juego y usa la opción de desatascar personaje desde la web.
