### ISSUE TITLE
Sustitucion Riendas del sable de hielo y sable de la noche 

### ISSUE THREAD

**Issue by Alhaguee** [athenaswow/BugTracker-Athenas-WoW#507]
https://es.wowhead.com/quest=7671/sustituci%C3%B3n-de-sable-de-hielo
estas misiones son unas diarias que al completar podremos escoger entre unos tigres que nos dan, pero al ir a las misiones estan no se pueden iniciar, ni completar de ninguna manera.

**Comment by athenaswow** [comment]
Misión Deshabilitada.
