### ISSUE TITLE
Oro perdido en Subastas

### ISSUE THREAD

**Issue by joal55** [athenaswow/BugTracker-Athenas-WoW#508]
Pj principal: Xervez 
Usuario de discord: Xervez23#2255
Descripción del problema: Buenos días, lo que ocurre es la desaparición del oro que se supone la casa de subastas me debería entregar, he vendido varios objetos pequeños y tan solo me han aparecido los mensajes de compra, mas no el oro indicado en cada uno de ellos. Espero su pronta ayuda, gracias de antemano.
Adjunto fotos de los mensajes.
https://ibb.co/GTrWnxq
https://ibb.co/1LvMPPp
https://ibb.co/wNvmqh5

![WoWScrnShot_072520_114146](https://user-images.githubusercontent.com/68785995/88462022-1ad34800-ce6e-11ea-837e-398f23cff3d5.jpg)
![WoWScrnShot_072520_114351](https://user-images.githubusercontent.com/68785995/88462025-1c9d0b80-ce6e-11ea-8a45-23ed637e520e.jpg)
![WoWScrnShot_072520_114145](https://user-images.githubusercontent.com/68785995/88462029-2161bf80-ce6e-11ea-8ecc-7f4c7016c432.jpg)

**Comment by athenaswowdaac** [comment]
Buenos dias amigo. Creo que tienes una pequeña confusion disculpa si me equivoco, el mensaje q recibes es el de aviso de que te han comprado, luego de 60minutos te llegara el oro en otro mensaje, deberia ser asi.
