### ISSUE TITLE
bug en la mision del señor del fuego

### ISSUE THREAD

**Issue by Keiichi243** [athenaswow/BugTracker-Athenas-WoW#513]
buen dia escribo este mensaje para reportar un bug, en el cual no te arroja la opcion de hablar con cenarius para activar la mision.
![image](https://user-images.githubusercontent.com/53916255/89443311-bb025a00-d715-11ea-960f-d6023f23ea7c.png)

**Comment by rampague** [comment]
![image](https://user-images.githubusercontent.com/35411793/95669685-f3287d80-0b48-11eb-8b40-4aa3b28a7ac8.png)
![image](https://user-images.githubusercontent.com/35411793/95669700-06d3e400-0b49-11eb-9585-305d0b02e4d7.png)
![image](https://user-images.githubusercontent.com/35411793/95669725-2bc85700-0b49-11eb-8514-ee1b20ffbfdf.png)

**Comment by rampague** [comment]
No veo ningún problema, quizá cuando tomaste la misión hubo alguna caída y se te bugueo elimina la misión y tómala de nuevo y comentas si se resolvió el problema.
