### ISSUE TITLE
Bug misión Asesinos oscuros 

### ISSUE THREAD

**Issue by jairgtlll** [athenaswow/BugTracker-Athenas-WoW#516]
Al hacer la cadena de misiones en tierras altas crepusculares del npc, Maestro Mathias Shaw.
dice que no cumple los requisitos para aceptar dicha misión.

v

https://imgur.com/a/PW7DUPu

**Comment by rampague** [comment]
hiciste la misión https://www.youtube.com/watch?v=NNYsMBhPznw ? la misión tiene como requisito haber completado esa misión para poder aceptarla.

**Comment by rampague** [comment]
https://www.youtube.com/watch?v=E81cHbAkVw4 esta también

**Comment by rampague** [comment]
Prueba y si con eso no resuelves tu problema deja tu comentario.
