### ISSUE TITLE
Mision: La purificación de Quel´dar

### ISSUE THREAD

**Issue by JOGUER5** [athenaswow/BugTracker-Athenas-WoW#519]
pj: Joguer
Mision: La purificación de Quel´dar esta bug es una mision en secuencia y esta mision https://es.wowhead.com/quest=24564/la-purificaci%C3%B3n-de-queldelar, no funciona al sumergir la espada no pasa nada se queda ahi sin  pasar nada, adjunto el funcionamiento correcto https://www.youtube.com/watch?v=i0KB-rAJER0, agradesco su colavoracion

**Comment by athenaswow** [comment]
Ya fue reportado por otro jugador.
