### ISSUE TITLE
Misión Bug Gelidar. 

### ISSUE THREAD

**Issue by Fustigador** [athenaswow/BugTracker-Athenas-WoW#523]
Pj principal con el problema: Vaedoran
Id del discord mió: Fibřīķ#3985

Buenas tardes!. Dejo esto para informar que tengo un problema con una misión de Gelidar llamada " Soltar la Trampa " Cual me manda a escender una fogata apagada, y cuando trato de darle a esta me dice que tengo que tener un objetivo o estoy bien pegado a la misma y no la prende es como si no la tuviese enfrente, y cuando le doy al objeto que me dieron para prender la misma no lo hace, incluso hay una apagado como muestran las imágenes y demás pero aun así me salta eso. 

Adjunto foto ( Es la fogata de mi izquierda )
https://imgur.com/a/wbhLUTY

Misión: https://es.wowhead.com/quest=11969/soltar-la-trampa

Video en el que me fije como se hace y como lo hace: 
https://www.youtube.com/watch?v=zTi8G3zlGHU

Espero que sea suficiente con esto para que me ayuden con esta quest! Ya que me impide continuar con la cadena de misiones!

**Comment by rampague** [comment]
Solucionado, el cambio se aplicara en unos dias.
