### ISSUE TITLE
Bug, misión Cementerio de Dragones. 

### ISSUE THREAD

**Issue by Fustigador** [athenaswow/BugTracker-Athenas-WoW#524]
Nick de personaje con el problema y principal: Vaedoran 
Id del discord: Fibřīķ#3985

" Conversando con las profundidades " 
https://es.wowhead.com/quest=12032/conversando-con-las-profundidades

En esta misión me surge el problema que cuando la llevo acabo e invoco al npc que me da 20 segundos para saltar al agua, y cuando llevo acabo esa acción no me la cumple cuando pregunte por Global me dijieron que estaba bug ademas que lo vi en el siguiente video y no me la completa. A parte cuando me tiro me dice " Objetivo no cumplido " o algo así, y me manda hacerla de nuevo.: 

https://www.youtube.com/watch?v=jZBF9FExel8

Si me pudiesen ayudar ya que me complica a la hora de seguir la cadena para terminar con la zona.

**Comment by athenaswow** [comment]
Ya reportado.
