### ISSUE TITLE
Cadena de misiones de Fiordo anda Bug. 

### ISSUE THREAD

**Issue by Fustigador** [athenaswow/BugTracker-Athenas-WoW#525]
Id del personaje con el problema y principal: Vaedoran
id del discord: Fibřīķ#3985

A continuación comenzare a especificar el problema que me surgió y más el que ando teniendo con respecto a una cadena de misiones. Lo que pasa es que el npc " Orfus de Komawa " de Fiordo Aquilonal me deberia de dar una misión llamada " Los muertos se Levantan " ( https://es.wowhead.com/quest=11504/los-muertos-se-levantan ) y en este caso no me la da: Adjunto pruebas de este npc: https://imgur.com/a/dyE9IpU 

Lo muestro con el mapa por que se supone que este npc debería de darme esa quest, ignoren que este en gris por que es obvio que soy lvl 80 y es de nivel 71. Pero no quita el hecho que este npc ande bug, o no se por que pregunte y nadie sabe al respecto, y no se necesita una misión para que este npc te la de, el solito ahí esperando que alguien se acerque para ayudarlo y así tomarla. 

Adjunto video que lo muestra: https://www.youtube.com/watch?v=FEegyMnxXyQ&t=4s Ademas anteriormente mostré la id en wowhead. Tanto para la horda y para la alianza la da el y no cambia en nada. ( las misiones en rojo son las misiones que le siguen luego de cumplir con la cadena de este y me pase a otro y así hasta terminar. ) 

Son las misiones restantes que me faltan para terminar con la zona (Se ve en la foto que tengo 85/105) No hay forma de proseguir, espero que puedan ayudarme o al menos darme una solución para poder seguir con esto, por que nadie sabe como responderme ante el problemita este xD Si, si soy el vicio que quiere sacar el titulo " 
 El Maestro cultural " Que no se diga más, pero de paso aviso que este npc anda bugueadisimo. 

Desde ya muchas gracias! 
Y si falta algo o necesitan algo más me avisan que puedo ayudar en lo que pueda. Pero creo que con eso es suficiente, no? Pero bueno, espero su respuesta!

**Comment by athenaswow** [comment]
No te entrega la misión por que debes hacer primero https://www.wowhead.com/quest=11573/orfus-of-kamagua
