### ISSUE TITLE
" Se aproxima un Frente Frió " 

### ISSUE THREAD

**Issue by Fustigador** [athenaswow/BugTracker-Athenas-WoW#531]
Nick de mi personaje: Vaedoran 
Id del discord: Fibřīķ#3985
Id de misión bug: https://db.wowlatinoamerica.com/?quest=13070

Lo que pasa con esta misión es que el Alto señor Tirion Vadín en la zona " La Vanguardia Argenta " es como que a esta quest la tiene como si fuese a entregarla con un signo de entrega diaria, y al darle no me la deja completar, ni menos me la dió, es como que si la hubiese tomado cuando ni otro Npc me dió esta y más cuando el es quien la da. 

Adjunto prueba: https://imgur.com/a/48n2Iov

**Comment by athenaswow** [comment]
No se encontró el error.
