### ISSUE TITLE
Npcs que desaparecieron por una quest que me la auto completo con solo tomarla. 

### ISSUE THREAD

**Issue by Fustigador** [athenaswow/BugTracker-Athenas-WoW#532]
Nombre del personaje con el problema de estos npc: Vaedoran
Id de mi discord: Fibřīķ#3985

Id de los Npc con sus respectivas quest: https://es.wowhead.com/npc=30631/jinete-oscura-arly#english-comments

https://es.wowhead.com/npc=30708/cruzado-olakin-sainrith

Problema: 

Lo que paso con estos dos npc fue que al tomar una quest (Cual no recuerdo su nombre por que se cayo el server). Cuando la tome fue que me la completo sola y la termino sin reclamar al npc, y al hacerlo estos dos Npc se esfumaron junto a las cadenas de misiones que estos tienen, dando lugar a una batalla entre Cruzados y Gigantes de carne abajo, es como si fuese otra zona. Cosa que si no mal recuerdo eso pasaba al final no al principio de las misiones, a la distancia se ven, pero cuando me acerco desaparecen. Seguro fue un error mió pero no estoy tan seguro de ello. Y ahora no se como hago para seguir por que de esos dos dependía que pueda continuar haciendo misiones en Corona de Hielo. (Hay otras misiones bug en el lugar cuales reportare cuando compruebe si realmente lo están). 

Adjunto pruebas. https://imgur.com/a/pE5p42A
https://imgur.com/a/W1JLvEa

No se si puedan ayudarme, y no creo que ahora no se como hacer para que estos dos feos aparezcan de nuevo, ya intente deslogueando y volviéndolo hacer o matandome para ver, pero nada funciono.

**Comment by athenaswow** [comment]
No tengo ningún problema al llevar a cabo la entrega de la misión, si el problema persiste por favor sube pruebas mas contundentes para encontrar el error.
