### ISSUE TITLE
Bestia elite Hidra no domesticable

### ISSUE THREAD

**Issue by angeldlr237** [athenaswow/BugTracker-Athenas-WoW#534]
Pj principal reznov-cazador elfo de sangre
usuario de discord: Angeldlr237#2244
Descripción: mi reporte se trata sobre que la bestia llamada hidra no puedo domesticarla y debería ser domesticable para todas los talentos del cazador, busque la mascota en varios lugares y en ningunos se puede domesticar y en esa expacion debería ser domesticable ayuda con eso 

les dejare unas imágenes de la bestia 
<blockquote class="imgur-embed-pub" lang="en" data-id="a/0jEZlFq"  ><a href="//imgur.com/a/0jEZlFq">hidra</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by athenaswow** [comment]
Se dice que es domesticable a partir del parche 6.0.
