### ISSUE TITLE
Msisión bug: (¡El monstruo del foso!) - entrañas

### ISSUE THREAD

**Issue by roockeii** [athenaswow/BugTracker-Athenas-WoW#535]
PJ principal: Vilz
Usuario de discord: iRoses#9986

Descripción del problema: Al ir al foso, el monstruo solo sale si me ubico en una zona exacta, pero cuando le doy alimentar dice que no hay ningún objetivo.

Imágenes y/o vídeo adjunto:
https://es.wowhead.com/quest=29361/el-monstruo-del-foso
https://www.youtube.com/watch?v=_IgLBcw83ms&t=2s

**Comment by roockeii** [comment]
por favor, lo necesito para el logro.

**Comment by wilbm** [comment]
He tratado la misma misión hace poco y sigue sin funcionar.
