### ISSUE TITLE
Portal de tierras altas crepusculares a ventormenta dañado

### ISSUE THREAD

**Issue by TrEx000-M** [athenaswow/BugTracker-Athenas-WoW#539]
Nombre de mi personaje principal: Pinkruso.
Id de mi usuario de Discord: TrEx000#7944

Referencias: - https://es.wowhead.com/twilight-highlands (Aqui no encontré nada sobre el portal, pero tiene que ver con el area que menciono.)
- https://www.wowhead.com/spell=59065/portal-to-stormwind (Asi deberia funcionar el portal.)
- https://wow.gamepedia.com/Twilight_Highlands#Portals (Aqui habla de los portales que hay en tierras altas, y de como se deberian abrir de ida y venida al completar cierta cadena de misiones.)

Descripción: No me funciona el portal de tierras altas crepusculares hacia ventormenta, mientras que si me funciona el de ventor hacia tierras altas, comento esto como un error tomando en cuenta los portales de tol barad, que funcionan ambos, y los de infralar, que también funcionan ambos.

Foto de referencia: https://ibb.co/X3kNrX1

Links que validen el error:  - https://wow.gamepedia.com/Twilight_Highlands#Portals (Aqui habla de los portales que hay en tierras altas, y de como se deberian abrir de ida y venida al completar cierta cadena de misiones.)
- https://cata-twinhead.twinstar.cz/?spell=59065 (Aqui habla del funcionamiento del portal.)

**Comment by Montyz96** [comment]
Mejor borre este post

**Comment by TrEx000-M** [comment]
Por?

**Comment by rampague** [comment]
En revisión.

**Comment by rampague** [comment]
Corregido, estará en revisión y se subirá al servidor en unos días.
