### ISSUE TITLE
problemas al encontrar los npc

### ISSUE THREAD

**Issue by danteinfernus15** [athenaswow/BugTracker-Athenas-WoW#54]
pj principal: vacaloca
discord: peketo-danteinfernus15#9862

https://es.wowhead.com/quest=29196/al-santuario

en la cadena de misiones se a venido encontrando un problema con el npc llamado matogarra, que al momento de entregar la mision en el sitio donde la indica, no se encuentra ese npc y no es posible entregarla impiendo continuar con la cadena de misiones de  Guardianes de hyal: ¡invacion a las tierras de fuego!
https://es.wowhead.com/quest=29388/guardianes-de-hyjal-invasi%C3%B3n-de-las-tierras-de-fuego

**Comment by athenaswow** [comment]
Necesito un vídeo con mas pruebas para poder llegar al error.
![image](https://user-images.githubusercontent.com/50283962/70751766-2880f680-1cff-11ea-8296-616636a67fda.png)

**Comment by kaymbel** [comment]
pj principal: Bankotzu
discord: kaymbel#9968
https://es.wowhead.com/quest=29389/guardianes-de-hyjal-invasi%C3%B3n-de-las-tierras-de-fuego 
El npc no aparece estoy haciendo la misma cadena de misiones y no se pueden completar por que el npc llamado matogarra no se encuentra
![WoWScrnShot_010920_194004](https://user-images.githubusercontent.com/59715235/72118305-b2cc7280-331e-11ea-9205-08153079365f.jpg)
