### ISSUE TITLE
Bug de la profesión alquimia "Convertir: elementos vivos"

### ISSUE THREAD

**Issue by raigerdruida** [athenaswow/BugTracker-Athenas-WoW#541]
Pj principal: Raiger
Usuario de discord: athenaswow#8453
Descripción del problema: El hechizo de alquimia "Convertir: elementos vivos" no funciona correctamente ya que debería crear volátiles específicos acorde a la zona donde se transmuta y el problema radica básicamente en que no respeta dichas zonas, en este caso en la imagen que adjuntaré mas abajo estaba en la zona Vashj'ir, utilicé el hechizo y me dio aire volátil lo cual es erróneo.
Habilidad:    https://es.wowhead.com/spell=78866/convertir-elementos-vivos#comments
Prueba n°1:  https://ibb.co/q1Hk8MW
Prueba n°2:  https://blue.mmo-champion.com/topic/142053-aclaraci%C3%B3n-sobre-convertir-elementos-vivos/

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
