### ISSUE TITLE
Items Bug - Isla intemporal -pandaria

### ISSUE THREAD

**Issue by cobrac505x** [athenaswow/BugTracker-Athenas-WoW#542]
PJ principal: Cobrac
usuario de discord: xifiax#9329
Descripción del problema: En la isla intemporal hay unos cofres los cuales al abrirlos nos pueden dropear unos items como por ejemplo este: https://es.wowhead.com/item=102285/botas-de-tela-intemporales el problema es que al usarlo para que nos de la armadura,no nos suelta nada
https://ibb.co/Q6yTfx1

**Comment by rampague** [comment]
este es el bug tracker de cataclysmo, por favor sube un nuevo reporte en el bug tracker de pandaria. https://github.com/athenaswow/BugTracker-Athenas-WoW-Pandaria-
