### ISSUE TITLE
Bug de la Feria Luna Negra. - Arena - 

### ISSUE THREAD

**Issue by Fustigador** [athenaswow/BugTracker-Athenas-WoW#543]
Nick del personaje : Mulzusi 

Problema/Bug: Lo que pasa y lo que anda sucediendo en esto es que surgió un bug a través de un arma. ¿Como es esto? y ¿Que arma es? La Crematoría (Cualquiera) el bug que provoca esta arma es que reinicia la aparición del cofre que da un abalorio de la fosa, tantas formas y maneras posibles hasta el cansancio, incluso hay gente que vende este dichoso abalorio o cofre a una cierta cantidad de oro determinada. 

El dichoso bug es cuando se quita el arma y se la vuelve equipar, con solo tener un macro o tener un acceso rápido al gestión de equipamiento sale. No hay mucho que decir sobre esto, solo es ir con esa arma y probar y probar hasta que salga, pero solo funciona estando parado al lado del Npc de la fosa 

https://imgur.com/a/ICvXRs4 ( La gente que aprovecha este bug es cuando no hay gente, lo hace sin asco alguno, como dije antes el horario siempre lo hacen a la noche o bien a la madrugada o a la mañana, en lo general casi siempre anda vacía la feria y es ahí cuando aprovechan para hacer este bug ) 

Si bien no se ve haciendo bug, se puede ver que quizás estaba por hacerlo y que justo haya aparecido yo de la nada para ver que hace o cacharlo en el instante. La verdad no se como es que surgió este bug, si tuviese una forma de grabar lo haría pero es imposible cacharlos y cuando intente abrir el programa ya se habran ido, solo es tomar capturas de las veces que el anunciador de la fosa dice lo mismo y no hará falta grabar nada.

**Comment by athenaswow** [comment]
Necesitamos mas información.
