### ISSUE TITLE
Personaje bug de pets exoticas magria y ankha

### ISSUE THREAD

**Issue by claupao27** [athenaswow/BugTracker-Athenas-WoW#544]
claupao
babas#5574
pòdria jurar que mi personaje anda bug porque e estado en hyjal 2 meses campeando y 3 semanas sin moverme de ahi  hasta amanecerme luego que vi que unos amigos domaron a ankha y magria  y yo no logro verlas ahora nose si me faltan misiones pero las q tengo no me dejan seguir ya que andan bug y mis amigos logran ver las pets con menos misiones de las que  yo complete quisiera me ayudes en eso porque es mucho tiempo y nose me hace justo q unos puedan ver las pets y yo no, no se si habra mas casos como el mio pero son meses mande como 50 tikets todos dicen que me contacte con vantepaz pero tampoco me da una solucion
las misiones bug son 
https://es.wowhead.com/quest=29125/entre-los-%C3%A1rboles
https://es.wowhead.com/quest=29148/alas-ardientes
https://es.wowhead.com/quest=29162/la-bendici%C3%B3n-de-la-naturaleza
https://es.wowhead.com/quest=29165/la-llamada-de-la-manada
https://es.wowhead.com/quest=29199/petici%C3%B3n-de-refuerzos
https://es.wowhead.com/quest=29101/temporada-de-patadas
y hay amigos q si completaron estas misiones pero a mi no me dejan y podes ver el registro no me muevo de hyjal espero puedas ayudarme gracias.

**Comment by athenaswow** [comment]
Si tu problema persiste por favor repórtalo nuevamente.
