### ISSUE TITLE
Mi personaje esta bug 

### ISSUE THREAD

**Issue by zSlaYFeRz** [athenaswow/BugTracker-Athenas-WoW#545]
Pj: Zslayferz
Usuario de Discord : zSlaYFeRz#8231

Buenas dias o tardes el motivo de este video que voy a mostrarles, es de mi PJ el cual después de unos cuantos duelos se Buguea y la mayoría de CC no me afecta, ta les como la POLIMORFIA DEL MAGO, LA RANA DEL CHAMI, EL ANILLO DE HIELO DEL MAGO, EL PORRAZO DEL PICARO Y LA TRAMPA DE HIELO DEL CAZA entre otros y desearía que los solucionaran, No estoy muy seguro del motivo que ocasiona este error, pero creeria que es el poder de Exanime Nato. GrAcias por su Ayuda.

![World Of Warcraft 2020 10 07 - 23 18 24 01_Trim_Trim_Trim (2)_Trim_Moment - copia](https://user-images.githubusercontent.com/72638602/95645340-a7f86700-0a83-11eb-9e2d-295e557f787d.jpg)
![World Of Warcraft 2020 10 07 - 23 18 24 01_Trim_Trim_Trim (2)_Trim_Moment(2)](https://user-images.githubusercontent.com/72638602/95645341-a9299400-0a83-11eb-8ccb-316e0a87dbdf.jpg)
![World Of Warcraft 2020 10 07 - 23 18 24 01_Trim_Trim_Trim (2)_Trim_Moment(3)](https://user-images.githubusercontent.com/72638602/95645342-a9c22a80-0a83-11eb-9070-fc9d51967998.jpg)
![World Of Warcraft 2020 10 07 - 23 18 24 01_Trim_Trim_Trim (2)_Trim_Moment(4)](https://user-images.githubusercontent.com/72638602/95645343-aa5ac100-0a83-11eb-8cb8-9a0cb5b39649.jpg)
![World Of Warcraft 2020 10 07 - 23 18 24 01_Trim_Trim_Trim (2)_Trim_Moment(6) - copia](https://user-images.githubusercontent.com/72638602/95645344-aaf35780-0a83-11eb-92b4-f77ad5e713f5.jpg)
![World Of Warcraft 2020 10 07 - 23 18 24 01_Trim_Trim_Trim (2)_Trim_Moment(7) - copia](https://user-images.githubusercontent.com/72638602/95645345-ab8bee00-0a83-11eb-96c5-0aa623e40627.jpg)
![World Of Warcraft 2020 10 07 - 23 18 24 01_Trim_Trim_Trim (2)_Trim_Moment(8)](https://user-images.githubusercontent.com/72638602/95645346-acbd1b00-0a83-11eb-923a-d43bebc39353.jpg)
![World Of Warcraft 2020 10 07 - 23 18 24 01_Trim_Trim_Trim (2)_Trim_Moment(10) - copia](https://user-images.githubusercontent.com/72638602/95645347-ad55b180-0a83-11eb-8ea0-17e5e7684b4e.jpg)
![World Of Warcraft 2020 10 07 - 23 18 24 01_Trim_Trim_Trim (2)_Trim_Moment](https://user-images.githubusercontent.com/72638602/95645348-ae86de80-0a83-11eb-9dd4-289f69cf27c9.jpg)

**Comment by rampague** [comment]
Abre un ticket en juego para que reseteen tus auras.
