### ISSUE TITLE
Misión Bug: NPC desapareció, Misión: Lycanthoth el Corruptor

### ISSUE THREAD

**Issue by ARC123sk** [athenaswow/BugTracker-Athenas-WoW#547]
Personaje: Drestok
Discord: Arcan#6291

Estaba haciendo la misión de cadenas en Monte Hyjal, en la que debía de hacer cadena de misiones. Al hablar con Takrik Iraullido y hacer la Primera quest de matar a "Barbaro de Lycanthoth", la segunda misión es Lycanthoth el Corruptor, donde luego de matar al lobo, aparece el Lobo Lo 'Gosh (Facción Horda) donde te montas y empieza a hacer una limpieza de la zona como corresponde, donde finalmente luego de eliminar a todos los Barbaros de Lycanthoth reposa en su Estatua y completas la misión

Video de Misión Original : https://www.youtube.com/watch?v=C-UdETGa6Lg

En athenas wow, al hablar con Takrik Iraullido y hacer la Primera quest de matar a "Barbaro de Lycanthoth", me dio la segunda misión que era Lycanthoth el Corruptor, donde luego de matar al lobo, aparece el Lobo Lo 'Gosh (Facción Horda) . Al terminar de limpiar la zona el lobo como corresponde, demoré en recibir al recompensa y el NPC Lobo Lo 'Gosh desaparecio sin yo poder completar la quest y borrando así la misión completa sin poder tomarla nuevamente.

Adjunto video donde no me aparece el NPC ni para volver a tomar la misión: https://youtu.be/7H0gWrTLAgM
![imagen](https://user-images.githubusercontent.com/72975365/96251643-616ca600-0f76-11eb-9aef-5a8d1c46d732.png)

**Comment by athenaswow** [comment]
Debes hablar con un Game master para que te de la misión ya que no es fallo de la misión, Perdiste la misión por una caída del servidor.
