### ISSUE TITLE
Bug en cadena de misiones de ala abisal

### ISSUE THREAD

**Issue by Darkside58** [athenaswow/BugTracker-Athenas-WoW#548]
El bug me ocurrió haciendo la cadena de misiones de ala abisal para conseguir la montura de draco del mismo lugar, cuando fui a hablar con Karymaku, complete la misión que ya había hecho y acepte la siguiente, cuando acepte esa misión se me completo de una vez sin hacer nada, hablé otra vez con la dragona y me llevó hasta Mordenai, completé la misión y no me dan mas misiones, no puedo reclamar mi draco ni ir a donde se consigue porque sigue marcándolos como enemigos, ¿Cómo podría solucionarlo?

Discord: Darkside#1223

**Comment by athenaswow** [comment]
Necesitamos mejor información..
Colocar en el reporte el nombre de su PJ principal.
Colocar en el reporte su usuario de discord (ej.: jugador#0123).
Agregar link de wowhead de el hechizo, item, logro para ser mas exactos.
Agregar una descripción del error comprensible para cualquier persona.
Agregar fotos y/o vídeos.
Agregar enlaces que validen el error (wowhead o https://cata-twinhead.twinstar.cz/)
Nota: https://cata-twinhead.twinstar.cz/ es una web que maneja las bases de datos de: Vanilla, TBC, Wotlk y Cataclysm.
