### ISSUE TITLE
bug de la lista de hermandad 

### ISSUE THREAD

**Issue by malzha** [athenaswow/BugTracker-Athenas-WoW#558]
Pj principal: diooss
Usuario de discord: beelfegor#5016
Descripción del problema : vengo a comentar un bug y es que en mi hermandad (GLADIADORES DE LA HORDA ) yo soy el guil master y e notado que en la lista donde aparecen la gente conectada dice que hay cierto numero de personas pero cuando voy a ver me aparece solo uno, muchos de los miembros de mi hermandad se a quejado de eso , tengo pruebas de lo que me refiero 

![Captura2](https://user-images.githubusercontent.com/73722348/97762637-2d959280-1ad7-11eb-8ca1-f9ffc314b57b.PNG)
grax por su atencion me ayudaria mucho

**Comment by athenaswow** [comment]
El problema aun persiste ?
