### ISSUE TITLE
Problema al pasar portales.

### ISSUE THREAD

**Issue by David5933** [athenaswow/BugTracker-Athenas-WoW#559]
El problema consiste en que al parecer  a mi personaje no se le permite ingresar o traspasar ningún tipo de portal (Por ejemplo el que nos envía a Terrallende o cualquiera para ingresar a alguna mazmorra) y debido a eso mi experiencia en el juego se ve algo comprometida y limitada ya que no puedo hacer instancias o ir a algunos lugares.
Para cualquier notificación en el juego dejo el nombre del personaje afectado:  Disbelief Cazador lv 85 Alianza
Adjunto imágenes para que se pueda apreciar mejor el error:
![WoWScrnShot_110120_172256](https://user-images.githubusercontent.com/73799681/97816910-ee964700-1c66-11eb-8001-1a09d3e32b2d.jpg)

![WoWScrnShot_110120_171402](https://user-images.githubusercontent.com/73799681/97816918-ff46bd00-1c66-11eb-84f3-15ed1080cf1a.jpg)

**Comment by athenaswow** [comment]
Esto ya no debería de fallar, si aun tienes el problema por favor elabora un nuevo reporte.
