### ISSUE TITLE
Misión: el retorno de zarpadura y misiones paralelas el espíritu del oso cardo, el espíritu del venado y el espíritu acechalunas

### ISSUE THREAD

**Issue by okapi37** [athenaswow/BugTracker-Athenas-WoW#56]
la Misión debería arrojarla el vigilante Karithus luego de completar la misión el vinculo del ritual que nos lleva a hacer el espíritu del oso, el espíritu del venado o el espíritu acechalunas pero esta tampoco funciona correcta, y luego no la arroja y es necesaria para avanzar en la trama de costa oscura y conseguir el logro de misiones de la zona y la mascota del marchituelo que da recuerdos de Auberdine
https://es.wowhead.com/quest=13599/el-retorno-de-zarpadura
https://www.youtube.com/watch?v=9YxTuUflTqE&list=PLsEQm4YuQsCVGjk6m1PZIapzvvPDGGkgX&index=3   minutos 12:00 a 14: 05

**Comment by athenaswow** [comment]
Necesito mas información de la falla un vídeo estaría bien.

**Comment by okapi37** [comment]
hum yo abrí consulta y me facilitaron la misión

**Comment by athenaswow** [comment]
falta de pruebas
