### ISSUE TITLE
Glifo sello de verdad no da pericia

### ISSUE THREAD

**Issue by sectario** [athenaswow/BugTracker-Athenas-WoW#569]
Glifo sello de verdad no da pericia, debería aumentar la pericia en 10 puntos cuando activamos el sello de verdad y rectitud, pero esto no pasa.
DC: Sectario#9142
pj: Sectario
https://youtu.be/vJ6f6PMpn0k

**Comment by Daniel-mecato** [comment]
Men pongase el sello y vuelva y abrir la pestaña del pj. 
mira el vídeo amigo.

**Comment by Daniel-mecato** [comment]
https://youtu.be/-OdJFzwTOrw
