### ISSUE TITLE
vuelo de dolanaar

### ISSUE THREAD

**Issue by okapi37** [athenaswow/BugTracker-Athenas-WoW#57]
El vuelo de dolanaar no esta activado

**Comment by athenaswow** [comment]
Necesito mas información.

**Comment by okapi37** [comment]
en la zona inicial de elfos nocturnos en cataclismo se añadió un vuelo en dolanaar pero aunque esta el maestro de vuelos este no da la opción de vuelo
https://wow-es.gamepedia.com/Fidelio

**Comment by okapi37** [comment]
![ERROR 1](https://user-images.githubusercontent.com/58822718/70756603-fecdcc80-1d0a-11ea-964a-9a140fd9290c.png)

**Comment by okapi37** [comment]
hola sera que
 si se resuelve?

**Comment by pangolp** [comment]
Ayer hice la quest, cuando tenes la misión de llevar el menaje a Darnassus, el maestro te muestra un gossip que te permite ir hasta allá, pero solo en caso de tener la misión. Nose si luego de completarla, podes ir y venir libremente entre una ciudad y otra. **Para eso, deberíamos de tener mas información que corrobore eso.**

**Comment by pangolp** [comment]
![WoWScrnShot_020520_015123](https://user-images.githubusercontent.com/2810187/73812035-1cbf2700-47ba-11ea-891d-565ad1985ced.jpg)

![WoWScrnShot_020520_015130](https://user-images.githubusercontent.com/2810187/73812038-2052ae00-47ba-11ea-96fd-a0293f523a1b.jpg)

Confirmado, si tenes la quest tomada, el npc te muestra el gossip y te lleva a darnassus, el tema ahora esta en averiguar, si el maestro de vuelo, una vez que completas la misión, siempre te lleva o no entre una ciudad y otra... o si solamente esta para esa misión.
