### ISSUE TITLE
Quest bug: Orillas Crepusculares

### ISSUE THREAD

**Issue by ing-diego-morales** [athenaswow/BugTracker-Athenas-WoW#578]
Pj: Bosterion 
Usuario discord: Nothing#0499
Link WoWhead: https://es.wowhead.com/quest=28832/orillas-crepusculares
Descripción: Al completarla e ir a entregarla no se encuentra el npc correspondiente para completar la misión 
Misión correctamente: https://www.youtube.com/watch?v=mk9-maryfDY

**Comment by athenaswow** [comment]
![image](https://user-images.githubusercontent.com/50283962/103958213-717dc700-511a-11eb-842f-c629d557345b.png)
