### ISSUE TITLE
Instructor de Chamanes

### ISSUE THREAD

**Issue by CritikalOwen** [athenaswow/BugTracker-Athenas-WoW#581]
El instructor de chamanes no esta donde el guardia te dice que tiene que estar, que es en la isla en el puente de ventormenta, si no que esta en el distrito de los enanos, ¿alguna razon en especial para que este ahi?

**Comment by athenaswow** [comment]
Esta mal el guardia en realidad el instructor esta en otro lugar https://es.wowhead.com/npc=44393/bolner-picomartillo
