### ISSUE TITLE
Problema con un servicio adquirido

### ISSUE THREAD

**Issue by slaughterize** [athenaswow/BugTracker-Athenas-WoW#583]
Personaje Principal: Xains
Nombre en Discord: 𝒥𝑒𝓈𝓈#6970
Buenas tardes, el día de ayer ( 27/12/2020 ) adquirí el servicio de la tienda, mas especifico el Cambio de Apariencia, cabe mencionar que con el único propósito que realice la donación fue para el cambio de nombre a mi personaje main por un nombre que tenia guardado desde hace tiempo pero no podía cambiarlo hasta el día de ayer, ayer día me doy con la sorpresa de que al momento de cambiar el nombre no me dejaba, me aparecía el mensaje que el nombre no estaba disponible, cosa que no es posible ya que borraba el personaje con el nombre exacto y lo volvía a crear y de igual manera no dejaba, haber si me dan una solución para tomar el nombre ya que fue la donación fue con el único motivo de cambio de nombre, El nombre el cual deseo ponerle al personaje es Strangers

Aquí las pruebas: 
https://imgur.com/03J2FUg - aqui se puede ver como tenia el nombre reservado con un personaje Trol, el cual fue borrado para hacer el cambio de nombre 
https://imgur.com/dqojRaE - aqui se ve como hago todos los cambios y al momento de confirmar me aparece que el nombre no esta disponbile 
https://imgur.com/fMjrBwD - aqui se ve como despues de haber hecho los cambios y que no me dejara utilizar el nombre en el personaje main puedo crear otro personaje con el mismo nombre, el cual quiero para mi Paladin Main

**Comment by athenaswow** [comment]
Este no es lugar para este tipo de reclamos por favor abre un ticket en juego o comunícate con un Game master por medio del grupo de discord.
