### ISSUE TITLE
"BUG CON LA BOMBA DE HUMO DEL PICARO EN ALAMUERTE"

### ISSUE THREAD

**Issue by KiIItox** [athenaswow/BugTracker-Athenas-WoW#584]
Personaje principal: Killtox
Discord: Killtox#0967

El bug consiste en buguear las hemorragias que tira alamuerte "las babosas"  faltando 3 segundos para que caiga la hemorragia si todos los miembros de la banda mas sus pets se juntan y el pícaro tira bomba de humo, entonces, la Hemorragia no se activara.

Este bug lo supe cuando se armo una ID por medio del chat global de la alianza, y pues no quiero que se sigan aprovechando de esto los jugadores.

**Comment by jucevena** [comment]
fotos o video pes para entender mejor

**Comment by athenaswow** [comment]
Reglas para subir reportes:
Colocar en el reporte el nombre de su PJ principal.
Colocar en el reporte su usuario de discord (ej.: jugador#0123).
Agregar link de wowhead de el hechizo, item, logro para ser mas exactos.
Agregar una descripción del error comprensible para cualquier persona.
Agregar fotos y/o vídeos.
Agregar enlaces que validen el error (wowhead o https://cata-twinhead.twinstar.cz/)
Nota: https://cata-twinhead.twinstar.cz/ es una web que maneja las bases de datos de: Vanilla, TBC, Wotlk y Cataclysm.
