### ISSUE TITLE
COMPRA DE PERSONAJE NO RECIBIDO

### ISSUE THREAD

**Issue by ElJoshe** [athenaswow/BugTracker-Athenas-WoW#585]
Ayer en la cuenta con el user "Magimiria" se compraron 3 personajes de los cuales uno no llego a la cuenta, el nick de personaje que no llego es "Blinded".
Dc personal: Magi☆Miria#3137

**Comment by athenaswow** [comment]
No es el lugar correcto para este tipo de reclamos.
