### ISSUE TITLE
(Quest) ¡Al santuario! - Monte Hyjal.

### ISSUE THREAD

**Issue by danteinfernus15** [athenaswow/BugTracker-Athenas-WoW#59]
pj principal: vacaloca
discord: peketo-danteinfernus15#9862

https://es.wowhead.com/quest=29196/al-santuario

en la cadena de misiones se a venido encontrando un problema con el npc llamado matogarra, que al momento de entregar la mision en el sitio donde la indica, no se encuentra ese npc y no es posible entregarla impiendo continuar con la cadena de misiones de: 

Guardianes de hyal: ¡invacion a las tierras de fuego!

https://es.wowhead.com/quest=29388/guardianes-de-hyjal-invasi%C3%B3n-de-las-tierras-de-fuego

[Imagen(1).pdf](https://github.com/athenaswow/BugTracker-Athenas-WoW/files/3958085/Imagen.1.pdf)

**Comment by pangolp** [comment]
El npc existe, el problema es que puede que este fuera de fase. Necesitaría un poco más de información como para intentar reproducir el problema. Es decir, si esta es una cadena de misiones que recién comienza o si viene desde antes, en alguna otra zona del mapa.

![WoWScrnShot_011920_062419](https://user-images.githubusercontent.com/2810187/72678425-81714680-3a84-11ea-8c8f-a1316124b7de.jpg)

**Comment by danteinfernus15** [comment]
esa cadena de misiones empieza después de terminar todas las misiones del monte hyal.

la cual según en Internet para llegar al frente de magma, todo se comienza con la misión (Guardianes de hyal: llamada de los ancianos) que después de terminar con casi todas las misiones del monte hyal,sin quedar ninguna misión por completar. Nos dirigimos al tablón de misiones en ogrimar donde se adquiere una cadena de misión nueva llamada (Guardianes de hyal: ¡ invacion a las tierras de fuego!) cabe resaltar que en algunos sitios o videos esta mision se obtiene en la (arboleda de aessina en el monte hyal con el NPC archidruida hamuul).

despues de aceptar la mision nos indica a entregarla al santuario malorne con matogarra.

ese problema de "fase" no solamente se presenta en esa mision, si no tambien con las siguientes despues de completarla, e recibido ayuda de gms pudiendo completarla pero se sigue igual presentando el problema de cambio de fase, donde no deja entregarla o encontrar el npc en el sitio.

no solamente me ocurre a mi, e visto ya varios con lo mismo e incluso con la misiones diarias han presentado problemas, un gm dijo que tal vez pondrían a prueba esa zona con la cadena de misiones indicada anteriormente.

**Comment by pangolp** [comment]
A pesar de que recibió ayuda, la idea es tratar de solucionar el problema así que le pido que deje el tema abierto para que se evite crear muchos temas del mismo tipo al menos. Gracias por haber reportado. Si vuelve a encontrar algún problema no dude en avisar.

**Comment by athenaswow** [comment]
Corregido se aplicara en unos dias.
