### ISSUE TITLE
Xploit abalorio feria de la luna negra

### ISSUE THREAD

**Issue by Metash17** [athenaswow/BugTracker-Athenas-WoW#599]
En el video se muestra, el paso a paso para que el npc empieze a spamear el abalorio 

https://youtu.be/jTanz1yhy3Y

id del item: https://es.wowhead.com/item=74034/luchador-de-fosa
Parte de la mision para conseguir : https://es.wowhead.com/item=74035/maestro-luchador-de-fosa

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos dias.
