### ISSUE TITLE
Guarded by the light, en la rama de sagrado

### ISSUE THREAD

**Issue by Topen01** [athenaswow/BugTracker-Athenas-WoW#6]
Topen
Topen#1425

Guarded by the light, un talento de la rama de protección se activa cuando usamos nuestro guardián estando en la rama de sagrado (heal)

https://www.youtube.com/watch?v=awkNU10Gsb0

Como vemos en el video, al estar full vida, usar el guardián y curarnos con Palabra de gloria, nos dejará un buff llamado Guarded by the light, un buff que solo se debería activar si estamos en la rama de protección y tenemos el talento, como se ve en el video, no tengo el talento pero aún así este buff se activa.

**Comment by DennisCalderon** [comment]
actualmente bajo revisión

**Comment by DennisCalderon** [comment]
Reparado, mañana martes  se aplica el cambio
