### ISSUE TITLE
Misión diaria bug: Cima del trueno 

### ISSUE THREAD

**Issue by ing-diego-morales** [athenaswow/BugTracker-Athenas-WoW#608]
Pj main: Bosterion
Discord: Nothing# 0499
Link Youtube: https://www.youtube.com/watch?v=LuZex0_mbV8
Link Wowhead: https://es.wowhead.com/quest=29354/adornos-lustrosos
Descripción: La misión diaria de cocina no funciona correctamente, simplemente los items requeridos para completar esta misión no aparecen. Busque y pregunté durante un buen rato y me comentaron que estaba bug, busqué un tutorial y nada. Simplemente no habían piedras para recoger.

**Comment by rampague** [comment]
![image](https://user-images.githubusercontent.com/35411793/108772024-7b248800-752a-11eb-8290-265455305dd5.png)
esta funcionando bien.

**Comment by ing-diego-morales** [comment]
Acabe de comprobarlo, funciona bien. Pero antes cuando lo reporté no había
ninguna piedra lustrosa
