### ISSUE TITLE
Muñecos de Entrenamiento Bugs 

### ISSUE THREAD

**Issue by LJokerx** [athenaswow/BugTracker-Athenas-WoW#61]
Nombre PJ: Ljokerl
Usuario DC: Joker_85D#5901

https://es.classic.wowhead.com/spell=5221/triturar

 Al momento de usar triturar en los muñecos de entrenamiento no deja usar el hechizo triturar que como dice en la descripción se debe usar detrás de un objetivo al hacer esto en un muñeco no deja saliendo un mensaje que que dice que no esta situado detrás del objetivo.

https://youtu.be/4GvjNhvQZe8

**Comment by athenaswow** [comment]
corregido.
