### ISSUE TITLE
Logro bug: Barredor de minas

### ISSUE THREAD

**Issue by ing-diego-morales** [athenaswow/BugTracker-Athenas-WoW#610]
Pj main: Bosterion
Discord: Nothing#0499
Link Youtube: https://www.youtube.com/watch?v=GRV_NgIMKhQ
Link Wowhead: https://es.wowhead.com/achievement=1428/barredor-de-minas
Descripción: Te puedes comer las minas que quieras, en montura o sin montura. Pero no te dan la animación de la explosión y en fin lo intenté por 30m viendo tutoriales pero no funciono de ninguna forma. Pregunte y me dijeron que no funcionaba.

**Comment by athenaswow** [comment]
Corregido, el cambio será agregado en unos días.
