### ISSUE TITLE
Quest Bug: El frente roto 

### ISSUE THREAD

**Issue by ing-diego-morales** [athenaswow/BugTracker-Athenas-WoW#614]
Pj main: Bosterion
Discord: Nothing#0499
Link YouTube: https://www.youtube.com/watch?v=2Oin6JFW2x4
Link Wowhead: https://es.wowhead.com/quest=13228/el-frente-roto
Descripción: Al hablarle al npc que toca hablarle, la misión no se completa.

**Comment by rampague** [comment]
Necesitamos pruebas.

**Comment by ing-diego-morales** [comment]
https://youtu.be/lo6ZRRNrbno

Ahí está la prueba, espero sea suficiente

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
