### ISSUE TITLE
Quest Bug: Véngame

### ISSUE THREAD

**Issue by ing-diego-morales** [athenaswow/BugTracker-Athenas-WoW#615]
Pj main: Bosterion
Discord: Nothing#0499
Link Wowhead: https://es.wowhead.com/quest=13230/v%C3%A9ngame
Descripción: Mato los adds que debo matar, pero no cuentan. Es como si hicieras una misión en una banda. No cuenta.

**Comment by rampague** [comment]
Necesitamos mas pruebas.

**Comment by ing-diego-morales** [comment]
https://youtu.be/flX9fBFQZGA
Disculpa la calidad del video, pero puedes observar que al matar no cuentan

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
