### ISSUE TITLE
Bug Bandera de Cumbres Gemelas

### ISSUE THREAD

**Issue by sectario** [athenaswow/BugTracker-Athenas-WoW#616]
Cuando tenia la bandera en Cumbres Gemelas usé el comando /afk me sacó de la bg; hasta ahí normal.
Pero me quedé con la bandera y ni relogeado se quita el bufo de penalización. La bandera no salió de nuevo en la bgs porque mi team quedo dentro de la bg y me confirmaron este dato.

En la imagen pueden ver que me quedó el buffo de penalización

Main: Sectario
DC: Sectario#9142
https://media.discordapp.net/attachments/753844760707334177/812900530816679936/unknown.png?width=886&height=498

**Comment by athenaswow** [comment]
Haber un ticket para que remuevan el buff.
