### ISSUE TITLE
Misión: Compañeros de viaje

### ISSUE THREAD

**Issue by wilbm** [athenaswow/BugTracker-Athenas-WoW#618]
Pj: Bathory
Discord: questioner#2968

Misión en wowhead: https://es.wowhead.com/quest=27381/compa%C3%B1eros-de-viaje

Al terminar la misión "Adelante, hacia la Capilla de la Esperanza de la Luz" que comienza con el NPC Fiona (ID: 45417) en un lugar y termina con Fiona en la Capilla, debería estar disponible la siguiente misión de la cadena: "Compañeros de viaje" que la da el NPC Tarenar Golpe Solar (ID: 45429), sin embargo, la misión no aparece. He estado haciendo misiones para el logro: El maestro cultural, así que me he apoyado en dos addons para trackear misiones: quest completist y quest hubber, ambos me muestran la misma información de la cadena y wowhead también dice lo mismo. En este momento llevo 67/70 misiones en  Tierras de la Peste del Este, he sobrevolado todo el mapa y ya no tengo misiones disponibles, tampoco misiones que provengan de otra zona y abran misiones allí.

https://ibb.co/MgtcCw0

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
