### ISSUE TITLE
Npc Mil Agujas bug

### ISSUE THREAD

**Issue by Therowes** [athenaswow/BugTracker-Athenas-WoW#619]
PJ:Gekyo Picaro 85 Alianza
Discord : ֆօʊʟ z0#9388

NPC Intargeteable : En mil agujas,cuando uno se encuentra leveleando hay un npc llamado Brienna Brillaestrella este mismo le entrega una mision la cual es -Juntos de nuevo- ( https://es.wowhead.com/quest=27275/juntos-de-nuevo) este mismo lo lleva a entregar dicha quest al npc Centinela-de-feralas. Aca concluye el problema ya que este npc si bien en el mapa aparece con el logo de entregar la quest,Al momento de clickearlo no hay ninguna interaccion, por ende no deja entregar la quest y seguir con su larga cadena de misiones la cual necesito que este npc sea arreglado cuanto antes 

VIDEO 

https://user-images.githubusercontent.com/79948831/109738841-5d4cc800-7ba7-11eb-9f62-9727252da07b.mp4

IMAGEN Y UBICACION DEL NPC 
![imagen_2021-03-02_223529](https://user-images.githubusercontent.com/79948831/109738970-97b66500-7ba7-11eb-945b-7a9c2d36eb4f.png)
![WoWScrnShot_030221_223504](https://user-images.githubusercontent.com/79948831/109738995-a0a73680-7ba7-11eb-9d62-e4eaca64a650.jpg)

Espero se pueda solucionar desde ya muchas gracias

**Comment by athenaswow** [comment]
Ya fue corregido, el cambio se aplicara pronto.
