### ISSUE TITLE
Misión: compañeros de viaje (segundo reporte por daño diferente)

### ISSUE THREAD

**Issue by wilbm** [athenaswow/BugTracker-Athenas-WoW#620]
Pj: Bathory
Discord: questioner#2968

En el reporte anterior, mostraba cómo al finalizar una misión de cadena, esta misión "Compañeros de viaje" no aparecía automáticamente. Un GM, al ver que ya había reportado acá, me puso en la misión, pero no se deja completar:

https://ibb.co/0m14Vyd

Ese NPC debería dejar completar la misión, es decir, debería unirse a la caravana, pero al darle clic no pasa nada.

Se supone que al completar "Compañeros de viaje" con Argus Altofaro [npc=45451], este debería dar la misión: "Caminos difíciles" [quest=27382], que curiosamente hacer parte de la cadena pero el NPC la da desde mucho antes, pero entonces no es posible avanzar a la que sigue en la cadena que es: "la pequeña pamela" [27383]

Misiones involucradas en el orden de la cadena:
* Compañeros de viaje: https://es.wowhead.com/quest=27381/compa%C3%B1eros-de-viaje (dos bugs, el primero ya reportado que no aparece, y el segundo: no se deja completar)
* Caminos difíciles: https://es.wowhead.com/quest=27382/caminos-dif%C3%ADciles (debería aparecer luego de completar compañeros de viaje, pero aparece mucho antes disponible)
* La pequeña Pamela: https://es.wowhead.com/quest=27383/la-peque%C3%B1a-pamela (no es posible acceder a esta misión)

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos dias.
