### ISSUE TITLE
Misión: Perder la cabeza... por unos cardos ID: 10570

### ISSUE THREAD

**Issue by wilbm** [athenaswow/BugTracker-Athenas-WoW#627]
Pj: Bathory
Discord: questioner#2968

Zona: Valle Sombraluna

El NPC que da la misión, te entrega este ítem: https://es.wowhead.com/item=30616/fardo-de-cardos-de-sangre que debes poner al final del puente, pero el objeto no se deja poner en ninguna ubicación: dice: requiere que estés al final del puente.

Se supone que al soltar el objeto se acercan dos mobs, uno de ellos se va y el otro llega a ver el objeto, en ese momento se aprovecha para matarlo y coger la carta que pide la misión, pero nada de esto funciona, de hecho ya hay unos elites en el sector que los he matado para ver si tal vez estaba de casualidad la carta en ellos, pero no dropean nada.

Foto del sector (también ensayé en el otro puente, pero en ningún lado se deja poner el objeto):

<a href="https://ibb.co/wB71jxn"><img src="https://i.ibb.co/RYNWdVX/Captura-de-pantalla-176.png" alt="Captura-de-pantalla-176" border="0"></a>

https://ibb.co/wB71jxn

**Comment by athenaswow** [comment]
Corregido, el cambio se agregara en unos días.
