### ISSUE TITLE
Misiones BUGS de Athenas wow Pandaria

### ISSUE THREAD

**Issue by zSlaYFeRz** [athenaswow/BugTracker-Athenas-WoW#635]
Pj: Zslayferz 

Mision:  Hacia la verde inmensidad
No me deja interactuar con los dracos para poder hacer la mision 

Mison:  Asegurar el perímetro
Al matar a los add que piden en la mision esos no cuenta para la Mision

GRACIAS.****

**Comment by rampague** [comment]
El reporte debe ir en bug tracker de pandaría https://github.com/athenaswow/Athenas-WoW-Pandaria-BugTracker
