### ISSUE TITLE
Problema Para Obtener Reputación Exaltado Eremitas

### ISSUE THREAD

**Issue by JMVillota** [athenaswow/BugTracker-Athenas-WoW#637]
Pj: Espartaco
Discord: Espartacø#7687
Facción: Los Eremitas
Muy buen día. Realice la obtención de los logros de los pergaminos que permiten subir a exaltado con la facción de los Eremitas que se encuentran en la zona Valle de la Flor Eterna. Se supone que a medida que se van completando los logros de los pergaminos debe llegar un mensaje con un ítem de misión que se entrega al NPC Eremita Cho (Valle de la Flor Eterna - 83.2, 29.6). El problema que tengo es que ya obtuve todos los logros y realicé todas las misiones de los pergaminos. Y no pude ser Exaltado con los Eremitas, ya que la única forma de hacerlo es a través de esas misiones, adjunto imágenes.

https://es.wowhead.com/faction=1345/los-eremitas
![WoWScrnShot_040621_191914](https://user-images.githubusercontent.com/82066417/113796326-a1863780-9714-11eb-9d71-b2ac4a715060.jpg)
![WoWScrnShot_040621_191814](https://user-images.githubusercontent.com/82066417/113796328-a2b76480-9714-11eb-8ff7-1d45218b918a.jpg)
![WoWScrnShot_040621_191826](https://user-images.githubusercontent.com/82066417/113796329-a2b76480-9714-11eb-886c-f27db1340663.jpg)
Agradezco la atención prestada.

**Comment by rampague** [comment]
Este reporte debe ir en bug tracker de pandaría https://github.com/athenaswow/Athenas-WoW-Pandaria-BugTracker
