### ISSUE TITLE
Misión bug recinto de los esclavos

### ISSUE THREAD

**Issue by dank251** [athenaswow/BugTracker-Athenas-WoW#638]
Nombre de pj: Luketh
Nick de discord: Dank#8477
https://es.wowhead.com/quest=29565/el-coraz%C3%B3n-de-la-cuesti%C3%B3n
Como se puede ver en el vídeo el jefe no da el item respectivo para la misión por lo cual no es posible completarse. (Pasó en repetidas ocasiones)
https://youtu.be/FgBU8opQSjo

**Comment by athenaswow** [comment]
Debes reportar esto en el Bug Tracker de Pandaria https://github.com/athenaswow/Athenas-WoW-Pandaria-BugTracker/issues
