### ISSUE TITLE
Totem Capacitador BUGG

### ISSUE THREAD

**Issue by Arolong47** [athenaswow/BugTracker-Athenas-WoW#640]
Cutestorm 
Crabbed#4552

El totem al invocarlo inicia una cuenta regresiva de 5seg, al llegar a 0 debe explotar y aturdir a todos lo enemigos en un radio de 8metros, adjunto video donde se evidencia que no funciona.
https://youtu.be/np76nmiS2EA

https://es.wowhead.com/spell=192058/t%C3%B3tem-capacitador#changelog

**Comment by athenaswow** [comment]
Debes reportar esto en el Bug Tracker de Pandaria https://github.com/athenaswow/Athenas-WoW-Pandaria-BugTracker/issues
