### ISSUE TITLE
Armas de Honor con precios equivocados

### ISSUE THREAD

**Issue by Infernose** [athenaswow/BugTracker-Athenas-WoW#641]
El nombre de mi PJ Principal es **Infernose**, Undead Mage Horda
Mi nombre de Discord **Uziell#1133**

El problema es el siguiente, algunas armas de honor, en el Vendor Lok'Nor Puño Sangre cuestan más de lo debido, algunas incluso más de 6.000 de honor, cosa que es imposible ya que el maximo permitido es de 4.000. Tampoco están a la venta las armas de Off-hand para casters, por lo que es imposible obtener armas para caster, ya que el bastón cuesta 6619 y no existen las Off-hand. 

Los precios deberían ser los siguientes:
- Bastones, Armas de dos manos, Armas de cazador **3.500** de honor  
- Dagas de _Caster_ y Varitas **2.250** de honor
- Dagas de _melee_ **1,750** de honor
- Off-Hand de _casters_ y _escudos_ **1.250** de honor
![WoWScrnShot_041521_123335](https://user-images.githubusercontent.com/82601975/114905434-f1d15980-9de6-11eb-8872-f26422585545.jpg)

**Comment by athenaswow** [comment]
Debes reportar esto en el Bug Tracker de Pandaria https://github.com/athenaswow/Athenas-WoW-Pandaria-BugTracker/issues
