### ISSUE TITLE
( Npc ) Duplicado - Werg Filo Grueso

### ISSUE THREAD

**Issue by Dokho0** [athenaswow/BugTracker-Athenas-WoW#643]
Pj Principal : Dokho
Usuario Discord : Dokho#838

Link Wowhead :
https://es.wowhead.com/npc=12943/werg-filo-grueso#screenshots:id=605281

Error : El Npc esta duplicado y creo que el impostor es la X
https://ibb.co/6JC9Tgh

Video que puede ayudar :  min 0:35
https://www.youtube.com/watch?v=fHoNOMMPKt8

Al principio del video bajo la carpa morada : min 0:3 
https://www.youtube.com/watch?v=ysHtDWWatgs

**Comment by athenaswow** [comment]
El duplicado no fue encontrado.
