### ISSUE TITLE
( Npc ) Duplicado - Sacerdotisa de las Sombras Vandis

### ISSUE THREAD

**Issue by Dokho0** [athenaswow/BugTracker-Athenas-WoW#644]
Pj Principal : Dokho
Usuario Discord : Dokho#838

Link Wowhead :
https://ptr.wowhead.com/npc=11055/shadow-priestess-vandis

Error : La duplicada es la X
https://ibb.co/kxGbyp3
https://ibb.co/Sn6rML8

Video que puede ayudar : En el aparece la npc al principio del video dando la misión.
https://www.youtube.com/watch?v=ysHtDWWatgs

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
