### ISSUE TITLE
Buzones Duplicados !! 

### ISSUE THREAD

**Issue by Dokho0** [athenaswow/BugTracker-Athenas-WoW#645]
Pj Principal : Dokho
Usuario Discord : Dokho#838

Coordenadas Buzones duplicados 

* Ciudad de Lunargenta :
1-  67.68, 29.38  https://ibb.co/zPQVt9j
2-  71.44, 75.04  https://ibb.co/wz2mC98
3-  71.53, 79.16  https://ibb.co/LzSZ11b
4-  58.77, 60.91  https://ibb.co/GxFhPMy

* Tierras Fantasma 
Tranquillien : 
1-  47.68, 31.19  https://ibb.co/L03mpMj

**Comment by athenaswow** [comment]
Procura compartir capturas y pruebas mas concretas por favor

**Comment by Dokho0** [comment]
Listo actualice el post con las capturas de imagen de todos los buzones que encontré ... por ahora !!  .. c_c

**Comment by athenaswow** [comment]
![image](https://user-images.githubusercontent.com/50283962/119060240-6cb60300-b997-11eb-8cb5-a382f3958505.png)
no me permite abrir sus capturas.
