### ISSUE TITLE
( Npc ) Duplicado - Presagista Balthazad

### ISSUE THREAD

**Issue by Dokho0** [athenaswow/BugTracker-Athenas-WoW#646]
Pj Principal : Dokho
Usuario Discord : Dokho#838

Link Wowhead :
https://www.wowhead.com/npc=10879/harbinger-balthazad

Error : Trate de tomarle fotos a los dos al mismo tiempo pero están en distintas zonas ya que el npc se supone que camina.
En la foto se ve como están marcados los dos a los lados de la foto.
https://ibb.co/mRPGHQ5

Calavera : https://ibb.co/C1Qhqf0  ( 67.87, 47.46 ) 
X : https://ibb.co/jTNns51  ( 65.18, 33.22 ) 

Si no están en esas coordenadas el npc se movió ya que camina.

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
