### ISSUE TITLE
( Npc ) Duplicado - Burkrum

### ISSUE THREAD

**Issue by Dokho0** [athenaswow/BugTracker-Athenas-WoW#647]
Pj Principal : Dokho
Usuario Discord : Dokho#838

Link Wowhead :
https://www.wowhead.com/npc=6028/burkrum

Error : El Real es la calavera y el duplicado es la X.
https://ibb.co/K9LrTdx

Videos que pueden ayudar : 
Min 0:28 no se ve el que esta afuera
https://www.youtube.com/watch?v=qww7iJhrLqc

Min 0:13 se puede ver el Npc dentro
https://www.youtube.com/watch?v=iUdTOQiHQYA

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
