### ISSUE TITLE
( Npc ) Duplicado - Qeeju

### ISSUE THREAD

**Issue by Dokho0** [athenaswow/BugTracker-Athenas-WoW#648]
Pj Principal : Dokho
Usuario Discord : Dokho#838

Link Wowhead :
https://es.wowhead.com/npc=15131/qeeju

Error : El Duplicado es la X.
https://ibb.co/LpRKWVd

Video : Se ve la Ubicación del Npc. 
https://www.youtube.com/watch?v=qww7iJhrLqc ( Min 0:28 )

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos dias.
