### ISSUE TITLE
Mineros Duplicados !!

### ISSUE THREAD

**Issue by Dokho0** [athenaswow/BugTracker-Athenas-WoW#649]
Pj Principal : Dokho
Usuario Discord : Dokho#838

Lugar : Puesto del hachazo  - vallefresno ( 72.33, 57.45 )

Error : Se ven dos mineros en el mismo puesto ( Prácticamente toda la cueva ) y solo debería ser 1 como se ve en el video.
https://www.youtube.com/watch?v=qww7iJhrLqc

**Comment by athenaswow** [comment]
necesitamos mas información, pruebas del fallo mas detallado por favor

**Comment by Dokho0** [comment]
A lo que me refiero es que respawnean dos mineros en el mismo puesto y solo debería ser 1 en cada puesto , haciendo ver mas Npc (Mineros) de la cuenta. 
Toda la cueva esta asi.
Fotos : 
https://ibb.co/4ghrRnr
https://ibb.co/P4KrPTG
https://ibb.co/sgNbvgY
https://ibb.co/qmbGzrs

Lo normal seria como se ve en los videos. 
Otro video donde se ve los mismo https://www.youtube.com/watch?v=XZxsq9kGqhQ

**Comment by athenaswow** [comment]
Corregido los cambios se aplicaran en unos días.
