### ISSUE TITLE
Problema al entregar misión

### ISSUE THREAD

**Issue by tadsuro** [athenaswow/BugTracker-Athenas-WoW#65]
Tadsuro
gatsushi

Misión: Sacudir el mercado.
https://www.youtube.com/watch?v=8-w-AlMguFQ
a tomar la misión de unos planos en un barco del puerto esta nos debe de dirigir a hablar con un Goblin: SUPERVISOR PANTOQUE. y luego iniciar un combate, para posteriormente entregar la misión al NPC: Señor de la guerra Krogg. (para continuar con la cadena de misiones hacia tierras crepusculares LvL 84-85)

como funciona en el servidor:
La misión se auto completa y aparece el icono de entrega ahí mismo, sin que se puede entregar al NPC: Señor de la guerra Krogg. Ni al pergamino del cual se tomo la misión.

no se puede entregar en ninguna de las 2 localizaciones 
![WoWScrnShot_121619_190538](https://user-images.githubusercontent.com/58959391/70951922-170b5780-203b-11ea-837b-82a14df383a8.jpg)
![WoWScrnShot_121619_190632](https://user-images.githubusercontent.com/58959391/70951936-1f639280-203b-11ea-86e5-a7e4aedbe9a8.jpg)

**Comment by athenaswow** [comment]
corregido.
