### ISSUE TITLE
( Npc ) Duplicado - Kranal Fiss

### ISSUE THREAD

**Issue by Dokho0** [athenaswow/BugTracker-Athenas-WoW#650]
Pj Principal : Dokho
Usuario Discord : Dokho#838

Link Wowhead :
https://ptr.wowhead.com/npc=5907/kranal-fiss

Error : El que anda marcado con la X es el duplicado.
https://ibb.co/MD8qbQh

Video : Al principio del video se ve la ubicación del npc.
https://www.youtube.com/watch?v=KE14dmPfzl0

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
