### ISSUE TITLE
( Npc ) Duplicado - Supervisor Asas (rare)

### ISSUE THREAD

**Issue by Dokho0** [athenaswow/BugTracker-Athenas-WoW#651]
Pj Principal : Dokho
Usuario Discord : Dokho#838

Link Wowhead :
https://es.wowhead.com/npc=5835/supervisor-asas#english-comments

Error : Como se ve en la imagen es el mismo rare dos veces en el mismo sitio.

Foto : Ubicación ( 56.73, 19.35 )
https://ibb.co/x534XsP

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
