### ISSUE TITLE
Presteza ancestral.

### ISSUE THREAD

**Issue by Lalan5** [athenaswow/BugTracker-Athenas-WoW#653]
Pieck - Lalan#3779
Wowhead no tiene el resultado exacto para esta habilidad.
Adjunto foto de la habilidad en juego.
https://imgur.com/a/cPUGkSP
La habilidad pasiva del talento presteza ancestral no da el buff que debería.

**Comment by athenaswow** [comment]
Esto debe estar reportado en el bug tracker de pandaria. https://github.com/athenaswow/Athenas-WoW-Pandaria-BugTracker/issues
