### ISSUE TITLE
( Npc ) Duplicado - Jinar'Zillen

### ISSUE THREAD

**Issue by Dokho0** [athenaswow/BugTracker-Athenas-WoW#655]
Pj Principal : Dokho
Usuario Discord : Dokho#838

Link Wowhead :
https://es.wowhead.com/npc=11317/jinarzillen

Error : Duplicado.
https://ibb.co/zfM08d0

Al Principio del video se ve el Npc
https://www.youtube.com/watch?v=UigRwA0QMAk

**Comment by athenaswow** [comment]
Corregido, El cambio se aplicara en unos días.
