### ISSUE TITLE
( Npc ) Duplicado - Skarr el Roto ( Rare )

### ISSUE THREAD

**Issue by Dokho0** [athenaswow/BugTracker-Athenas-WoW#656]
Pj Principal : Dokho
Usuario Discord : Dokho#838

Link Wowhead :
https://es.wowhead.com/npc=11498/skarr-el-roto#drops

Error : El Npc esta duplicado y se encuentra en dos partes al mismo tiempo donde suele respawnear. ( Se puede ver que la hora del juego en la parte de abajo derecha solo transcurrió un minuto para ir de Npc en Npc ). Digo esto para resaltar que las fotos fueron tomadas el mismo día en el mismo instante.

1- https://ibb.co/hgvrfdg
https://ibb.co/F0DrMRV

2- https://ibb.co/10BVDZP
https://ibb.co/zHpjbZS

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
