### ISSUE TITLE
( Npc ) Duplicado - Lakota Son del Viento

### ISSUE THREAD

**Issue by Dokho0** [athenaswow/BugTracker-Athenas-WoW#657]
Pj Principal : Dokho
Usuario Discord : Dokho#838

Link Wowhead :
https://es.wowhead.com/npc=45442/lakota-son-del-viento

Error :  La duplicada es la X. 
https://ibb.co/n3gZCrP
https://ibb.co/YyGLvg3

La verdadera es la que esta dentro de la cueva como muestra en los videos.
https://www.youtube.com/watch?v=J--bMR7khG8  ( Min 1:27 )
https://www.youtube.com/watch?v=dTYW2GYEIUk ( Min 1:00 )

**Comment by athenaswow** [comment]
El problema no fue encontrado trata de resolver el error en las capturas no me salen.
