### ISSUE TITLE
( Npc ) Duplicado - Arnak Tótem Siniestro

### ISSUE THREAD

**Issue by Dokho0** [athenaswow/BugTracker-Athenas-WoW#658]
Pj Principal : Dokho
Usuario Discord : Dokho#838

Link Wowhead :
https://ptr.wowhead.com/npc=45438/arnak-grimtotem

Error : El Duplicado es el que no es elite ( X )
https://ibb.co/PNfcZtr

El verdadero es el elite como muestra en los videos
https://www.youtube.com/watch?v=59ZGxPSWRXU ( Min 0:45 )
https://www.youtube.com/watch?v=lzLxbgjnVRA ( Min 2:40 )

**Comment by athenaswow** [comment]
corregido, el cambio se aplicara en unos días.
