### ISSUE TITLE
( Npc ) Duplicado - Zanara

### ISSUE THREAD

**Issue by Dokho0** [athenaswow/BugTracker-Athenas-WoW#659]
Pj Principal : Dokho
Usuario Discord : Dokho#838

Link Wowhead :
https://es.wowhead.com/npc=9552/zanara

Error : la Duplicada es la que esta sentada en la hoguera
https://ibb.co/DKGY7cc

Video : Acá se ve como al lado de la hoguera no hay nada y la verdadera esta debajo de la carpa roja al lado del tauren.
https://www.youtube.com/watch?v=-ql4dYr1DX4 ( Min 1:43 )
https://www.youtube.com/watch?v=ku9d-U2eg0o ( Min 0:56 )

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
