### ISSUE TITLE
( Npc ) Duplicado - Kresh

### ISSUE THREAD

**Issue by Dokho0** [athenaswow/BugTracker-Athenas-WoW#660]
Pj Principal : Dokho
Usuario Discord : Dokho#838

Link Wowhead :
https://es.wowhead.com/npc=3653/kresh

Error : El Duplicado es la ( X ). El verdadero debe recorrer el pasillo de agua como se muestra en el video.
https://ibb.co/Yjg5b10

Video : Acá se ve como la tortuga va caminando el pasillo de agua.
https://www.youtube.com/watch?v=6uwYCC4ysXE ( Min 3:39 )
https://www.youtube.com/watch?v=9635-3UOc54  ( Min 1:40 )

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
