### ISSUE TITLE
( Npc ) Duplicado y Mal ubicado - Lady anacondra

### ISSUE THREAD

**Issue by Dokho0** [athenaswow/BugTracker-Athenas-WoW#661]
Pj Principal : Dokho
Usuario Discord : Dokho#838

Link Wowhead :
https://es.wowhead.com/npc=3671/lady-anacondra

Error : Sale duplicada y aparte no esta en el sitio que le corresponde ya que es uno de los bosses de esta mazmorra y su ubicación se encuentra en el mapa ( la calavera roja empezando la mazmorra ) lado izquierdo.
https://ibb.co/bJTG4Zb
https://ibb.co/h9SVZCt
https://ibb.co/WnGpzpw
La Ubicación correcta es donde esta el cuadrado azul.
https://ibb.co/W6StX8P

Videos que lo demuestran : 
https://www.youtube.com/watch?v=x6NIxwcxfmI
https://www.youtube.com/watch?v=OJNRm7gVPkc

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
