### ISSUE TITLE
( Npc ) Duplicado - Lord Serpentis

### ISSUE THREAD

**Issue by Dokho0** [athenaswow/BugTracker-Athenas-WoW#662]
Pj Principal : Dokho
Usuario Discord : Dokho#838

Link Wowhead :
https://es.wowhead.com/npc=3673/lord-serpentis

Error : Sale Duplicado siendo Uno de los bosses de la mazmorra.
https://ibb.co/7CJdFRJ

Video : 
https://www.youtube.com/watch?v=CaLWcrieti0

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
