### ISSUE TITLE
( Npc ) Duplicado - Mutanus el Devorador ( Boss )

### ISSUE THREAD

**Issue by Dokho0** [athenaswow/BugTracker-Athenas-WoW#663]
Pj Principal : Dokho
Usuario Discord : Dokho#838

Link Wowhead :
https://es.wowhead.com/npc=3654/mutanus-el-devorador

Error : Al entrar  a la mazmorra e ir a la ubicación del ultimo boss esta el boss que no corresponde ( X ) y no debería estar ahi, ya que si uno completa la mazmorra matando los demas jefes al activar el npc tauren de la entrada toca escoltarlo hasta la misma ubicación del boss y termina invocando otro que seria el verdadero. ( Calavera ).
https://ibb.co/vJfV99J
https://ibb.co/zbF3fcx ( el Npc X es el muerto, toco matarlo por que el tauren lo ataco )

En pocas palabras no debería estar el boss al entrar a la mazmorra sin matar los minibosses primero y yendo activar el npc tauren para escoltarlo y que aparezca al llegar a su sitio.
https://ibb.co/rHVPf8r ( Npc que se tiene que escoltar )
https://ibb.co/xgW5QZz ( Acá se ve la opción para hablarle y poderlo escoltar )
https://ibb.co/7ptnJfg ( Npc activado )
https://ibb.co/7SDBxCz ( Escoltando )
https://ibb.co/fkPLmjh ( Hizo el ritual para despertar a naralex y salió el otro boss )

Video que explica lo que digo
https://www.youtube.com/watch?v=IjYyn6pC7S8

**Comment by athenaswow** [comment]
Todos los links de las imágenes que compartes están rotos.

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
