### ISSUE TITLE
( Npc ) Triplicado - Tritesta el Azotador ( Rare )

### ISSUE THREAD

**Issue by Dokho0** [athenaswow/BugTracker-Athenas-WoW#664]
Pj Principal : Dokho
Usuario Discord : Dokho#838

Link Wowhead :
https://es.wowhead.com/npc=3652/tritesta-el-azotador

Error : Sale tres veces en el mismo sitio siendo un rare. 
( Ubicación : afuera de la mazmorra cueva de los lamentos ) ( 43.11, 64.25 )
https://ibb.co/sv0K1WC

Video : Muestra su ubicación Exacta ( Min 1:54 ) 
https://www.youtube.com/watch?v=ZnlJ6efrUe4

**Comment by athenaswow** [comment]
Corregido, el cambio será aplicado en unos días.
