### ISSUE TITLE
BUG EN TOL BARAD (No hay angeles de resureccion para resucitar, cuando no encuentras el cadaver)

### ISSUE THREAD

**Issue by Urminol767** [athenaswow/BugTracker-Athenas-WoW#669]
![image](https://user-images.githubusercontent.com/83848309/117520581-2b8e1e00-afa9-11eb-8f62-a8d818881d5f.png)
Hola, soy Shadopan un panda horda y me he quedado barado en tol barad, en la forma fantasmal sin poder resucitar.
No hay manera de econtrar un angel de resurreccion alli, pero tampoco puedo desatascar el pj desde la pagina.
Haber si pueden solucionar ese problemilla, porque de momento me toca esperar sentado.
Gracias, y perdonen las molestias.

**Comment by athenaswow** [comment]
Debes reportar esto en el Bug Traker de pandaria
