### ISSUE TITLE
¡Los Drakkari! no necesitan elementales de agua

### ISSUE THREAD

**Issue by kadar0357** [athenaswow/BugTracker-Athenas-WoW#671]
PJ: Kaelthalas
Discord: Bullshet#4595

Zona: Zul'Drak
Reporto daño en la misión: ¡Los Drakkari no necesitan elementales de agua! ID = 12562 https://es.wowhead.com/quest=12562/los-drakkari-no-necesitan-elementales-de-agua 
Se debe matar unos npc https://wow.zamimg.com/uploads/screenshots/normal/109698-los-drakkari-no-necesitan-elementales-de-agua.jpg https://wow.zamimg.com/uploads/screenshots/normal/313790-los-drakkari-no-necesitan-elementales-de-agua.jpg

Comparto algunas imagenes de donde deberían de estar los npc:
 https://ibb.co/XVsr8bJ
https://ibb.co/477Pwhw

**Comment by athenaswow** [comment]
No se encontró el problema.
![image](https://user-images.githubusercontent.com/50283962/119059928-e26d9f00-b996-11eb-8407-25b39010af51.png)
