### ISSUE TITLE
Mision [Un Disfraz Apropiado]

### ISSUE THREAD

**Issue by Deadmean11AE** [athenaswow/BugTracker-Athenas-WoW#672]
PJ Tank: Deadmean
Discord: Deadmean Official#2388

Hola Principalmente La Cadena De Misiones Que Estoy Llevando a Cabo De La [Empuñadura Maltrecha] No Ah Tenido Ningun Tipo De Dificultad Ya Que Las Primeras Misiones Funcionan Ala Perfeccion,, Pero Al Llegar Ala Mision 4 [Disfraz Apropiado] :  https://www.youtube.com/watch?v=24mVt3rbCP4  <---- Cuando Estas En La Terraza Con El NPC [Shandy Lustre Brillo] Que Esta En Un Balcon En Dalaran Le Das Click Para Prestar Su Ayuda a Cambio De Un [Tabardo Prestado] y Lamentablemente No Hace Nada.. 

En El Video Anterior Veras Lo Que Deberia Hacer Una Vez Le Des Click Al NPC Pero Lastimosamente Esta Bugeada La Mision y No Podre Terminar La Cadena De Misiones De La [Empuñadora Maltrecha] AQUI EL VIDEO : https://www.youtube.com/watch?v=24mVt3rbCP4

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.
