### ISSUE TITLE
Misiones no entregables Ahh´Qiraj

### ISSUE THREAD

**Issue by jeiiver** [athenaswow/BugTracker-Athenas-WoW#675]
Pj Pandaria: Blackframe
Id Discord: Temate#0390

Buenas noches
Estoy reportando unas misiones que no se dejan entregar en la banda Ahh´Qiraj para la clase cazador, tengo los ítems necesarios para las misiones y no me es posible entregar las misiones teniendo los ítems.
Teniendo reputacion exaltada con los  Linaje de Nozdormu
Adjunto fotos links de las misiones para ver si podemos arreglarlo muchas gracias y buena noche 

1. https://es.wowhead.com/quest=8659/los-espaldares-de-asediador   = Esta mision teniendo los items no puedo entregarla
2. https://es.wowhead.com/item=21370/camisote-de-asediador  = Esta mision teniendo los items no puedo entregarla
3. https://es.wowhead.com/item=21368/leotardos-de-asediador  = Esta mision teniendo los items no puedo entregarla
4. https://es.wowhead.com/item=21365/guardapi%C3%A9s-de-asediador = Esta mision teniendo los items no puedo entregarla}

Excepcion
5. https://es.wowhead.com/quest=8657/la-diadema-de-asediador = Esta mision si me permitio entregarla 

![WoWScrnShot_060821_205905](https://user-images.githubusercontent.com/85595640/121280846-8662b000-c89c-11eb-9ee6-f764c531e303.jpg)
![WoWScrnShot_060821_205918](https://user-images.githubusercontent.com/85595640/121280849-8793dd00-c89c-11eb-96ba-2e8f9ecbacc1.jpg)
![WoWScrnShot_060821_205832](https://user-images.githubusercontent.com/85595640/121280851-882c7380-c89c-11eb-9f5c-f4d939150072.jpg)
![WoWScrnShot_060821_205853](https://user-images.githubusercontent.com/85595640/121280853-88c50a00-c89c-11eb-8a49-ff356d4ac215.jpg)
![WoWScrnShot_060821_205859](https://user-images.githubusercontent.com/85595640/121280855-895da080-c89c-11eb-9e4c-07f9c1d37401.jpg)

**Comment by athenaswow** [comment]
Corregido, el cambio se aplicara en unos días.

**Comment by jeiiver** [comment]
Buenas dias señor gm mira que se solucionaron las misiones pero faltaron 2 ó no se si se arreglaran de a poco?
