### ISSUE TITLE
NPC faltante en Orgrimmar

### ISSUE THREAD

**Issue by lacraso** [athenaswow/BugTracker-Athenas-WoW#678]
Personaje principal: Yeika
Nombre de usuario en Discord: lacraso#2361
Link del npc que falta: https://es.wowhead.com/npc=58155/rugok 
El Npc Rugok <Intendente de justicia de legado> no se encuentra en Orgrimmar simplemente no esta en donde debería
![Uploading rugok.png…]()

**Comment by athenaswow** [comment]
![image](https://user-images.githubusercontent.com/50283962/126409055-3f149fd1-64d4-4634-847c-26b5621f22a3.png)
