### ISSUE TITLE
Guardián bug del paladín II Represión 

### ISSUE THREAD

**Issue by Cuevsx** [athenaswow/BugTracker-Athenas-WoW#69]
https://youtu.be/FoRP4mCF3s0 
Poder:
https://es.wowhead.com/spell=86659/guardián-de-los-antiguos-reyes

------------------------------------------------------------------------------------------------------------------------
Lo explico muy claro con los diálogos en el vídeo pero con cada ataque el de buff de fuerza que da el guardián debe reiniciarse con cada ataque, cada vez que pegamos con el guardián activo y al disiparse o acabarse debe dejar de contarnos ese buff y debe empezar a contar para desaparecer no desaparecer de golpe así como lo vieron.
EN EL VÍDEO ESTA TODO !!!!!!!!!

**Comment by ghost** [comment]
No esta bien el reporte ya que lo que se expone de esta habilidad en Athenas wow se encuentra correcta, aquí esta la información de la habilidad para el parche 4.3.4 (https://cata-twinhead.twinstar.cz/?spell=86150) bueno si lees bien lo que dice al final de la habilidad: Tras 30seg o al morir tu guardián liberarás Furia antigua. que infringirá 514p. de daño a 514p. por aplicación de poder antiguo (buffo que se acumula aumentando la fuerza cada vez que damos un golpe). dividido entre todos los objetivos en un radio de 10m. las cargas de poder antiguo no tienen por que quedarse después de que el guardián desaparece.

**Comment by Cuevsx** [comment]
Si según tú esta mal, por que tienen tiempos separados la fuerza y el guardián? 
El reporte esta bien cuando desaparece el guardián simplemente debe acabar el buffo de fuerza por tiempo no por que se vaya el guardián

**Comment by ghost** [comment]
No, cuando activas el guardián y das golpes obtienes el buffo Poder antiguo que es el buffo de aumento de fuerza, bien pues como te anexé en el comentario anterior si lees bien la habilidad esta dice que cuando el tiempo del guardián finalicé las cargas de poder antiguo se convierten en daño a todos los objetivos en un radio de 10m, no se deben quedar a que pase el tiempo.

**Comment by athenaswow** [comment]
Elaborar un nuevo reporte si siguen teniendo este problema.
