### ISSUE TITLE
Misión Bug: Into Unrelenting Flame

### ISSUE THREAD

**Issue by JBBallini** [athenaswow/BugTracker-Athenas-WoW#695]
PJ Principal: Mistroy
Discord: Porokiin#9395

Descripción:
La misión pide hablar con la NPC Aggra en en Infralar para pedir una teleportación a Tierra del Fuego. La teleportación funciona correctamente. Una vez en el sitio te pide entregar la misión a Aggra en ese lugar pero, la NPC no se puede encontrar en ningun lado (me encargue de revisar casa sitio de la zona y no la pude encontrar) y esto impide que se pueda completar la mision y se interrumpe la cadena de misiones.

Video de mision bug: https://www.youtube.com/watch?v=d4XQb1VrDZ0
Video de mision funcionando correctamente: https://www.youtube.com/watch?v=uejdy4m_u70
Link de WoWHead: https://www.wowhead.com/quest=29338/into-unrelenting-flame

**Comment by athenaswow** [comment]
Se esta trabajando en frente de magma.
