### ISSUE TITLE
Lluvia de fuego brujo destruccion

### ISSUE THREAD

**Issue by Nero-Is-Blazing** [athenaswow/BugTracker-Athenas-WoW#696]
Pj main: Nero
Discord: NeroS#4598

descripcion: es simple, la lluvia de fuego deberia generar ascuas ardientes asi no este golpeando nada, y pues basicamente no lo hace, solo genera ascuas si esta golpeando algo, claro esta que la lluvia de fuego no es que genere una cantidad exagerada de ascuas pero quemando mana con full lluvia en cuestion de 4 a 5 segundos deberia cargar 1 ascua.

tome foto usando lluvia de fuego a quema mana, para demostrar que no sube ni un poco ni genera un pequeño porcentaje, no se si fue una decision por parte de los desarrolladores o si es un bug, pero me parecio interesante reportarlo.

https://www.youtube.com/watch?v=K7RTpdsQoWc

en esta guia a pesar de la calidad jajaj demuestra como lluvia de fuego carga ascuas.

![WoWScrnShot_081021_202212](https://user-images.githubusercontent.com/83606891/128955812-5f2d6291-43b1-4181-b1e5-7ad47203d337.jpg)

**Comment by Revly** [comment]
Este es el Bugtracker del Cata.

aqui t dejo el link del <a href="https://github.com/athenaswow/BugTracker-Athenas-WoW-Pandaria-/issues" rel="nofollow"> BugTracker Panda <a/>
