### ISSUE TITLE
Shadow Walk y Shadow Ambusher en Pozo de la Eternidad

### ISSUE THREAD

**Issue by Topen01** [athenaswow/BugTracker-Athenas-WoW#7]
Topen
Topen#1425

https://www.youtube.com/watch?v=VzJQNH309Lw

In Well of Eternity, after killing the first mob, you find Illidan and he will give you a buff called “Shadow Walk”(spell=103020) the spell says that after you do or receive damage you will get the buff "Shadow Ambusher”(spell=103018) however the duration of it is like 0.5 seconds , the duration of “Shadow Ambusher” depends on the amount of stacks of “Shadow Walk” which must be 1 second per stack, thats why in the last clip the shaman got 100% crit chance, and if you look closely to his buffs, you will see that Shadow Ambusher last for 30 seconds at 30 stacks.

**Comment by athenaswow** [comment]
Si el fallo aun persiste por favor elaborar un nuevo reporte.
