### ISSUE TITLE
Misión de Mazmorra: Limpiar Drak'tharon (Fortaleza de Drak'tharon)

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#70]
Nombre de personaje principal: Skala
Usuario de discordia: JorDaNN # 5575
Descripción del error: Como se ve en el vídeo tengo todo lo necesario para invocar a Drakuru, pero aún estando en frente del Blandón de drakuru no me deja invocarle. Esta misión es necesaria para 2 logros que suceden en zul drak,
Misión necesaria para logro: https://es.wowhead.com/achievement=1596/gur%C3%BA-de-drakuru
La otra misión funciona correctamente ya que la he completado
Misión wowhead: https://es.wowhead.com/quest=12238/limpiar-draktharon
Athenaswow: https://www.youtube.com/watch?v=V04tj-pGcH4&feature=youtu.be
Como debería funcionar: Minuto 3:30 https://www.youtube.com/watch?v=SHodJ-MRUms

**Comment by athenaswow** [comment]
corregido a hora funcionara 100% blizzlike.
