### ISSUE TITLE
Bugs de brujo 4.3.4

### ISSUE THREAD

**Issue by lalitop12** [athenaswow/BugTracker-Athenas-WoW#704]
Pj principal: Alisei
usuario de discord: no tengo
 
Problema: la pet de brujo esta bug, al usar la montura desaparece lo que debe de pasar es que la pet camine contigo no desaparezca esto genera un gran desbalance puesto que enlace de alma se quita y tienes que estar activándolo,
![image](https://user-images.githubusercontent.com/89762551/131285860-235bf171-c93f-4527-8993-4e45e94ddd57.png)
![image](https://user-images.githubusercontent.com/89762551/131285915-03b4088a-3d06-4322-9df8-44be0f484f19.png)
como debe de funcionar: https://www.youtube.com/watch?v=_UIiaVIwl1M&t=594s  minuto8:58

**Comment by athenaswow** [comment]
Gracias por tu reporte, pero ya fue reportado aquí https://github.com/athenaswow/BugTracker-Athenas-WoW/issues/564
