### ISSUE TITLE
Misión: Diario de Mikhail (Colinas Pardas)

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#71]
Nombre de personaje principal: Skala
Usuario de discordia: JorDaNN # 5575
Descripción de la situación: Como ya he reportado antes, este tipo de misiones de drop necesitan una misión previa para que el drop sea alto. Sin embargo, una vez completada la misión previa e irse a hacer otra cosa, el drop es bajisimo. Solo hay que leer los comentarios de wowhead a las personas quejandose. Si pudieran verificar o revisar el drop de este item para que sea más cómodo para todos.
Misión wowhead: https://www.wowhead.com/quest=12423/mikhails-journal
item: https://www.wowhead.com/item=37830/mikhails-journal

**Comment by athenaswow** [comment]
corregido, a hora sera drapeado al 100%.
