### ISSUE TITLE
Bug Misiones se completan solas

### ISSUE THREAD

**Issue by ErLusho** [athenaswow/BugTracker-Athenas-WoW#712]
Lushordemort
Erlusho#9245

Buenas, hoy entre al servidor de pandaria después de mucho tiempo inactivo debido a problemas personales, y cuando entro a hacer unas misiones me di cuenta que las misiones se completaban solas sin necesidad de hacer nada, sin percatarme complete varias sin prestarle mucha atención pero me pareció muy raro ya que no vi ningún aviso al respecto, lo siento si no puedo adjuntar pruebas pero al parecer me banearon por completar esas misiones

**Comment by athenaswow** [comment]
https://github.com/athenaswow/BugTracker-Athenas-WoW-Pandaria-
