### ISSUE TITLE
Misión: Volver a descansar en paz (Fiordo alquilonal)

### ISSUE THREAD

**Issue by Skala101** [athenaswow/BugTracker-Athenas-WoW#74]
Nombre de personaje principal: Skala
Usuario de discord: JorDaNN#5575
Descripción del error: Pues como se ve en el vídeo no completa lo listado en la misión al usar el item que nos dan. Hay veces en que se tiene que buscar una ubicación específica en el juego para esto pero al parecer este no es el caso. Según wowhead esta misión es necesaria para abrir la cadena de misiones de este lugar y completar logro.
Misión wowhead: https://es.wowhead.com/quest=11568/volver-a-descansar-en-paz#comments
Athenaswow: https://www.youtube.com/watch?v=7KY4OooxOkQ&feature=youtu.be
Como debería funcionar: https://www.youtube.com/watch?v=W2EP58rfzd4

**Comment by athenaswow** [comment]
corregido.
