### ISSUE TITLE
Error Mision de Goblin

### ISSUE THREAD

**Issue by Zendezenit** [athenaswow/BugTracker-Athenas-WoW#78]
Hola! ¿Cómo les va? Espero que bien y felices fiestas!
Estoy teniendo un problema tecnico en cuanto a una mision en WoW.
La misión es "Rendios!" de la raza goblin
El problema, o mas bien el bug presente, es que "As" (El goblin al que hay que seguir para ir a buscar la rendicion del lider Naga)
No avanza, ni tampoco va la prole naga detras de él (Pensé que era normal, hasta que vi un video de como pasar la mision en youtube y ahi me percaté de que estaba bugeado)
Queria avisar de esto, debido a que no puedo avanzar en la mision, y por ende, no podré salir de la isla.
Desde ya, muchas gracias. <3

**Comment by Zendezenit** [comment]
me olvidé de publicar las screens, pido mil disculpas

![WoWScrnShot_122519_101139](https://user-images.githubusercontent.com/59227149/71446282-7256dd00-2700-11ea-9e1b-9b54c2bcde81.jpg)
![WoWScrnShot_122519_101147](https://user-images.githubusercontent.com/59227149/71446283-7256dd00-2700-11ea-8634-6aa9caf84987.jpg)
![WoWScrnShot_122519_101514](https://user-images.githubusercontent.com/59227149/71446284-7256dd00-2700-11ea-8754-7fe841be789f.jpg)
![WoWScrnShot_122519_101810](https://user-images.githubusercontent.com/59227149/71446285-72ef7380-2700-11ea-847b-51d4503895c3.jpg)
![WoWScrnShot_122519_101934](https://user-images.githubusercontent.com/59227149/71446287-72ef7380-2700-11ea-8b12-5fe3497516ec.jpg)

**Comment by athenaswow** [comment]
Esa misión no funciona correctamente pero se puede hacer, debes ir y matar al Npc y ya esta.
