### ISSUE TITLE
Misión diaria   (Destrucción del núcleo solar) Frente Magma

### ISSUE THREAD

**Issue by Salchipapas** [athenaswow/BugTracker-Athenas-WoW#79]
### Discord: Ameyal- Daniel#0481
**_Link  de la mision:_**
 https://cata-twinhead.twinstar.cz/?quest=29211

_**Descripción del problema:**_

La quest  Destrucción del núcleo solar con id  29211 que se encuentra ubicada  en frente magma, no hay interacción con el núcleo, por ello no se puede entregar  realizar la quest como corresponde. 

**_Link de como debería funcionar la misión:_**

https://www.youtube.com/watch?v=k3LpwhPQwWQ

_**Pruebas del mal funcionamiento.**_
### Recogida de mision.

https://ibb.co/NTPgbSt

### Interacción con el núcleo.

https://ibb.co/523yQYR

**Comment by pangolp** [comment]
Hola, la quest no funciona 100% igual que en el vídeo, pero al llegar al lugar puede encontrar núcleo y me dio como completada la misión. Te pido que la recibís y me avisas si es que sigue fallando.

![WoWScrnShot_012020_060538](https://user-images.githubusercontent.com/2810187/72713078-2191a300-3b4b-11ea-8e77-d428023c2909.jpg)

**Comment by athenaswow** [comment]
Todos los reportes de hyjal serán  cerrados ya que estoy trabajando en ese lugar desde cero logrando un mejor resultado en las cadenas de misiones, el parche se aplicara a mas tardar el 15 de abril del 2020.
