### ISSUE TITLE
Se puede dar duelo dentro de Fin de los Dias

### ISSUE THREAD

**Issue by Topen01** [athenaswow/BugTracker-Athenas-WoW#8]
Topen
Topen#1425

https://www.youtube.com/watch?v=LSwJ9TY46mk

Dentro de la mazmorra Fin de los Dias, en la zona donde nos enfrentamos con Eco Sylvanas (Ruby Drangonshrine) es posible hacer duelos, en Athenas wow entrar o salir de duelo reinicia todos tus CD's y te sube la vida y mana al 100%, justamente se suele usar esta mecánica para agilizar la limpiada de la mazmorra

**Comment by athenaswow** [comment]
Corregido.
