### ISSUE TITLE
Misión diaria  (Soportando el calor), Frente Magma

### ISSUE THREAD

**Issue by Salchipapas** [athenaswow/BugTracker-Athenas-WoW#80]
### Discord: Ameyal- Daniel#0481
**_Link  de la mision:_**
 https://cata-twinhead.twinstar.cz/?quest=29210

_**Descripción del problema:**_

La quest  Soportando el calor  con id  29210 que se encuentra ubicada  en frente magma, no hay interacción  con todas las 8 runas  solo hay disponibles cuatro , por ello no se puede completar las 8 runas, fuera de ello cuando uno entra a la cueva  no hace el primer check list  que es ingresar a la cueva.

**_Link de como debería funcionar la misión:_**

https://www.youtube.com/watch?v=l5fASoBU2pY

_**Pruebas del mal funcionamiento.**_
### Recogida de mision.

https://ibb.co/9Gy06pQ

### Interacción con la cueva

https://ibb.co/L615KMZ

### Interracion con las runas ( solo hay 4 disponibles)

 #https://ibb.co/0VpQrtr

**Comment by pangolp** [comment]
El crédito de haber entrado en la cueva se me otorgo, lo que no estoy seguro si las runas tienen alguna forma especial en ser activadas o igual el orden.

![WoWScrnShot_012020_061624](https://user-images.githubusercontent.com/2810187/72714066-da0c1680-3b4c-11ea-83e1-6a2556886eae.jpg)

**Comment by athenaswow** [comment]
Todos los reportes de hyjal serán  cerrados ya que estoy trabajando en ese lugar desde cero logrando un mejor resultado en las cadenas de misiones, el parche se aplicara a mas tardar el 15 de abril del 2020.
