### ISSUE TITLE
Frente Magma, bug  en  la corriente magma

### ISSUE THREAD

**Issue by Salchipapas** [athenaswow/BugTracker-Athenas-WoW#81]
Pj principal: Ameyal
Discord: Ameyal- Daniel#0481

Descripción del problema:

Bueno en Frente magma hay una parte en donde un tiene que bajar para recoger las misiones diarias de  la PNJ Thisalee Cuervo, uno hace las misiones normal, pero a la hora de salir supuestamente  la corriente que hay ahi, lo impulsa a uno hacia la parte superior para poder salir del frente magma, pero en este caso no hace nada, ni impulsa ni nada.

No encontre  un video donde se pueda evidenciar  el funcionamiento de la corriente pero adjunto   las pruebas de ubicacion del mismo.

Pruebas del mal funcionamiento.

Parte superior
https://ibb.co/b77YsKZ

Parte inferior ( no hay impulso hacia la parte superior)
https://ibb.co/X7KJrbS

**Comment by Salchipapas** [comment]
El problema como tal es de un  hechizo automatico llamado  Corriente térmica.


Link del hechizo.

https://es.wowhead.com/spell=101849/corriente-t%C3%A9rmica

 El cual no funciona.

**Comment by athenaswow** [comment]
Todos los reportes de hyjal serán  cerrados ya que estoy trabajando en ese lugar desde cero logrando un mejor resultado en las cadenas de misiones, el parche se aplicara a mas tardar el 15 de abril del 2020.
