### ISSUE TITLE
Misión Diaria (Un mal trago) Frente magma

### ISSUE THREAD

**Issue by Salchipapas** [athenaswow/BugTracker-Athenas-WoW#82]
Pj principal: Ameyal
Discord: Ameyal- Daniel#0481

Descripción del problema:

Bueno en Frente magma hay una mision llamada Un mal trago en la cual consiste en   atacar  al gran gusano, no se puede atacar debido a que el gusano es amistoso, por ello mismo no se puede completar la  misión.

Link mision en wowhead:

https://es.wowhead.com/quest=29263/un-mal-trago

Cómo debería funcionar:

https://www.youtube.com/watch?v=RqM3X77Snjg

Pruebas del mal funcionamiento.

https://ibb.co/MBvZtyz

**Comment by athenaswow** [comment]
Todos los reportes de hyjal serán  cerrados ya que estoy trabajando en ese lugar desde cero logrando un mejor resultado en las cadenas de misiones, el parche se aplicara a mas tardar el 15 de abril del 2020.
