### ISSUE TITLE
Misión Diaria ( Cierra los portales del fuego) Frente Magma

### ISSUE THREAD

**Issue by Salchipapas** [athenaswow/BugTracker-Athenas-WoW#83]
### Discord: Ameyal- Daniel#0481
**_Link  de la mision:_**
https://es.wowhead.com/quest=29143/cierra-los-portales-de-fuego

_**Descripción del problema:**_

En la quest  Cierra los portales del fuego con id  29143  que se encuentra ubicada  en frente magma, Cuando uno recibe la misión debe otorgar un  aura el cual lo persigue a uno para llevarlo al portal para  así poder cerrar el portal

**_Link de como debería funcionar la misión:_**

https://www.youtube.com/watch?v=jpjGCvQy1sU

_**Pruebas del mal funcionamiento.**_

### Recogida de misión.

https://ibb.co/80LF2xM

### Demostración de que no da el aura para cerrar el portal

https://ibb.co/Xk3vTSs

**Comment by athenaswow** [comment]
Necesito mas pruebas trata de subir un vídeo de como esta funcionando en athenas por favor.
