### ISSUE TITLE
Misión Diaria ( Al fuego) Frente Magma

### ISSUE THREAD

**Issue by Salchipapas** [athenaswow/BugTracker-Athenas-WoW#84]
### Discord: Ameyal- Daniel#0481
**_Link  de la mision:_**
https://es.wowhead.com/quest=29206/al-fuego

_**Descripción del problema:**_

En la quest  (Al fuego)  con id  29206  que se encuentra ubicada  en frente magma, Cuando uno recibe la misión  uno tiene que hablar con  un druida el cual abre espacio por el fuego que se encuentra allí, y uno debe protegerlo, cuando el sube debe sacar a un mob, el cual debemos darle muerte  para que nos abra otra zona para poder hacer las quest.

**_Link de como debería funcionar la misión:_**

https://www.youtube.com/watch?v=ROvMEeK_MI0

_**Pruebas del mal funcionamiento.**_

### Recogida de misión.

https://ibb.co/z2X5LDF

### Demostración de que el druida no abre camino por el fuego y sigue derecho

https://ibb.co/3NpXBSf

**Comment by athenaswow** [comment]
Todos los reportes de hyjal serán  cerrados ya que estoy trabajando en ese lugar desde cero logrando un mejor resultado en las cadenas de misiones, el parche se aplicara a mas tardar el 15 de abril del 2020.
