### ISSUE TITLE
Misiones  Interes en la cima  Aves Territoriales  Frente magma no se pueden  realizar ni testear

### ISSUE THREAD

**Issue by Salchipapas** [athenaswow/BugTracker-Athenas-WoW#85]
### Discord: Ameyal- Daniel#0481

_**Descripción del problema:**_

Cuando uno llega a la parte superior para coger las misiones para ir a  la cima pluma  de fuego se encuentran dos npcs ( Arthon son del viento, Morthis alasusurro) ellos entregan las siguientes misiones.

Interés en la cima 
link:
https://es.wowhead.com/quest=29287/inter%C3%A9s-en-la-cima
Aves territoriales
link
https://es.wowhead.com/quest=29296/aves-territoriales

El problema es cuando uno sube, hay unos vientos que lo impulsan a uno para realizar la quest, pero ellos no lo impulsan, osea no se puede hacer la mision. 

_**Pruebas del mal funcionamiento.**_

https://ibb.co/K223HWb

**Comment by Salchipapas** [comment]
El problema como tal es de un hechizo automatico llamado Corriente térmica.

Link del hechizo.

https://es.wowhead.com/spell=101849/corriente-t%C3%A9rmica

El cual no funciona.

**Comment by athenaswow** [comment]
Todos los reportes de hyjal serán  cerrados ya que estoy trabajando en ese lugar desde cero logrando un mejor resultado en las cadenas de misiones, el parche se aplicara a mas tardar el 15 de abril del 2020.
