### ISSUE TITLE
Cadena de misiones en Tanaris.

### ISSUE THREAD

**Issue by kevinQ28** [athenaswow/BugTracker-Athenas-WoW#87]
pj: Shoot / Zask  Discord: koreano28#8755

Estuve subiendo nivel hasta llegar a 45 omitiendo la zona de "Mil agujas", tomé la misión del cartel en Orgrimar para iniciar las misiones, me dirigí a Tanaris pero a la hora de entregar esta misión del cartel simplemente me dice que no reuno los requisitos para esa misión, de tal forma que no puedo continuar con las misiones de este lugar y me tocó subir 5 niveles matando mob y me pasó en 2 personajes distintos, hablé con una amiga y le pasó lo mismo con otro personaje de ella.

*Revisar el chat donde me dice que no cumplo los requisitos*

![WoWScrnShot_122919_121421](https://user-images.githubusercontent.com/59348190/71565074-2db8a200-2a70-11ea-8847-0c6daec88dad.jpg)

![WoWScrnShot_122919_121408](https://user-images.githubusercontent.com/59348190/71565076-3315ec80-2a70-11ea-81a6-54a57657bc03.jpg)

**Comment by athenaswow** [comment]
Corregido.
