### ISSUE TITLE
No puedo canjear la arma arrojadiza cata normal a elite (warrior)

### ISSUE THREAD

**Issue by leone30** [athenaswow/BugTracker-Athenas-WoW#88]
Buenas noches, lo que pasa que esta noche saque el 2.200 de elite pero al canjear los items, no puedo canjear la arma arrojadiza normal a la elite, ambas tienen el mismo nombre pero diferente imagen.
Discord: Gian#6576
Pj: Sudestada
https://imgur.com/a/NBKxlE1

**Comment by pangolp** [comment]
@leone30 se te cerro el tema porque es un bugtracker de errores sobre reparaciones, para reclamo de items y esas cosas, creo que el medio es otro, nose si los atiende Vantepaz de manera personal, la verdad no te quiero mentir porque no estoy 100%, pero creo que si, que los atiende el, vía discord.
