### ISSUE TITLE
Bug en Monte Hyjal

### ISSUE THREAD

**Issue by Zeirbit** [athenaswow/BugTracker-Athenas-WoW#92]
Nombre del pj: Chirroski
Dc: no tengo.

El bug es que en monte Hyjal el npc Motogarra no esta en el Santuario de Marlone.
Así que la misión "Guardianes de Hyjal: ¡Invasión de las Tierras de Fuego!" no se puede entregar. 
Aquí les dejo la evidencia. 
https://imgur.com/UYP8pBy

**Comment by athenaswow** [comment]
Este bug ya fue reportado.
