### ISSUE TITLE
Mision bug de Uldum (diaria)

### ISSUE THREAD

**Issue by Anciano9** [athenaswow/BugTracker-Athenas-WoW#93]
Anciano
Anciano#0370

La misión Fuego desde el cielo] lo que trata es de tener que subirse a un tanke que esta alado del npc donde se coje la mision y matar a mobs que estan alfrente en un templo con este tanke
https://es.wowhead.com/quest=28497/fuego-desde-el-cielo#videos:id=96651

En la misión  [Fuego desde el cielo] no deja subirse a la Artillería confiscada la cual debemos de utilizar para poder matar a unos npc que están en un templo de enfrente; cabe recalcar que esta misión diaria también aporta un logro llamado  [¡Ayuda al bombardero! ¡Yo soy el bombardero!]
https://imgur.com/a/MEwICR0

**Comment by Revly** [comment]
¿Aun sigue Bug, o Solo no me funciona a mi?
