### ISSUE TITLE
Misiones diarias de Joyeria bug

### ISSUE THREAD

**Issue by EstebanJCh97** [athenaswow/BugTracker-Athenas-WoW#94]
Main Melisa 
Discord Esteban#0511
La mision es 
https://es.wowhead.com/quest=25155/las-ogrozonianas-est%C3%A1n-de-humor
Supongo que todas las de joyería que implican entregar como por ejemplo piedra nocturna intemporal tienen el mismo problema.
En las misiones diarias de joyería aparece lo que hay que entregar en ingles y español , resulta que al tener el objeto en español no me lo cuenta en ingles y asi al inversa, quisiera saber si podrian arreglar esto porfavor y gracias :)
Aqui en esta imagen muestro como tengo el objeto en mochila pero solo me lo completa en el idioma de español y no es ingles.
https://imgur.com/yBCJmxi

**Comment by Salchipapas** [comment]
Ese objeto se debe crear cuando  le den la misión, no antes o si no, NO la cuenta.

Lo digo porque a mi ya me paso y soy joyero.

**Comment by EstebanJCh97** [comment]
Lo que pasa es que no debería ser así ya que solo pide tener el objeto en si , lo que pasa es que al estar en dos idiomas la misión se buguea y no cuenta el objeto en el otro idioma

**Comment by athenaswow** [comment]
Reporte invalido.
![image](https://user-images.githubusercontent.com/50283962/71754649-12c1a580-2e55-11ea-8bce-d3873e3a90fd.png)

**Comment by athenaswow** [comment]
![image](https://user-images.githubusercontent.com/50283962/71754688-43094400-2e55-11ea-9565-c044f4427028.png)
