### ISSUE TITLE
NO SE REVIVEN PETS EN CAMPOS DE BATALLA

### ISSUE THREAD

**Issue by tequilas-elite** [athenaswow/BugTracker-Athenas-WoW#95]
- Personaje principal: Tequilas
- Discord; Tequilas#1502
- Bug: al revivir en cementerios de bgs el jugador debería revivir con su mascota viva, incluso si la mascota murió previo al jugador.
-Evidencia: https://youtu.be/W7Ao2canfjw
- Aqui un video random de un jugador en retail usando pet, muriendo y siendo revivido por el cementerio junto a su pet https://www.youtube.com/watch?v=SZIjZNC6e54
min 07:29 - 07:55

**Comment by DennisCalderon** [comment]
reparado, el día de mañana se aplica en el servidor
