### ISSUE TITLE
Bug Arena si estas en Frente de Magma

### ISSUE THREAD

**Issue by ghost** [athenaswow/BugTracker-Athenas-WoW#96]
Buen dia, hoy quiero reportar un bug bastante extraño que me ocurrió; me encontraba haciendo arenas y pues también comencé a hacer las diarias del frente de magma estando en esta zona salto la arena y al entrar lo primero que paso fue que me mando a volar y quede en el techo y luego me tele transportó a el centro de la arena pero no me podía mover hasta que me tiraron algún efecto de aturdimiento, también me movía como si estuviera en el piso de alguna zona de vash'ir y podía "volar" como si estuviera nadando en la zona Vash'ir.

Vídeo de Pruebas: https://youtu.be/cLknVlDZ9SM

Muchas gracias por su atención C:

**Comment by athenaswow** [comment]
Todos los reportes de hyjal serán  cerrados ya que estoy trabajando en ese lugar desde cero logrando un mejor resultado en las cadenas de misiones, el parche se aplicara a mas tardar el 15 de abril del 2020.
