### ISSUE TITLE
Bug secuencia de misiones Hyjal

### ISSUE THREAD

**Issue by yairanacona** [athenaswow/BugTracker-Athenas-WoW#97]
Empiezas las misiones con los tableros entregas hay mismo y coges la siguiente, luego de hay todas estan bug no aparecen los Npc y en la que voy que me han colaborado aparecen 2 Npc iguales que no dejan seguir la secuencia.
Mi nick de personaje es Parapeto.
Mi Id de jugador es Yair#2166.
![image](https://user-images.githubusercontent.com/59518740/71773420-c8aaf380-2f2a-11ea-9f2e-53d973f263bb.png)
![image](https://user-images.githubusercontent.com/59518740/71773423-d82a3c80-2f2a-11ea-8aed-4d7ea98cb575.png)

**Comment by athenaswow** [comment]
Todos los reportes de hyjal serán  cerrados ya que estoy trabajando en ese lugar desde cero logrando un mejor resultado en las cadenas de misiones, el parche se aplicara a mas tardar el 15 de abril del 2020.
